export default {
  'pages_admin.setting.title': 'Settings',
  'pages_admin.setting.RolesPermission': 'Roles & Permissions',
  'pages_admin.setting.Department': 'Departments',
  'pages_admin.setting.Positions': 'Positions',
  'pages_admin.setting.Locations': 'Locations',
  'pages_admin.setting.grades': 'Grades',
  'pages_admin.setting.grade': 'Grade',
  'pages_admin.setting.domain': 'Domain',
  'pages_admin.setting.addRoleAndPermission': 'Add Roles & Permission',
  'pages_admin.setting.roleId': 'Role ID',
  'pages_admin.setting.description': 'Description',
  'pages_admin.setting.permissions': 'Permissions',
  'pages_admin.setting.permission': 'Permission',
  'pages_admin.setting.action': 'Action',
  'pages_admin.setting.sureMove': 'Sure to remove?',
  'pages_admin.setting.edit': 'Edit',
  'pages_admin.setting.addNew': 'Add New',
  'pages_admin.setting.rolePermission': 'Role & Permissions',
  'pages_admin.setting.roleName': 'Role Name',
  'pages_admin.setting.roleDescription': 'Role Description',
  'pages_admin.setting.departmentId': 'Department ID',
  'pages_admin.setting.departmentName': 'Department Name',
  'pages_admin.setting.departmentParentInfo': 'Parent Department',
  'pages_admin.setting.departmentParentName': 'Parent Department Name',
  'pages_admin.setting.hrPOC': 'HR POC',
  'pages_admin.setting.financePOC': 'Finance POC',
  'pages_admin.setting.financePointContact': 'Finance Point of Contact',
  'pages_admin.setting.addDepartment': 'Add Department',
  'pages_admin.setting.department': 'Department',
  'pages_admin.setting.hrPoint': 'HR Point of Contact',
  'pages_admin.setting.typeToSearch': 'Type to search',
  'pages_admin.setting.addDivision': 'Add as Division',
  'pages_admin.setting.positionName': 'Position Name',
  'pages_admin.setting.role': 'Role',
  'pages_admin.setting.roles': 'Roles',
  'pages_admin.setting.gradeObj': 'Grade Level',
  'pages_admin.setting.timeSheetRequired': 'Timesheet Required',
  'pages_admin.setting.addPosition': 'Add Position',
  'pages_admin.setting.position': 'Position',
  'pages_admin.setting.EligibleCompOff': 'Eligible For Comp Off',
  'pages_admin.setting.simpleTimeSheet': 'Simple Timesheet',
  'pages_admin.setting.complexTimeSheet': 'Complex Timesheet',
  'pages_admin.setting.name': 'Name',
  'pages_admin.setting.addGrade': 'Add Grade',
  'pages_admin.setting.gradeName': 'Grade Name',
  'pages_admin.setting.addNewDomain': 'Add a New Domain',
  'pages_admin.setting.save': 'Save',
  // Message Rule
  'pages_admin.setting.enterRoleId': 'Please enter the role ID!',
  'pages_admin.setting.enterRoleName': 'Please enter the role name!',
  'pages_admin.setting.enterRoleDescription': 'Please enter the role description!',
  'pages_admin.setting.enterDepartmentName': 'Please enter department name!',
  'pages_admin.setting.existDepartmentName': 'Department name is exist.',
  'pages_admin.setting.searchDepartment': 'Search Department',
  'pages_admin.setting.enterDepartment': 'Enter the department name',
  'pages_admin.setting.selectParentDepartment': 'Select the parent department',
  'pages_admin.setting.selectHrPoint': 'Please select HR Point of Contact',
  'pages_admin.setting.selectFinancePoint': 'Please select Finance Point of Contact',
  'pages_admin.setting.searchPosition': 'Search Position',
  'pages_admin.setting.pleaseSelectDepartmentName': 'Please select the department name!',
  'pages_admin.setting.selectDepartmentName': 'Select the department name',
  'pages_admin.setting.enterPositionName': 'Please enter the position name!',
  'pages_admin.setting.selectEnterPositionName': 'Select enter position name',
  'pages_admin.setting.pleaseSelectGradeLevel': 'Please select the grade level',
  'pages_admin.setting.selectGradeLevel': 'Select the grade level',
  'pages_admin.setting.domainUse': 'This domain is in use',
  'pages_admin.setting.deleteAllRecords':
    'Please delete all records related to this domain and try again!',
  'pages_admin.setting.sureDeleteDomain': 'Are you sure you want to delete the domain?',
  'pages_admin.setting.primaryDomain': 'Must to have one Primary Domain',
  'pages_admin.setting.cantDisable':
    'You can not disable primary for all domains, please set the other domain as primary.',
  'pages_admin.setting.allPagePublic':
    ' All of the pages in your site will be published to the domain you create here.',
  'pages_admin.setting.chooseDomain': 'Choose a domain name like “example.yourcompany.com”',
  'pages_admin.setting.domainName': 'Domain Name',
  'pages_admin.setting.setDomain': 'Set domain',
  'pages_admin.setting.primaryDomainText': 'Primary Domain',
};
