export default {
  'component.GroupInfoType2.plan': 'Plan',
  'component.GroupInfoType2.coverageEndDate': 'Coverage End Date',
  'component.tagSelect.expand': 'Expand',
  'component.tagSelect.collapse': 'Collapse',
  'component.tagSelect.all': 'All',
  'component.appFooter.imgAlt': 'The Logo Not Found At Location',
  'component.Authorized.unAuthentication': 'Sorry, you are not authorized to access this page.',
  'component.ChangePasswordBox.changePass': 'Change your password',
  'component.ChangePasswordBox.createAccount':
    'To make your account secure, please create a new password',
  'component.globalHeader.search': 'Search',
  'component.globalHeader.search.example1': 'Search example 1',
  'component.globalHeader.search.example2': 'Search example 2',
  'component.globalHeader.search.example3': 'Search example 3',
  'component.globalHeader.help': 'Help',
  'component.globalHeader.notification': 'Notification',
  'component.globalHeader.notification.empty': 'You have viewed all notifications.',
  'component.globalHeader.message': 'Message',
  'component.globalHeader.message.empty': 'You have viewed all messsages.',
  'component.globalHeader.event': 'Event',
  'component.globalHeader.event.empty': 'You have viewed all events.',
  'component.globalHeader.avatarDropdown.view-profile': 'View profile',
  'component.globalHeader.avatarDropdown.change-password': 'Change password',
  'component.globalHeader.avatarDropdown.settings': 'Settings',
  'component.globalHeader.avatarDropdown.session-login': 'Session login',
  'component.globalHeader.avatarDropdown.logout': 'Logout',

  'component.globalHeader.approvalPage': 'Approval Page',
  'component.globalHeader.switch': 'Switch',
  'component.globalHeader.switchCompany': 'Switch Company',
  'component.globalHeader.switchingCompany': 'Switching to {newCompName} company...',
  'component.globalHeader.switchTo': 'Switch to',
  'component.globalHeader.advancedSearch': 'Advanced Search',
  'component.globalHeader.quickLinks': 'Quick Links',
  'component.globalHeader.raiseTicket': 'Raise Ticket',
  'component.globalHeader.faq': 'FAQ',
  'component.globalHeader.policies': 'Policies & Regulations',
  'component.globalHeader.helpCenter': 'HR-OS Help Center',
  'component.globalHeader.current': 'Current',
  'component.globalHeader.selectCompany': 'Please select a company.',
  'component.globalHeader.chooseCompany': '>Choose your company and click Switch.',
  'component.globalHeader.control': 'Control Panel',

  'component.noticeIcon.clear': 'Clear',
  'component.noticeIcon.cleared': 'Cleared',
  'component.noticeIcon.empty': 'No notifications',
  'component.noticeIcon.view-more': 'View more',

  /* directory */
  'component.directory.table.fullName': 'Full Name',
  'component.directory.table.employeeID': 'Employee ID',
  'component.directory.table.userID': 'User ID',
  'component.directory.table.email': 'Email ID',
  'component.directory.table.title': 'Title',
  'component.directory.table.department': 'Department',
  'component.directory.table.location': 'Location',
  'component.directory.table.reportingManager': 'Reporting Manager ',
  'component.directory.table.employmentType': 'Employment Type',
  'component.directory.table.employeeType': 'Employee Type',
  'component.directory.table.action': 'Action',
  'component.directory.pagination.showing': 'Showing',
  'component.directory.pagination.of': 'of',

  /* color picker */
  'component.colorPicker.pickColor': 'Pick the color',

  /* layout left menu */
  'component.layoutLeftMenu.saveChange': 'Save your changes ?',

  /* country selector */
  'component.countrySelector.select': 'Select the country',

  /* Editor Quill */
  'component.editor.invalidFile':
    'Invalid file. Only images to be accepted and must smaller than 5MB!',

  /* Add candidate */
  'component.candidate.extendDate': 'Extend Offer Date',
  'component.candidate.extendLetterDate': 'Extend offer letter date',
  'component.candidate.withdraw': 'Withdraw Offer',
  'component.candidate.offerWithdraw': 'Offer Withdraw',

  /* Admin */
  'component.admin.adminApp': 'Admin App',
  'component.admin.changeLogo': 'Change Logo',
  'component.admin.upCompanyLogo': 'Upload company logo',
  'component.admin.removeLogo': 'Remove Logo',
  'component.admin.uploadLogo': 'Upload Logo',
  'component.admin.sure': 'Are you sure?',

  /* Layout Customer */
  'component.customer.idGenerated': 'Customer ID is auto-generated',
  'component.customer.statusGenerated': 'Status is auto-generated',
  'component.customer.basicDetail': 'Basic Customer Detail',
  'component.customer.id': 'Customer ID',
  'component.customer.enterId': 'Enter Customer ID',
  'component.customer.enterStatus': 'Enter Status',
  'component.customer.requiredFail': 'Required field!',
  'component.customer.enterCompanyName': 'Enter Company legal name',
  'component.customer.enterCompanySortName': '"Enter Company short name"',
  'component.customer.DAB': 'Doing Business As (DBA)',
  'component.customer.DABExist': 'Doing Business As(DBA) is exist.',
  'component.customer.accOwner': 'Account Owner',
  'component.customer.companyAlias': 'Company alias (DBA)',
  'component.customer.openLeads': 'Open Leads',
  'component.customer.activeProjects': 'Active Projects',
  'component.customer.openTickets': 'Open Tickets',
  'component.customer.openTasks': 'Open Tasks',
  'component.customer.profilePictureUpdate': 'Profile Picture Update',
  'component.customer.editCustomer': 'Edit Customer',

  /* Layout Employee */
  'component.employee.maxCharacters': 'Only 170 character allowed!',
  'component.employee.remainingCharacters': 'Remaining characters',
  'component.employee.limitExceeded': 'Limit exceeded',
  'component.employee.editBio': 'Edit Bio',
  'component.employee.putOnLeave': 'Put on Leave (LWP)',
  'component.employee.raiseTermination': 'Raise Termination',
  'component.employee.requestDetails': 'Request Details',
  'component.employee.noCertifications': 'No certifications',
  'component.employee.showProfile': 'Show profile picture to other users',
  'component.employee.linkedIn': 'LinkedIn',
  'component.employee.updateLinkedin':
    'Please update the Linkedin Profile in the Employee profile page',
  'component.employee.copyClipboard': 'Copied to clipboard',

  /* Project */
  'app.projectID': 'Project ID',
  'app.projectAlias': 'Project alias',
  'component.project.engagementType': 'Engagement Type',
  'component.project.engineeringOwner': 'Engineering Owner',
  'component.project.editProject': 'Edit Project',
  'component.project.pm': 'Project Manager',
  'component.project.type': 'Project Type',
  'component.project.duration': 'Duration',
  'component.project.status': 'Project Status',
  'component.project.viewDetail': 'View project details',

  /* Profile */
  'component.profile.uploadAvt': 'Upload avatar',
  'component.profile.rpManager': 'Reporting Manager',
  'component.profile.mobile': 'Mobile',
  'component.profile.emailId': 'Email id',
  'component.profile.email': 'Email',
  'component.profile.location': 'Location',
  'component.profile.localTime': 'Local Time',
  'component.profile.view': 'View full profile',
  'component.profile.certifications': 'Certifications',

  /* Modal New Page */
  'component.newPage.addPage': 'Add Page',
  'component.newPage.add': 'Add',
  'component.newPage.pageName': 'Name of the page',
  'component.newPage.selectPage': 'Select the Page',
  'component.newPage.choosePosition': 'Choose Position',
  'component.newPage.before': 'Before',
  'component.newPage.after': 'After',

  /* Feedback */
  'component.feedback.feedback': 'Feedback',
  'component.feedback.appFeedback': 'Application Feedback',
  'component.feedback.thankForFeedback':
    'Thank you for your feedback ! Your feedback has been recorded and will be shared with the appropriate team.',
  'component.feedback.description':
    'Please describe what you would like to change or what you liked ?',
  'component.feedback.thankForDescription':
    'Thank you for helping us improve the application ! Please select an option below.',
  'component.feedback.reportIssue': 'Report an issue',
  'component.feedback.suggest': ' Suggest an Enhancement',
  'component.feedback.type': ' Type here...',
  'component.feedback.uploadScreenshot': ' Upload Screenshot',
  'component.feedback.highlightPage': ' Highlight Page',
  'component.feedback.descriptionChange':
    'Please describe what you would like to change or what you liked? You can also pinpoint areas of the current page that relate to your feedback with the "Highlight Page" tool.',
  'component.feedback.validate.radio': 'Please check the radio !',
  'component.feedback.validate.maxCharacters': 'Only fill up to 1000 characters !',
  'component.feedback.validate.inputField': 'Please input field !',
  'component.feedback.uploadNew': 'Upload new',
  'component.feedback.addDocument': 'Add Document',
  'component.feedback.uploadNextScreen':
    'You can upload a screenshot and describe the issue in the next screen.',
  'component.feedback.dragAndDrop': 'Drag & drop your file here',
  'component.feedback.or': 'or',
  'component.feedback.browse': 'browse',
  'component.feedback.toUpload': 'to upload a file',
  'component.feedback.fileSize':
    'File size should not be more than 2MB. Supported file for view: pdf & jpeg!',
  'component.feedback.clickHighlight': 'Click and drag to highlight the area.',

  /*  Signature */
  'component.signature.inputName': 'Please input your name',
  'component.signature.generate': 'Generate',
  'component.signature.fileType': 'You can only upload image and PDF file!',
  'component.signature.fileSize': 'Image must smaller than 5MB!',
  'component.signature.optionSignature': 'Choose your options for Signature',
  'component.signature.draw': 'Draw',
  'component.signature.digital': 'Digital Signature',
  'component.signature.chooseFile': 'Choose file',
  'component.signature.dropFile': 'or drop file here',
  'component.signature.validate.enterName': 'Please enter name',
  'component.signature.validate.signDocument':
    'To sign the document, please type your name and select the signature format of your choice.',

  /*  Review Image */
  'component.reviewImage.title': 'Review Image',

  /*  Modal Upload */
  'component.upload.validate.fileType': 'You can only upload JPG/PNG file!',
  'component.upload.validate.fileSize': 'Image must smaller than 5MB!',
  'component.upload.uploadFail': 'file upload failed.',
  'component.upload.uploadNew': 'Upload new',
  'component.upload.clickOrDragToUpload': 'Click or drag file to this area to upload',
  'component.upload.fileType': 'Type of file: PDF/PNG/JPEG',
  'component.upload.fileSize': 'Size of image must be smaller than 5MB!',
  'component.upload.pdfType': 'You can only upload PDF file!',
  'component.upload.multiFiles': 'You can only upload JPG/PNG/PDF file!',
  'component.upload.imgSmaller': 'Image must smaller than',
  'component.upload.fileSmaller': 'File must smaller than',
  'component.upload.fileUnder5Mb': 'File must me under 5 Mb',

  /* Policies */
  'component.policies.stillHelp': 'Still need our help?',
  'component.policies.support24/7':
    'Our support team is waiting to help you 24/7. Get an emailed response from our team.',
  'component.policies.contact': 'Contact Us',

  /* Question */
  'component.question.question': 'question',
  'component.question.add': 'Add question',
  'component.question.edit': 'Edit question',
  'component.question.rows': 'Rows',
  'component.question.columns': 'Columns',
  'component.question.addRow': 'Add row',
  'component.question.addColumn': 'Add column',
  'component.question.options': 'Options',
  'component.question.addOption': 'Add Option',
  'component.question.option': 'Option',
  'component.question.answer': 'Answer',
  'component.question.answerHere': 'Answer here',
  'component.question.enterAnswer': 'Enter the answer',
  'component.question.selectOption': 'Select a option',
  'component.question.note': 'Note',
  'component.question.typeYourQuestion': 'Type your question',
  'component.question.mandatory': 'Mandatory',
  'component.question.label': 'Label',
  'component.question.typeHere': 'Type here',
  'component.question.optionalOnboarding': 'Optional Question Onboarding',
  'component.question.addOptionalOnboarding': 'Add optional onboarding questions',

  'component.question.type.text': 'Free form text',
  'component.question.type.singleChoice': 'Single choice',
  'component.question.type.multipleChoice': 'Multiple choice',
  'component.question.type.dropdown': 'Dropdown',
  'component.question.type.singleRating': 'Single rating choice',
  'component.question.type.multipleRating': 'Multiple rating choice',
  'component.question.type': 'Type of questions',

  'component.question.specify': 'Specify',
  'component.question.specify.atLeast': 'At least',
  'component.question.specify.atMost': 'At most',
  'component.question.specify.exactly': 'Exactly',
  'component.question.specifyAnswers': 'This allows to specify how answers should be chosen.',

  'component.question.validate.requiredAnswer':
    'This type of question must have at least one answer!',
  'component.question.validate.maxCharacters': 'Maximum characters limit 200.',
  'component.question.validate.greaterThan': 'This value must be greater than',
  'component.question.validate.atLeast': 'This question has at least {num} answers',
  'component.question.validate.atMost': 'This question has at most {num} answers',
  'component.question.validate.exactly': 'This question has exactly {num} answers',

  /* Raise ticket */
  'component.raiseTicket.raiseTicket': 'Raise Ticket',
  'component.raiseTicket.addAttachments': 'Add attachments',
  'component.raiseTicket.supportTeam': 'Support Team',
  'component.raiseTicket.requestDate': 'Request Date',
  'component.raiseTicket.queryType': 'Query Type',
  'component.raiseTicket.status': 'Status',
  'component.raiseTicket.new': 'New',
  'component.raiseTicket.priority': 'Priority',
  'component.raiseTicket.subject': 'Subject',
  'component.raiseTicket.description': 'Description',
  'component.raiseTicket.interestList': 'Interest List',
  'component.raiseTicket.upload2Documents': 'You can upload upto 2 documents of 2MB each',
  'component.raiseTicket.addUser': 'Add any user you want copied to this ticket',
  'component.raiseTicket.typeSearch': 'Type to search',
  'component.raiseTicket.validate.selectTeam': 'Please select the support team',
  'component.raiseTicket.validate.queryType': 'Please select the query type',
  'component.raiseTicket.validate.priority': 'Please select the priority',
  'component.raiseTicket.validate.subject': 'Please enter the subject',
  'component.raiseTicket.validate.description': 'Please enter the description',

  /* Document */
  'component.document.name': 'Document Name',
  'component.document.type': 'Document Type',
  'component.document.userId': 'User ID',
  'component.document.uploadedBy': 'Uploaded By',
  'component.document.view': 'View Document',
  'component.document.sign': 'Sign',
  'component.document.downloading': 'Downloading file. Please wait...',
  'component.document.size': 'Document Size (KB/MB/GB)',
  'component.document.validate.enterDocumentName': 'Enter document name',
  'component.document.validate.enterSize': 'Enter document size',
  'component.document.validate.modifiedBy': 'Modified By',
  'component.document.validate.enterModifiedBy': 'Enter modified by',
  'component.document.validate.enterDocumentType': 'Enter document type',

  /* debounceSelect */
  'component.debounceSelect.placeholder': 'Type to Search',

  /* Search */
  'component.search.employees': 'Employees',
  'component.search.documents': 'Documents',
  'component.search.tickets': 'Tickets',
  'component.search.onBoarding': 'On boarding',
  'component.search.createdOn': 'Created On',
  'component.search.documentOwner': 'Document Owner',
  'component.search.searchDocumentText': 'Search document name, type, owner, size, created on...',
  'component.search.modifiedOn': 'Modified On',
  'component.search.personalDetails': 'Personal Details',
  'component.search.searchPersonal': 'Search for personal details such as name, phone number...',
  'component.search.firstName': 'First Name',
  'component.search.userID': 'User ID',
  'component.search.enterFirstName': 'Enter first name',
  'component.search.enterUserID': 'Enter user ID',
  'component.search.state': 'State',
  'component.search.enterState': 'Enter state',
  'component.search.middleName': 'Middle Name',
  'component.search.lastName': 'Last Name',
  'component.search.city': 'City',
  'component.search.jobDetails': 'Job Details',
  'component.search.enterCity': 'Enter city',
  'component.search.searchJobDetail': 'Search for job details such as job title, department...',
  'component.search.enterLastName': 'Enter last name',
  'component.search.enterMiddleName': 'Enter middle name',
  'component.search.phoneNumber': 'Phone Number',
  'component.search.enterPhoneNumber': 'Enter phone number',
  'component.search.country': 'Country',
  'component.search.enterCountry': 'Enter country',
  'component.search.enterEmployeeID': 'Enter employee ID',
  'component.search.enterSkills': 'Enter skills',
  'component.search.building': 'Building',
  'component.search.enterBuilding': 'Enter building',
  'component.search.enterReportingManager': 'Enter reporting manager',
  'component.search.selectJobTitle': 'Select job title',
  'component.search.floor': 'Floor',
  'component.search.enterFloor': 'Enter floor',
  'component.search.employeeType': 'Employee Type (Regular or Contingent)',
  'component.search.selectEmployeeType': 'Select employee type',
  'component.search.codeNumber': 'Code number',
  'component.search.enterCodeNumber': 'Enter code number',
  'component.search.classification': 'Classification (Intern/Part Time/Full Time)',
  'component.search.enterClassification': 'Enter classification',
  'component.search.validate.enterCreatedOn': 'Enter created on',
  'component.search.validate.enterDocumentOwner': 'Enter document owner',
  'component.search.validate.enterModifiedOn': 'Enter modified on',
  'component.search.searchTicket': 'Search ID, employee name, created by, assigned to...',
  'component.search.ticketID': 'Ticket ID',
  'component.search.enterTicketID': 'Enter ticket ID',
  'component.search.assignedTo': 'Assigned To',
  'component.search.enterAssignedTo': 'Enter assigned to',
  'component.search.status': 'Status',
  'component.search.resolvedBy': 'Resolved By',
  'component.search.enterResolvedBy': 'Enter resolved by',
  'component.search.createdBy': 'Created By',
  'component.search.enterCreatedBy': 'Enter created by',

  // Modal
  'component.modal.yourTitle': 'Your title',
};
