export default {
  'pages.customerProfile.customerProfile': 'Customer Profile',
  'pages.customerProfile.addAnotherDivision': 'Add another Division',
  'pages.customerProfile.addDivision': 'Add Division',
  'pages.customerProfile.editDivision': 'Edit Division',
  // Modal
  'pages.customerProfile.basicDivisionDetail': 'Basic Division Detail',
  'pages.customerProfile.contactDetail': 'Contact Detail',
  'pages.customerProfile.otherDetails': 'Other Details',
  'pages.customerProfile.sameAddressAsHQ': 'Same addresAdd Documents as HQ',

  // Tab Name
  'pages.customerProfile.contactInfo': 'Contact Info',
  'pages.customerProfile.divisions': 'Divisions',
  'pages.customerProfile.people': 'People',
  'pages.customerProfile.documents': 'Documents',
  'pages.customerProfile.projects': 'Projects',
  'pages.customerProfile.leads': 'Leads',
  'pages.customerProfile.tickets': 'Tickets',
  'pages.customerProfile.emails': 'Emails',
  'pages.customerProfile.appointments': 'Appointments',
  'pages.customerProfile.tasks': 'Tasks',
  'pages.customerProfile.notes': 'Notes',
  'pages.customerProfile.auditTrail': 'Audit Trail',
  // Division item
  'pages.customerProfile.divisionId': 'Division ID',
  'pages.customerProfile.divisionName': 'Division Name',
  'pages.customerProfile.primaryPOCName': 'Primary POC Name',
  'pages.customerProfile.primaryPOCNo': 'Primary POC Ph No.',
  'pages.customerProfile.primaryPOCEmailId': 'Primary POC Email ID',
  'pages.customerProfile.primaryPOCDesignation': 'Primary POC Designation',
  'pages.customerProfile.secondaryPOCName': 'Secondary POC Name',
  'pages.customerProfile.secondaryPOCNo': 'Secondary POC Ph No.',
  'pages.customerProfile.secondaryPOCEmailId': 'Secondary POC Email ID',
  'pages.customerProfile.secondaryPOCDesignation': 'Secondary POC Designation',
  // PlaceHolders
  'pages.customerProfile.divisionIdPlaceHolder': 'Enter Division ID',
  'pages.customerProfile.divisionNamePlaceHolder': 'Enter Division Name',
  'pages.customerProfile.primaryPOCNamePlaceHolder': 'Enter Primary POC Name',
  'pages.customerProfile.primaryPOCNoPlaceHolder': 'Enter Primary POC Ph No.',
  'pages.customerProfile.primaryPOCEmailIdPlaceHolder': 'Enter Primary POC Email ID',
  'pages.customerProfile.primaryPOCDesignationPlaceHolder': 'Enter Primary POC Designation',
  'pages.customerProfile.secondaryPOCNamePlaceHolder': 'Enter Secondary POC Name',
  'pages.customerProfile.secondaryPOCNoPlaceHolder': 'Enter Secondary POC Ph No.',
  'pages.customerProfile.secondaryPOCEmailIdPlaceHolder': 'Enter Secondary POC Email ID',
  'pages.customerProfile.secondaryPOCDesignationPlaceHolder': 'Enter Secondary POC Designation',
  'pages.customerProfile.searchBox': 'Search by Document Name, Uploaded By',
  'pages.customerProfile.addNoteReference': 'Add a note for reference',
};
