export default {
  'pages.directory.viewActivityLog': 'View activity logs',
  'pages.directory.directoryTab': 'Directory',
  'pages.directory.employeesManagementTab': 'Employees Management',
  'pages.directory.organisationChartTab': 'Organization Chart',
  'pages.directory.directory.activeEmployeesTab': 'Active Employees',
  'pages.directory.directory.myTeamTab': 'My Team',
  'pages.directory.directory.viewProfile': 'View Profile',
  'pages.directory.directory.inactiveEmployeesTab': 'Inactive Employees',
  'pages.directory.directory.setUpNewProfile': 'Set Up New Profile',
  'pages.directory.directory.addTeamMember': 'Add team member',
  'pages.directory.tableFilter.filter': 'Filters',
  'pages.directory.tableFilter.reset': 'Reset',
  'pages.directory.tableFilter.name': 'Name',
  /* organisationChart */
  'pages.directory.organisationChart.search': 'Search...',
  'pages.directory.organisationChart.search.placeholder': 'Type to search by Employee Name or ID',
  'pages.directory.organisationChart.expandAll': 'Expand All',
  'pages.directory.organisationChart.collapseAll': 'Colapse All',
  'pages.directory.organisationChart.download': 'Download',
  'pages.directory.organisationChart.skills': 'Skills',
  'pages.directory.organisationChart.certifications': 'Certifications',
  'pages.directory.organisationChart.workNumber': 'Mobile',
  'pages.directory.organisationChart.copy': 'Copy',
  'pages.directory.organisationChart.copySuccess': 'Copied to clipboard',
  'pages.directory.organisationChart.viewProfile': 'View full profile',
  'pages.directory.organisationChart.message': 'Message',
  'pages.directory.organisationChart.email': 'Email',
  'pages.directory.organisationChart.linkedIn': 'LinkedIn',
  'pages.directory.organisationChart.needLinkedIn':
    'Please update the Linkedin Profile in the Employee profile page',
  'pages.directory.organisationChart.reportees': 'reportees',
  'pages.directory.organisationChart.sub1Reportee': '- 1 reportee',
  'pages.directory.organisationChart.add1Reportee': '+ 1 reportee',
  'pages.directory.organisationChart.you': 'You',
  /* tableFilter */
  'component.directory.tableFilter.name': 'by employee id / user id / name...',
  'component.directory.tableFilter.name.placeholder':
    'Type to search by Employee ID / User ID / Name...',
  'component.directory.tableFilter.department': 'By department id / name',
  'component.directory.tableFilter.department.placeholder': 'Search by Department',
  'component.directory.tableFilter.division': 'By division name',
  'component.directory.tableFilter.division.placeholder': 'Search by Division Name',
  'component.directory.tableFilter.title': 'by job title',
  'component.directory.tableFilter.title.placeholder': 'Search by job title',
  'component.directory.tableFilter.manager': 'By reporting manager',
  'component.directory.tableFilter.manager.placeholder': 'Type to search',
  'component.directory.tableFilter.location': 'By location',
  'component.directory.tableFilter.location.placeholder': 'Search by Location',
  'component.directory.tableFilter.country': 'By country',
  'component.directory.tableFilter.country.placeholder': 'Search by country',
  'component.directory.tableFilter.empTypeOther': 'By employee type',
  'component.directory.tableFilter.empTypeOther.placeholder': 'Search by Employee Type',
  'component.directory.tableFilter.employeeType': 'By employment type',
  'component.directory.tableFilter.employeeType.placeholder': 'Search by Employment Type',
  'component.directory.tableFilter.skill': 'By skills & certifications',
  'component.directory.tableFilter.skill.placeholder': 'Search by Skills',
  'component.directory.tableFilter.experience': 'By yrs of experience',
  'component.directory.tableFilter.from': 'From',
  'component.directory.tableFilter.to': 'To',
  /* Modal */
  'component.directory.addEmployeeModal.title': 'Add Employee',
  'component.directory.importEmployeeModal.title': 'Import Employee',
  'component.directory.importEmployeeModal.error':
    'Submit failed because of not allow empty following fields: [joinDate, title, workEmail, location, department]! at row',
  'component.directory.importEmployeeModal.label': 'Company',
  'component.directory.importEmployeeModal.placeholder': 'Select Company',
  'component.directory.importEmployeeModal.onabortImport': 'File reading was aborted !',
  'component.directory.importEmployeeModal.onerrorImport': 'File reading has failed !',
  'component.directory.importEmployeeModal.uploadSuccess': 'Upload file successfully!',
  'component.directory.importEmployeeModal.uploaded': 'Uploaded',
  'component.directory.importEmployeeModal.chooseAnotherFile': 'Choose an another file',
  'component.directory.importEmployeeModal.dragAndDrop': 'Drag and drop the file here',
  'component.directory.importEmployeeModal.or': 'or',
  'component.directory.importEmployeeModal.chooseFile': 'Choose file',
  'component.directory.terminalModal.title': 'Terminate employee',
  'component.directory.terminalModal.reason': 'Reason',
  'component.directory.terminalModal.reason.placeholder': 'Fill in the box...',
  'component.directory.terminalModal.message1': 'Only fill up to 1000 characters !',
  'component.directory.terminalModal.message2': 'Required field!',
  'component.directory.terminalModal.lastWorkingDate': 'Last Working Date',
  /* Table */
  'component.directory.table.fullName': 'Full Name',
  'component.directory.table.employeeID': 'Employee ID',
  'component.directory.table.workNumber': 'Work Number',
  'component.directory.table.userID': 'User ID',
  'component.directory.table.email': 'Email ID',
  'component.directory.table.title': 'Title',
  'component.directory.table.department': 'Department',
  'component.directory.table.location': 'Location',
  'component.directory.table.reportingManager': 'Reporting Manager ',
  'component.directory.table.employmentType': 'Employment Type',
  'component.directory.table.employeeType': 'Employee Type',
  'component.directory.table.action': 'Action',
  'component.directory.table.terminate': 'Terminate',
  'component.directory.pagination.showing': 'Showing',
  'component.directory.pagination.of': 'of',
};
