export default {
  'pages_admin.documents.title': 'Documents Management',
  'pages_admin.documents.documentTable.activeDocumentsTab': 'Active Documents',
  'pages_admin.documents.documentTable.inactiveDocumentsTab': 'Inactive Documents',
  'pages_admin.documents.documentTable.addDocument': 'Add document',
  'pages_admin.documents.documentTable.importDocuments': 'Import documents',
  'pages_admin.documents.tableFilter.filter': 'Filters',
  'pages_admin.documents.tableFilter.reset': 'Reset',
  'pages_admin.documents.tableFilter.name': 'Name',
  'pages_admin.documents.confirmRemoveDocument':
    'Are you sure to remove &quot;{name}&quot; document?',
  'pages_admin.documents.createNewTemplate': 'Create new template',
  'pages_admin.documents.table.id': 'Document ID',
  'pages_admin.documents.table.type': 'Document Type',
  'pages_admin.documents.table.name': 'Document Name',
  'pages_admin.documents.table.uploadBy': 'Uploaded By',
  'pages_admin.documents.table.company': 'Company',
  'pages_admin.documents.table.createdDate': 'Created Date',
  'pages_admin.documents.table.action': 'Action',
  'pages_admin.documents.addDocument': 'Add Document',
  'pages_admin.documents.chooseAnotherFile': 'Choose an another file',
  'pages_admin.documents.uploaded': 'Uploaded',
  'pages_admin.documents.addDocumentSuccess': 'Add document successfully! Refreshing page...',
  'pages_admin.documents.employeeId': 'Employee ID',
  'pages_admin.documents.employeeName': 'Employee Name',
  'pages_admin.documents.documentGroup': 'Document Group',
  'pages_admin.documents.identityType': 'Identity Type',
  'pages_admin.documents.visa': 'Visa',
  'pages_admin.documents.passport': 'Passport',
  'pages_admin.documents.passportNumber': 'Passport Number',
  'pages_admin.documents.adhaarCard': 'Adhaar Card',
  'pages_admin.documents.adhaarNumber': 'Adhaar Number',
  'pages_admin.documents.country': 'Country',
  'pages_admin.documents.issuedOn': 'Issued On',
  'pages_admin.documents.validTill': 'Valid Till',
  'pages_admin.documents.visaNumber': 'Visa Number',
  'pages_admin.documents.visaType': 'Visa Type',
  'pages_admin.documents.entryType': 'Entry Type',
  'pages_admin.documents.nothing': 'nothing...',
  'pages_admin.documents.singleEntry': 'Single Entry',
  'pages_admin.documents.passportExist': 'The passport of this employee is already existed',
  'pages_admin.documents.validate.employeeExist': 'Employee does not exists!',
  'pages_admin.documents.validate.chooseFile': 'Please choose file to upload!',
  'pages_admin.documents.validate.inputEmployeeId': 'Please input employee ID!',
  'pages_admin.documents.validate.inputCompany': 'Please select company!',
  'pages_admin.documents.validate.inputDocument': 'Please input document name!',
  'pages_admin.documents.validate.inputDocumentGroup': 'Please select document group!',
  'pages_admin.documents.validate.selectDocumentType': 'Please select document type!',
  'pages_admin.documents.validate.selectIdentityType': 'Please select identity type!',
  'pages_admin.documents.validate.invalidAdhaarNumber': 'Invalid Adhaar Number',
  'pages_admin.documents.validate.invalidPassportNumber': 'Invalid Passport Number',
  'pages_admin.documents.validate.selectCountry': 'Please select country!',
  'pages_admin.documents.validate.selectIssuedTime': 'Please select issued time!',
  'pages_admin.documents.validate.selectExpiredTime': 'Please select expired time!',
  'pages_admin.documents.validate.selectVisaType': 'Please select visa type!',
  'pages_admin.documents.validate.selectEntryType': 'Please select entry type!',
  'pages_admin.documents.validate.invalidVisa': 'Invalid Visa Number',
};
