export default {
  'pages.employeeProfile.title': 'Employee Profile',
  'pages.employeeProfile.updateSuccess': 'Update information successfully',
  'pages.employeeProfile.okay': 'Okay',
  'pages.employeeProfile.generalInfoTab': 'General Info',
  'pages.employeeProfile.validateNumber':
    'Just only number & this field maximun be 16 number, please!',
  'pages.employeeProfile.validateSocialSecurityNumber':
    'Just only number and "-" character & this field maximun be 12 number, please!',
  'pages.employeeProfile.validateWorkNumber': 'Just only number & Area code, please!',
  'pages.employeeProfile.validateVisaNumber': 'Invalid visa number!',
  'pages.employeeProfile.validateVisaType': 'Invalid visa type!',
  'pages.employeeProfile.validatePassPortNumber': 'Invalid passport number',
  'pages.employeeProfile.validateDate':
    'Inappropriate date. Valid till date must be after issue date',
  'pages.employeeProfile.validateName': 'Just only word not number, please!',
  'pages.employeeProfile.validateEmail': 'This field must be a valid email.',
  'pages.employeeProfile.validatelinkedIn': 'This field must be a valid url.',
  'pages.employeeProfile.employmentAndCompensationTab': 'Employment & Compensation',
  'pages.employeeProfile.performanceHistoryTab': 'Performance History',
  'pages.employeeProfile.accountsAndPaychecksTab': 'Accounts and Paychecks',
  'pages.employeeProfile.documentsTab': 'Documents',
  'pages.employeeProfile.workEligibilityAndI-9Tab': 'Work Eligibility & I-9',
  'pages.employeeProfile.timeAndSchedulingTab': 'Time & Scheduling',
  'pages.employeeProfile.benefitPlansTab': 'Benefit Plans',

  'pages.employeeProfile.putOnLeave': 'Put on Leave (PWP)',
  'pages.employeeProfile.raiseTermination': 'Raise Termination',
  'pages.employeeProfile.requestDetails': 'Request Details',
  'pages.employeeProfile.actionMenu': 'Action',

  'pages.employeeProfile.location': 'Location',
  'pages.employeeProfile.joinedOn': 'Joined on',
  'pages.employeeProfile.Payslip': 'No pay slips',

  'pages.employeeProfile.bank': 'bank',
  'pages.employeeProfile.self': 'Self',
  'pages.employeeProfile.cancel': 'Cancel',
  'pages.employeeProfile.save': 'Save Change',
  'pages.employeeProfile.add': 'Add',
  'pages.employeeProfile.firstName': 'First Name',
  'pages.employeeProfile.firstName.placeholder': 'Enter the first name',
  'pages.employeeProfile.firstName.validate': 'Please type first name!',
  'pages.employeeProfile.lastName': 'Last Name',
  'pages.employeeProfile.lastName.placeholder': 'Enter the last name',
  'pages.employeeProfile.lastName.validate': 'Please type last name!',
  'pages.employeeProfile.gender': 'Gender',
  'pages.employeeProfile.gender.placeholder': 'Select the gender',
  'pages.employeeProfile.gender.validate': 'Please select gender!',
  'pages.employeeProfile.male': 'Male',
  'pages.employeeProfile.female': 'Female',
  'pages.employeeProfile.other': 'Other',
  'pages.employeeProfile.relationship': 'Relationship',
  'pages.employeeProfile.relationship.placeholder': 'Enter the relationship',
  'pages.employeeProfile.relationship.validate': 'Please select the relationship!',
  'pages.employeeProfile.father': 'Father',
  'pages.employeeProfile.mother': 'Mother',
  'pages.employeeProfile.spouse': 'Spouse',
  'pages.employeeProfile.child': 'Child',
  'pages.employeeProfile.grandfather': 'Grandfather',
  'pages.employeeProfile.grandmother': 'Grandmother',
  'pages.employeeProfile.dob': 'Date of Birth',
  'pages.employeeProfile.dob.placeholder': 'Select the date of birth',
  'pages.employeeProfile.dob.validate': 'Please choose date of birth!',
  'pages.employeeProfile.download': 'DownLoad',
  'pages.employeeProfile.view': 'View',
  'pages.employeeProfile.single': 'Single',
  'pages.employeeProfile.married': 'Married',
  'pages.employeeProfile.widowed': 'Widowed',
  'pages.employeeProfile.divorced': 'Divorced',
  'pages.employeeProfile.separated': 'Separated',
  'pages.employeeProfile.notMention': 'Rather not mention',
  'pages.employeeProfile.resident': 'Resident',
  'pages.employeeProfile.nonResident': 'Non Resident',
  'pages.employeeProfile.eligibilityDocuments': 'Eligibility Documents',
  'pages.employeeProfile.bankDetails': 'Bank Details',
  'pages.employeeProfile.adhaarIdDetails': 'Adhaar ID Details',
  'pages.employeeProfile.passportInformation': 'Passport Information',
  'pages.employeeProfile.tdsCertificate': 'TDS Certificate',
  'pages.employeeProfile.submit': 'Submit',
  'pages.employeeProfile.return': 'Cancel & Return',
  'pages.employeeProfile.reason': 'Reason',
  'pages.employeeProfile.requestSuccess': 'Your request has been registered successfully!',
  'pages.employeeProfile.delete': 'Delete',
  'pages.employeeProfile.oldTaxRegime': 'Old Tax Regime',
  'pages.employeeProfile.newTaxRegime': 'New Tax Regime',
  'pages.employeeProfile.addAnother': 'Add another',
  'pages.employeeProfile.continue': 'Continue',
  'pages.employeeProfile.previous': 'Previous',

  /* employmentTab */
  'pages.employeeProfile.edit': 'Edit',
  'pages.employeeProfile.makeChanges': 'Make changes',
  'pages.employeeProfile.editEmployment': 'Edit Employment',
  'pages.employeeProfile.employmentHistory': 'Employment History',
  'pages.employeeProfile.steps': 'steps',
  'pages.employeeProfile.back': 'Back',
  'pages.employeeProfile.employmentDetails': 'Employment Details',
  'pages.employeeProfile.customerLocation': 'Customer Location',
  'pages.employeeProfile.jobTitle': 'Job Title',
  'pages.employeeProfile.jobTitle.placeholder': 'Enter Job Title',
  'pages.employeeProfile.department': 'Department',
  'pages.employeeProfile.department.placeholder': 'Enter Department',
  'pages.employeeProfile.grade': 'Grade',
  'pages.employeeProfile.grade.placeholder': 'Enter the grade',
  'pages.employeeProfile.joiningDate': 'Joining Date',
  'pages.employeeProfile.initialJoiningDate': 'Initial Joining Date',
  'pages.employeeProfile.workLocation': 'Work Location',
  'pages.employeeProfile.workLocation.placeholder': 'Select the work location',
  'pages.employeeProfile.locationCustomer': 'Location Customer',
  'pages.employeeProfile.employmentType': 'Employment Type',
  'pages.employeeProfile.employmentType.placeholder': 'Select an employment type',
  'pages.employeeProfile.employeeType': 'Employee Type',
  'pages.employeeProfile.employeeType.placeholder': 'Select an employee type',
  'pages.employeeProfile.timeOffPolicy': 'Time Off Policy',
  'pages.employeeProfile.regular': 'Regular',
  'pages.employeeProfile.contingentWorker': 'Contingent Worker',
  'pages.employeeProfile.typeToSearch': 'Type to search',
  'pages.employeeProfile.changedReason': 'Changed Reason',
  'pages.employeeProfile.changeType': 'Change Type',
  'pages.employeeProfile.effectiveDate': 'Effective Date',
  'pages.employeeProfile.changeDate': 'Change Date',
  'pages.employeeProfile.changedBy': 'Change By',

  'pages.employeeProfile.dateRequired': 'Please enter a date',
  'pages.employeeProfile.titleRequired':
    'Please choose a job title corresponds with the selected department',
  'pages.employeeProfile.appropriateDateRequired': 'Please enter an appropriate date',
  'pages.employeeProfile.fifthStep': 'Who do you wish to notify about the changes that are made?',
  'pages.employeeProfile.firstStep': 'When do you wish the changes to take effect?',
  'pages.employeeProfile.fourthStep': 'Do you wish to change the compensation?',
  'pages.employeeProfile.secondStep': 'What do you wish to change?',
  'pages.employeeProfile.seventhStep': 'What is the reason to make this change?',
  'pages.employeeProfile.sixthStep': 'Please review all the changes below',
  'pages.employeeProfile.thirdStep': 'What do you wish to change?',
  'pages.employeeProfile.employee': 'Employee',
  'pages.employeeProfile.reportingManager': 'Employee’s Reporting Manager',
  'pages.employeeProfile.others': 'Others',
  'pages.employeeProfile.annualCTC': 'Annual CTC',
  'pages.employeeProfile.annualCTC.placeholder': 'Enter the Annual CTC',
  'pages.employeeProfile.compensationType': 'Compensation Type',
  'pages.employeeProfile.compensationType.placeholder': 'Select a compensation type',
  'pages.employeeProfile.reasonChange': 'Enter Reason for change...',
  'pages.employeeProfile.titleLabel': 'Title',
  'pages.employeeProfile.titleLabel.placeholder': 'Select a title',
  'pages.employeeProfile.reportTo': 'Reporting To',
  'pages.employeeProfile.reportTo.placeholder': 'Select a manager',
  'pages.employeeProfile.reportees': 'Reportees',
  'pages.employeeProfile.reportees.placeholder': 'Select reportees',
  'pages.employeeProfile.noChange': 'No changes made',

  /* generalInfo */
  'pages.employeeProfile.requiredField': 'Required field!',
  'pages.employeeProfile.contactNo': 'Contact No.',
  'pages.employeeProfile.contactNo.placeholder': 'Enter the Emergency Contact’s Number',
  'pages.employeeProfile.addAnotherEmergencyContact': 'Add another Emergency Contact',
  'pages.employeeProfile.employeeInformation': 'Employee Information',
  'pages.employeeProfile.fullname': 'Full Name',
  'pages.employeeProfile.employeeId': 'Employee ID',
  'pages.employeeProfile.workEmail': 'Work Email',
  'pages.employeeProfile.workEmail.placeholder': 'Enter the Work Email',
  'pages.employeeProfile.workNumber': 'Work Number',
  'pages.employeeProfile.workNumber.placeholder': 'Enter the Work Number',
  'pages.employeeProfile.adhaarCardNumber': 'Adhaar Card Number',
  'pages.employeeProfile.adhaarCardNumber.placeholder': 'Enter the Adhaar Card Number',
  'pages.employeeProfile.nationalIdentificationNumber': 'National Identification Number',
  'pages.employeeProfile.nationalIdentificationNumber.placeholder':
    'Enter the National Identification Number',
  'pages.employeeProfile.socialSecurityNumber': 'Social Security Number',
  'pages.employeeProfile.socialSecurityNumber.placeholder': 'Enter the Social Security Number',
  'pages.employeeProfile.requireLegalReasons': 'We require your gender for legal reasons.',
  'pages.employeeProfile.personalInformation': 'Personal Information',
  'pages.employeeProfile.personalNumber': 'Personal Number',
  'pages.employeeProfile.personalNumber.placeholder': 'Enter the Personal Number',
  'pages.employeeProfile.personalEmail': 'Personal Email',
  'pages.employeeProfile.personalEmail.placeholder': 'Enter the Personal Email',
  'pages.employeeProfile.bloodGroup': 'Blood Group',
  'pages.employeeProfile.maritalStatus.placeholder': 'Select the Marital Status',
  'pages.employeeProfile.nationality': 'Nationality',
  'pages.employeeProfile.nationality.placeholder': 'Enter the Nationality',
  'pages.employeeProfile.permanentAddress': 'Permanent Address',
  'pages.employeeProfile.currentAddress': 'Current Address',
  'pages.employeeProfile.contentNumber':
    'The number will be still visible to your Reporting Manager, HR and Finance teams however you can Choose to keep it hidden from other co-workers by toggling the highlighted toggle switch!',
  'pages.employeeProfile.contentEmail':
    'The email will be still visible to your Reporting Manager, HR and Finance teams however you can Choose to keep it hidden from other co-workers by toggling the highlighted toggle switch!',
  'pages.employeeProfile.addressLine1': 'Address Line 1',
  'pages.employeeProfile.addressLine1.placeholder': 'Enter the Address Line 1',
  'pages.employeeProfile.addressLine1.validate': 'Please input address',
  'pages.employeeProfile.addressLine2': 'Address Line 2',
  'pages.employeeProfile.addressLine2.placeholder': 'Enter the Address Line 2',
  'pages.employeeProfile.cityName': 'City name',
  'pages.employeeProfile.cityName.placeholder': 'Enter the City',
  'pages.employeeProfile.shortlyDisabledTitle': 'Temporarily Disabled - will be enabled shortly.',
  'pages.employeeProfile.passportDetails': 'Passport Details',
  'pages.employeeProfile.uploadedFile': 'Uploaded File:',
  'pages.employeeProfile.issuedByCountry': 'Issued By Country',
  'pages.employeeProfile.issuedOn': 'Issued On',
  'pages.employeeProfile.validTill': 'Valid Till',
  'pages.employeeProfile.passportNumber': 'Passport Number',
  'pages.employeeProfile.country': 'Country',
  'pages.employeeProfile.country.placeholder': 'Select the Country',
  'pages.employeeProfile.country.validate': 'Please choose country',
  'pages.employeeProfile.state': 'State',
  'pages.employeeProfile.state.placeholder': 'Select the State',
  'pages.employeeProfile.zipCode': 'Zip/Postal Code',
  'pages.employeeProfile.zipCode.placeholder': 'Enter the Zip/Postal Code',
  'pages.employeeProfile.sameAsAbove': 'Same as above',
  'pages.employeeProfile.professionalAcademicBackground': 'Professional & Academic Background',
  'pages.employeeProfile.preJobTitle': 'Previous Job Title',
  'pages.employeeProfile.preJobTitle.placeholder': 'Type the previous job title',
  'pages.employeeProfile.preCompany': 'Previous Company',
  'pages.employeeProfile.preCompany.placeholder': 'Type the previous company',
  'pages.employeeProfile.totalExperience': 'Total Experience',
  'pages.employeeProfile.totalExperience.inYrs': 'Total Experience (in years)',
  'pages.employeeProfile.totalExperience.placeholder': 'Type the total experience',
  'pages.employeeProfile.highestQualification': 'Highest Qualification',
  'pages.employeeProfile.highestQualification.placeholder': 'Type the highest qualification',
  'pages.employeeProfile.linkedIn': 'LinkedIn',
  'pages.employeeProfile.linkedIn.placeholder': 'Type the linkedin url',
  'pages.employeeProfile.enterName': 'Enter name',
  'pages.employeeProfile.sureToRemove': 'Sure to remove?',
  'pages.employeeProfile.addAttachments': 'Add attachments',
  'pages.employeeProfile.visaDetails': 'Visa Details',
  'pages.employeeProfile.visaNumber': 'Visa Number',
  'pages.employeeProfile.visaType': 'Visa Type',
  'pages.employeeProfile.entryType': 'Entry Type',
  'pages.employeeProfile.singleEntry': 'Single Entry',
  'pages.employeeProfile.multipleEntry': 'Multiple Entry',
  'pages.employeeProfile.validUntil': 'Valid Until',
  'pages.employeeProfile.visa': 'Visa:',

  /* ModalAddInfo */
  'pages.employeeProfile.employeeDetails': 'Employee Details',
  'pages.employeeProfile.disabledTitle': 'Temporarily Disabled - Please move to the next field.',
  'pages.employeeProfile.emergencyDetails': 'Emergency Contact Details',
  'pages.employeeProfile.bankDetail': 'Bank Details',
  'pages.employeeProfile.required':
    'You are required to fill in the below details to proceed further',
  'pages.employeeProfile.emergencyPersonName': 'Emergency Contact Name',
  'pages.employeeProfile.emergencyPersonName.placeholder': 'Enter the Emergency Contact’s Name',
  'pages.employeeProfile.emergencyPersonName.validate1': 'Please enter emergency contact name!',
  'pages.employeeProfile.emergencyPersonName.validate2': 'Invalid format, please try again',
  'pages.employeeProfile.relation': 'Relation',
  'pages.employeeProfile.relation.validate': 'Please enter relation!',
  'pages.employeeProfile.select': 'Please select a choice',
  'pages.employeeProfile.emergencyContact': 'Emergency Contacts Phone Number',
  'pages.employeeProfile.emergencyContact.validate1':
    "Please enter the emergency contact's phone number!",
  'pages.employeeProfile.emergencyContact.validate2': 'Invalid format, please try again',
  'pages.employeeProfile.AcademicBackground': 'Professional & Academic Background',
  'pages.employeeProfile.totalExp': 'Total Years of Experience',
  'pages.employeeProfile.totalExp.validate1': 'Please enter relevant years of experience!',
  'pages.employeeProfile.totalExp.validate2':
    'Input only number, greater than or equal to zero and less than 99!',
  'pages.employeeProfile.qualification': 'Highest Educational Qualification',
  'pages.employeeProfile.qualification.validate':
    'Please enter your highest educational qualification!',
  'pages.employeeProfile.certifications': 'Certifications',
  'pages.employeeProfile.addOtherCertification': 'Add another Certification',
  'pages.employeeProfile.skills': 'Skills',
  'pages.employeeProfile.skills.validate': 'Please enter skills',
  'pages.employeeProfile.bankName': 'Bank Name',
  'pages.employeeProfile.bankName.validate': 'Please enter the bank name!',
  'pages.employeeProfile.branchName': 'Branch Name',
  'pages.employeeProfile.branchName.validate': 'Please enter the branch name!',
  'pages.employeeProfile.accountType': 'Account Type',
  'pages.employeeProfile.accountType.validate': 'Please enter the account type!',
  'pages.employeeProfile.salaryAccount': 'Salary Account',
  'pages.employeeProfile.personalAccount': 'Personal Account',
  'pages.employeeProfile.accountNumber': 'Account Number',
  'pages.employeeProfile.accountNumber.validate1': 'Please enter the account number!',
  'pages.employeeProfile.accountNumber.validate2': 'Input numbers only and a max of 16 digits',
  'pages.employeeProfile.swiftcode': 'Swift Code',
  'pages.employeeProfile.swiftcode.validate': 'Please enter the swift code!',
  'pages.employeeProfile.addAnotherAccount': 'Add another Account',
  'pages.employeeProfile.limitedAccount': 'You can add upto 4 accounts',
  'pages.employeeProfile.checkingAccount': 'Checking Account',
  'pages.employeeProfile.savingsAccount': 'Savings Account',
  'pages.employeeProfile.routingNumber': 'Routing Number',
  'pages.employeeProfile.routingNumber.validate1': 'Please enter the routing number!',
  'pages.employeeProfile.routingNumber.validate2': 'Input numbers only and a max of 9 digits',
  'pages.employeeProfile.ifscCode': 'IFSC Code',
  'pages.employeeProfile.micrcCode': 'MICR Code',
  'pages.employeeProfile.micrcCode.validate': 'Please enter the MICR code!',
  'pages.employeeProfile.uanNumber': 'UAN Number',
  'pages.employeeProfile.uanNumber.placeholder': 'Enter the UAN Number',
  'pages.employeeProfile.uanNumber.validate': 'Input numbers only and a max of 16 digits',
  'pages.employeeProfile.taxDetails': 'Tax Details',
  'pages.employeeProfile.nationalId': 'National ID Card Number',
  'pages.employeeProfile.nationalId.validate': 'Please enter the National id card number',
  'pages.employeeProfile.maritalStatus': 'Marital Status',
  'pages.employeeProfile.maritalStatus.validate': 'Please select your marital status!',
  'pages.employeeProfile.noOfDependents': 'No. of Dependents',
  'pages.employeeProfile.noOfDependents.validate': 'Please enter the no. of dependents!',
  'pages.employeeProfile.residencyStatus': 'Residency Status',
  'pages.employeeProfile.residencyStatus.validate': 'Please select your residency status!',
  'pages.employeeProfile.socialSecurity': 'Social Security Card Number',
  'pages.employeeProfile.socialSecurity.validate': 'Please enter the Social security card number',
  'pages.employeeProfile.incomeTaxRule': 'Income Tax Rule',
  'pages.employeeProfile.incomeTaxRule.validate': 'Please select an Income tax rule!',
  'pages.employeeProfile.panNumber': 'PAN Number',
  'pages.employeeProfile.panNumber.validate': 'Please enter your pan number!',

  'pages.employeeProfile.setApprovalChain': 'Set Approval Chain',
  'pages.employeeProfile.approvalChain.validate': 'Please type the text field!',
  'pages.employeeProfile.approvalChain.extra': 'Type Names of Manager, or any higher authority.',
  'pages.employeeProfile.approvalChain.placeholder': 'Select your manager',
  'pages.employeeProfile.reason.validate': 'Please type the text box!',
  'pages.employeeProfile.reason.placeholder': 'Type here...',
  'pages.employeeProfile.manager': 'Manager',
  'pages.employeeProfile.manager1': 'Manager1',
  'pages.employeeProfile.manager2': 'Manager2',

  'pages.employeeProfile.search': 'Search..',
  'pages.employeeProfile.clickItemFilter': 'Click on item {key}',

  /* upload */
  'pages.employeeProfile.validateUpload': 'You can only upload JPG/PNG/PDF file!',
  'pages.employeeProfile.isLt2M': 'Image must smaller than 2MB!',
  'pages.employeeProfile.isLt5M': 'Image must smaller than 5MB!',
  'pages.employeeProfile.uploadFile': 'Upload File',

  /* chart */
  'pages.employeeProfile.loadingChart': 'Loading Chart ...',
  'pages.employeeProfile.year': 'Year',
  'pages.employeeProfile.performanceScore': 'Performance Score',
  'pages.employeeProfile.certainty': 'certainty',
  'pages.employeeProfile.tooltip': 'tooltip',
  'pages.employeeProfile.careerPathChart': 'CareerPathChart',

  /* documents */
  'pages.employeeProfile.documents.infoCollapseType2.type': 'Type',
  'pages.employeeProfile.documents.infoCollapseType2.generatedBy': 'Generated By',
  'pages.employeeProfile.documents.infoCollapseType2.uploadedBy': 'Uploaded By',
  'pages.employeeProfile.documents.infoCollapseType2.date': 'Date',
  'pages.employeeProfile.documents.infoCollapseType2.status': 'Status',
  'pages.employeeProfile.documents.viewDocument.title': 'View Document',
  'pages.employeeProfile.documents.viewDocument.goBack': 'Go back',
  'pages.employeeProfile.documents.viewDocument.documentType': 'Document Type',
  'pages.employeeProfile.documents.viewDocument.documentName': 'Document Name',
  'pages.employeeProfile.documents.viewDocument.number': 'Number',
  'pages.employeeProfile.documents.viewDocument.shareWith': 'Share with',
  'pages.employeeProfile.documents.viewDocument.emailPlaceholder': 'Select emails...',
  'pages.employeeProfile.documents.viewDocument.uploadNewBtn': 'Upload new',
  'pages.employeeProfile.documents.noDocument': 'There is no any documents',
  /* benefitTab */
  'pages.employeeProfile.BenefitTab.coveredIndividuals': 'Covered Individuals',
  'pages.employeeProfile.BenefitTab.kycDetails': 'KYC Details',
  'pages.employeeProfile.BenefitTab.electedCoverage': 'Elected Coverage',
  'pages.employeeProfile.BenefitTab.availablePlans': 'Available Benefit Plans',
  'pages.employeeProfile.BenefitTab.forGlobalEmployees': 'For Global Employees',
  'pages.employeeProfile.BenefitTab.forIndianEmployees': 'For Indian Employees',
  'pages.employeeProfile.BenefitTab.addDependant': 'Add Dependant',
  'pages.employeeProfile.BenefitTab.editDependant': 'Edit Dependant',
  'pages.employeeProfile.BenefitTab.dependent': 'Dependent',
  'pages.employeeProfile.BenefitTab.kyc.kycStat': 'KYC Status',
  'pages.employeeProfile.BenefitTab.kyc.walletStat': 'Wallet Status',
  'pages.employeeProfile.BenefitTab.kyc.adhaar': 'Adhaar Number',
  'pages.employeeProfile.BenefitTab.kyc.paytm': 'Paytm Number',
  'pages.employeeProfile.BenefitTab.health': 'Health & Wellbeing',
  'pages.employeeProfile.BenefitTab.financial': 'Financial',
  'pages.employeeProfile.BenefitTab.legal': 'Legal',
  'pages.employeeProfile.BenefitTab.plan': 'Plan',
  'pages.employeeProfile.BenefitTab.coverageEndDate': 'Coverage End Date',
  /* performanceTab */
  'pages.employeeProfile.performanceTab.syncWithEPAS': 'Click here to Sync With EPAS',
  'pages.employeeProfile.performanceHistory.performanceReview': 'Performance Reviews',
  'pages.employeeProfile.performanceHistory.performanceReview.date': 'Date',
  'pages.employeeProfile.performanceHistory.performanceReview.reportingTo': 'Reporting To',
  'pages.employeeProfile.performanceHistory.performanceReview.collaboration_teamwork':
    'Collaboration & TeamWork',
  'pages.employeeProfile.performanceHistory.performanceReview.problemSolving': 'Problem Solving',
  'pages.employeeProfile.performanceHistory.performanceReview.decisionMaking': 'Decision Making',
  'pages.employeeProfile.performanceHistory.performanceReview.organizing':
    'Organizing and Planning',
  'pages.employeeProfile.performanceHistory.projectHistory': 'Project History',
  'pages.employeeProfile.performanceHistory.projectHistory.projectName': 'Project Name',
  'pages.employeeProfile.performanceHistory.projectHistory.team': 'Team',
  'pages.employeeProfile.performanceHistory.projectHistory.status': 'Status',
  'pages.employeeProfile.performanceHistory.projectHistory.projectDuration': 'Project Duration',
  'pages.employeeProfile.performanceHistory.projectHistory.engagement': 'Engagement',
  'pages.employeeProfile.performanceHistory.career.careerGraph': 'Career Graph',
  'pages.employeeProfile.performanceHistory.career.averageScore': 'Average Score',
  'pages.employeeProfile.performanceHistory.career.duration': 'Duration',
  'pages.employeeProfile.performanceHistory.career.performanceScore': 'Performance Score',
  'pages.employeeProfile.performanceHistory.lestThan1month': 'Less than 1 month',
  'pages.employeeProfile.performanceHistory.1month': '1 Month',
  'pages.employeeProfile.performanceHistory.2month': '2 Month',
  'pages.employeeProfile.performanceHistory.3month': '3 Month',
  'pages.employeeProfile.performanceHistory.roomToImprove': 'Room to improve 😄',
  'pages.employeeProfile.performanceHistory.budding': 'Budding ⚒️',
  'pages.employeeProfile.performanceHistory.nice': 'Nice 💎',
  'pages.employeeProfile.performanceHistory.woah': 'Woah 🔥',
  /* compensation */
  'pages.employeeProfile.compensation.summary': 'Compensation Summary',
  'pages.employeeProfile.compensation.paySlips': 'Pay Slips',
  'pages.employeeProfile.compensation.form16': 'Form 16',
  'pages.employeeProfile.compensation.bankAccount': 'Bank Account',
  'pages.employeeProfile.compensation.tax': 'Tax Withholding Info',
  'pages.employeeProfile.compensation.stocks': 'Stocks',
  'pages.employeeProfile.compensation.addBankAccount': 'Add Bank Account',
  'pages.employeeProfile.compensation.limitedAccount': 'You can up to 4 account',
  'pages.employeeProfile.compensation.bankName': 'Bank Name',
  'pages.employeeProfile.compensation.bankName.placeholder': 'Bank Name',
  'pages.employeeProfile.compensation.bankName.validate': 'Please enter the bank name!',
  'pages.employeeProfile.compensation.branchName': 'Branch Name',
  'pages.employeeProfile.compensation.branchName.placeholder': 'Branch Name',
  'pages.employeeProfile.compensation.branchName.validate': 'Please enter the branch name!',
  'pages.employeeProfile.compensation.accountType': 'Account Type',
  'pages.employeeProfile.compensation.accountType.validate': 'Please enter the account type!',
  'pages.employeeProfile.compensation.accountNumber': 'Account Number',
  'pages.employeeProfile.compensation.accountNumber.validate1': 'Please enter the account number!',
  'pages.employeeProfile.compensation.accountNumber.validate2':
    'Input numbers only and a max of 16 digits',
  'pages.employeeProfile.compensation.swiftcode': 'Swift Code',
  'pages.employeeProfile.compensation.swiftcode.placeholder': 'Swift Code',
  'pages.employeeProfile.compensation.swiftcode.validate': 'Please enter the swift code!',
  'pages.employeeProfile.compensation.routingNumber': 'Routing Number',
  'pages.employeeProfile.compensation.routingNumber.placeholder': 'Routing Number',
  'pages.employeeProfile.compensation.routingNumber.validate1': 'Please enter the routing number!',
  'pages.employeeProfile.compensation.routingNumber.validate2':
    'Input numbers only and a max of 9 digits',
  'pages.employeeProfile.compensation.salaryAccount': 'Salary Account',
  'pages.employeeProfile.compensation.personalAccount': 'Personal Account',
  'pages.employeeProfile.compensation.accountName': 'Account Name',
  'pages.employeeProfile.compensation.accountName.placeholder': 'Account Name',
  'pages.employeeProfile.compensation.accountName.validate': 'Please enter the account name!',
  'pages.employeeProfile.compensation.payDetail': 'Pay Details (Yearly basis)',
  'pages.employeeProfile.compensation.payHistory': 'Pay History',
  'pages.employeeProfile.compensation.annualCTC': 'Current Annual CTC',
  'pages.employeeProfile.compensation.basic': 'Basic',
  'pages.employeeProfile.compensation.otherAllowances': 'Other Allowances',
  'pages.employeeProfile.compensation.variablePayTraget': 'Variable Pay Traget %',
  'pages.employeeProfile.compensation.viewGrossPay': '- View Gross Pay',
  'pages.employeeProfile.compensation.viewDeductions': '+ View Deductions',
  'pages.employeeProfile.compensation.changeType': 'Change Type',
  'pages.employeeProfile.compensation.salary': 'Salary',
  'pages.employeeProfile.compensation.effectiveDate': 'Effective Date',
  'pages.employeeProfile.compensation.initiatedDate': 'Initiated Date',
  'pages.employeeProfile.compensation.changedBy': 'Changed By',
  'pages.employeeProfile.compensation.changeDate': 'Changed Date',
  'pages.employeeProfile.compensation.showing': 'Showing',
  'pages.employeeProfile.compensation.of': 'of',
  'pages.employeeProfile.compensation.grossPay': 'Gross Pay',
  'pages.employeeProfile.compensation.deductions': 'Deductions',
  'pages.employeeProfile.compensation.netPay': 'Net Pay',
  'pages.employeeProfile.compensation.paySlipAugust': 'Pay Slip - August',
  /* requestDetails */
  'pages.employeeProfile.requestDetails.requestType': 'Request Type',
  'pages.employeeProfile.requestDetails.requestType.placeholder': 'Select the type',
  'pages.employeeProfile.requestDetails.requestType.validate': 'Please select the type',
  'pages.employeeProfile.requestDetails.additionalInfo': 'Additional Info',
  'pages.employeeProfile.requestDetails.eligibilityRequest': 'Request Proof of Eligibility',
  /* raiseTermination */
  'pages.employeeProfile.happenChanged': 'A change that already happened.',
  'pages.employeeProfile.immediateChanged': 'An immediate change.',
  'pages.employeeProfile.scheduledChanged': 'Scheduled change.',
  'pages.employeeProfile.raiseTermination.changeTakeEffect':
    'When do you wish the changes to take effect?',
  'pages.employeeProfile.raiseTermination.selectLeaveDate': 'Please select Leave from date',
  'pages.employeeProfile.raiseTermination.dateChanged': 'Please select date changed !',
  /* putOnLeave */
  'pages.employeeProfile.putOnLeave.warning':
    'This will put {fullName} on leave for the days selected without pay, a Notification for the update will be sent to the employee as well.',
  'pages.employeeProfile.putOnLeave.leaveFrom': 'Leave From',
  'pages.employeeProfile.putOnLeave.leaveFrom.validate': 'Please select Leave from date',
  'pages.employeeProfile.putOnLeave.leaveTo': 'Leave To',
  'pages.employeeProfile.putOnLeave.leaveTo.validate': 'Please select Leave to date',
  'pages.employeeProfile.addMore': 'Add more',
  'pages.employeeProfile.warning':
    ' This will put {fullName} on leave for the days selected without pay, a Notification for the update will be sent to the employee as well.',
};
