export default {
  'component.employeeOnboarding.onboardingOverview': 'Onboarding overview',
  'component.employeeOnboarding.settings': 'Settings',
  'component.employeeOnboarding.newJoinees': 'New Joinees',
  'component.employeeOnboarding.customFields': 'Custom fields',
  'component.employeeOnboarding.generate': 'Export',
  'component.employeeOnboarding.viewActivityLogs': 'View Activity log ',
  'component.onboardingOverview.viewActivityLogs': 'View Activity log ',
  'component.onboardingOverview.sentEligibilityForms': 'Sent Eligibility forms ',
  'component.onboardingOverview.receivedSubmittedDocuments': 'Received Submitted Documents',
  'component.receivedSubmittedDocuments.rookieId': 'Rookie Id',
  // Onboard Table
  'component.onboardingOverview.candidateId': 'Candidate Id',
  'component.onboardingOverview.candidateName': 'Candidate Name',
  'component.onboardingOverview.position': 'Position',
  'component.onboardingOverview.location': 'Location',
  'component.onboardingOverview.dateSent': 'Date sent',
  'component.onboardingOverview.dateReceived': 'Date received',
  'component.onboardingOverview.dateJoin': 'Date of joining',
  'component.onboardingOverview.documentVerified': 'No. Of documents verified',
  'component.onboardingOverview.resubmit': 'Resubmits',
  'component.onboardingOverview.expire': 'Expires on',
  'component.onboardingOverview.changeRequest': 'Change request',
  'component.onboardingOverview.requestDate': 'Request date',
  'component.onboardingOverview.comments': 'Comments',
  'component.onboardingOverview.actions': 'Actions',
  'component.onboardingOverview.viewDraft': 'View Draft',
  'component.onboardingOverview.new': 'new',
  'component.onboardingOverview.review': 'review',
  'component.onboardingOverview.prepareProvisionalOffer': 'prepare provisional offer',
  'component.onboardingOverview.draftFinalOffer': 'draft final offer',
  'component.onboardingOverview.viewForm': 'view form',
  'component.onboardingOverview.viewDraft2': 'view draft',
  'component.onboardingOverview.sendOffer': 'send offer',
  'component.onboardingOverview.sendForApproval': 'send for approval',
  'component.onboardingOverview.createProfile': 'send for approval',
  'component.onboardingOverview.noData': 'No data',
  // Left menu
  'component.onboardingOverview.pendingEligibilityChecks': 'Pending Eligibility Checks',
  'component.onboardingOverview.addTeamMember': 'Add team member',
  // Settings document and templates
  'component.documentAndTemplates.title': 'Document & Templates',
  'component.documentAndTemplates.subTitle':
    'You can manage all of your documents , templates and custom emails here. The app can generate and send your company’s offer letters, employee handbooks, hiring agreements and custom emails to your new hires.',
  'component.documentAndTemplates.download': 'Download',
  'component.documentAndTemplates.delete': 'Delete',
  'component.documentAndTemplates.defaultTemplate': 'System default templates',
  'component.documentAndTemplates.recentDocuments': 'Recent documents',
  // Settings non extemp notice
  'component.nonExtempNotice.title': 'Non-Extempt Notice',
  'component.nonExtempNotice.formTitle': `Worker's compensation`,
  'component.nonExtempNotice.isSelfInsured': 'Are you self-insured?',
  'component.nonExtempNotice.carrierName': `Insurance carrier's name`,
  'component.nonExtempNotice.carrierAddress': `Insurance carrier's address`,
  'component.nonExtempNotice.phoneNumber': `Phone number`,
  'component.nonExtempNotice.policyNumber': `Policy number`,
  'component.nonExtempNotice.save': `Save`,
  'component.nonExtempNotice.yes': `Yes`,
  'component.nonExtempNotice.no': `No`,
  // Background checks
  'component.backgroundChecks.title': `Background checks`,
  'component.backgroundChecks.subTitle': `Run background checks on new and existing workers.`,
  'component.backgroundChecks.learnMore': `Learn more`,
  'component.backgroundChecks.generalSettings': `General Settings`,
  'component.authorization.title': `Authorization`,
  'component.authorization.link': `Change signatory`,
  'component.backgroundCheck.title': `Background Check`,
  'component.billingInformation.title': `  Billing information for background check`,
  // Optional Onboaring Questions
  'component.optionalOnboardingQuestions.title': `Optional Onboarding Questions`,
  'component.optionalOnboardingQuestions.subTitle': `During onboarding we will collect information from your new hires`,
  'component.optionalOnboardingQuestions.addCustomFields': `+ Add custom fields`,
  'component.optionalOnboardingQuestions.customFields': `Custom fields`,
  'component.optionalOnboardingQuestions.newSection': `+ New Section`,
  'component.optionalOnboardingQuestions.newField': `+ New Field`,
  'component.optionalOnboardingQuestions.sectionName': `Section name`,
  'component.optionalOnboardingQuestions.fieldName': `Field name`,
  'component.optionalOnboardingQuestions.saveOrdering': `Save ordering`,
  'component.optionalOnboardingQuestions.addQuestion': `Add more questions`,
  // Settings custom emails
  'component.emailReminderNote.title': 'Note',
  'component.emailReminderNote.note1':
    'Custom Email messages are a great way to recognize important dates and milestones.',
  'component.emailReminderNote.note2':
    'For example, you can remind managers of their team members’ start dates or create reminders for events, like license renewals or 30 day check-ins. ',
  'component.emailReminderNote.note3':
    'You can use the Auto Text feature to generate personalized emails from a template.',
  'component.emailReminderHeader.title': 'Create a custom email reminder',
  'component.emailReminderForm.title': 'Create a custom email reminder',
  'component.emailReminderForm.triggerNote': 'You can add additional events with',
  'component.emailReminderForm.triggerNoteLink': 'Custom fields',
  'component.emailReminderForm.addCondition': '+ Add another condition',
  'component.emailReminderForm.cancel': 'Cancel',
  'component.emailReminderForm.submit': 'Submit',
  'component.customEmailsTableField.title': 'Custom emails',
  'component.customEmailsTableField.description':
    'Cras gravida bibendum dolor eu varius. Morbi fermentum velit nisl, eget vehicula lorem sodales eget. Donec quis volutpat orci. Sed ipsum felis, tristique id egestas et, convallis ac velit.',
  'component.customEmailsTableField.titleTable': 'Custom emails created',
  'component.customEmailsTableField.pagination.showing': 'Showing',
  'component.customEmailsTableField.pagination.of': 'of',
  'component.customEmailsTableField.emailSubject': 'Email subject',
  'component.customEmailsTableField.createdOn': 'Created On',
  'component.customEmailsTableField.triggerEvent': 'Trigger Event',
  'component.customEmailsTableField.frequency': 'Frequency',
  'component.customEmailsTableField.actions': 'Actions',

  // Company Signatory
  'component.companySignatory.title': 'Company Signatory',
  'component.companySignatory.description':
    "The signature will be used on all relieving and experience letters. An authorized signatory is someone who will sign all the letters on company's behalf.",
  // Edit email
  'component.editEmailNote.title': 'Note',
  'component.editEmailNote.note1':
    'Custom Email messages are a great way to recognize important dates and milestones.',
  'component.editEmailNote.note2':
    'For example, you can remind managers of their team members’ start dates or create reminders for events, like license renewals or 30 day check-ins. ',
  'component.editEmailNote.note3':
    'You can use the Auto Text feature to generate personalized emails from a template.',
  'component.customEmailsTableField.editEmail': 'Edit email',
  'component.editEmailHeader.defaultTitle': 'View a system default email',
  'component.editEmailHeader.title': 'Edit a custom email reminder',
  'component.editEmailForm.addCondition': '+ Add another condition',
  'component.editEmailForm.triggerNote': 'You can add additional events with',
  'component.editEmailForm.triggerNoteLink': 'Custom fields',
  'component.editEmailForm.cancel': 'Cancel',
  'component.editEmailForm.submit': 'Submit',
  'component.editEmailForm.title': 'Edit a custom email',
};
