export default {
  'pages.helpPage.updateSetting': 'Please update data in the setting page',
  'pages.helpPage.settings': 'Settings',
  'pages.helpPage.support24/7':
    'Our support team is waiting to help you 24/7. Get an emailed response from our team.',
  'pages.helpPage.contactUs': 'Contact Us',
  'pages.helpPage.needHelp': 'Still need our help?',
  'pages.helpPage.name': '{name} Name',
  'pages.helpPage.enterName': 'Enter the {name} name',
  'pages.helpPage.addName': 'Add {name}',
  'pages.helpPage.editName': 'Edit {name}',
  'pages.helpPage.viewName': 'View {name}',
  'pages.helpPage.deleteName': 'Delete {name}',
  'pages.helpPage.updateName': 'Update {name}',
  'pages.helpPage.table.numOf': 'No. of {name}',
  'pages.helpPage.selectName': 'Select the {name}',
  'pages.helpPage.searchTopic': 'Search by topic or description',
  'pages.helpPage.validate.selectCountry': 'Please select the country',
  'pages.helpPage.validate.existName': '{name} is exist',
  'pages.helpPage.validate.requiredField': 'Required field!',
  'pages.helpPage.validate.questionExist': 'This question is exist',
  'pages.helpPage.validate.maxTopicCharacter': 'Topic must be maximum 500 characters.',
  'pages.helpPage.validate.maxDescriptionCharacter': 'Description must be maximum 2000 characters.',
  'pages.helpPage.table.category': 'Category Name',
  'pages.helpPage.table.action': 'Action',
  'pages.helpPage.editCategory': 'Edit Category',
  'pages.helpPage.enterCategory': 'Enter Category',
  'pages.helpPage.saveChanges': 'Save Changes',
  'pages.helpPage.deleteYes': 'Yes, delete',
  'pages.helpPage.confirmDelete': 'Are you sure you want to delete the item ',
  'pages.helpPage.category': 'Category',
  'pages.helpPage.categoryName': 'Category Name',
  'pages.helpPage.categories': 'Categories',
  'pages.helpPage.addCategories': 'Add Categories',
  'pages.helpPage.faqCategories': 'FAQ Categories',
  'pages.helpPage.faqCategory': 'FAQ Category',
  'pages.helpPage.faqList': 'FAQ List',
  'pages.helpPage.FAQ': 'Frequently Asked Questions',
  'pages.helpPage.addFAQ': 'Add FAQ',
  'pages.helpPage.editFAQ': 'Edit FAQ',
  'pages.helpPage.question': 'Question',
  'pages.helpPage.answer': 'Answer',
  'pages.helpPage.faqSearch': 'Search by question or answer',
  'pages.helpPage.helpCategories': 'Help Center Categories',
  'pages.helpPage.helpTopics': 'Help Center Topics',
  'pages.helpPage.topics': 'Topics',
  'pages.helpPage.topic': 'Topic',
  'pages.helpPage.searchByTopic': 'Search by topic or description',
  'pages.helpPage.helpCategory': 'Help Category',
  'pages.helpPage.description': 'Description',
  'pages.helpPage.uploadMedia': 'Upload Media File',
  'pages.helpPage.addedBy': 'Added By',
  'pages.helpPage.addedOn': 'Added On',
  'pages.helpPage.byCategoryName': 'By Category Name',
  'pages.helpPage.searchByCategory': 'Search by Category Name',
  'pages.helpPage.byCreator': 'By Creator',
  'pages.helpPage.searchByCreator': 'Search by Creator',
  'pages.helpPage.byCreatedDate': 'By Created Date',
  'pages.helpPage.byDuration': 'By Duration',
  'pages.helpPage.signPolicy':
    'Sign this document to certify that you have read all the policy documents.',
  'pages.helpPage.sign': 'Sign',
  'pages.helpPage.signed': 'Signed',
  'pages.helpPage.readPolicy':
    'Please read all the policy documents and sign to mark your acceptance. Please reach out to the HR in case of any questions.',
  'pages.helpPage.acknowledgement': 'Acknowledgement',
  'pages.helpPage.instructions': 'Instructions',
  'pages.helpPage.signatureEmployee': 'Signature of the employee',
  'pages.helpPage.thank': 'Thank you!',
  'pages.helpPage.documentSent':
    'A copy of the signed document has been sent to you and the HR. You can also find this document under the Documents tab of Employee Profile.',
  'pages.helpPage.policies': 'Policies',
  'pages.helpPage.policiesCertification': 'Policy Certification',
  'pages.helpPage.exportPolicies': 'Export Policy Certification',
  'pages.helpPage.policiesCategories': 'Policy Categories',
  'pages.helpPage.policiesRegulations': 'Policies & Regulations',
  'pages.helpPage.addPolicy': 'Add Policy',
  'pages.helpPage.deletePolicy': 'Delete Policy',
  'pages.helpPage.editPolicy': 'Edit Policy',
  'pages.helpPage.policyName': 'Policy Name',
  'pages.helpPage.searchPolicy': 'Search by Policy name',
  'pages.helpPage.addPoliciesCategories': 'Add Policies Categories',
  'pages.helpPage.categoriesName': 'Categories Name',
  'pages.helpPage.documentCount': 'Document Count',
  'pages.helpPage.deletePoliciesCategories': 'Delete Policies Categories',
  'pages.helpPage.editPoliciesCategories': 'Edit Policies Categories',
  'pages.helpPage.selectCountry': 'Please select country',
  'pages.helpPage.enterCategoriesName': 'Please enter the categories name',
  'pages.helpPage.selectPolicyCategories': 'Please select Policy Categories',
  'pages.helpPage.selectPolicies': 'Please select Policies',
  'pages.helpPage.enterPolicyName': 'Please enter Policy Name',
  'pages.helpPage.existPolicyName': 'Policy Name is exist',
  'pages.helpPage.categoriesNameExist': 'Categories Name is exist',
  'pages.helpPage.onlyUploadPDF': 'You can only upload image and PDF file!',
  'pages.helpPage.invalidFile': 'Invalid file',
  'pages.helpPage.dropFile': 'Drop file here',
  'pages.helpPage.browse': 'browse',
  'pages.helpPage.toUpload': 'to upload file',
  'pages.helpPage.fileAndSizeSupport':
    'Maximum file size is 5MB. Supported file types are pdf & jpeg',
  'pages.helpPage.viewDocument': 'View Document',
  'pages.helpPage.uploadDocument': 'Upload Document',
  'pages.helpPage.policyDocument': 'Policy Document',
};
