export default {
  'pages.home.notifyMess': 'You have',
  'pages.home.isFillTimesheet': 'Have you filled in your Timesheet yet?',
  'pages.home.announcements': 'Announcements',
  'pages.home.isAnnouncements': 'No Announcements',
  'pages.home.editPost': 'Edit post',
  'pages.home.newPost': 'New post',
  'pages.home.deletePostMess': 'Are you sure you want to delete this post?',
  'pages.home.social': 'Social',
  'pages.home.shareSomething': 'let share something today',
  'pages.home.enterDescription': 'Enter the description',
  'pages.home.charLimit': 'Character Limit',
  'pages.home.mediaFile': 'Media file',
  'pages.home.chooseFiles': 'Choose files',
  'pages.home.dropFiles': 'or drop files here',
  'pages.home.fileSizeAndFormat':
    'Maximum file size is 5MB. Supported file formats are png, jpg, jpeg, mp4 & mov',
  'pages.home.hidePost': 'Hide this post',
  'pages.home.flagPost': 'Flag as inappropriate',
  'pages.home.noComment': 'No comment',
  'pages.home.addComment': 'Add a comment...',
  'pages.home.approvalPage': 'Approval Page',
  'pages.home.noBanners': 'No banners',
  'pages.home.letsCelebrate': 'Lets celebrate',
  'pages.home.sayBirthday': 'Say Happy Birthday!',
  'pages.home.sayCongratulation': 'Say Congratulations!',
  'pages.home.congratulations': 'Congratulations',
  'pages.home.onCompleting': 'on completing',
  'pages.home.happyBirthday': 'Happy birthday',
  'pages.home.upBirthday': 'Upcoming birthday',
  'pages.home.txtYear': 'year',
  'pages.home.txtYears': 'years',
  'pages.home.txtWith': 'with',
  'pages.home.welcomeNewbie': 'Welcome to the team Newbie !!!',
  'pages.home.birthdayEmpty': 'No birthday today',
  'pages.home.gallery': 'Gallery',
  'pages.home.myTeam': 'My Team',
  'pages.home.myTickets': 'My Tickets',
  'pages.home.myCalendar': 'My Calendar',
  'pages.home.quickLinks': 'Quick Links',
  'pages.home.editQuickLink': 'Edit Quick Link',
  'pages.home.newQuickLink': 'New Quick Link',
  'pages.home.flagAsInappropriate': 'Flag as Inappropriate',
  // Settings
  'pages.home.employeesVotedOption': 'employees voted for this option',
  'pages.home.numberOfEmloyeesVoted': 'Number of Employees whose votes have been recorded.',
  'pages.home.pollEndsOn': 'Poll Ends on',
  'pages.home.howDoYouFeel': 'How do you feel about getting back to office?',
  'pages.home.addUpTo3Response': '(Add upto 3 responses)',
  // Tab name
  'pages.home.postManagement': 'Post Management',
  'pages.home.quickLinkManagement': 'Quick Link Management',
  'pages.home.employeePost': 'Employee’s Post',
  'pages.home.general': 'General',
  'pages.home.forTimeoff': 'For Timeoff',
  // PlaceHolder
  'pages.home.employeePlaceHolder': 'Select by the user who created',
};
