export default {
  // main
  'menu.welcome': 'Welcome',
  'menu.more-blocks': 'More Blocks',
  'menu.home': 'Home',
  'menu.home-settings': 'Settings',
  'menu.home-settings.add-post': 'New Post',
  'menu.login': 'Login',
  'menu.register': 'Register',
  'menu.register.result': 'Register Result',
  'menu.dashboard.analysis': 'Analysis',
  'menu.dashboard.monitor': 'Monitor',
  'menu.dashboard.workplace': 'Workplace',
  'menu.exception.403': '403',
  'menu.exception.404': '404',
  'menu.exception.500': '500',
  'menu.form': 'Form',
  'menu.form.basic-form': 'Basic Form',
  'menu.form.step-form': 'Step Form',
  'menu.form.step-form.info': 'Step Form(write transfer information)',
  'menu.form.step-form.confirm': 'Step Form(confirm transfer information)',
  'menu.form.step-form.result': 'Step Form(finished)',
  'menu.form.advanced-form': 'Advanced Form',
  'menu.list': 'List',
  'menu.list.table-list': 'Search Table',
  'menu.list.basic-list': 'Basic List',
  'menu.list.card-list': 'Card List',
  'menu.list.search-list': 'Search List',
  'menu.list.search-list.articles': 'Search List(articles)',
  'menu.list.search-list.projects': 'Search List(projects)',
  'menu.list.search-list.applications': 'Search List(applications)',
  'menu.profile': 'Profile',
  'menu.profile.basic': 'Basic Profile',
  'menu.profile.advanced': 'Advanced Profile',
  'menu.result': 'Result',
  'menu.result.success': 'Success',
  'menu.result.fail': 'Fail',
  'menu.exception': 'Exception',
  'menu.exception.not-permission': '403',
  'menu.exception.not-find': '404',
  'menu.exception.server-error': '500',
  'menu.exception.trigger': 'Trigger',
  'menu.account': 'Account',
  'menu.account.center': 'Account Center',
  'menu.account.settings': 'Account Settings',
  'menu.account.trigger': 'Trigger Error',
  'menu.account.logout': 'Logout',
  'menu.editor': 'Graphic Editor',
  'menu.editor.flow': 'Flow Editor',
  'menu.editor.mind': 'Mind Editor',
  'menu.editor.koni': 'Koni Editor',
  'menu.change-password': 'Change Password',
  // control panel
  'menu.control-panel.name': 'Control Panel',
  'menu.control-panel.companyProfile': 'Company Profile',

  // admin app
  'menu.admin': 'Admin',
  'menu.admin-app': 'Admin App',
  'menu.admin.sub-page': 'Sub-Page',
  'menu.users': 'Users Management',
  'menu.employees': 'Employees Management',
  'menu.candidates': 'Candidates Management',
  'menu.companies': 'Companies Management',
  'menu.add-company': 'Add Company',
  'menu.company-detail': 'Company Detail',
  'menu.documents': 'Documents Management',
  'menu.timeoff-management': 'Timeoff Management',
  'menu.offboarding-management': 'Offboarding Management',
  'menu.settings': 'Settings',
  'menu.permission': 'Permission',
  'menu.user-profile': 'User Profile',
  // onboarding
  'menu.onboarding': 'Onboarding',
  'menu.employee-onboarding': 'Employee Onboarding',
  'menu.add-team-member': 'Add a team member',
  'menu.onboarding.create-field-section': 'Create custom field section',
  'menu.create-email-reminder': 'Create Email Reminder',
  'menu.edit-email': 'Edit Email',
  'menu.view-email': 'View Email',
  // offboarding
  'menu.offboarding': 'Offboarding',
  'menu.ticket-id': 'Ticket Id',
  'menu.offboarding.relieving-detail': 'Ticket Id',
  'menu.resignation-request': 'Resignation Request',
  'menu.review-resignation-ticket': 'Review Ticket',
  'menu.create-custom-email': 'Create custom email',
  'menu.offboarding.template.email': 'Offboarding Template Details',
  'menu.offboarding.setting.form.view-form': 'View form',
  'menu.offboarding.setting.form.add-form': 'Add custom form',
  'menu.offboarding.setting.form.edit-form': 'Edit form',
  // timeoff
  'menu.time-off': 'Timeoff',
  'menu.request-for-timeoff': 'Request for Timeoff',
  'menu.edit-timeoff-request': 'Edit timeoff request',
  'menu.view-timeoff-request': 'View timeoff request',
  'menu.request-for-compoff': 'Request for Comp Off Balance',
  'menu.edit-compoff-request': 'Edit comp off request',
  'menu.view-compoff-request': 'View comp off request',
  'menu.time-off-type-configuration': 'Configure timeoff type',
  'menu.timeoff-setup': 'Setup Timeoff policy',
  'menu.timeoff-history': 'Timeoff History',
  'menu.timeoff-overview': 'Overview',
  // project management
  'menu.project-management': 'Project Management',
  'menu.project-management.view-project': 'View Project',
  // ticket management
  'menu.ticket-management': 'Ticket Management',
  'menu.ticket-management.view-ticket': 'View Ticket',
  'menu.ticket-management.settings': 'Settings',
  'menu.ticket-management.settings.config': 'Configure support team',
  // resource management
  'menu.resource-management': 'Resource Management',
  // customer management
  'menu.view-customer': 'View Customer',
  'menu.customer-management': 'Customer Management',
  // directory
  'menu.directory': 'Directory',
  'menu.employee-profile': 'Employee Profile',
  // candidate onboarding
  'menu.candidate-profile': 'Candidate Profile',
  'menu.candidate-detail': 'Candidate Detail',
  'menu.candidate-portal': 'Candidate Portal',
  'menu.candidate-change-password': 'Candidate Change Password',

  // dashboard
  'menu.dashboard': 'Dashboard',
  'menu.dashboard-approvals': 'Approvals',
  // search
  'menu.search-result': 'Search Result',
  'menu.search-result.advanced-search': 'Advanced Search',
  // timesheet
  'menu.timesheet': 'Timesheet',

  // Reports
  'menu.reports': 'Reports',

  // policies regulation
  'menu.policies-regulations': 'Policies & Regulations',
  'menu.policies-certification': 'Policies Certification',

  // others
  'menu.view-document': 'View Document',
  'menu.template-details': 'Template Details',
  'menu.create-new-template': 'Create New Template',
  'menu.upload-document': 'Add Document',
  'menu.create-template': 'Create New Template',
  'menu.faqs': 'FAQs',
  'menu.hrms-help-center': 'HR-OS Help Center',
};
