/* eslint-disable react/react-in-jsx-scope */
export default {
  'component.reminder.title': 'Reminder',
  'component.reminder.content':
    'This will be used to login to Terralogic portal once the candidate is confirmed as an employee. This field cannot be viewed by the candidate yet.',
  'component.basicInformation.step1': 'Previous experience in years',
  'component.basicInformation.title': 'Basic Information',
  'component.basicInformation.subtitle': 'Please verify your details below',
  'component.basicInformation.firstName': 'First Name',
  'component.basicInformation.middleName': 'Middle Name',
  'component.basicInformation.lastName': 'Last Name',
  'component.basicInformation.employeeId': 'Employee Id',
  'component.basicInformation.firstNameRequiredAlert': 'Please input your first name!',
  'component.basicInformation.middleNameRequiredAlert': 'Please input your middle name!',
  'component.basicInformation.lastNameRequiredAlert': 'Please input your last name!',
  'component.basicInformation.privateEmail': 'Personal e-mail id',
  'component.basicInformation.workEmail': 'Work email id',
  'component.basicInformation.experienceYear':
    'Previous Experience in years (relevant to this role)',
  'component.jobDetail.title': 'Job Details',
  'component.jobDetail.subtitle':
    'The details of the position the candidate is being recruited for',
  'component.jobDetail.positionTab': 'Position',
  'component.jobDetail.positionTabRadio1': 'Employee',
  'component.jobDetail.positionTabRadio2': 'Contingent worker',
  'component.jobDetail.classificationTab': 'Classification',
  'component.jobDetail.classificationRadio1':
    'Full-Time (Employee working more than 30 hours a week)',
  'component.jobDetail.classificationRadio2':
    'Part-Time (Employee working less than 30 hours a week)',
  'component.jobDetail.classificationRadio3':
    'Internship (A student or trainee participating in an internship)',
  'component.jobDetail.jobGrade': 'Grade',
  'component.jobDetail.department': 'Department',
  'component.jobDetail.jobTitle': 'Job Title',
  'component.jobDetail.jobCategory': 'Job Category',
  'component.jobDetail.city': 'City',
  'component.jobDetail.country': 'Country',
  'component.jobDetail.workLocation': 'Work Location',
  'component.jobDetail.reportingManager': 'Reporting Manager',
  'component.jobDetail.filledByCandidate':
    'Please add a tentative joining date for the candidate below.',
  'component.jobDetail.candidateNoticePeriod': `Candidate's notice Period`,
  'component.jobDetail.prefferedDateOfJoining': 'Preferred date of joining',
  'component.jobDetail.reminder.content': 'Anticipated Date of joining by the company',
  'component.jobDetail.reminder.content2': '22nd September, 2020',

  'component.offerDetail.title': 'Offer details',
  'component.offerDetail.subtitle': `All documents supporting candidate's employment eligibility will be display here`,
  'component.offerDetail.offerLetter': 'Offer letter',
  'component.offerDetail.notInclude': 'Do not include offer letter',
  'component.offerDetail.include': 'Use an existing offer letter',
  'component.offerDetail.uploadOffer': 'Upload offer letter',
  'component.offerDetail.agreementTitle': 'Hiring agreements',
  'component.offerDetail.agreement': 'Default YC IP / Confidentiality Agreement',
  'component.offerDetail.handbookTitle': 'Company handbook',
  'component.offerDetail.handbook': `My company's handbook`,
  'component.offerDetail.compensationTitle': 'Compensation type',
  'component.offerDetail.amountTitle': 'Amount in',
  'component.offerDetail.timeoffTitle': 'Time off Policy',
  'component.offerDetail.alertContent1': 'This offer letter will be sent in ',
  'component.offerDetail.phase3': 'Phase 3',
  'component.offerDetail.alertContent2': ' of the onboarding process. ',
  'component.offerDetail.alertContent3': 'To view salary related insights, explore the ',
  'component.offerDetail.alertContent4': 'Compensation Management App',
  'component.offerDetail.alertContent5':
    'Are you sure? This hire will not be able to submit any time off requests.',
  'component.previewOffer.title': 'employee agreement',
  'component.previewOffer.hrSignature': 'Signature of the HR',
  'component.previewOffer.candidateSignature': 'Signature of the Candidate',
  'component.previewOffer.undersigned': 'Undersigned - Ms Riddhima Chaudhary',
  'component.previewOffer.managerSignature': 'Signature of the HR Manager',
  'component.previewOffer.managerUndersigned': 'Undersigned - Ms. Bhumika Vaidya',
  'component.previewOffer.uploadNew': 'Upload new',
  'component.previewOffer.upload': 'Upload',
  'component.previewOffer.submit': 'Submit',
  'component.previewOffer.submitted': 'Signature submitted',
  'component.previewOffer.send': 'Send for approval',
  'component.previewOffer.note1': 'By default notifications ',
  'component.previewOffer.note2': 'will be sent to HR',
  'component.previewOffer.note3':
    ', your manager and recursively loop to your department head for approval.',
  'component.previewOffer.also':
    'Also, add e-mail of the new joinee. You can send the offer once all approvals are inorder.',
  'component.previewOffer.hrMail': 'HR Email ID',
  'component.previewOffer.invalidMailErr': 'The input is not valid email!',
  'component.previewOffer.emptyMailErr': 'Please input your email!',
  'component.previewOffer.sendForApproval': 'Send for approval',
  'component.customField.title': 'custom fields',
  'component.customField.subTitle':
    ' All documents supporting candidate’s employment eligibility will be displayed here',
  'component.customField.dentalLabel': 'dental contribution tier*',
  'component.customField.visionLabel': 'vision contribution tier*',
  'component.customField.medicalLabel': 'medical contribution tier*',
  'component.customField.additionalLabel': 'additional information',
  'component.noteComponent.content': `Onboarding is a step-by-step process. It takes anywhere around working days for entire process to complete`,
  'component.noteComponent.title': 'Note',
  'component.salaryStructureHeader.title': 'Salary Structure',
  'component.salaryStructureHeader.subTitle1':
    'The pay division is as per the selected Job title. Additionally you may enter a new salary structure. To do so',
  'component.salaryStructureHeader.subTitle2': ' Download salary structure template',
  'component.salaryStructureHeader.subTitle3': ' and upload',
  'component.salaryStructure.tableWrapper':
    ' The table of salary structure should populate here. Need clarification here if this table or information is editable by the HR?',
  'component.salaryAcceptanceContent.content': 'Acceptance of salary structure by candidate',
  'component.salaryAcceptance.title1': 'The salary structure has been accepted by the candidate.',
  'component.salaryAcceptance.note1':
    'You have gone through all the contents of the table and accept the salary as terms of your employment.',
  'component.salaryAcceptance.title2':
    'A re-negotiation has been asked by the candidate on the salary structure',
  'component.salaryAcceptance.note2':
    'You have gone through all the contents of the table. However, I would like to renegotiate.',
  'component.salaryAcceptance.title3': 'The salary structure has been rejected by the candidate.',
  'component.salaryAcceptance.note3':
    'You have gone through all the contents of the table and do not accept the offer given to me.',
  'component.salaryAcceptance.closeCandidature': ' Close Candidature',
  'component.salaryAcceptance.pendingMessage':
    'We are waiting for Ms. Ashwini Narayana to mark the acceptance of the shared salary structure',
  'component.salaryAcceptance.sendFormAgain': ' Send form again',
  'component.salaryAcceptance.submitForm': 'Submit form',
  'component.salaryAcceptance.sendEmail': 'Send email',
  'component.salaryAcceptance.acceptanceTitle': 'Acceptance of salary structure',
  'component.salaryAcceptance.note':
    '  The Salary structure has been sent as a provisional offer. The candidate must acknowledge the salary structure as a part of final negotiation in order to proceed.',
  'component.salaryStructureTemplate.done': 'Done',
  'component.salaryStructureTemplate.edit': 'Edit',
  'component.eligibilityDocs.TypeA': 'Type A: Identity Proof',
  'component.eligibilityDocs.aadharCard': 'Aadhar Card',
  'component.eligibilityDocs.pan': 'PAN',
  'component.eligibilityDocs.passport': 'Passport',
  'component.eligibilityDocs.drivingLicense': 'Driving License',
  'component.eligibilityDocs.voterCard': 'Voter Card',
  'component.eligibilityDocs.TypeB': 'Type B: Address Props',
  'component.eligibilityDocs.rentalAgreement': 'Rental Agreement',
  'component.eligibilityDocs.electricityUtilityBills': 'Electricity & Utility Bills',
  'component.eligibilityDocs.telephoneBills': 'Telephone Bills',
  'component.eligibilityDocs.TypeC': 'Type C: Educational',
  'component.eligibilityDocs.sslc': 'SSLC',
  'component.eligibilityDocs.intermediateDiploma': 'Intermediate/Diploma',
  'component.eligibilityDocs.graduation': 'Graduation',
  'component.eligibilityDocs.postGraduate': 'Post Graduate',
  'component.eligibilityDocs.phdDoctorate': 'PHD/Docturate',
  'component.eligibilityDocs.TypeD': 'Type D: Technical Certifications',
  'component.eligibilityDocs.TypeE': 'Type E: Previous Employment',
  'component.eligibilityDocs.offerLetter': 'Offer letter',
  'component.eligibilityDocs.appraisalLetter': 'Appraisal letter',
  'component.eligibilityDocs.paystubs': 'Paystubs',
  'component.eligibilityDocs.form16': 'Form 16',
  'component.eligibilityDocs.relievingCard': 'Relieving Letter',
  'component.eligibilityDocs.employerDetail': 'Employer 1 Detail',
  'component.eligibilityDocs.nameOfTheEmployer': 'Name of the employer',
  'component.eligibilityDocs.workDuration': 'Work Duration(In year, months, days',
  'component.eligibilityDocs.proofOfEmployment': 'Proof of Employment',
  'component.eligibilityDocs.suggestion': 'Can submit any of the below other than (*)mandatory',
  'component.eligibilityDocs.noteNormal':
    'The candidate must upload all required documents. And, the HR must approve the documents and mark candidate as eligible.',
  'component.eligibilityDocs.noteBold':
    'Post this approval, the remaining processes will open for onboarding.',
  'component.eligibilityDocs.sentForm': 'Sent Form',
  'component.eligibilityDocs.viaEmail': 'Via Email',
  'component.eligibilityDocs.emailSubtitle': `The form will be sent on candidate's private email id `,
  'component.eligibilityDocs.generateLink': 'Generate Link',
  'component.eligibilityDocs.linkSubtitle':
    'The link to the form will be generated which can be shared',
  'component.eligibilityDocs.headerReminder': 'To be uploaded by candidate only',
  'component.eligibilityDocs.title': 'Background Check',
  'component.eligibilityDocs.subtitle':
    'Please choose all the acceptable documents that the candidate can provide. The mandatory documents are required and cannot be deselected.',
  'component.eligibilityDocs.emailLabel': 'Personal email id of the joinee',
  'component.eligibilityDocs.sendEmail': 'Send email',
  'component.eligibilityDocs.markAsDone': 'Mark as done',
  'component.eligibilityDocs.restrictedAccess': 'Restricted access',
  'component.eligibilityDocs.restrictedHelper': 'Only authorised people can access this link',
  'component.eligibilityDocs.owner': 'Owner',
  'component.eligibilityDocs.change': 'Change',
  'component.Benefits.Title': 'Benefits',
  'component.Benefits.subTitle':
    'The list of benefits the candidate is eligible for is populated below',
  'component.Benefits.globalEmployeeTitle': 'For Global employees',
  'component.Benefits.subHeader': 'Coverage will take effect on 20/04/2021',
  'component.Benefits.medical': 'Medical',
  'component.Benefits.openAccess': '[2021] Open Access Plus - Choice Plan',
  'component.Benefits.OAP': '[2021] OAP - Base Plan',
  'component.Benefits.dental': 'Dental',
  'component.Benefits.volDental': '[2021] Voluntary Dental',
  'component.Benefits.vision': 'Vision',
  'component.Benefits.visionPro': '[2021] Vision PRO',
  'component.Benefits.life': 'Life',
  'component.Benefits.basicLife': '[2021] Basic Life / AD & D',
  'component.Benefits.volLife': '[2021] Vol life / AD & D',
  'component.Benefits.shortTerm': 'Short-term disability',
  'component.Benefits.shortTermTitle': 'shortTerm',
  'component.Benefits.IndiaEmployeeTitle': 'For India employees',
  'component.Benefits.paytm': 'Paytm Wallet',
  'component.Benefits.Employee': 'Employee Provident Fund',
  'component.Benefits.employeeTitle': 'employeeProvident',
  'page.signUp.signUpHeader': 'Sign Up for your',
  'component.References.title': 'References',
  'component.References.subTitle': 'Candidate needs to fill in the reference details',
  'component.References.mention':
    'Please mention the no. of references needed to be filled out by the candidate',
};
