export default {
  'pages.offboardingManagement.title': 'Offboarding Management',
  'pages.offboardingManagement.status.approved': 'Approved',
  'pages.offboardingManagement.status.inProgress': 'In Progress',
  'pages.offboardingManagement.status.rejected': 'Rejected',
  'pages.offboardingManagement.status.draft': 'Draft',
  'pages.offboardingManagement.status.onHold': 'On-hold',
  'pages.offboardingManagement.status.deleted': 'Deleted',
  'pages.offboardingManagement.status.done': 'Done',
  'pages.offboardingManagement.status.completed': 'Completed',
  'pages.offboardingManagement.userIdName': 'User ID - Name',
  'pages.offboardingManagement.userA': 'User A',
  'pages.offboardingManagement.userB': 'User B',
  'pages.offboardingManagement.selectUser': 'Select an user',
  'pages.offboardingManagement.getData': 'Get data',
  'pages.offboardingManagement.downloadCSV': 'Download as CSV',
  'pages.offboardingManagement.no': 'No.',
  'pages.offboardingManagement.ticketID': 'Ticket ID',
  'pages.offboardingManagement.userID': 'User ID',
  'pages.offboardingManagement.fullName': 'Full Name',
  'pages.offboardingManagement.group': 'Group',
  'pages.offboardingManagement.submittedDate': 'Submitted Date',
  'pages.offboardingManagement.status': 'Status',
  'pages.offboardingManagement.lastWorkingDate': 'Last Working Date',
  'pages.offboardingManagement.action': 'Action',
  'pages.offboardingManagement.viewRequest': 'View Request',
};
