export default {
  'pages.reports.hrReports': 'HR Reports',
  'pages.reports.resourceManagementReports': 'Resource Management Reports',
  // LEAVE REPORT
  'pages.reports.hrReports.leaveReport': 'Leave Report',
  'pages.reports.hrReports.leaveReport.viewRequest': 'View Request',
  'pages.reports.hrReports.leaveReport.leaveType': 'Leave Type',
  'pages.reports.hrReports.leaveReport.count': 'Count (in days)',
  'pages.reports.hrReports.leftReport': 'Left Report',
  'pages.reports.hrReports.joinedReport': 'Joined Report',
  'pages.reports.hrReports.pendingLeaveReport': 'Pending Leave Report',
  'pages.reports.hrReports.pendingLeaveReport.totalPTO': 'Total PTO Accrued',
  'pages.reports.hrReports.pendingLeaveReport.ptoTaken': 'PTO Taken',
  'pages.reports.hrReports.pendingLeaveReport.ptoBalance': 'PTO Balance left',
  'pages.reports.hrReports.pendingLeaveReport.totalSLAccrued': 'Total SL Accrued',
  'pages.reports.hrReports.pendingLeaveReport.slTaken': 'SL Taken',
  'pages.reports.hrReports.pendingLeaveReport.slBalance': 'SL Balance left',
  'pages.reports.hrReports.biometricReport': 'Biometrics Attendance Report',
  'pages.reports.hrReports.biometricReport.numberOfDay': 'Number of Day',
  'pages.reports.hrReports.biometricReport.totalNumberOfHours': 'Total Number of Hours',

  'pages.reports.hrReports.payrollReport': 'Payroll Input Report',
  'pages.reports.hrReports.payrollReport.doj': 'DOJ (DD-MMM-YYYY)',
  'pages.reports.hrReports.payrollReport.designation': 'Designation',
  'pages.reports.hrReports.payrollReport.skillSet': 'Skill Set',
  'pages.reports.hrReports.payrollReport.dob': 'DOB (DD-MMM-YEAR)',
  'pages.reports.hrReports.payrollReport.panNo': 'PAN NO',
  'pages.reports.hrReports.payrollReport.gender': 'Gender',
  'pages.reports.hrReports.payrollReport.fatherName': 'FATHERS NAME',
  'pages.reports.hrReports.payrollReport.maritalStatus': 'Marital Status',
  'pages.reports.hrReports.payrollReport.spouseName': 'Spouse Name',
  'pages.reports.hrReports.payrollReport.uanNo': 'UAN No',
  'pages.reports.hrReports.payrollReport.adharr': 'Adhaar Card No',
  'pages.reports.hrReports.payrollReport.passportNo': 'Passport No',
  'pages.reports.hrReports.payrollReport.emailId': 'E-mail id',
  'pages.reports.hrReports.payrollReport.banAccount': 'BANK Account Number',
  'pages.reports.hrReports.payrollReport.totalCTC': 'Total CTC',
  'pages.reports.hrReports.payrollReport.payTm': 'Paytm',
  'pages.reports.hrReports.payrollReport.kycStatus': 'KYC status',

  'pages.reports.hrReports.benefitsReport': 'Benefits Report',
  'pages.reports.hrReports.benefitsReport.dayOfBirth': 'Date of Birth',
  'pages.reports.hrReports.benefitsReport.spouseDOB': 'Spouse DOB',
  'pages.reports.hrReports.benefitsReport.child1Name': 'Child 1 Name',
  'pages.reports.hrReports.benefitsReport.child1Gender': 'Child 1 Gender',
  'pages.reports.hrReports.benefitsReport.child2Gender': 'Child 2 Gender',
  'pages.reports.hrReports.benefitsReport.child1DOB': 'Child 1 DOB',
  'pages.reports.hrReports.benefitsReport.child2Name': 'Child 2 Name',

  'pages.reports.resourceManagement': 'Project Allocation Report',
  'pages.reports.projectTrackingReport': 'Project Tracking Report',
  'pages.reports.skillsMatrixReport': 'Skills Matrix Report',
  'pages.reports.resourceAllocationEndDatesReport': 'Resource Allocation End Dates Report',
  'pages.reports.trackerReport': 'Resource Tracker Report',
  'pages.reports.resourceUtilizationReport': 'Resource Utilization Report',
  'pages.reports.projectUtilizationReport': 'Project Utilization Report',

  'pages.reports.searchPlaceholder': 'Search by customer name, project name, division',
  'pages.reports.searchPlaceholder2': 'Search by Project ID, Customer name',
  'pages.reports.searchPlaceholder3': 'Search by employee name, employee ID, user ID',

  'pages.reports.month': 'Month',
  'pages.reports.total': 'Total',
  'pages.reports.bench': 'Bench',
  'pages.reports.billable': 'Billable',
  'pages.reports.buffer': 'Buffer',
  'pages.reports.unpaid': 'Unpaid',
  'pages.reports.efficiency': 'Efficiency (%)',
  'pages.reports.allProjects': 'All projects',
  'pages.reports.allProjectsType': 'All projects type',
  'pages.reports.search': 'Search...',
  'pages.reports.designation': 'Designation',
  'pages.reports.currentManager': 'Current Manager',
  'pages.reports.experience': 'Experience (in yrs)',
  'pages.reports.currentProject': 'Current Project(s)',
  'pages.reports.billStatus': 'Billing Status',
  'pages.reports.utilization': 'Utilization',
  'pages.reports.revisedEndDate': 'Revised End Date',
  'pages.reports.addComment': 'Add Comment',
  'pages.reports.employeesSkills': `Employee's Skills`,
  'pages.reports.selectDate': `Select date`,
  'pages.reports.engineeringOwner': 'Engineering Owner',
  'pages.reports.viewMoreDetails': 'View more details',
  'pages.reports.engagementModel': 'Engagement Model',
  'pages.reports.selectLeaveType': `Select leave type`,
  'pages.reports.exportResource': `Exporting data resource...`,
  'pages.reports.addCommentSuccess': `Add comment Successfully`,
};
