export default {
  'component.employeeOnboarding.onboardingOverview': 'Onboarding overview',
  'component.employeeOnboarding.settings': 'Settings',
  'component.employeeOnboarding.newJoinees': 'New Joiness',
  'component.employeeOnboarding.customFields': 'Custom fields',
  'component.employeeOnboarding.generate': 'Export',
  'component.employeeOnboarding.viewActivityLogs': 'View Activity log ',
  'component.onboardingOverview.viewActivityLogs': 'View Activity log ',
  'component.onboardingOverview.sentEligibilityForms': 'Sent Eligibility forms ',
  'component.onboardingOverview.receivedSubmittedDocuments': 'Received Submitted Documents',
  'component.receivedSubmittedDocuments.rookieId': 'Rookie Id',
  // Onboard Table
  'component.onboardingOverview.candidateId': 'Candidate Id',
  'component.onboardingOverview.candidateName': 'Candidate Name',
  'component.onboardingOverview.position': 'Position',
  'component.onboardingOverview.location': 'Location',
  'component.onboardingOverview.dateSent': 'Date sent',
  'component.onboardingOverview.dateReceived': 'Date received',
  'component.onboardingOverview.dateJoin': 'Date of joining',
  'component.onboardingOverview.documentVerified': 'No. Of documents verified',
  'component.onboardingOverview.resubmit': 'Resubmits',
  'component.onboardingOverview.expire': 'Expires on',
  'component.onboardingOverview.changeRequest': 'Change request',
  'component.onboardingOverview.requestDate': 'Request date',
  'component.onboardingOverview.comments': 'Comments',
  'component.onboardingOverview.actions': 'Actions',
  'component.onboardingOverview.viewDraft': 'View Draft',
  'component.onboardingOverview.new': 'new',
  'component.onboardingOverview.review': 'review',
  'component.onboardingOverview.prepareProvisionalOffer': 'prepare provisional offer',
  'component.onboardingOverview.draftFinalOffer': 'draft final offer',
  'component.onboardingOverview.viewForm': 'view form',
  'component.onboardingOverview.viewDraft2': 'view draft',
  'component.onboardingOverview.sendOffer': 'send offer',
  'component.onboardingOverview.sendForApproval': 'send for approval',
  'component.onboardingOverview.createProfile': 'send for approval',
  'component.onboardingOverview.noData': 'No data',
  // Left menu
  'component.onboardingOverview.pendingEligibilityChecks': 'Pending Eligibility Checks',
  'component.onboardingOverview.addTeamMember': 'Add team member',
  // Settings document and templates
  'component.documentAndTemplates.title': 'Document & Templates',
  'component.documentAndTemplates.subTitle':
    'You can manage all of your documents , templates and custom emails here. The app can generate and send your company’s offer letters, employee handbooks, hiring agreements and custom emails to your new hires.',
  'component.documentAndTemplates.download': 'Download',
  'component.documentAndTemplates.delete': 'Delete',
  'component.documentAndTemplates.defaultTemplate': 'System default templates',
  'component.documentAndTemplates.recentDocuments': 'Recent documents',
  // Settings non extemp notice
  'component.nonExtempNotice.title': 'Non-Extempt Notice',
  'component.nonExtempNotice.formTitle': `Worker's compensation`,
  'component.nonExtempNotice.isSelfInsured': 'Are you self-insured?',
  'component.nonExtempNotice.carrierName': `Insurance carrier's name`,
  'component.nonExtempNotice.carrierAddress': `Insurance carrier's address`,
  'component.nonExtempNotice.phoneNumber': `Phone number`,
  'component.nonExtempNotice.policyNumber': `Policy number`,
  'component.nonExtempNotice.save': `Save`,
  'component.nonExtempNotice.yes': `Yes`,
  'component.nonExtempNotice.no': `No`,
  // Background checks
  'component.backgroundChecks.title': `Background checks`,
  'component.backgroundChecks.subTitle': `Run background checks on new and existing workers.`,
  'component.backgroundChecks.learnMore': `Learn more`,
  'component.backgroundChecks.generalSettings': `General Settings`,
  'component.authorization.title': `Authorization`,
  'component.authorization.link': `Change signatory`,
  'component.backgroundCheck.title': `Background Check`,
  'component.billingInformation.title': `  Billing information for background check`,
  // Optional Onboaring Questions
  'component.optionalOnboardingQuestions.title': `Optional Onboarding Questions`,
  'component.optionalOnboardingQuestions.subTitle': `During onboarding we will collect information from your new hires`,
  'component.optionalOnboardingQuestions.addCustomFields': `+ Add custom fields`,
  'component.optionalOnboardingQuestions.customFields': `Custom fields`,
  'component.optionalOnboardingQuestions.newSection': `+ New Section`,
  'component.optionalOnboardingQuestions.newField': `+ New Field`,
  'component.optionalOnboardingQuestions.sectionName': `Section name`,
  'component.optionalOnboardingQuestions.fieldName': `Field name`,
  'component.optionalOnboardingQuestions.saveOrdering': `Save ordering`,
  'component.optionalOnboardingQuestions.addQuestion': `Add more questions`,
  // Settings custom emails
  'component.emailReminderNote.title': 'Note',
  'component.emailReminderNote.note1':
    'Custom Email messages are a great way to recognize important dates and milestones.',
  'component.emailReminderNote.note2':
    'For example, you can remind managers of their team members’ start dates or create reminders for events, like license renewals or 30 day check-ins. ',
  'component.emailReminderNote.note3':
    'You can use the Auto Text feature to generate personalized emails from a template.',
  'component.emailReminderHeader.title': 'Create a custom email reminder',
  'component.emailReminderForm.title': 'Create a custom email reminder',
  'component.emailReminderForm.triggerNote': 'You can add additional events with',
  'component.emailReminderForm.triggerNoteLink': 'Custom fields',
  'component.emailReminderForm.addCondition': '+ Add another condition',
  'component.emailReminderForm.cancel': 'Cancel',
  'component.emailReminderForm.submit': 'Submit',
  'component.customEmailsTableField.title': 'Custom emails',
  'component.customEmailsTableField.description':
    'Cras gravida bibendum dolor eu varius. Morbi fermentum velit nisl, eget vehicula lorem sodales eget. Donec quis volutpat orci. Sed ipsum felis, tristique id egestas et, convallis ac velit.',
  'component.customEmailsTableField.titleTable': 'Custom emails created',
  'component.customEmailsTableField.pagination.showing': 'Showing',
  'component.customEmailsTableField.pagination.of': 'of',
  'component.customEmailsTableField.emailSubject': 'Email subject',
  'component.customEmailsTableField.createdOn': 'Created On',
  'component.customEmailsTableField.triggerEvent': 'Trigger Event',
  'component.customEmailsTableField.frequency': 'Frequency',
  'component.customEmailsTableField.actions': 'Actions',

  // Company Signatory
  'component.companySignatory.title': 'Company Signatory',
  'component.companySignatory.description':
    "The signature will be used on all relieving and experience letters. An authorized signatory is someone who will sign all the letters on company's behalf.",
  // Edit email
  'component.editEmailNote.title': 'Note',
  'component.editEmailNote.note1':
    'Custom Email messages are a great way to recognize important dates and milestones.',
  'component.editEmailNote.note2':
    'For example, you can remind managers of their team members’ start dates or create reminders for events, like license renewals or 30 day check-ins. ',
  'component.editEmailNote.note3':
    'You can use the Auto Text feature to generate personalized emails from a template.',
  'component.customEmailsTableField.editEmail': 'Edit email',
  'component.editEmailHeader.defaultTitle': 'View a system default email',
  'component.editEmailHeader.title': 'Edit a custom email reminder',
  'component.editEmailForm.addCondition': '+ Add another condition',
  'component.editEmailForm.triggerNote': 'You can add additional events with',
  'component.editEmailForm.triggerNoteLink': 'Custom fields',
  'component.editEmailForm.cancel': 'Cancel',
  'component.editEmailForm.submit': 'Submit',
  'component.editEmailForm.title': 'Edit a custom email',

  // resource management
  'pages.resourceManagement.overview': 'Overview',
  'pages.resourceManagement.resources': 'Resources',
  'pages.resourceManagement.projects': 'Projects',
  'pages.resourceManagement.project': 'Project',
  'pages.resourceManagement.people': 'People',
  'pages.resourceManagement.utilization': 'Resource Utilization',
  'pages.resourceManagement.latest': 'Latest',
  'pages.resourceManagement.trend': 'Trend',
  'pages.resourceManagement.export': 'Export',
  'pages.resourceManagement.totalResources': 'Total Resources',
  'pages.resourceManagement.totalBillable': 'Total Billable resources',
  'pages.resourceManagement.totalBuffer': 'Total Buffer resources',
  'pages.resourceManagement.totalBenched': 'Total Benched resources',
  'pages.resourceManagement.currentUtilization': 'Current Utilization',
  'pages.resourceManagement.currentUtilization.tooltip': `Current utilization is calculated as a percentage of Total Billable resources / Total Resources
  <br />
  <br />
  Compared to the previous week, the Resource utilization has increased by
  {increasePercent}%`,
  'pages.resourceManagement.jobTitle': 'Job Title',
  'pages.resourceManagement.division': 'Division',
  'pages.resourceManagement.noOfPeople': 'No. of people',
  'pages.resourceManagement.newJoinees': 'New Joinees',
  'pages.resourceManagement.byCandidateId': 'by candidate id',
  'pages.resourceManagement.byName': 'by name',
  'pages.resourceManagement.byJobTitle': 'By job title',
  'pages.resourceManagement.byJoiningDate': 'By joining date',
  'pages.resourceManagement.to': 'to',
  'pages.resourceManagement.filter': 'Filter',
  'pages.resourceManagement.byNameUserId': 'BY NAME/USER ID',
  'pages.resourceManagement.byDivision': 'BY DIVISION',
  'pages.resourceManagement.byDesignation': 'BY DESIGNATION',
  'pages.resourceManagement.bySkill': 'BY SKILL',
  'pages.resourceManagement.byCurrentProject': 'BY CURRENT PROJECT',
  'pages.resourceManagement.byBillingStatus': 'BY BILLING STATUS',
  'pages.resourceManagement.byExperience': 'By EXPERIENCE',
  'pages.resourceManagement.byStartDate': 'By Start Date',
  'pages.resourceManagement.byTentativeEndDate': 'BY TENTATIVE END DATE',
  'pages.resourceManagement.editPorjectDetail': 'Edit Project Details',
  'pages.resourceManagement.skip': 'Skip',
  'pages.resourceManagement.update': 'Update',
  'pages.resourceManagement.add': 'Add',
  'pages.resourceManagement.delete': 'Delete',
  'pages.resourceManagement.viewProject': 'View Project',
  'pages.resourceManagement.viewComment': 'View Comment',
  'pages.resourceManagement.deleteComment': 'Delete comment',
  'pages.resourceManagement.close': 'Close',
  'pages.resourceManagement.addComment': 'Add Comment',
  'pages.resourceManagement.editComment': 'Edit Comment',
  'pages.resourceManagement.resourceAssigned': 'Resource assigned!',
  'pages.resourceManagement.bandwidth': 'Bandwidth Allocation (%)',
  'pages.resourceManagement.comments': 'Comments (optional)',
  'pages.resourceManagement.projectDetails': 'Project Details',
  'pages.resourceManagement.currentResource': 'Current resource allocation:',
  'pages.resourceManagement.customer': 'Customer',
  'pages.resourceManagement.engagementType': 'Engagement Type',
  'pages.resourceManagement.status': 'Status',
  'pages.resourceManagement.done': 'Done',
  'pages.resourceManagement.projectName': 'Project Name',
  'pages.resourceManagement.current': 'Current',
  'pages.resourceManagement.projectDescription': 'Project Description',
  'pages.resourceManagement.readMore': 'Read More',
  'pages.resourceManagement.empId': 'Emp Id:',
  'pages.resourceManagement.name': 'Name:',
  'pages.resourceManagement.designationDot': 'Designation:',
  'pages.resourceManagement.experienceDot': 'Experience:',
  'pages.resourceManagement.totalProjects': 'Total Projects:',
  'pages.resourceManagement.manager': 'Manager',
  'pages.resourceManagement.projectType': 'Project Type',
  'pages.resourceManagement.projectManager': 'Project Manager',
  'pages.resourceManagement.resourcePlan': 'Resource Planned',
  'pages.resourceManagement.resourceAssignedHeader': 'Resource Assigned',
  'pages.resourceManagement.billableResource': 'Billable Resource',
  'pages.resourceManagement.bufferResource': 'Buffer Resource',
  'pages.resourceManagement.billEfficiency': 'Billing Efficiency (%)',
  'pages.resourceManagement.billableEffort': 'Billable Effort (days)',
  'pages.resourceManagement.spentEffort': 'Spent Effort (days)',
  'pages.resourceManagement.variance': 'Variance',
  'pages.resourceManagement.byProjectId': 'By Project ID',
  'pages.resourceManagement.byProjectName': 'By PROJECT NAME',
  'pages.resourceManagement.byCustomer': 'By customer',
  'pages.resourceManagement.byEngagementType': 'By engagement type',
  'pages.resourceManagement.byProjectManager': 'By PROJECT manager',
  'pages.resourceManagement.byStatus': 'By status',
  'pages.resourceManagement.customerId': 'Customer ID:',
  'pages.resourceManagement.accountOwnerDot': 'Account Owner:',
  'pages.resourceManagement.contactPhone': 'Contact Phone:',
  'pages.resourceManagement.contactEmail': 'Contact Email:',
  'pages.resourceManagement.address': 'Address:',
  'pages.resourceManagement.customerDetail': 'View customer details',
  'pages.resourceManagement.statusDot': 'Status:',
  'pages.resourceManagement.projectTypeDot': 'Project Type:',
  'pages.resourceManagement.projectIdDot': 'Project ID:',
  'pages.resourceManagement.projectAlias': 'Project Alias:',
  'pages.resourceManagement.engineeringOwnerDot': 'Engineering Owner:',
  'pages.resourceManagement.duration': 'Duration:',
  'pages.resourceManagement.projectStatus': 'Project Status:',
  'pages.resourceManagement.projectDetail': 'View project details',
  'pages.resourceManagement.accountOwner': 'Account Owner',
  'pages.resourceManagement.engineeringOwner': 'Engineering Owner',
  'pages.resourceManagement.projectId': 'Project ID',
  'pages.resourceManagement.viewMoreDetail': 'View more details',

  // table
  'pages.resourceManagement.ticketId': 'Candidate ID',
  'pages.resourceManagement.candidateFullName': 'Name',
  'pages.resourceManagement.joiningDate': 'Joining Date',
  'pages.resourceManagement.designation': 'Designation',
  'pages.resourceManagement.managerName': 'Current Manager',
  'pages.resourceManagement.experience': 'Experience (in yrs)',
  'pages.resourceManagement.currentProjects': 'Current Project(s)',
  'pages.resourceManagement.billStatus': 'Billing Status',
  'pages.resourceManagement.utilizationTable': 'Utilization',
  'pages.resourceManagement.startDate': 'Start Date',
  'pages.resourceManagement.endDate': 'End Date',
  'pages.resourceManagement.revisedDate': 'Revised End Date',
  'pages.resourceManagement.comment': 'Comments',
  'pages.resourceManagement.employeeSkills': `Employee's Skills`,
  'pages.resourceManagement.action': 'Actions',
  'pages.resourceManagement.assignToProject': 'Assign to project',
  'pages.resourceManagement.changeManager': 'Change manager',
  'pages.resourceManagement.resourceHistory': 'Resource history',
  'pages.resourceManagement.effectiveDay': 'Effective Day of change',

  // message
  'pages.resourceManagement.nothing': 'Nothing to export',
  'pages.resourceManagement.acceptNumber': 'Only accept number',
  'pages.resourceManagement.noData': 'No Data present for the selected time range',
  'pages.resourceManagement.selectTimeSmall': `The selected time range is too small. <br />
  Minimum time range should be 1 month.`,
  'pages.resourceManagement.changeManagerQuestion':
    'Would you like to change the reporting manager?',
  'pages.resourceManagement.assignedSuccess':
    ' The resource has been successfully assigned to the project',
  'pages.resourceManagement.assignProject': 'Please select the project!',
  'pages.resourceManagement.startDateEmpty': 'Start date value could not be empty!',
  'pages.resourceManagement.endDateEmpty': 'End date value could not be empty!',
  'pages.resourceManagement.selectStatus': 'Please select the status!',
  'pages.resourceManagement.enterBandwidth': 'Please enter the bandwidth allocation (%)!',
  'pages.resourceManagement.valueNumber': 'Value enter has to be a number!',
  'pages.resourceManagement.bandwidth100%': `The bandwidth allocation (%) can't be greater than 100%!`,
  'pages.resourceManagement.lessThan0': 'Your cannot enter a value that is less than 0!',
  'pages.resourceManagement.noData.message': 'No Data',
  'pages.resourceManagement.enterBandwith': 'Please enter the bandwith allocation (%)!',
  'pages.resourceManagement.selectManager': 'Please select the manager!',
  'pages.resourceManagement.duplicateManager': 'Manager duplicate with current manager!',
  'pages.resourceManagement.selectEffectiveDay': 'Please select the effective day!',
  'pages.resourceManagement.inputComment': 'Please input your comment!',

  // description
  'pages.resourceManagement.chooseRange': 'Please choose another range',
  'pages.resourceManagement.loadingExport': 'Exporting to PNG...',
  'pages.resourceManagement.multipleProject': 'The employee is assigned to multiple projects.',
  'pages.resourceManagement.changeManager.description':
    'Are you sure you want to change the manager?',
  'pages.resourceManagement.sureDeleteComment': 'Are you sure to delete this comment?',

  // placeholder
  'pages.resourceManagement.searchDivision.placeholder': 'Search by Division',
  'pages.resourceManagement.selectDivision.placeholder': 'Select the division',
  'pages.resourceManagement.searchJobTitle.placeholder': 'Search by Job Title',
  'pages.resourceManagement.searchCandidate.placeholder': 'Search by Candidate ID, Name...',
  'pages.resourceManagement.selectCandidateId.placeholder': 'Select the Candidate ID',
  'pages.resourceManagement.selectTheName.placeholder': 'Select the name',
  'pages.resourceManagement.searchByName.placeholder': 'Search by Name, user ID',
  'pages.resourceManagement.selectDesignation.placeholder': 'Select the designation',
  'pages.resourceManagement.typeSearch.placeholder': 'Type to search',
  'pages.resourceManagement.selectLocation.placeholder': 'Select the location',
  'pages.resourceManagement.selectProject.placeholder': 'Select the project',
  'pages.resourceManagement.selectBillingStatus.placeholder': 'Select the billing status',
  'pages.resourceManagement.yearOfExp.placeholder': 'Years of Exp',
  'pages.resourceManagement.fromDate.placeholder': 'From Date',
  'pages.resourceManagement.toDate.placeholder': 'To Date',
  'pages.resourceManagement.startDate.placeholder': 'Enter Start Date',
  'pages.resourceManagement.selectStatus.placeholder': 'Select the status',
  'pages.resourceManagement.enterEndDate.placeholder': 'Enter End Date',
  'pages.resourceManagement.enterDate.placeholder': 'Enter Date',
  'pages.resourceManagement.enterComments.placeholder': 'Enter Comments',
  'pages.resourceManagement.selectEffectiveDay.placeholder': 'Select the effective day',
  'pages.resourceManagement.searchCustomer.placeholder': 'Search by Project ID, customer name',
  'pages.resourceManagement.select.placeholder': 'Select',
  'pages.resourceManagement.selectProjectId.placeholder': 'Select Project ID',
  'pages.resourceManagement.selectDivision2.placeholder': 'Select Division',
  'pages.resourceManagement.selectProjectName.placeholder': 'Select Project Name',
  'pages.resourceManagement.selectCustomer.placeholder': 'Select Customer',
  'pages.resourceManagement.selectEngagementType.placeholder': 'Select Engagement Type',
  'pages.resourceManagement.selectProjectManager.placeholder': 'Select Project Manager',
  'pages.resourceManagement.selectStatus2.placeholder': 'Select Status',
};
