export default {
  'pages.ticketManagement.overView': 'Overview',
  'pages.ticketManagement.allTickets': 'All Tickets',
  'pages.ticketManagement.settings': 'Settings',
  'pages.ticketManagement.location': 'Location',
  'pages.ticketManagement.selectAll': 'Select All',
  'pages.ticketManagement.outOfSLA': 'Out of SLA',
  'pages.ticketManagement.new': 'New',
  'pages.ticketManagement.assigned': 'Assigned',
  'pages.ticketManagement.inProgress': 'In Progress',
  'pages.ticketManagement.clientPending': 'Client Pending',
  'pages.ticketManagement.resolved': 'Resolved',
  'pages.ticketManagement.closed': 'Closed',
  'pages.ticketManagement.searchRequesterByName': 'Search by Requester Name',
  'pages.ticketManagement.byName': 'BY NAME',
  'pages.ticketManagement.byTeam': 'BY TEAM',
  'pages.ticketManagement.byRequestType': 'BY REQUEST TYPE',
  'pages.ticketManagement.byPriority': 'BY PRIORITY',
  'pages.ticketManagement.byAssignedTo': 'BY ASSIGNED TO',
  'pages.ticketManagement.byRequestDate': 'BY REQUEST DATE',
  'pages.ticketManagement.ticketId': 'Ticket ID',
  'pages.ticketManagement.supportTeam': 'Support Team',
  'pages.ticketManagement.requestType': 'Request Type',
  'pages.ticketManagement.subject': 'Subject',
  'pages.ticketManagement.priority': 'Priority',
  'pages.ticketManagement.SLATime': 'SLA Time',
  'pages.ticketManagement.requestDate': 'Request Date',
  'pages.ticketManagement.requesterName': 'Requester Name',
  'pages.ticketManagement.assignedTo': 'Assigned To',
  'pages.ticketManagement.actions': 'Actions',
  'pages.ticketManagement.dailyMail': 'Daily Email',
  'pages.ticketManagement.enabled': 'Enabled',
  'pages.ticketManagement.disabled': 'Disabled',
  'pages.ticketManagement.queryType': 'Query Type',
  'pages.ticketManagement.status': 'Status',
  'pages.ticketManagement.description': 'Description',
  'pages.ticketManagement.interestList': 'Interest List',
  'pages.ticketManagement.emailAddress': 'Email addresses',
  'pages.ticketManagement.interestListTooltip': 'Add any user you want copied to this ticket',
  'pages.ticketManagement.addAttachMentDescription': 'You can upload upto 2 documents of 2MB each',
  'pages.ticketManagement.moveToAnotherTeam': 'Move To Another Team',
  'pages.ticketManagement.addNewTeam': 'Add New Team',
  'pages.ticketManagement.reAssign': 'Re-Assign',
  'pages.ticketManagement.ccTo': 'CC to',
  'pages.ticketManagement.supportTeamSettingTab': 'Support Team',
  'pages.ticketManagement.priorityLevelSettingTab': 'Priority Level',
  'pages.ticketManagement.deleteWarning': 'Are you sure you want to delete this support team?',
  'pages.ticketManagement.onFinishPriorityLevelWarning': 'Please input the level name',
  'pages.ticketManagement.deleteWarningPriorityLevel':
    'Are you sure you want to delete this priority level?',
  'pages.ticketManagement.configTeamSupportTitle': 'Select and Configure your Support Teams',
  'pages.ticketManagement.configTeamSupportDescription': `Please create and configure the required support teams and their respective`,
  'pages.ticketManagement.setupSupportTeam': 'Setup Support Team',
  'pages.ticketManagement.configSupportTeam': 'Configure Support Team',
  'pages.ticketManagement.configSupportTeamDesc':
    'Please configure all the properties for the support team below.',
  'pages.ticketManagement.basicInfoFormTitle': 'Team’s name and Query type',
  'pages.ticketManagement.enterNameSupportTeam': 'Enter the name of the support team',
  'pages.ticketManagement.addQueryTypes': 'Add Query types',
  'pages.ticketManagement.queryTypeDropdown': 'Type and press enter',
  'pages.ticketManagement.addEmailAddress': 'Add Email addresses',
  'pages.ticketManagement.SLATitle': 'Set the SLA time for each priority level (optional)',
  'pages.ticketManagement.configPriorityLevel': 'Select and Configure Priority Levels',
  'pages.ticketManagement.addNewPriorityLevel': 'Add New Priority Level',
  'pages.ticketManagement.addonAfterDay': 'day(s)',
  'pages.ticketManagement.addonAfterHours': 'Hours',
  'pages.ticketManagement.editPriorityLevel': 'Edit Priority Level',
  'pages.ticketManagement.timeTaken': 'Time taken',
  'pages.ticketManagement.ticketDetails': 'Ticket Details',
  'pages.ticketManagement.openBy': 'Opened by',
  'pages.ticketManagement.attachments': 'Attachments',
  'pages.ticketManagement.notes': 'Notes',
  'pages.ticketManagement.attachmentsRemoved': ' Attachments removed',
  'pages.ticketManagement.attachmentsAdded': 'Attachments added',
  'pages.ticketManagement.notifyNewTicket': 'Notify for New Tickets',
  'pages.ticketManagement.notifyEveryNewTicket':
    'All the users in this list will be notified on every new ticket.',
  'pages.ticketManagement.enableDailyEmail': 'Enable Daily Email Summary',
  'pages.ticketManagement.enableDailySendMail':
    'Enabling this option sends a daily email summary on the tickets to all the Managers in the support team.',

  // employee
  'pages.ticketManagement.ticketQueue': 'Ticket Queue',
  'pages.ticketManagement.myTickets': 'My Tickets',
  // 'pages.ticketManagement.ticketsInQueue': 'Tickets in Queue',
  'pages.ticketManagement.assignedTickets': 'Assigned Tickets',
  'pages.ticketManagement.highPriorityTickets': 'High Priority Tickets',
  'pages.ticketManagement.ticketsOutOfSLA': 'Tickets out of SLA',
  'pages.ticketManagement.noSubmitTicket': 'No raise ticket is submitted',
  'pages.ticketManagement.assignToSelf': 'Assign to self',

  // action
  'pages.ticketManagement.moveTo': 'Move To',
  'pages.ticketManagement.viewDetail': 'View Detail',
  'pages.ticketManagement.remove': 'Remove',
  'pages.ticketManagement.send': 'Send',
  'pages.ticketManagement.start': 'Start',
  'pages.ticketManagement.assignTo': 'Assign to',
  'pages.ticketManagement.moveToTeam': 'Move to Team',
  'pages.ticketManagement.addAttachMent': 'Add attachments',
  'pages.ticketManagement.editTicket': 'Edit Ticket',
  'pages.ticketManagement.selectUser': 'Select User',

  // placeHolder
  'pages.ticketManagement.subjectPlaceHolder': 'Enter the subject',
  'pages.ticketManagement.supportTeamPlaceholder': 'Select the support team',
  'pages.ticketManagement.queryTypePlaceholder': 'Select the query type',
  'pages.ticketManagement.descriptionPlaceHolder': 'Enter the description',
  'pages.ticketManagement.byNamePlaceHolder': 'Search by Name',
  'pages.ticketManagement.byTeamNamePlaceHolder': 'Search by Team Name',
  'pages.ticketManagement.byRequestTypePlaceHolder': 'Select request type',
  'pages.ticketManagement.byPriorityPlaceHolder': 'Select priority',
  'pages.ticketManagement.byAssignedToPlaceHolder': 'Search by assigned',
  'pages.ticketManagement.fromDatePlaceHolder': 'From Date',
  'pages.ticketManagement.toDatePlaceHolder': 'To Date',
  'pages.ticketManagement.interestListPlaceHolder': 'Type to search',
  'pages.ticketManagement.ccToPlaceHolder': 'Search a person you want to loop',
  'pages.ticketManagement.nameSupportTeamPlaceHolder': 'Enter the support team name',
  'pages.ticketManagement.enterQueryTypePlaceHolder': 'Enter new query type',
  'pages.ticketManagement.priorityPlaceHolder': 'Select the priority',
  'pages.ticketManagement.SLATimePlaceHolder': 'Enter SLA time',
  'pages.ticketManagement.namePriorityLevelPlaceHolder': 'Enter the level name',
  'pages.ticketManagement.textAreaPlaceHolder': 'Type your message here...',

  // rules form antd
  'pages.ticketManagement.rulesSupportTeam': 'Please select the support team',
  'pages.ticketManagement.rulesQueryType': 'Please select the query type',
  'pages.ticketManagement.rulesPriority': 'Please select the priority',
  'pages.ticketManagement.rulesSubject': 'Please enter the subject',
  'pages.ticketManagement.rulesDescription': 'Please enter the description',
  'pages.ticketManagement.rulesMoveToAnotherTeam': 'Please select a team',
  'pages.ticketManagement.rulesLocation': 'Please select the country!',
  'pages.ticketManagement.rulesNameSupportTeam': 'Please enter the name of support team!',
  'pages.ticketManagement.rulesEnterQueryType': 'Please enter the query type!',
  'pages.ticketManagement.rulesEmailAddress': 'The input is not valid email!',
  'pages.ticketManagement.rulesRequiredField': 'Required field!',
  'pages.ticketManagement.rulesTimeTaken': 'Time taken must be a number or float number',

  'pages.ticketManagement.selectPriority': 'Select the priority',
};
