export default {
  'pages.timeOff.timeoffRequest': 'Timeoff request',
  'pages.timeOff.compoffRequest': 'Comp off request',
  'pages.timeOff.timeoff': 'Timeoff',
  'pages.timeOff.history': 'History',
  'pages.timeOff.setup': 'Setup',
  'pages.timeOff.setUpPolicy': 'Setup Timeoff policy',
  'pages.timeOff.setUp': 'Setup',
  'pages.timeOff.requestTimeoff': 'Request Time Off',
  'pages.timeOff.requestCompoff': 'Request Comp Off Balance',
  'pages.timeOff.requestBehalfOf': 'Request On Behalf Of',
  'pages.timeOff.inProgress': 'In Progress',
  'pages.timeOff.approved': 'Approved',
  'pages.timeOff.rejected': 'Rejected',
  'pages.timeOff.rejectedS': 'rejected',
  'pages.timeOff.accepted': 'accepted',
  'pages.timeOff.reject': 'Reject',
  'pages.timeOff.drafts': 'Drafts',
  'pages.timeOff.onHold': 'On Hold',
  'pages.timeOff.withdrawn': 'Withdrawn',
  'pages.timeOff.withdrawnRequest': 'Withdraw Request',
  'pages.timeOff.withdrawnRequestDetails': 'Withdraw Request details',
  'pages.timeOff.unknown': 'Unknown',
  'pages.timeOff.ticketId': 'Ticket ID',
  'pages.timeOff.days': 'days',
  'pages.timeOff.daysB': 'Days',
  'pages.timeOff.day': 'Day',
  'pages.timeOff.leaveTime': 'Leave time',
  'pages.timeOff.from': 'From',
  'pages.timeOff.to': 'To',
  'pages.timeOff.toS': 'to',
  'pages.timeOff.noOfDays': 'No. of Days',
  'pages.timeOff.date': 'Date',
  'pages.timeOff.cancel': 'Cancel',
  'pages.timeOff.countAndQty': 'Count/Q.ty',
  'pages.timeOff.startTime': 'Start time',
  'pages.timeOff.endTime': 'End time',
  'pages.timeOff.noOfHours': 'No. of hours',
  'pages.timeOff.subject': 'Subject',
  'pages.timeOff.duration': 'Duration',
  'pages.timeOff.fromDate': 'From Date',
  'pages.timeOff.toDate': 'To Date',
  'pages.timeOff.description': 'Description',
  'pages.timeOff.attachments': 'Attachments',
  'pages.timeOff.saveToDraft': 'Save to Draft',
  'pages.timeOff.submit': 'Submit',
  'pages.timeOff.ok': 'OK',
  'pages.timeOff.start': 'Start',
  'pages.timeOff.end': 'End',
  'pages.timeOff.wholeDay': 'Whole day',
  'pages.timeOff.morning': 'Morning',
  'pages.timeOff.afternoon': 'Afternoon',
  'pages.timeOff.showAll': 'Show All',
  'pages.timeOff.holidays': 'Holidays',
  'pages.timeOff.holiday': 'Holiday',
  'pages.timeOff.applied': 'Applied',
  'pages.timeOff.edited': 'Edited',
  'pages.timeOff.viewByList': 'View By List',
  'pages.timeOff.viewByCalendar': 'View By Calendar',
  'pages.timeOff.requestForCompoff': 'Request for Comp Off Balance',
  'pages.timeOff.compoff': 'Comp Off',
  'pages.timeOff.compoffBalance': 'Comp Off Balance',
  'pages.timeOff.managedBy': ' Managed by',
  'pages.timeOff.extraTimeSpent': 'Extra time spent',
  'pages.timeOff.timeSpent': 'Time Spent (In Hrs)',
  'pages.timeOff.totalExtraTime': 'Total extra time spent',
  'pages.timeOff.hrs': 'hrs',
  'pages.timeOff.hours': 'hours',
  'pages.timeOff.hoursB': 'Hours',
  'pages.timeOff.note': 'Note',
  'pages.timeOff.chainOfApproval': 'Chain of approval',
  'pages.timeOff.timeoffRequests': 'Timeoff Requests',
  'pages.timeOff.leaveRequests': 'Leave Requests',
  'pages.timeOff.specialLeaveRequests': 'Special Leave Requests',
  'pages.timeOff.LOPRequests': 'LOP Requests',
  'pages.timeOff.wfhcpRequests': 'WFH/CP Requests',
  'pages.timeOff.compoffRequests': 'Comp Off Requests',
  'pages.timeOff.project': 'Project',
  'pages.timeOff.requestedOn': 'Requested on',
  'pages.timeOff.assigned': 'Assigned',
  'pages.timeOff.action': 'Action',
  'pages.timeOff.updated': 'Updated',
  'pages.timeOff.new': 'New',
  'pages.timeOff.add': 'Add',
  'pages.timeOff.type': 'Type',
  'pages.timeOff.leaveDate': 'Leave date',
  'pages.timeOff.giveFeedback': 'Give feedback',
  'pages.timeOff.yes': 'Yes',
  'pages.timeOff.no': 'No',
  'pages.timeOff.listView': 'List View',
  'pages.timeOff.calendarView': 'Calendar View',
  'pages.timeOff.timeoffCalendar': 'Time off Calendar',
  'pages.timeOff.upcoming': 'Upcoming',
  'pages.timeOff.leaveTaken': 'Leave taken',
  'pages.timeOff.viewLeaveBreakdown': 'View Leave breakdown',
  'pages.timeOff.remaining': 'Remaining',
  'pages.timeOff.totalLeaveBalance': 'Total Leave Balance',
  'pages.timeOff.leaveBalancesDetail': 'Leave balances detail',
  'pages.timeOff.commonLeaves': 'Common Leaves',
  'pages.timeOff.under': 'Under',
  'pages.timeOff.specialLeaves': 'Special Leaves',
  'pages.timeOff.requestee': 'Requestee',
  'pages.timeOff.comment': 'Comment',
  'pages.timeOff.view': 'View',
  'pages.timeOff.approve': 'Approve',
  'pages.timeOff.viewRequest': 'View Request',
  'pages.timeOff.leaveDates': 'Leave Dates',
  'pages.timeOff.noData': 'No data',
  'pages.timeOff.inProgressPM': 'In Progress (PM Approved)',
  'pages.timeOff.approvedPM': 'Approved (PM Approved)',
  'pages.timeOff.deleted': 'Deleted',
  'pages.timeOff.delete': 'Delete',
  'pages.timeOff.viewReport': 'VIEW REPORT',
  'pages.timeOff.requesteeDetails': 'Requestee details',
  'pages.timeOff.EmployeeID': 'Employee ID',
  'pages.timeOff.employeeName': 'Employee Name',
  'pages.timeOff.position': 'Position',
  'pages.timeOff.currentProject': 'Current Project',
  'pages.timeOff.projectManager': 'Project Manager',
  'pages.timeOff.projectHealth': 'Project Health',
  'pages.timeOff.viewReportS': 'View Report',
  'pages.timeOff.total': 'Total',
  'pages.timeOff.compoffRequestDetails': 'Comp Off request details',
  'pages.timeOff.requestRejectionPM': 'Request Rejection Comments (Project Manager)',
  'pages.timeOff.requestRejectionRH': 'Request Rejection Comments (Region Head)',
  'pages.timeOff.requestComments': 'Request Rejection Comments',
  'pages.timeOff.startDate': 'Start Date',
  'pages.timeOff.endDate': 'End Date',
  'pages.timeOff.noProject': 'No project',
  'pages.timeOff.timeoffRequestDetails': 'Timeoff request details',
  'pages.timeOff.reason': 'Reason',
  'pages.timeOff.reasonDot': 'Reason...',
  'pages.timeOff.status': 'Status',
  'pages.timeOff.withdraw': 'Withdraw',
  'pages.timeOff.withdrawingApproved': 'Withdrawing an approved request',
  'pages.timeOff.rejectWithdrawal': 'Reject withdrawal',
  'pages.timeOff.acceptWithdrawal': 'Accept withdrawal',
  'pages.timeOff.quickLinks': 'Quick Links',
  'pages.timeOff.approvedWithdrawn': 'Approved Withdrawn Request',
  'pages.timeOff.waitingApproval': 'Waiting for Approval',
  'pages.timeOff.waitingWithdrawn': 'Waiting for Withdrawn',
  'pages.timeOff.rejectedWithdrawn': 'Rejected Withdrawn Request',
  'pages.timeOff.noteWithdrawal': 'Note - Withdrawal of requests',
  'pages.timeOff.byTimeoffTypes': 'BY TIMEOFF TYPES',
  'pages.timeOff.byDuration': 'By Duration',
  'pages.timeOff.timeoffHistory': 'Timeoff History',
  'pages.timeOff.leaveType': 'Leave type',
  'pages.timeOff.edit': 'Edit',
  'pages.timeOff.withdrawalRequests': 'Withdrawal of applications/requests',
  'pages.timeOff.withdrawompoff': 'You can withdraw this comp off application...',
  'pages.timeOff.proceed': 'Proceed',
  'pages.timeOff.viewMore': 'View More',
  'pages.timeOff.discard': 'Discard',
  'pages.timeOff.balance': 'balance',
  'pages.timeOff.afterWithdrawal': 'After withdrawal',
  'pages.timeOff.timeoffRules': 'Timeoff Type & Rules',
  'pages.timeOff.employeeWorkSchedule': 'Employee Work Schedule',
  'pages.timeOff.holidayCalendar': 'Holiday Calendar',
  'pages.timeOff.manageBalances': 'Manage Balances',
  'pages.timeOff.assignPolicies': 'Assign Policies',
  'pages.timeOff.standardHoliday': 'Standard Holiday calendar',
  'pages.timeOff.assignTo': 'Assign to',
  'pages.timeOff.allEmployees': 'All employees',
  'pages.timeOff.excluding': 'Excluding',
  'pages.timeOff.casualLeavePolicy': 'Casual Leave policy',
  'pages.timeOff.sickLeavePolicy': 'Sick Leave policy',
  'pages.timeOff.finish': 'Finish',
  'pages.timeOff.setupStandard': 'Setup the standard company Holiday Calendar',
  'pages.timeOff.loadingCountry': 'Loading country list...',
  'pages.timeOff.selectAll': 'Select All',
  'pages.timeOff.addAHoliday': 'Add a holiday',
  'pages.timeOff.createHoliday': 'Create a new holiday',
  'pages.timeOff.switch': 'Switch',
  'pages.timeOff.importData': 'Import Data',
  'pages.timeOff.downloadSpreadsheet': 'Download spreadsheet',
  'pages.timeOff.chooseFile': 'Choose file',
  'pages.timeOff.balancesEffectiveDate': 'Balances effective date',
  'pages.timeOff.next': 'Next',
  'pages.timeOff.save': 'Save',
  'pages.timeOff.leaveAccrual': 'Leave Accrual',
  'pages.timeOff.helpSetup': 'Help us setup the timeoff policies for your employees.',
  'pages.timeOff.getStarted': 'Get Started',
  'pages.timeOff.configureTimeoff': 'Select & Configure Timeoff Types',
  'pages.timeOff.configureLeave': 'Configure Leave Type',
  'pages.timeOff.configureAll': 'Please configure all the properties for the leave type below.',
  'pages.timeOff.carryForward': 'Carry Forward',
  'pages.timeOff.setupTimeoff': 'Setup Timeoff policy',
  'pages.timeOff.accrualMethod': 'Accrual Method',
  'pages.timeOff.unlimited': 'Unlimited',
  'pages.timeOff.day/yearFrontload': 'Days / Year (Frontload)',
  'pages.timeOff.day/yearWorked': 'Days / Quarter Worked',
  'pages.timeOff.day/yearFortnight': 'Days / Fortnight worked',
  'pages.timeOff.accrualRate': 'Accrual Rate',
  'pages.timeOff.addAccrualRate': 'Add a new accrual rate',
  'pages.timeOff.perYear': 'per Year',
  'pages.timeOff.perQuarter': 'per Quarter',
  'pages.timeOff.perMonth': 'per Month',
  'pages.timeOff.perFortnight': 'per Fortnight',
  'pages.timeOff.anniversaryDate': 'Anniversary Date',
  'pages.timeOff.calendarDate': 'Calendar Date',
  'pages.timeOff.addCarryForward': 'Add new carry forward',
  'pages.timeOff.carryForwardCap': 'Carry Forward Cap',
  'pages.timeOff.carryForwardAllowed': 'Carry Forward Allowed',
  'pages.timeOff.maximumCarryForward': 'Maximum Carry Forward Value',
  'pages.timeOff.LOPSabbaticalLeave': 'LOP/Sabbatical Leave Accrual Policy',
  'pages.timeOff.meansUnlimited': 'means unlimited',
  'pages.timeOff.maximumLeaveAmount': 'Maximum Leave Amount',
  'pages.timeOff.annualResetPolicy': 'Annual Reset Policy',
  'pages.timeOff.schedulePolicy': 'Standard work schedule policy',
  'pages.timeOff.accrualPolicy': 'Accrual Policy',
  'pages.timeOff.accrualStart': 'Accrual Start',
  'pages.timeOff.carryForwardPolicy': 'Carry Forward Policy',
  'pages.timeOff.emailNotifications': 'Email Notifications',
  'pages.timeOff.employmentType': 'Employment Type',
  'pages.timeOff.leaveApplicationStart': 'Leave Application Start',
  'pages.timeOff.leaveTypeName': 'Leave Type Name',
  'pages.timeOff.maximumBalanceAllowed': 'Maximum Balance Allowed',
  'pages.timeOff.minimumLeaveAmount': 'Minimum Leave Amount',
  'pages.timeOff.hireProrationPolicy': 'New Hire Proration Policy',
  'pages.timeOff.noticeAccrualPolicy': 'Notice Period Leave Accrual Policy',
  'pages.timeOff.hrNotify': 'Notify HR when an employee takes this type of leave',
  'pages.timeOff.negativeLeave': 'Negative Leave Balance',
  'pages.timeOff.maximumNegativeLeave': 'Maximum Negative Leave Balance',
  'pages.timeOff.prorationRule': 'Proration rule',
  'pages.timeOff.addProrationRate': 'Add a new proration rate',
  'pages.timeOff.endOfMonth': 'End of the month',
  'pages.timeOff.startOfMonth': 'Start of the month',
  'pages.timeOff.percentageProrated': 'Percentage Prorated',
  'pages.timeOff.leaveCategory': 'Leave Category',
  'pages.timeOff.totalAccrued': 'Total Accrued',
  'pages.timeOff.totalTaken': 'Total Taken',
  'pages.timeOff.totalRemaining': 'Total Remaining',
  'pages.timeOff.historyTimeOff': 'History of Timeoff',
  'pages.timeOff.operation': 'Operation',
  'pages.timeOff.changedBy': 'Changed By',
  'pages.timeOff.numberOfDays': 'Number of Days',
  'pages.timeOff.currentBalance': 'Current Balance',
  'pages.timeOff.holidayCelebrated':
    'Below is a list of holidays celebrated in your region/country. Select the ones for which your company provides holidays. You may add holidays to the list as well.',
  'pages.timeOff.workHour': 'Work Hours',
  'pages.timeOff.employeeTakeOff':
    'For each day the employee takes off, the number of hours as per the standard work schedule will be deducted from the total leave balance.',
  'pages.timeOff.totalHourWorkday': 'Total hours in a workday',
  'pages.timeOff.hours/day': 'hours/day',
  'pages.timeOff.workDayStart': 'Workday starts at',
  'pages.timeOff.workDayEnd': 'Workday ends at',
  'pages.timeOff.AM': 'AM',
  'pages.timeOff.PM': 'PM',
  'pages.timeOff.workdays': 'Work Days',
  'pages.timeOff.onlyBalance':
    'Only for the days selected below, timeoff hours will be deducted from the total leave balance ',
  'pages.timeOff.leaveAccrues': 'Leave accrues during notice period ?',

  // Month
  'pages.timeOff.Jan': 'Jan',
  'pages.timeOff.Feb': 'Feb',
  'pages.timeOff.Mar': 'Mar',
  'pages.timeOff.Apr': 'Apr',
  'pages.timeOff.May': 'May',
  'pages.timeOff.Jun': 'Jun',
  'pages.timeOff.Jul': 'Jul',
  'pages.timeOff.Aug': 'Aug',
  'pages.timeOff.Sep': 'Sep',
  'pages.timeOff.Oct': 'Oct',
  'pages.timeOff.Nov': 'Nov',
  'pages.timeOff.Dec': 'Dec',

  // description
  'pages.timeOff.timeoffRequest.description.withdraw':
    'Timeoff request [Ticket ID: {tickedId}] [Type: {typeName}] was withdrawn.',
  'pages.timeOff.timeoffRequest.description.drafts':
    'Draft request [Ticket ID: {tickedId}] [Type: {typeName}] was deleted.',
  'pages.timeOff.timeoffRequest.description.approved':
    'Withdrawal request [Ticket ID: {tickedId}] [Type: {typeName}] was sent.',
  'pages.timeOff.timeoffRequest.description.compoffRequest':
    'Comp off request [Ticket ID: {tickedId}] was withdrawn & deleted.',
  'pages.timeOff.applyForLeaves':
    'Apply for leaves with/without pay, work from home or client office.',
  'pages.timeOff.requestcompensation':
    'Request for a compensation leave if you have worked for extra days/hours.',
  'pages.timeOff.defaultNotifications':
    'By default notifications will be sent to HR, your manager and recursively loop to your department head.',
  'pages.timeOff.notApplied': 'You have not applied for any Leave requests.',
  'pages.timeOff.notAppliedSpecial': 'You have not applied for any Special Leave requests.',
  'pages.timeOff.notAppliedLOP': 'You have not applied for any LOP requests.',
  'pages.timeOff.notAppliedWFH':
    'You have not applied any request to Work from home or Client’s place.',
  'pages.timeOff.submittedCasual':
    'Submitted Casual, Sick & Comp off requests will be displayed here.',
  'pages.timeOff.submittedRestricted':
    'Submitted Restricted Holiday, Bereavement, Marriage & Maternity/ Paternity leave requests will be displayed here.',
  'pages.timeOff.submittedRequests':
    'You have not submitted any requests to earn compensation leaves.',
  'pages.timeOff.noLeave': 'No Leave requests received.',
  'pages.timeOff.noLOP': 'No LOP requests received.',
  'pages.timeOff.noCompoff': 'No Comp off requests received.',
  'pages.timeOff.noWFH': 'No Work from home or Client’s place requests received.',
  'pages.timeOff.noSpecial': 'No Special Leave requests received.',
  'pages.timeOff.submitCSC': 'Submitted Casual, Sick & Comp off requests will be displayed here.',
  'pages.timeOff.submitRestricted':
    'Submitted Restricted Holiday, Bereavement, Marriage & Maternity/ Paternity leave requests will be displayed here.',
  'pages.timeOff.withdrawApplication':
    'You can withdraw this timeoff application till one day prior to the date applied for. The withdraw option will not be available after that.',
  'pages.timeOff.withdrawCompoff': 'Withdraw comp off request?',
  'pages.timeOff.withdrawTimeoff': 'Withdraw timeoff request?',
  'pages.timeOff.withdrawingDelete':
    'Withdrawing request will delete this ticket id and no longer will be kept track of.',
  'pages.timeOff.bothNotified': 'Both your Manager and HR will be notified of this change.',
  'pages.timeOff.discardDraft': 'Discard draft request?',
  'pages.timeOff.discardingDraft':
    'Discarding draft will delete this ticket id and no longer will be kept track of.',
  'pages.timeOff.standardWorkhours': 'Standard Workhours and days',
  'pages.timeOff.belowHolidays':
    'Below is a list of holidays celebrated in your region/country. Select the ones for which your company provides holidays. You may add holidays to the list as well.',
  'pages.timeOff.keepCurrent':
    'Keep current employee timeoff balances, but move them to new policies',
  'pages.timeOff.importTimeoff': 'Import new timeoff balances for employees.',
  'pages.timeOff.findGeneric':
    ' You will find below a list of generic timeoffs which every company provides. Configure the rules for each timeoff as per your company norms. Also you can add timeoffs under each category as per your company requirements. This step will take about 80 minutes to complete.',
  'pages.timeOff.rateAt': 'the rate at which an employee accrues or earns paid time off.',
  'pages.timeOff.conceptWhere':
    'a concept where in an employee’s unutilized leaves from the current year can be carried forward to the next year. Carry forward is usually done at the end of a financial year.',
  'pages.timeOff.miniumNumber':
    'Minimum number of calendar days before the accrual starts for a newly onboarded employee.',

  // message
  'pages.timeOff.applyTimeoff': 'Apply for Timeoff from Office',
  'pages.timeOff.applyForTimeoff': 'Apply for Timeoff',
  'pages.timeOff.applyCompoff': 'Apply for Comp Off Balance',
  'pages.timeOff.notAllowedEdit': 'You are not allowed to edit this leave request!',
  'pages.timeOff.requiredApprovals': 'Timeoff requests requires approvals.',
  'pages.timeOff.takesAnyWhere':
    'It takes anywhere around 2-4 standard working days for the entire process to complete.',
  'pages.timeOff.validLeaveTime': 'Please select valid leave time dates!',
  'pages.timeOff.requestSavedDraft': 'request saved as draft.',
  'pages.timeOff.requestSubmitted': 'request submitted to the HR and your manager.',
  'pages.timeOff.editTicket': 'Edits to ticket id: {ticketID} submitted to HR and manager',
  'pages.timeOff.needSelectDuration': 'You need to select the duration first',
  'pages.timeOff.uploadDocument': 'Upload your document here',
  'pages.timeOff.typeToSearch': 'Type to search',
  'pages.timeOff.pleaseSelect': 'Please select!',
  'pages.timeOff.miniumTimeOff': 'Minimum timeoff needs to be 2 hours',
  'pages.timeOff.maximumTimeOff': 'Maximum timeoff can only be 8 hours',
  'pages.timeOff.notAllowedEditComoff': 'You are not allowed to edit this comp off request!',
  'pages.timeOff.optionalAttach':
    'You can optionally attach upto 2 supporting documents of 2MB each',
  'pages.timeOff.compOffDraft': 'Comp off request saved as draft.',
  'pages.timeOff.compOffRequest': 'Comp off request submitted to the HR and your manager.',
  'pages.timeOff.editTicketId': 'Edits to ticket id: {ticketID} submitted to HR and manager',
  'pages.timeOff.selectDuration': 'Selected duration will show as days',
  'pages.timeOff.allowdInput': 'Allowed input: 1- 9 hrs/day',
  'pages.timeOff.compoffRequires': 'Comp off requests requires approvals.',
  'pages.timeOff.onceCompoff':
    'Once the comp off request is approved, a comp off balance will be shown with your leave balance. You can apply for comp off leave then.',
  'pages.timeOff.thankFeedback': 'Thank you for your valuable feedback !',
  'pages.timeOff.helpUs':
    'It will help us to cover that extra mile to delivering the best product to you.',
  'pages.timeOff.takeSometime': 'We request to take out sometime to tell us what problem you face',
  'pages.timeOff.satisfiedApp': 'Are you satisfied with our Timeoff app?',
  'pages.timeOff.recursivelyLoop':
    'By default notifications will be sent to HR, the requestee and recursively loop to your department head.',
  'pages.timeOff.compoffRejected':
    'Comp off request has been rejected from your end. All in loop will be notified.',
  'pages.timeOff.compoffApproved':
    'Comp off request has been approved from your end. All in loop will be notified.',
  'pages.timeOff.timeOffRejected':
    'Timeoff request has been rejected from your end. All in loop will be notified.',
  'pages.timeOff.timeOffApproved':
    'Timeoff request has been approved from your end. All in loop will be notified.',
  'pages.timeOff.withdrawingTimeOffApproved':
    'Withdrawing timeoff request has been approved from your end. All in loop will be notified.',
  'pages.timeOff.withdrawingTimeOffRejected':
    'Withdrawing timeoff request has been rejected from your end. All in loop will be notified.',
  'pages.timeOff.needLeaveBalances': 'All you need to know about Leave balances',
  'pages.timeOff.balanceShown':
    'The leave balance shown is across all the type of leaves. Please look at the Leave Breakdown option to look at the types of leaves and balances.',
  'pages.timeOff.sureWithdraw': 'Are you sure you want to withdraw your leave request?',
  'pages.timeOff.thisWithdraw': 'Withdraw this timeoff request?',
  'pages.timeOff.needApproveWithdraw':
    'Withdrawal of timeoff requests will need to be approved by your Manager and the HR.',
  'pages.timeOff.manageExisting': 'Manage existing & future Timeoff employee balances',
  'pages.timeOff.uploadExcelFile': 'You can only upload Excel file!',
  'pages.timeOff.image2MB': 'Image must smaller than 2MB!',
  'pages.timeOff.dropFile': 'Or drop file here',
  'pages.timeOff.perAssigned': 'As per any assigned new policies, their accrual will begin on',
  'pages.timeOff.tellTimeoff':
    ' Tell us the kind of time offs (both paid, unpaid & holidays) your company provide. We will setup the policies for you.',
  'pages.timeOff.setupWorkSchedule':
    'Please setup work schedule before adding/updating time off types',
  'pages.timeOff.completeRequiredFields': 'Please complete required fields!',
  'pages.timeOff.requiredField': 'Required field!',
  'pages.timeOff.invalidFormat': 'Invalid format',
  'pages.timeOff.yearLess': 'Years to Less than',
  'pages.timeOff.yearService': 'Years of Service',
  'pages.timeOff.sureMove': 'Sure to remove',
  'pages.timeOff.wantReset': 'How do you want to reset?',
  'pages.timeOff.selectDate': 'Select Date',
  'pages.timeOff.selectAllEmployeeType':
    'Select all the employee types eligible for this leave type',
  'pages.timeOff.selectAllEmploymentType': 'Select the Employment Type',
  'pages.timeOff.miniumCalendarDay':
    'Minimum number of calendar days before a newly onboarded employee can apply for a leave.',
  'pages.timeOff.enterNameLeaveType': 'Enter the name of the leave type',
  'pages.timeOff.accruesLOP': 'Leave accrues during LOP / Sabbatical ?',
  'pages.timeOff.maximumLeave':
    'Maximum Leave Balance allowed (Leave accrual stops if an employee reaches this value).',
  'pages.timeOff.maximumNumber':
    ' Maximum number of days of leave that can be taken in a single request.',
  'pages.timeOff.minimumAmountApplied': 'Minimum amount of leave that needs to be applied.',
  'pages.timeOff.negativeLeaveAllowed': 'Negative Leave Balance allowed ?',
  'pages.timeOff.shouldHire':
    ' Should new hires have their leave balance prorated for the 1st time period ?',
  'pages.timeOff.invalid': 'Invalid format',

  // placeholder
  'pages.timeOff.selectTimeOffProceed': 'Please select a Timeoff type to proceed',
  'pages.timeOff.selectEmployee': 'Select Employee',
  'pages.timeOff.pleaseSelectEmployee': 'Please select Employee!',
  'pages.timeOff.typeSearchEmployee': 'Type to search the employee who you want to request for',
  'pages.timeOff.selectTimeOffType': 'Select Timeoff Type',
  'pages.timeOff.pleaseSelectTimeOffType': 'Please select Timeoff Type!',
  'pages.timeOff.timeoffType': 'Timeoff Type',
  'pages.timeOff.pleaseInputSubject': 'Please input subject!',
  'pages.timeOff.enterSubject': 'Enter the subject',
  'pages.timeOff.selectDayTakeOff': 'Select the days you want to take off',
  'pages.timeOff.pleaseSelectDate': 'Please select a date!',
  'pages.timeOff.inputDescription': 'Please input description!',
  'pages.timeOff.reasonTakingTimeoff': 'The reason I am taking timeoff is …',
  'pages.timeOff.ccOnly': 'CC (only if you want to notify other than HR & your manager)',
  'pages.timeOff.searchPerson': 'Search a person you want to loop',
  'pages.timeOff.typeSearchPerson': 'Type to search a person you want to loop',
  'pages.timeOff.enterProjectName': 'Enter Project name',
  'pages.timeOff.enterProject': 'Enter Project',
  'pages.timeOff.pleaseEnterProjectName': 'Please enter project name!',
  'pages.timeOff.reasonRejecting': 'The reason I am rejecting this request is…',
  'pages.timeOff.searchTimeoffTypes': 'Search by Timeoff Types',
  'pages.timeOff.searchEmployessID': 'Search by Employee ID, name...',
  'pages.timeOff.none': 'None',
  'pages.timeOff.selectCountry': 'Select country',
  'pages.timeOff.inputHoliday': 'Please input Holiday Name!',
  'pages.timeOff.inputNameHoliday': 'Input name of holiday',
  'pages.timeOff.selectType': 'Select type',
  'pages.timeOff.inputDateHoliday': 'Please input Holiday date!',
  'pages.timeOff.chooseTypeHoliday': 'Please choose type of holiday!',
  'pages.timeOff.enterTypeName': 'Enter the type name',
  'pages.timeOff.selectOperation': 'Select Operation',
  'pages.timeOff.selectLeaveType': 'Select Leave Type',
  'pages.timeOff.dateRange': 'Date range',
  'pages.timeOff.youSureMove': 'Are you sure to remove?',
  'pages.timeOff.disableFeature': 'Support for this feature will be coming in the near future.',
};
