export default {
  'pages.timeSheet.myTimesheet': 'My Timesheet',
  'pages.timeSheet.hrReports': 'HR Reports',
  'pages.timeSheet.myTeam': 'My Team',
  'pages.timeSheet.financeReports': 'Finance Reports',
  'pages.timeSheet.myProjects': 'My Projects',
  'pages.timeSheet.weeklyReports': 'My Weekly Reports',
  'pages.timeSheet.settings': 'Settings',
  'pages.timeSheet.continue': 'Continue',
  'pages.timeSheet.day': 'Day',
  'pages.timeSheet.activity': 'Activity',
  'pages.timeSheet.timeIn': 'Time In',
  'pages.timeSheet.timeOut': 'Time Out',
  'pages.timeSheet.timeOff': 'Time Off',
  'pages.timeSheet.nightShift': 'Nightshift',
  'pages.timeSheet.totalHrs': 'Total Hrs',
  'pages.timeSheet.notes': 'Notes',
  'pages.timeSheet.action': 'Action',
  'pages.timeSheet.division': 'Division',
  'pages.timeSheet.designation': 'Designation',
  'pages.timeSheet.department': 'Department',
  'pages.timeSheet.requestLeave': 'Request Leave',
  'pages.timeSheet.addTask': 'Add Task',
  'pages.timeSheet.import': 'Import',
  'pages.timeSheet.incompleteTimesheets': 'Incomplete Timesheets',
  'pages.timeSheet.dayOfHours': 'Day of hours',
  'pages.timeSheet.project': 'Project',
  'pages.timeSheet.task': 'Task',
  'pages.timeSheet.description': 'Description',
  'pages.timeSheet.time': 'Time',
  'pages.timeSheet.totalHours': 'Total Hrs',
  'pages.timeSheet.is': 'is',
  'pages.timeSheet.allProjects': 'All Projects',
  'pages.timeSheet.total': 'Total',
  'pages.timeSheet.noTasks': 'No tasks',
  'pages.timeSheet.startTime': 'Start time',
  'pages.timeSheet.endTime': 'End time',
  'pages.timeSheet.breakTime': 'Break time (In Mins)',
  'pages.timeSheet.overTime': 'Over time (In Mins)',
  'pages.timeSheet.clientLocation': 'Client Location',
  'pages.timeSheet.delete': 'Delete',
  'pages.timeSheet.submit': 'Submit',
  'pages.timeSheet.cancel': 'Cancel',
  'pages.timeSheet.update': 'Update',
  'pages.timeSheet.next': 'Next',
  'pages.timeSheet.reSubmit': 'Re-Submit',
  'pages.timeSheet.previous': 'Previous',
  'pages.timeSheet.export': 'Export',
  'pages.timeSheet.download': 'Download',
  'pages.timeSheet.totalHourDot': 'Total hours:',
  'pages.timeSheet.timeDuration': 'Time Duration',
  'pages.timeSheet.timeOffDetail': 'Timeoff Details',
  'pages.timeSheet.timeoff': 'Timeoff',
  'pages.timeSheet.noTimeOff': 'No Timeoff',
  'pages.timeSheet.selectTimesheetPeriod': 'Select Timesheet Period',
  'pages.timeSheet.selectTheTimesheetPeriod': 'Select the Timesheet Period',
  'pages.timeSheet.pleaseSelectTimesheetPeriod': 'Please select Timesheet Period',
  'pages.timeSheet.areHoliday': 'are Holidays',
  'pages.timeSheet.workOn': 'Did you work on {holiday} day?',
  'pages.timeSheet.viewDailyMode': 'View in Daily mode',
  'pages.timeSheet.viewMoreTask': 'View +{task} more tasks',
  'pages.timeSheet.taskDetails': 'Task Details',
  'pages.timeSheet.addAnotherTask': 'Add another task',
  'pages.timeSheet.editTask': 'Edit Task',
  'pages.timeSheet.totalHour': 'Total Hours',
  'pages.timeSheet.daily': 'Daily',
  'pages.timeSheet.weekly': 'Weekly',
  'pages.timeSheet.monthly': 'Monthly',
  'pages.timeSheet.importTasks': 'Import Tasks',
  'pages.timeSheet.tasksSelected': 'Tasks Selected:',
  'pages.timeSheet.yes': 'Yes',
  'pages.timeSheet.no': 'No',
  'pages.timeSheet.nightShift1': 'Night shift',
  'pages.timeSheet.addActivity': 'Add Activity',
  'pages.timeSheet.startDate': 'Start Date',
  'pages.timeSheet.endDate': 'End Date',
  'pages.timeSheet.employeeName': 'Employee Name',
  'pages.timeSheet.totalWorkedTime': 'No.of hours worked',
  'pages.timeSheet.totalOTTime': 'No.of overtime hours',
  'pages.timeSheet.pto': 'PTO',
  'pages.timeSheet.showing': 'Showing',
  'pages.timeSheet.of': 'of',
  'pages.timeSheet.duplicateTask': 'Duplicate Task',
  'pages.timeSheet.duplicate': 'Duplicate',
  'pages.timeSheet.employeeID': 'Employee ID',
  'pages.timeSheet.location': 'Location',
  'pages.timeSheet.date': 'Date',
  'pages.timeSheet.inTime': 'In Time',
  'pages.timeSheet.outTime': 'Out Time',
  'pages.timeSheet.leaves': 'Leaves',
  'pages.timeSheet.projectDetails': 'Project Details',
  'pages.timeSheet.employee': 'Employee',
  'pages.timeSheet.projectName': 'Project Name',
  'pages.timeSheet.taskName': 'Task Name',
  'pages.timeSheet.date&Time': 'Date & Time',
  'pages.timeSheet.days': 'days',
  'pages.timeSheet.hour': 'hour',
  'pages.timeSheet.customer': 'Customer',
  'pages.timeSheet.projectBasic': 'project',
  'pages.timeSheet.resouce': 'resouce',
  'pages.timeSheet.totalTime': 'Total Time',
  'pages.timeSheet.byCustomer': 'By Customer',
  'pages.timeSheet.byProject': 'By Project',
  'pages.timeSheet.byResources': 'By resources',
  'pages.timeSheet.employeesSelected': 'Employees selected',
  'pages.timeSheet.remindEmployee': 'Remind Employee',
  'pages.timeSheet.byEmployee': 'By Employee',
  'pages.timeSheet.noMatches': 'No matches',
  'pages.timeSheet.byDepartment': 'By department id/name',
  'pages.timeSheet.reportingManager': 'Reporting Manager',
  'pages.timeSheet.projects': 'Projects',
  'pages.timeSheet.workingDays': 'Working Days',
  'pages.timeSheet.timeOffInDay': 'Timeoff (In Days)',
  'pages.timeSheet.projectView': 'Project View',
  'pages.timeSheet.teamView': 'Team View',
  'pages.timeSheet.view': 'View',
  'pages.timeSheet.resubmit': 'Resubmit',
  'pages.timeSheet.moreTasks': 'more tasks',
  'pages.timeSheet.projectManager': 'Project Manager',
  'pages.timeSheet.PMAssigned': 'PM Assigned',
  'pages.timeSheet.viewDetails': 'View details',
  'pages.timeSheet.ticketID': 'Ticket ID',
  'pages.timeSheet.dateRange': 'Date Range',
  'pages.timeSheet.approvedBy': 'Approved By',
  'pages.timeSheet.comments': 'Comments',
  'pages.timeSheet.comment': 'Comment',
  'pages.timeSheet.status': 'Status',
  'pages.timeSheet.manager': 'Manager',
  'pages.timeSheet.readMore': 'Read More',
  'pages.timeSheet.leaveOn': 'Leave on',
  'pages.timeSheet.totalDays': 'Total Days',
  'pages.timeSheet.resources': 'Resources',
  'pages.timeSheet.hours': 'Hours',
  'pages.timeSheet.hrs': 'hrs',
  'pages.timeSheet.paymentDueDate': 'Payment Due Date',
  'pages.timeSheet.projectType': 'Project Type',
  'pages.timeSheet.timesheetDetails': 'Timesheet Details',
  'pages.timeSheet.timeTaken': 'Time taken',
  'pages.timeSheet.overlap': '*You can not import the tasks that have the same time slot',

  // Message
  'pages.timeSheet.takenTimeoff':
    'You are being taken to the timeoff page - your leave details will be automatically updated on the timesheet once it has been applied',
  'pages.timeSheet.onlyImport': 'You can only import for Daily view',
  'pages.timeSheet.haveManager': 'User does not have manager',
  'pages.timeSheet.invalidProjectName': 'Invalid project name',
  'pages.timeSheet.selectProject': 'Select the project',
  'pages.timeSheet.selectTask': 'Select a task',
  'pages.timeSheet.selectTheTask': 'Select the task',
  'pages.timeSheet.selectStartTime': 'Select the start time',
  'pages.timeSheet.onlyNumber': 'Just only numbers',
  'pages.timeSheet.sureDelete': 'Are you sure you want to delete',
  'pages.timeSheet.selectTimesheet': 'Select Timesheet Date',
  'pages.timeSheet.pleaseEnterDescription': 'Please enter the description',
  'pages.timeSheet.pleaseSelectTask': 'Please select the tasks that you want to import',
  'pages.timeSheet.pleaseSelectMoreDate':
    'Please select one or more dates to which the tasks must be imported.',
  'pages.timeSheet.sheetForEmpty': 'The sheet for {moment} is empty!',
  'pages.timeSheet.sureToMove': 'Sure to remove?',
  'pages.timeSheet.enterNote': 'Enter notes...',
  'pages.timeSheet.selectTime': 'Select time',
  'pages.timeSheet.selectDurationDay': 'Select Duration Day',
  'pages.timeSheet.selectedTasks': 'Selected Tasks',
  'pages.timeSheet.byJobTitle': 'by job title',
  'pages.timeSheet.noReport': 'No Direct Reports Found',

  // placeholder
  'pages.timeSheet.enterTaskName': 'Enter the task name',
  'pages.timeSheet.enterDescription': 'Enter the description',
  'pages.timeSheet.selectTheStartTime': 'Select the start time',
  'pages.timeSheet.selectTheEndTime': 'Select the end time',
  'pages.timeSheet.0': '0',
  'pages.timeSheet.searchCustomer': 'Search by Customer',
  'pages.timeSheet.searchCustomerProjectEmployee': 'Search by customer, project and employee',
  'pages.timeSheet.searchEmployee': 'Search by Employee',
  'pages.timeSheet.searchProject': 'Search by Project',
  'pages.timeSheet.searchResources': 'Search by Resources',
  'pages.timeSheet.searchNameUserId': 'Search by Name/User ID',
  'pages.timeSheet.searchByDepartment': 'Search by Department',
  'pages.timeSheet.pleaseSelectDurationDay': 'Please Select Duration Day',
  'pages.timeSheet.searchByDesignation': 'Search by Designation',
  'pages.timeSheet.searchNameTask': 'Search by Name, Task...',
};
