export default {
'pages.adminApp.legalBusinessName': `Tên doanh nghiệp hợp pháp*`,
'pages.adminApp.doingBusinessAs': `Kinh doanh với tư cách (DBA)*`,
'pages.adminApp.employerIdentificatioNumber': `Số CCCD/CMND của nhân viên (EIN)*`,
'pages.adminApp.sameAddress': `Giống với địa chỉ trụ sở chính`,
'pages.adminApp.workLocationMessage': `Thông tin này được sử dụng để phân công nhân viên đến đúng văn phòng. Chúng tôi cũng sẽ cho phép bạn phân công cho quản trị viên tại văn phòng, lọc nhân viên theo vị trí làm việc, xem báo cáo Doanh nghiệp thông minh. Bạn không cần phải thêm địa chỉ từ xa của bạn tại đây.`,
'pages.adminApp.locationNotification': `Đã cập nhật vị trí thành công.`,
'pages.adminApp.nothingChangedNotification': `Không có thay đổi.`,
'pages.adminApp.whoYourNewAdmin': `Ai là quản trị viên mới của bạn?`,
'pages.adminApp.essentialsBundleMonthly': `Gói Thiết Yếu đã thanh toán hằng tháng`,
'pages.adminApp.moreInformation': `Hãy liên hệ để biết thêm thông tin.`,
'pages.adminApp.fLexbenBankAccount': `Tài khoản ngân hàng Flexben`,
'pages.adminApp.planTypeText': `Gói Thiết Yếu bao gồm những phúc lợi liên quan đến:`,
'pages.adminApp.integrationsInform': `Ban có thể tích hợp API của bên thứ 3 để tận dụng tối đa Terramind và tối ưu quy trình làm việc của công ty.`,
'pages.adminApp.legalBusinessNamePlaceHolder': `Vui lòng nhập tên doanh nghiệp hợp pháp!`,
'pages.adminApp.DBAPlaceHolder': `Vui lòng nhập DBA!`,
'pages.adminApp.EINPlaceHolder': `Vui lòng nhập EIN!`,
'pages.adminApp.companyDetails': `Chi tiết công ty`,
'pages.adminApp.workLocations': `Vị trí làm việc`,
'pages.adminApp.administrator': `Quản trị viên`,
'pages.adminApp.planInfo': `Thông tin kế hoạch`,
'pages.adminApp.billingPayments': `Hoá đơn & Thanh toán`,
'pages.adminApp.permission': `Quyền hạn`,
'pages.adminApp.integrations': `Tích hợp`,
}