export default {
'pages_admin.setting.title': `Cài đặt`,
'pages_admin.setting.RolesPermission': `Vai trò & quyền hạn`,
'pages_admin.setting.Department': `Bộ phận`,
'pages_admin.setting.Positions': `Chức vụ`,
'pages_admin.setting.Locations': `Vị trí`,
'pages_admin.setting.grades': `Bậc lương`,
'pages_admin.setting.grade': `Bậc lương`,
'pages_admin.setting.domain': `Tên miền`,
'pages_admin.setting.addRoleAndPermission': `Thêm vai trò & quyền hạn`,
'pages_admin.setting.roleId': `ID vai trò`,
'pages_admin.setting.description': `Mô tả`,
'pages_admin.setting.permissions': `Quyền hạn`,
'pages_admin.setting.permission': `Quyền hạn`,
'pages_admin.setting.action': `Tách vụ`,
'pages_admin.setting.sureMove': `Bạn có chắc muốn xoá?`,
'pages_admin.setting.edit': `Chỉnh sửa`,
'pages_admin.setting.addNew': `Thêm mới`,
'pages_admin.setting.rolePermission': `Vai trò & quyền hạn`,
'pages_admin.setting.roleName': `Tên vai trò`,
'pages_admin.setting.roleDescription': `Mô tả về vai trò`,
'pages_admin.setting.departmentId': `ID bộ phận`,
'pages_admin.setting.departmentName': `Tên bộ phận`,
'pages_admin.setting.departmentParentInfo': `Phòng ban`,
'pages_admin.setting.departmentParentName': `Tên phòng ban`,
'pages_admin.setting.hrPOC': `Đầu mối liên hệ nhân sự`,
'pages_admin.setting.financePOC': `Đầu mối liên hệ tài chính`,
'pages_admin.setting.financePointContact': `Đầu mối liên hệ tài chính`,
'pages_admin.setting.addDepartment': `Thêm bộ phận`,
'pages_admin.setting.department': `Bộ phận`,
'pages_admin.setting.hrPoint': `Đầu mối liên hệ nhân sự`,
'pages_admin.setting.typeToSearch': `Nhập để tìm kiếm`,
'pages_admin.setting.addDivision': `Thêm bộ phận`,
'pages_admin.setting.positionName': `Tên chức vụ`,
'pages_admin.setting.role': `Vai trò`,
'pages_admin.setting.roles': `Vai trò`,
'pages_admin.setting.gradeObj': `Cấp bậc lương`,
'pages_admin.setting.timeSheetRequired': `Yêu cầu chấm công`,
'pages_admin.setting.addPosition': `Thêm chức vụ`,
'pages_admin.setting.position': `Chức vụ`,
'pages_admin.setting.EligibleCompOff': `Đủ điều kiện OT (overtime)`,
'pages_admin.setting.simpleTimeSheet': `Bảng chấm công đơn giản`,
'pages_admin.setting.complexTimeSheet': `Bảng chấm công phức tạp`,
'pages_admin.setting.name': `Tên`,
'pages_admin.setting.addGrade': `Thêm bậc lượng`,
'pages_admin.setting.gradeName': `Tên bậc lương`,
'pages_admin.setting.addNewDomain': `Thêm tên miền mới`,
'pages_admin.setting.save': `Lưu`,
'pages_admin.setting.enterRoleId': `Vui lòng nhập ID của vai trò`,
'pages_admin.setting.enterRoleName': `Vui lòng nhập vai trò`,
'pages_admin.setting.enterRoleDescription': `Vui lòng nhập mô tả về vai trò`,
'pages_admin.setting.enterDepartmentName': `Vui lòng nhập tên bộ phận`,
'pages_admin.setting.existDepartmentName': `Tên bộ phận không tồn tại !`,
'pages_admin.setting.searchDepartment': `Tìm kíếm bộ phận`,
'pages_admin.setting.enterDepartment': `Nhập tên bộ phận`,
'pages_admin.setting.selectParentDepartment': `Chọn phòng ban`,
'pages_admin.setting.selectHrPoint': `Vui lòng chọn đầu mối liên hệ nhân sự`,
'pages_admin.setting.selectFinancePoint': `Vui lòng chọn đầu mối liên hệ tài chính`,
'pages_admin.setting.searchPosition': `Chọn chức vụ`,
'pages_admin.setting.pleaseSelectDepartmentName': `Vui lòng chọn tên bộ phận`,
'pages_admin.setting.selectDepartmentName': `Chọn tên bộ phận`,
'pages_admin.setting.enterPositionName': `Vui lòng nhập chức vụ`,
'pages_admin.setting.selectEnterPositionName': `Chọn tên chức vụ`,
'pages_admin.setting.pleaseSelectGradeLevel': `Vui lòng chọn cấp bật lương`,
'pages_admin.setting.selectGradeLevel': `Chọn cấp bật lương`,
'pages_admin.setting.domainUse': `Tên miền đang được sử dụng`,
'pages_admin.setting.deleteAllRecords': `Vui lòng xoá tất cả bàn ghi liên quan đế tên miền và thử lại?`,
'pages_admin.setting.sureDeleteDomain': `Bạn có chắc chắc muốn xoá tên miền này?`,
'pages_admin.setting.primaryDomain': `Phải có một tên miền chính`,
'pages_admin.setting.cantDisable': `Bạn không thể tắt tên miền chính cho tất cả các miền, vui lòng đặt tên miền khác làm tên miền chính.`,
'pages_admin.setting.allPagePublic': `Tất cả các trang sẽ được công bố đến tên miền mà bạn tạo ở đây.`,
'pages_admin.setting.chooseDomain': `Chọn một tên domain như "example.yourcompany.com"`,
'pages_admin.setting.domainName': `Tên miền`,
'pages_admin.setting.setDomain': `Thiết lệp tên miền`,
'pages_admin.setting.primaryDomainText': `Tên miền chính`,
}