export default {
'component.GroupInfoType2.plan': `Kế hoạch`,
'component.GroupInfoType2.coverageEndDate': `Ngày kết thúc bảo hiểm`,
'component.tagSelect.expand': `Mở rộng`,
'component.tagSelect.collapse': `Thu gọn`,
'component.tagSelect.all': `Tất cả`,
'component.appFooter.imgAlt': `Logo không tìm thấy`,
'component.Authorized.unAuthentication': `Xin lỗi, bạn không được phép truy cập vào trang này.`,
'component.ChangePasswordBox.changePass': `Thay đổi mật khẩu`,
'component.ChangePasswordBox.createAccount': `Để bảo mật tài khoản của bạn, vui lòng tạo mật khẩu mới`,
'component.globalHeader.search': `Tìm kiếm`,
'component.globalHeader.search.example1': `Tìm kiếm ví dụ 1`,
'component.globalHeader.search.example2': `Tìm kiếm ví dụ 2`,
'component.globalHeader.search.example3': `Tìm kiếm ví dụ 3`,
'component.globalHeader.help': `Trợ giúp`,
'component.globalHeader.notification': `Thông báo`,
'component.globalHeader.notification.empty': `Bạn đã xem tất cả các thông báo`,
'component.globalHeader.message': `Tin nhắn`,
'component.globalHeader.message.empty': `Bạn đã xem tất cả các tin nhắn`,
'component.globalHeader.event': `Sự kiện`,
'component.globalHeader.event.empty': `Bạn đã xem tất cả các sự kiện`,
'component.globalHeader.avatarDropdown.view-profile': `Xem hồ sơ`,
'component.globalHeader.avatarDropdown.change-password': `Đổi mật khẩu`,
'component.globalHeader.avatarDropdown.settings': `Cài đặt`,
'component.globalHeader.avatarDropdown.session-login': `Phiên đăng nhập`,
'component.globalHeader.avatarDropdown.logout': `Đăng xuất`,
'component.globalHeader.approvalPage': `Trang đã được duyệt`,
'component.globalHeader.switch': `Chuyển`,
'component.globalHeader.switchCompany': `Chuyển công ty`,
'component.globalHeader.switchingCompany': `Chuyển đến < name> công ty`,
'component.globalHeader.switchTo': `Chuyển đến`,
'component.globalHeader.advancedSearch': `Tìm kiếm nâng cao`,
'component.globalHeader.quickLinks': `Liên kết`,
'component.globalHeader.raiseTicket': `Nêu lên ticket`,
'component.globalHeader.faq': `FAQ`,
'component.globalHeader.policies': `Chính xách & Qui định`,
'component.globalHeader.helpCenter': `HR-OS trợ giúp`,
'component.globalHeader.current': `Hiện tại`,
'component.globalHeader.selectCompany': `Vui lòng chọn công ty`,
'component.globalHeader.chooseCompany': `Chọn công ty và nhấn Chuyển`,
'component.globalHeader.control': `Bàng điều khiển`,
'component.noticeIcon.clear': `Xoá`,
'component.noticeIcon.cleared': `Đã xoá`,
'component.noticeIcon.empty': `Không có thông báo`,
'component.noticeIcon.view-more': `Xem thêm`,
'component.directory.table.fullName': `Tên đầy đủ`,
'component.directory.table.employeeID': `ID nhân viên`,
'component.directory.table.userID': `ID người dùng`,
'component.directory.table.email': `ID emai`,
'component.directory.table.title': `Tiêu đề`,
'component.directory.table.department': `Bộ phận`,
'component.directory.table.location': `Vị trí`,
'component.directory.table.reportingManager': `Quản lý báo cáo`,
'component.directory.table.employmentType': `Loại công việc`,
'component.directory.table.employeeType': `Loại nhân viên`,
'component.directory.table.action': `Tách vụ`,
'component.directory.pagination.showing': `Đang hiển thị`,
'component.directory.pagination.of': `của`,
'component.colorPicker.pickColor': `Chọn màu`,
'component.layoutLeftMenu.saveChange': `Lưu thay đổi?`,
'component.countrySelector.select': `Chọn khu vực`,
'component.editor.invalidFile': `file không hợp lệ. Chỉ chấp nhận hình ảnh và phải nhỏ hơn 5MB`,
'component.candidate.extendDate': `Gia hạn ngày đề nghị`,
'component.candidate.extendLetterDate': `Gia hạn ngày có thư đề nghị`,
'component.candidate.withdraw': `Rút lại đề nghị`,
'component.candidate.offerWithdraw': `Đề nghị được rút lại`,
'component.admin.adminApp': `App của quản trị viên`,
'component.admin.changeLogo': `Thay đổi logo`,
'component.admin.upCompanyLogo': `Tải lên logo công ty`,
'component.admin.removeLogo': `Xoá logo`,
'component.admin.uploadLogo': `Tải lên logo`,
'component.admin.sure': `Bạn có chắc không?`,
'component.customer.idGenerated': `ID khách hàng được tạo tự động`,
'component.customer.statusGenerated': `Trang thái được tạo tự động`,
'component.customer.basicDetail': `Chi tiết khách hàng cơ bản`,
'component.customer.id': `ID khách hàng`,
'component.customer.enterId': `Nhập ID khách hàng`,
'component.customer.enterStatus': `Nhập trạng thái`,
'component.customer.requiredFail': `Phần bắt buộc!`,
'component.customer.enterCompanyName': `Nhập tên công ty hợp pháp`,
'component.customer.enterCompanySortName': `"Nhập tên viết tắt công ty"`,
'component.customer.DAB': `Kinh doanh với tư cách (DBA)`,
'component.customer.DABExist': `Hoạt động kinh doanh (DBA) đang hoạt động`,
'component.customer.accOwner': `Chủ tài khoản`,
'component.customer.companyAlias': `Bí danh công ty (DBA)`,
'component.customer.openLeads': ``,
'component.customer.activeProjects': `Dự án đang hoạt động`,
'component.customer.openTickets': `ticket đã mở`,
'component.customer.openTasks': `việc đã mở`,
'component.customer.profilePictureUpdate': `Cập nhật ảnh đại diện`,
'component.customer.editCustomer': `Chỉnh sửa khách hàng`,
'component.employee.maxCharacters': `Chỉ cho phép 170 ký tự!`,
'component.employee.remainingCharacters': `Ký tự còn lại`,
'component.employee.limitExceeded': `Vượt quá giới hạn`,
'component.employee.editBio': `Chỉnh sử tiểu sử`,
'component.employee.putOnLeave': `Nghỉ phép (LWP)`,
'component.employee.raiseTermination': `Chỉ định được nêu lên`,
'component.employee.requestDetails': `Yêu cầu chi tiết`,
'component.employee.noCertifications': `Không có chứng chỉ`,
'component.employee.showProfile': `Hiển thị ảnh địa diện cho những người dùng khác`,
'component.employee.updateLinkedin': `Vui lòng cập nhật hồ sơ Linkedin trong trang hồ sơ nhân viên`,
'app.projectID': `ID dự án`,
'app.projectAlias': `Bí danh dự án`,
'component.project.engagementType': `Loại cam kết`,
'component.project.engineeringOwner': `Chủ kỷ thuật`,
'component.project.editProject': `Chỉnh sửa dự án`,
'component.project.pm': `Quản lý dự án`,
'component.project.type': `Loại dự án`,
'component.project.duration': `Khoảng thời gian`,
'component.project.status': `Trạng thái dự án`,
'component.project.viewDetail': `Xem chi tiết dự án`,
'component.profile.uploadAvt': `Tải lên đại diện`,
'component.profile.rpManager': `Quản lý báo cáo`,
'component.profile.mobile': `Điện thoại`,
'component.profile.emailId': `ID email`,
'component.profile.location': `Vị trí`,
'component.profile.localTime': `Giờ địa phương`,
'component.profile.view': `Xem toàn bộ hồ sơ`,
'component.newPage.addPage': `Thêm trang`,
'component.newPage.add': `Thêm`,
'component.newPage.pageName': `Tên của trang`,
'component.newPage.selectPage': `Chọn trang`,
'component.newPage.choosePosition': `Chọn chức vụ`,
'component.newPage.before': `Trước`,
'component.newPage.after': `Sau`,
'component.feedback.feedback': `Đánh giá`,
'component.feedback.appFeedback': `Đánh giá`,
'component.feedback.thankForFeedback': `Cảm ơn đánh giá của bạn! Đánh giá của bạn sẽ được lưu lại và chia sẽ cho nhóm dự án.`,
'component.feedback.description': `Vui lòng mô tả điều bạn muốn thay đổi hoặc điều bạn thích?`,
'component.feedback.thankForDescription': `Cảm ơn đã giúp chúng tôi cải thiện ứng dụng này! Vui lòng chọn một phương án bên dưới.`,
'component.feedback.reportIssue': `Báo cáo một vấn đề`,
'component.feedback.suggest': `Đề xuất một cải tiến`,
'component.feedback.type': `Nhập tại đây...`,
'component.feedback.uploadScreenshot': `Tải lên ảnh chụp màn hình`,
'component.feedback.highlightPage': `Đánh dấu trang`,
'component.feedback.descriptionChange': `Vui lòng mô tả điều bạn muốn thay đổi hoặc điều bạn thích?Bạn cũng có thể xác định khu vực trang hiện tại có liên quan đến đánh giá của bạn bằng công cụ 'Đánh dấu trang'`,
'component.feedback.validate.radio': ``,
'component.feedback.validate.maxCharacters': `Chỉ điền tối đa 1000 ký tự!`,
'component.feedback.validate.inputField': `Vui lòng nhập trường!`,
'component.feedback.uploadNew': `Tải lên mới`,
'component.feedback.addDocument': `Thêm tài liệu`,
'component.feedback.uploadNextScreen': `Bạn có thể tải lên một ảnh chụp màng hình và mô tả vế đề ở màng hình kế tiêp`,
'component.feedback.dragAndDrop': `Kéo và thả file tại đây`,
'component.feedback.or': `hoặc`,
'component.feedback.browse': `duyệt`,
'component.feedback.toUpload': `để tải lên một file`,
'component.feedback.fileSize': `file không nên vượt quá 2MB. file hỗ trợ xem: PDF & JPEG`,
'component.feedback.clickHighlight': `Nhấn và kéo để đánh dấu khu vực`,
'component.signature.inputName': `Vui lòng nhập tên bạn`,
'component.signature.generate': `Phát ra`,
'component.signature.fileType': `Bạn chỉ có thể tải lên hình ảnh và file PDF!`,
'component.signature.fileSize': `Hình ảnh phải nhỏ hơn 5MB`,
'component.signature.optionSignature': `Chọn những tuỳ chọn cho chữ ký`,
'component.signature.draw': `Vẽ`,
'component.signature.digital': `Chữ kỳ điện tử`,
'component.signature.chooseFile': `Chọn file`,
'component.signature.dropFile': `hoặc ticket file tại đây`,
'component.signature.validate.enterName': `Vui lòng nhập tên`,
'component.signature.validate.signDocument': `Để ký tài liệu, vui lòng nhập tên của bạn và chọn định dạng chữ ký.`,
'component.reviewImage.title': `Xem lại hình ảnh`,
'component.upload.validate.fileType': `Bạn chỉ có thể tải lên JPG/PNG file!`,
'component.upload.validate.fileSize': `Hình ảnh phải nhỏ hơn 5MB`,
'component.upload.uploadFail': `file tải lên không thành công`,
'component.upload.uploadNew': `Tải lên mới`,
'component.upload.clickOrDragToUpload': `Nhấp hoặc kéo file vào khu vực này để tải lên`,
'component.upload.fileType': `Loại file: PDF/PNG/JPEG`,
'component.upload.fileSize': `Kích thước ảnh phải nhỏ hơn 5MB`,
'component.upload.pdfType': `Bạn chỉ có thể tải lên file PDF!`,
'component.upload.multiFiles': `Bạn chỉ có thể tải lên file JPG/PNG/PDF!`,
'component.upload.imgSmaller': `Hình ảnh phải nhỏ hơn`,
'component.upload.fileSmaller': `file phải nhỏ hơn`,
'component.upload.fileUnder5Mb': `Hình ảnh phải dưới 5MB`,
'component.policies.stillHelp': `Vẫn cần chúng tôi giúp?`,
'component.policies.support24/7': `Nhóm hỗ trợ của chúng tôi đang chờ đợi để giúp bạn 24/7. Nhận phản hồi qua email từ nhóm của chúng tôi.`,
'component.policies.contact': `Liên hệ với chúng tôi`,
'component.question.question': `câu hỏi`,
'component.question.add': `Thêm câu hỏi`,
'component.question.edit': `Chỉnh sửa câu hỏi`,
'component.question.rows': `Nhiều dòng`,
'component.question.columns': `Nhiều cột`,
'component.question.addRow': `Thêm dòng`,
'component.question.addColumn': `Thêm cột`,
'component.question.options': `Tuỳ chọn`,
'component.question.addOption': `Thêm tuỳ chọn`,
'component.question.option': `Tuỳ chọn {num}`,
'component.question.answer': `Trả lời {num}`,
'component.question.answerHere': `Trả lời tại đây`,
'component.question.enterAnswer': `Nhập câu trả lời`,
'component.question.selectOption': `Chọn một tuỳ chọn`,
'component.question.note': `Ghi chú`,
'component.question.typeYourQuestion': `Nhập câu hỏi của bạn`,
'component.question.mandatory': `Bắt buộc`,
'component.question.label': `Nhãn`,
'component.question.typeHere': `Nhập tại đây`,
'component.question.optionalOnboarding': `Câu hỏi giới thiệu tuỳ chọn`,
'component.question.addOptionalOnboarding': `Thêm câu hỏi giới thiệu tuỳ chọn`,
'component.question.type.text': `Văn bản dạng tự do`,
'component.question.type.singleChoice': `Lựa chọn đơn`,
'component.question.type.multipleChoice': `Nhiều lựa chọn`,
'component.question.type.dropdown': `Thả xuống`,
'component.question.type.singleRating': `Lựa chọn xếp hạng đơn`,
'component.question.type.multipleRating': `Nhiều lựa chọn đánh giá`,
'component.question.type': `Loại câu hỏi`,
'component.question.specify': `Chỉ định`,
'component.question.specify.atLeast': `Ít nhất`,
'component.question.specify.atMost': `Nhiều nhất`,
'component.question.specify.exactly': `Chính xác`,
'component.question.specifyAnswers': `Điều này cho phép chỉ định cách chọn câu trả lời.`,
'component.question.validate.requiredAnswer': `Loại câu hỏi này phải ít nhất 1 câu trả lời`,
'component.question.validate.maxCharacters': `Giới hạn tối đa 200 ký tự`,
'component.question.validate.greaterThan': `Giá trị này phải nhìều hơn`,
'component.question.validate.atLeast': `Câu hỏi này ít nhất {num} câu trả lời`,
'component.question.validate.atMost': `Câu hỏi này có nhiều nhất {num} câu trả lời`,
'component.question.validate.exactly': `Câu hỏi này có chính xác {num} câu trả lời`,
'component.raiseTicket.raiseTicket': `Nêu lên ticket`,
'component.raiseTicket.addAttachments': `Thêm file đính kèm`,
'component.raiseTicket.supportTeam': `Nhóm hỗ trợ`,
'component.raiseTicket.requestDate': `Ngày yêu cầu`,
'component.raiseTicket.queryType': `Loại truy vấn`,
'component.raiseTicket.status': `Trạng thái`,
'component.raiseTicket.new': `Mới`,
'component.raiseTicket.priority': `Ưu tiên`,
'component.raiseTicket.subject': `Vấn đề`,
'component.raiseTicket.description': `Mô tả`,
'component.raiseTicket.interestList': `Danh sách yêu thích`,
'component.raiseTicket.upload2Documents': `Bạn có thể tải lên tối đa 2 tài liệu, mỗi tài liệu 2MB`,
'component.raiseTicket.addUser': `Thêm bất kỳ người dùng nào bạn muốn sao chép vào ticket này`,
'component.raiseTicket.typeSearch': `Nhập để tìm kiếm`,
'component.raiseTicket.validate.selectTeam': `Vui lòng chọn team hỗ trợ`,
'component.raiseTicket.validate.queryType': `Vui lòng chọn loại truy vấn`,
'component.raiseTicket.validate.priority': `Vui lòng chọn mức mức độ ưu tiên`,
'component.raiseTicket.validate.subject': `Vui lòng nhập nhập vấn đề`,
'component.raiseTicket.validate.description': `Vui lòng nhập nhập mô tả`,
'component.document.name': `Tên tài liệu`,
'component.document.type': `Loại tài liệu`,
'component.document.userId': `ID người dùng`,
'component.document.uploadedBy': `Tải lên bởi`,
'component.document.view': `Xem tài liệu`,
'component.document.sign': `Ký`,
'component.document.downloading': `file đang tải. Vui lòng đợi...`,
'component.document.size': `Kích thước tài liệu (KB/MB/GB)`,
'component.document.validate.enterDocumentName': `Nhập tên tài liệu`,
'component.document.validate.enterSize': `Nhập kích thước tài liệu`,
'component.document.validate.modifiedBy': `Sửa đổi bởi`,
'component.document.validate.enterModifiedBy': `Nhập sửa đổi bởi`,
'component.document.validate.enterDocumentType': `Nhập loại tài liệu`,
'component.debounceSelect.placeholder': `Nhập để tìm kiếm`,
'component.search.employees': `Nhân viên`,
'component.search.documents': `Tài liệu`,
'component.search.tickets': `Ticket`,
'component.search.onBoarding': `Gia nhập`,
'component.search.createdOn': `Được tạo ra`,
'component.search.documentOwner': `Chủ tài liệu`,
'component.search.searchDocumentText': `Tìm kiếm tên, loại, chủ, kích thước, được tạo... tài liệu`,
'component.search.modifiedOn': `Đã được sửa đổi`,
'component.search.personalDetails': `Thông tin cá nhân`,
'component.search.searchPersonal': `Tìm kiếm thông tin cá nhân như tên, số đt,...`,
'component.search.firstName': `Họ`,
'component.search.userID': `ID người dùng`,
'component.search.enterFirstName': `Nhập họ`,
'component.search.enterUserID': `Nhập ID user`,
'component.search.state': `Quận`,
'component.search.enterState': `Nhập quận`,
'component.search.middleName': `Tên lót`,
'component.search.lastName': `Tên`,
'component.search.city': `Thành phố`,
'component.search.jobDetails': `Công việc chi tiết`,
'component.search.enterCity': `Nhập thành phố`,
'component.search.searchJobDetail': `Tìm kiếm thông tin công việc như chức danh công việc, bộ phận,...`,
'component.search.enterLastName': `Nhập tên`,
'component.search.enterMiddleName': `Nhập tên lót`,
'component.search.phoneNumber': `Số điện thoại`,
'component.search.enterPhoneNumber': `Nhập số điện thoại`,
'component.search.country': `Quốc gia`,
'component.search.enterCountry': `Nhập tỉnh`,
'component.search.enterEmployeeID': `Nhập ID nhân viên`,
'component.search.enterSkills': `Nhập kỷ năng`,
'component.search.building': `Toà nhà`,
'component.search.enterBuilding': `nhập toà nhà`,
'component.search.enterReportingManager': `Nhập báo cáo cho quản lý`,
'component.search.selectJobTitle': `Chọn chức danh công việc`,
'component.search.floor': `Tầng`,
'component.search.enterFloor': `Nhập tầng`,
'component.search.employeeType': `Loại nhân viêng (chính quy hoặc không chính quy)`,
'component.search.selectEmployeeType': `Chọn loại nhân viên`,
'component.search.codeNumber': `Mã số`,
'component.search.enterCodeNumber': `Nhập mã số`,
'component.search.classification': `Phân loại (Thực tập/Bán thời gian/Toàn thời gian)`,
'component.search.enterClassification': `Nhập phân loại`,
'component.search.validate.enterCreatedOn': `Nhập được tạo trên`,
'component.search.validate.enterDocumentOwner': `Nhập chủ tài liệu`,
'component.search.validate.enterModifiedOn': `Nhập sửa đổi trên`,
'component.search.searchTicket': `Tìm kiếm ID, tên nhân viên, tạo bởi, phân công cho,...`,
'component.search.ticketID': `ID ticket`,
'component.search.enterTicketID': `Nhập ID ticket`,
'component.search.assignedTo': `Đã phân công cho`,
'component.search.enterAssignedTo': `Nhập phân công cho`,
'component.search.status': `Trạng thái`,
'component.search.resolvedBy': `Giải quyết bởi`,
'component.search.enterResolvedBy': `Nhập tên người giải quyết`,
'component.search.createdBy': `Tạo bởi`,
'component.search.enterCreatedBy': `Nhập tên người tạo`,
}