export default {
'pages.customerManagement.customerTab': `Khách hàng`,
'pages.customerManagement.addNewCustomer': `Thêm khách hàng mới`,
'pages.customerManagement.customerId': `ID khách hàng`,
'pages.customerManagement.companyName': `Tên công ty`,
'pages.customerManagement.openLeads': ``,
'pages.customerManagement.pendingTickets': `Ticket chờ xử lý`,
'pages.customerManagement.pendingTasks': `Công việc chờ xử lý`,
'pages.customerManagement.activeProjects': `Dự án đang hoạt động`,
'pages.customerManagement.deleteProjectModalTitle': `Xoá dự án`,
'pages.customerManagement.legalNameRejectPromise': `Tên đang hoạt động`,
'pages.customerManagement.doingBusinessRejectPromise': `Hoạt động kinh doanh (DBA) đang hoạt động`,
'pages.customerManagement.addNewCustomerModalTitle': `Thêm khách hàng mới`,
'pages.customerManagement.basicCustomerDetail': `Chi tiết khách hàng cơ bản`,
'pages.customerManagement.doingBusiness': `Kinh doanh với tư cách (DBA)`,
'pages.customerManagement.contactDetail': `Chi tiết liên hệ`,
'pages.customerManagement.otherDetail': `Chi tiết khác`,
'pages.customerManagement.searchBoxPlaceHolder': `Tìm kiếm bằng tên công ty, ID, chủ tài khoản`,
'pages.customerManagement.customerIdPlaceHolder': `Nhập ID khách hàng`,
'pages.customerManagement.legalNamePlaceHolder': `Nhập tên công ty hợp pháp`,
'pages.customerManagement.companyDBAPlaceHolder': `Nhập DBA của công ty`,
'pages.customerManagement.phoneNumberPlaceHolder': `Nhập số điện thoại`,
'pages.customerManagement.emailPlaceHolder': `Nhập địa chỉ email`,
'pages.customerManagement.phoneNumberRules': `Vui lòng nhập số điện thoại hợp lệ!`,
'pages.customerManagement.customerIdPopover': `ID khách hàng được tạo tự động`,
'pages.customerManagement.statusPopover': `Trang thái được tạo tự động`,
'pages.customerManagement.settingTab': `Cài đặt`,
'pages.customerManagement.tableTitle': `Tất cả khách hàng`,
'pages.customerManagement.companyAlias': `Bí danh công ty`,
}