export default {
'pages.customerProfile.customerProfile': `Hồ sơ khách hàng`,
'pages.customerProfile.addAnotherDivision': `Thêm bộ phận khác`,
'pages.customerProfile.addDivision': `Tên bộ phận`,
'pages.customerProfile.editDivision': `Chỉnh sửa bộ phận`,
'pages.customerProfile.basicDivisionDetail': `Chi tiết bộ phần cơ bản`,
'pages.customerProfile.contactDetail': `Chi tiết liên hệ`,
'pages.customerProfile.otherDetails': `Chi tiết khác`,
'pages.customerProfile.sameAddressAsHQ': `Cùng địa chỉ Thêm tài liệu như HQ`,
'pages.customerProfile.contactInfo': `Thông tin liên hệ`,
'pages.customerProfile.divisions': `Bộ phận`,
'pages.customerProfile.people': `Người`,
'pages.customerProfile.documents': `Tài liệu`,
'pages.customerProfile.projects': `Dự án`,
'pages.customerProfile.leads': ``,
'pages.customerProfile.tickets': `Ticket`,
'pages.customerProfile.emails': `Email`,
'pages.customerProfile.appointments': `Cuộc họp`,
'pages.customerProfile.tasks': `Công việc`,
'pages.customerProfile.notes': `Ghi chú`,
'pages.customerProfile.auditTrail': `Kiểm toán truy nguyên`,
'pages.customerProfile.divisionId': `ID bộ phận`,
'pages.customerProfile.divisionName': `Tên bộ phận`,
'pages.customerProfile.primaryPOCName': `Tên người phụ trách chính`,
'pages.customerProfile.primaryPOCNo': `Số điện thoại người phụ trách chính`,
'pages.customerProfile.primaryPOCEmailId': `ID email người phụ trách chính`,
'pages.customerProfile.primaryPOCDesignation': `Chỉ định người phụ trách chính`,
'pages.customerProfile.secondaryPOCName': `Tên người phụ trách phụ`,
'pages.customerProfile.secondaryPOCNo': `Ph No. người phụ trách phụ`,
'pages.customerProfile.secondaryPOCEmailId': `Email ID người phụ trách phụ`,
'pages.customerProfile.secondaryPOCDesignation': `Chỉ định người phụ trách phụ`,
'pages.customerProfile.divisionIdPlaceHolder': `Nhập ID bộ phận`,
'pages.customerProfile.divisionNamePlaceHolder': `Nhập tên bộ phận`,
'pages.customerProfile.primaryPOCNamePlaceHolder': `Nhập tên người phụ trách chính`,
'pages.customerProfile.primaryPOCNoPlaceHolder': `Nhập số điện thoại người phụ trách chính`,
'pages.customerProfile.primaryPOCEmailIdPlaceHolder': `Nhập email ID người phụ trách chính`,
'pages.customerProfile.primaryPOCDesignationPlaceHolder': `Nhập chỉ định người phụ trách chính`,
'pages.customerProfile.secondaryPOCNamePlaceHolder': `Nhập tên người phụ trách phụ`,
'pages.customerProfile.secondaryPOCNoPlaceHolder': `Nhập số điện thoại người phụ trách phụ`,
'pages.customerProfile.secondaryPOCEmailIdPlaceHolder': `Nhập email ID người phụ trách phụ`,
'pages.customerProfile.secondaryPOCDesignationPlaceHolder': `Nhập chỉ định người phụ trách phụ`,
'pages.customerProfile.searchBox': `Tìm kiếm theo tên tài liệu, tải lên bởi`,
'pages.customerProfile.addNoteReference': `Thêm ghi chú tham khảo`,
}