export default {
'pages.dashboard.myDashboard': `Bảng điều khiển của tôi`,
'pages.dashboard.adminTab': `Quản trị viên`,
'pages.dashboard.personalTab': `Cá nhân`,
'pages.dashboard.activityLog.title': `nhật ký hoạt động`,
'pages.dashboard.activityLog.sort': `Sắp xếp theo`,
'pages.dashboard.activityLog.filter': `Lọc`,
'pages.dashboard.activityLog.all': `Tất cả`,
'pages.dashboard.activityLog.require': `Yêu cầu sự phê duyệt của tôi`,
'pages.dashboard.carousel.welcome': `Chào mừng`,
'pages.dashboard.new': `Mới`,
'pages.dashboard.view': `Xem`,
'pages.dashboard.approve': `Duyệt`,
'pages.dashboard.reject': `Từ chối`,
'pages.dashboard.ticketId': `ID ticket`,
'pages.dashboard.status': `Trạng thái`,
'pages.dashboard.calendar': `Lịch`,
'pages.dashboard.calendar.holidayCalendar': `Lịch nghỉ lễ`,
'pages.dashboard.calendar.myCalendar': `Lịch`,
'pages.dashboard.calendar.googleSync': `Đồng bộ hoá với tài khoản Google của bạn`,
'pages.dashboard.calendar.myCalendar.joinWithGoogle': `Tham gia Google Meet`,
'pages.dashboard.calendar.myCalendar.guest': `Khách`,
'pages.dashboard.calendar.myCalendar.minute': `trước 15 phút`,
'pages.dashboard.calendar.viewAllMeetings': `Xem tất cả cuộc họp`,
'pages.dashboard.calendar.viewAllHolidays': `Xem tất cả ngày lễ`,
'pages.dashboard.tasks': `Công việc`,
'pages.dashboard.tasks.tabName.myTaskDummy': `Việc của tôi [Dummy data]`,
'pages.dashboard.tasks.tabName.myTask': `Việc của tôi`,
'pages.dashboard.tasks.tabName.myProject': `Dự án của tôi`,
'pages.dashboard.tasks.sortBy': `Sắp xếp theo`,
'pages.dashboard.tasks.viewAllTask': `Xem tất cả công việc`,
'pages.dashboard.tasks.viewAllProject': `Xem tất cả dự án`,
'pages.dashboard.myTasks.status.medium': `Trung bình`,
'pages.dashboard.myTasks.status.high': `Cao`,
'pages.dashboard.myTasks.status.completed': `Hoàn tất`,
'pages.dashboard.myTasks.mockData.description1': `một -  một với`,
'pages.dashboard.myTasks.mockData.description2': ``,
'pages.dashboard.myProjects.more': `thêm`,
'pages.dashboard.activityLog': `Nhật ký hoạt động`,
'pages.dashboard.activityLog.tabName.pendingApprovals': `Đang chờ phê duyệt`,
'pages.dashboard.activityLog.tabName.notification': `Thông báo`,
'pages.dashboard.activityLog.tabName.myTicket': `Ticket`,
'pages.dashboard.activityLog.showAllRequest': `Hiển thị tất cả yêu cầu`,
'pages.dashboard.activityLog.showAllNotification': `Hiển thì tất cả thông báo`,
'pages.dashboard.activityLog.showAllMyTickets': `Xem tất cả ticket`,
'pages.dashboard.activityLog.penDingApprovalTag.timeOff': `Giờ nghỉ`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet': `Bảng chấm công`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.table.allProjects': `Tất cả dự án`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.table.totalHours': `Tổng giờ`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.table.total': `Tổng cộng`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.taskPopover.task': `Công việc`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.taskPopover.timeDuration': `Khoảng thời gian`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.taskPopover.noTask': `Không có công việc nào`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.taskPopover.noName': `Không tên`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.taskPopover.viewMore': `Xem +{quanity} công việc`,
'pages.dashboard.activityLog.penDingApprovalTag.timesheet.taskPopover.taskDetails': `Chi tiết công việc`,
'pages.dashboard.activityLog.penDingApprovalTag.request': `Yêu cầu từ`,
'pages.dashboard.activityLog.penDingApprovalTag.received': `đã được nhận`,
'pages.dashboard.activityLog.penDingApprovalTag.leaveType': `Loại thời gian nghỉ`,
'pages.dashboard.activityLog.penDingApprovalTag.leaveDuration': `Khoản thời gian nghỉ`,
'pages.dashboard.activityLog.penDingApprovalTag.requestedOn': `Yêu cầu trên`,
'pages.dashboard.activityLog.penDingApprovalTag.description': `Mô tả`,
'pages.dashboard.activityLog.penDingApprovalTag.requestDetails': `Yêu cầu chi tiết`,
'pages.dashboard.activityLog.penDingApprovalTag.addComments': `Thêm bình luận`,
'pages.dashboard.activityLog.penDingApprovalTag.typeHere': `Nhập tại đây...`,
'pages.dashboard.activityLog.penDingApprovalTag.employeeName': `Tên nhân viên`,
'pages.dashboard.activityLog.penDingApprovalTag.department': `Bộ phận`,
'pages.dashboard.activityLog.penDingApprovalTag.employeeID': `ID nhân viên`,
'pages.dashboard.activityLog.penDingApprovalTag.manager': `Quản lý`,
'pages.dashboard.activityLog.penDingApprovalTag.requesterName': `Tên người yêu cầu`,
'pages.dashboard.activityLog.penDingApprovalTag.requesterManager': `Quản lý của ngừời yêu cầu`,
'pages.dashboard.activityLog.penDingApprovalTag.requesterDepartment': `Bộ phận của người yêu cầu`,
'pages.dashboard.activityLog.penDingApprovalTag.requestDate': `Ngày yêu cầu`,
'pages.dashboard.activityLog.penDingApprovalTag.requestType': `Loại yêu cầu`,
'pages.dashboard.activityLog.penDingApprovalTag.requestReason': `Lý do yêu cầu`,
'pages.dashboard.activityLog.penDingApprovalTag.compoff': ``,
'pages.dashboard.activityLog.penDingApprovalTag.header': `Bình luận yêu cầu bị từ chối`,
'pages.dashboard.activityLog.penDingApprovalTag.placeholder': `Lý do tôi muốn huỷ yêu cầu này là...`,
'pages.dashboard.activityLog.penDingApprovalTag.detailTicket.title': `{type} chi tiết`,
'pages.dashboard.activityLog.penDingApprovalTag.detailTicket.contentRejectModal': `Đây là ticket {type}?`,
'pages.dashboard.activityLog.tickettag.ticketDetail': `Chi tiết ticket`,
'pages.dashboard.activityLog.tickettag.ticketID': `ID ticket #{ticketID}`,
'pages.dashboard.activityLog.tickettag.timeoffContent': `Thời gian nghỉ từ {fromDate} đến {toDate} là {status}`,
'pages.dashboard.activityLog.tickettag.supportContent': `Yêu cầu hỗ trợ về {typeNameSupportRequest} là {status}`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.requesteeDetail': `Người yêu cầu chi tiết`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.requesteeDate': `Ngày yêu cầu`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.priority': `Ưu tiên`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.duration': `Khoảng thời gian`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.subject': `Vấn đề`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.attachments': `file đính kèm`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.description': `Mô tả`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.chainOfApproval': `Chuỗi phê duyệt`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.status.assigned': `Đã phân công`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.status.inProgress': `Đang tiến hành`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.status.clientPending': `Khách hàng đang chờ xử lý`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.status.resolved': `Đã giải quyết`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.status.closed': `Đã đóng`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.notes': `Ghi chú`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.addNotes': `Thêm ghi chú`,
'pages.dashboard.activityLog.tickettag.ticketDetailModal.placeholder': `Thêm ghi chú tham khảo`,
'pages.dashboard.activityLog.notificationTag.content.firstText': `Mới {type} yêu cầu từ {name}`,
'pages.dashboard.activityLog.notificationTag.content.secondeText': `ID người dùng-{userId}`,
'pages.dashboard.activityLog.notificationTag.content.thirdText': `đã được nhận`,
'pages.dashboard.activityLog.notificationMessTag.contentFirst': ``,
'pages.dashboard.activityLog.notificationMessTag.contentSecond': `ID ứng viên #{candidateId}`,
'pages.dashboard.myTeam': `Team`,
'pages.dashboard.myTeam.viewAllTimeOff': `Xem tất cả thời gian nghỉ`,
'pages.dashboard.tabName.members': `Thành viên`,
'pages.dashboard.tabName.teamLeaveCalendar': `Lịch nghỉ phép của nhóm`,
'pages.dashboard.myApp': `Ứng dụng`,
'pages.dashboard.myApp.showAll': `Hiển thị tất cả`,
'pages.dashboard.myApp.timeSheets': `Bảng chấm công`,
'pages.dashboard.myApp.timeOff': `Giờ nghỉ`,
'pages.dashboard.myApp.directory': `Danh mục`,
'pages.dashboard.myApp.approval': `Duyệt`,
'pages.dashboard.timeSheets': `Bảng chấm công`,
'pages.dashboard.timeSheets.fillTimesheet': `Điền bảng chấm công`,
'pages.dashboard.widget.title': `Quản lý tiện ích`,
'pages.dashboard.widget.note': `Tất cả các widget từ app được hiên thị bên dưới. Hãy chọn các widget trên dashboard, chúng sẽ giúp cho quy trình làm việc của bạn đơn giản hơn và các công cụ bạn đã sử dụng có thể truy cập dễ dàng.`,
'pages.dashboard.widget.notification.error': `Vui lòng chọn ít nhất một tiện ích`,
'pages.dashboard.widget.notification.success': `Tiện ích của bạn đã được lưu`,
'pages.dashboard.widget.description.default': `Sử dụng tiện ích này để theo dõi tất cả cuộc họp và dự án`,
'pages.dashboard.widget.description.calendar': `Sử dụng tiện ích này để theo dõi tất cả cuộc họp và công việc`,
'pages.dashboard.approval.table.ticketId': `ID ticket`,
'pages.dashboard.approval.table.employeeId': `ID nhân viên`,
'pages.dashboard.approval.table.name': `Tên`,
'pages.dashboard.approval.table.manager': `Quản lý`,
'pages.dashboard.approval.table.department': `Bộ phận`,
'pages.dashboard.approval.table.dateRange': `Khoản thời gian`,
'pages.dashboard.approval.table.action': `Tách vụ`,
'pages.dashboard.approval.table.contentActionModal': `Tất cả {số lượng} ticket?`,
'pages.dashboard.approval.filterForm.label.employeeId': `Theo ID nhân viên`,
'pages.dashboard.approval.filterForm.label.name': `Theo tên`,
'pages.dashboard.approval.filterForm.label.department': `Theo tên phòng ban`,
'pages.dashboard.approval.filterForm.label.requestDate': `Theo ngày yêu cầu`,
'pages.dashboard.approval.filterForm.to': `đến`,
'pages.dashboard.approval.filterForm.placeholder.employeeId': `Tìm kiếm ID nhân viên`,
'pages.dashboard.approval.filterForm.placeholder.name': `Tìm kiếm theo tên`,
'pages.dashboard.approval.filterForm.placeholder.department': `Tìm kíếm bộ phận`,
'pages.dashboard.approval.filterForm.placeholder.fromDate': `Từ ngày`,
'pages.dashboard.approval.filterForm.placeholder.toDate': `Đến ngày`,
'pages.dashboard.approval.approveModal.content': `Bạn có chắc bạn muốn phê duyệt`,
'pages.dashboard.approval.rejectModal.content': `Bạn có chắc bạn muốn từ chối`,
}