export default {
'component.directory.table.fullName': `Tên đầy đủ`,
'component.directory.table.employeeID': `ID nhân viên`,
'component.directory.table.userID': `ID người dùng`,
'component.directory.table.email': `ID emai`,
'component.directory.table.title': `Tiêu đề`,
'component.directory.table.department': `Bộ phận`,
'component.directory.table.location': `Vị trí`,
'component.directory.table.reportingManager': `Quản lý báo cáo`,
'component.directory.table.employmentType': `Loại công việc`,
'component.directory.table.employeeType': `Loại nhân viên`,
'component.directory.table.action': `Tách vụ`,
'component.directory.pagination.showing': `Đang hiển thị`,
'component.directory.pagination.of': `của`,
'pages.directory.viewActivityLog': `Xem nhật ký hoạt động`,
'pages.directory.directoryTab': `Danh mục`,
'pages.directory.employeesManagementTab': `Quản lý nhân viên`,
'pages.directory.organisationChartTab': `Sơ đồ tổ chức`,
'pages.directory.directory.activeEmployeesTab': `Nhân viên đang hoạt động`,
'pages.directory.directory.myTeamTab': `Team`,
'pages.directory.directory.viewProfile': `Xem hồ sơ`,
'pages.directory.directory.inactiveEmployeesTab': `Nhân viên không họạt động`,
'pages.directory.directory.setUpNewProfile': ``,
'pages.directory.directory.addTeamMember': `Thêm thành viên`,
'pages.directory.tableFilter.filter': `Lọc`,
'pages.directory.tableFilter.reset': `Cài lại`,
'pages.directory.tableFilter.name': `Tên`,
'pages.directory.organisationChart.search': `Tìm kiếm...`,
'pages.directory.organisationChart.search.placeholder': `Nhập để tìm kiếm tên nhân viên hoặc ID`,
'pages.directory.organisationChart.expandAll': `Mở rộng tất cả`,
'pages.directory.organisationChart.collapseAll': `Thu gọn tất cả`,
'pages.directory.organisationChart.download': `Tải về`,
'pages.directory.organisationChart.skills': `Kỹ năng`,
'pages.directory.organisationChart.certifications': `Chứng chỉ`,
'pages.directory.organisationChart.workNumber': `Điện thoại`,
'pages.directory.organisationChart.copy': `Sao chép`,
'pages.directory.organisationChart.copySuccess': ``,
'pages.directory.organisationChart.viewProfile': `Xem toàn bộ hồ sơ`,
'pages.directory.organisationChart.message': `Tin nhắn`,
'pages.directory.organisationChart.email': `Email`,
'pages.directory.organisationChart.linkedIn': `LinkedIn`,
'pages.directory.organisationChart.needLinkedIn': ``,
'pages.directory.organisationChart.reportees': `người báo cáo`,
'pages.directory.organisationChart.sub1Reportee': `-1 người báo cáo`,
'pages.directory.organisationChart.add1Reportee': `#ERROR!`,
'pages.directory.organisationChart.you': ``,
'component.directory.tableFilter.name': `Theo Id nhân viên/ ID người dùng/ tên...`,
'component.directory.tableFilter.name.placeholder': `Nhập để tìm kiếm ID nhân viên/ ID người dùng/ tên...`,
'component.directory.tableFilter.department': `Theo ID phòng ban/ tên`,
'component.directory.tableFilter.department.placeholder': `Tìm kíếm bộ phận`,
'component.directory.tableFilter.division': `Theo tên bộ phận`,
'component.directory.tableFilter.division.placeholder': `Tìm kíếm tên bộ phận`,
'component.directory.tableFilter.title': `Theo chức danh công việc`,
'component.directory.tableFilter.title.placeholder': `Tìm kíếm chức danh công việc`,
'component.directory.tableFilter.manager': `Theo quản lý báo cáo`,
'component.directory.tableFilter.manager.placeholder': `Nhập để tìm kiếm`,
'component.directory.tableFilter.location': `Theo vị trí`,
'component.directory.tableFilter.location.placeholder': `Tìm kiếm theo vị trí`,
'component.directory.tableFilter.country': `Theo quốc gia`,
'component.directory.tableFilter.country.placeholder': `Tìm kiếm theo quốc gia`,
'component.directory.tableFilter.empTypeOther': `Theo loại nhân viên`,
'component.directory.tableFilter.empTypeOther.placeholder': `Tìm kiếm theo loại nhân viên`,
'component.directory.tableFilter.employeeType': `Theo loại công việc`,
'component.directory.tableFilter.employeeType.placeholder': `Tìm kiếm theo loại công việc`,
'component.directory.tableFilter.skill': `Theo kỷ năng & chứng nhận`,
'component.directory.tableFilter.skill.placeholder': `Tìm kiếm theo kỹ năng`,
'component.directory.tableFilter.experience': `Theo số năm làm việc`,
'component.directory.tableFilter.from': `Từ`,
'component.directory.tableFilter.to': `Đến`,
'component.directory.addEmployeeModal.title': `Thêm nhân viên`,
'component.directory.importEmployeeModal.title': `Nhân viên gia nhập`,
'component.directory.importEmployeeModal.error': `Gửi không thành công vì không cho phép trống các trường sau: [ngày tham gia, tiêu đề, email công việc, vị trí, bộ phận]! ở hàng`,
'component.directory.importEmployeeModal.label': `Công ty`,
'component.directory.importEmployeeModal.placeholder': `Chọn công ty`,
'component.directory.importEmployeeModal.onabortImport': `Đọc file đã bị huỷ!`,
'component.directory.importEmployeeModal.onerrorImport': `Đọc file không thàng công!`,
'component.directory.importEmployeeModal.uploadSuccess': `File được tảio lên thành công!`,
'component.directory.importEmployeeModal.uploaded': `Đã tải lên`,
'component.directory.importEmployeeModal.chooseAnotherFile': `Chọn một file khác`,
'component.directory.importEmployeeModal.dragAndDrop': `Kéo và thả file tại đây`,
'component.directory.importEmployeeModal.or': `hoặc`,
'component.directory.importEmployeeModal.chooseFile': `Chọn file`,
'component.directory.terminalModal.title': `Nhân viên bị sa thải`,
'component.directory.terminalModal.reason': `Lý do`,
'component.directory.terminalModal.reason.placeholder': `Điền vào chỗ trống...`,
'component.directory.terminalModal.message1': `Chỉ điền tối đa 1000 ký tự!`,
'component.directory.terminalModal.message2': `Phần bắt buộc!`,
'component.directory.terminalModal.lastWorkingDate': `Ngày làm việc cuối cùng`,
'component.directory.table.workNumber': `Số điện thoại công việc`,
'component.directory.table.terminate': ``,
}