export default {
'pages_admin.documents.title': `Quản lý tài liệu`,
'pages_admin.documents.documentTable.activeDocumentsTab': `Tài liệu đang hoạt động`,
'pages_admin.documents.documentTable.inactiveDocumentsTab': `Tài liệu không hoạt động`,
'pages_admin.documents.documentTable.addDocument': `Thêm tài liệu`,
'pages_admin.documents.documentTable.importDocuments': `Nhập tài liệu`,
'pages_admin.documents.tableFilter.filter': `Lọc`,
'pages_admin.documents.tableFilter.reset': `Cài lại`,
'pages_admin.documents.tableFilter.name': `Tên`,
'pages_admin.documents.confirmRemoveDocument': `{name}&quot`,
'pages_admin.documents.createNewTemplate': `Tạo mẫu mới`,
'pages_admin.documents.table.id': `ID Tài liệu`,
'pages_admin.documents.table.type': `Loại tài liệu`,
'pages_admin.documents.table.name': `Tên tài liệu`,
'pages_admin.documents.table.uploadBy': `Tải lên bởi`,
'pages_admin.documents.table.company': `Công ty`,
'pages_admin.documents.table.createdDate': `Ngày tạo`,
'pages_admin.documents.table.action': `Tách vụ`,
'pages_admin.documents.addDocument': `Thêm tài liệu`,
'pages_admin.documents.chooseAnotherFile': `Chọn một file khác`,
'pages_admin.documents.uploaded': `Đã tải lên`,
'pages_admin.documents.addDocumentSuccess': `Thêm tài liệu thành công! Đang tải lại trang...`,
'pages_admin.documents.employeeId': `ID nhân viên`,
'pages_admin.documents.employeeName': `Tên nhân viên`,
'pages_admin.documents.documentGroup': `Nhóm tài liệu`,
'pages_admin.documents.identityType': `Loại xác thực`,
'pages_admin.documents.visa': `Thị thực`,
'pages_admin.documents.passport': `Hồ chiếu`,
'pages_admin.documents.passportNumber': `Số hộ chiếu`,
'pages_admin.documents.adhaarCard': `ticket Adhaar`,
'pages_admin.documents.adhaarNumber': ` Số Adhaar`,
'pages_admin.documents.country': `Quốc gia`,
'pages_admin.documents.issuedOn': `Bạn hành ngày`,
'pages_admin.documents.validTill': `Hợp lệ đến`,
'pages_admin.documents.visaNumber': `Số thị thực`,
'pages_admin.documents.visaType': `Loại thị thực`,
'pages_admin.documents.entryType': `Loại mục nhập`,
'pages_admin.documents.nothing': `không có gì...`,
'pages_admin.documents.singleEntry': `Mục duy nhất`,
'pages_admin.documents.passportExist': `Hộ chiếu của nhân viên này đã có`,
'pages_admin.documents.validate.employeeExist': `Thông tin nhân viên không tồn tại!`,
'pages_admin.documents.validate.chooseFile': `Vui lòng chọn file để tải lên!`,
'pages_admin.documents.validate.inputEmployeeId': `Vui lòng nhập ID nhân viên`,
'pages_admin.documents.validate.inputCompany': `Vui lòng chọn công ty!`,
'pages_admin.documents.validate.inputDocument': `Vui lòng nhập tên tài liệu!`,
'pages_admin.documents.validate.inputDocumentGroup': `Vui lòng chọn nhóm tài liệu`,
'pages_admin.documents.validate.selectDocumentType': `Vui lòng chọn loại tài liệu`,
'pages_admin.documents.validate.selectIdentityType': `Vui lòng chọn loại xác thực`,
'pages_admin.documents.validate.invalidAdhaarNumber': `Số Adhaar không hợp lệ`,
'pages_admin.documents.validate.invalidPassportNumber': `Số hộ chiếu không hợp lệ`,
'pages_admin.documents.validate.selectCountry': `Vui lòng chọn công ty!`,
'pages_admin.documents.validate.selectIssuedTime': `Vui lòng chọn thời gian ban hành!`,
'pages_admin.documents.validate.selectExpiredTime': `Vui lòng chọn thời gian hết hạn!`,
'pages_admin.documents.validate.selectVisaType': `Vui lòng chọn loại thị thực!`,
'pages_admin.documents.validate.selectEntryType': `Vui lòng chọn loại mục nhập!`,
'pages_admin.documents.validate.invalidVisa': `Số hộ chiếu không hợp lệ`,
}