export default {
'pages_admin.employees.title': `Quản lý nhân viên`,
'pages_admin.employees.table.activeEmployeesTab': `Nhân viên đang hoạt động`,
'pages_admin.employees.table.inactiveEmployeesTab': `Nhân viên không họạt động`,
'pages_admin.employees.table.downloadTemplate': `Tải mẫu`,
'pages_admin.employees.table.exportEmployees': `Nhân viên nghỉ`,
'pages_admin.employees.table.importEmployees': `Nhân viên gia nhập`,
'pages_admin.employees.table.addEmployee': `Thêm nhân viên`,
'pages_admin.employees.table.userID': `ID người dùng`,
'pages_admin.employees.table.joinedDate': `Gia nhập ngày`,
'pages_admin.employees.table.email': `Email`,
'pages_admin.employees.tabFilter.filter': `Lọc`,
'pages_admin.employees.tabFilter.reset': `Cài lại`,
'pages_admin.employees.tabFilter.name': `Tên`,
'addEmployee.employeeID': `ID nhân viên`,
'addEmployee.placeholder.employeeID': `Nhập ID nhân viên`,
'addEmployee.validate.employeeID': `ID nhân viên không hợp lệ!`,
'addEmployee.name': `Tên`,
'addEmployee.placeholder.name': `Nhập tên`,
'addEmployee.firstName': `Họ`,
'addEmployee.placeholder.firstName': `Nhập họ`,
'addEmployee.middleName': `Tên lót`,
'addEmployee.placeholder.middleName': `Nhập tên lót`,
'addEmployee.lastName': `Tên`,
'addEmployee.placeholder.lastName': `Nhập tên`,
'addEmployee.validate.name': ``,
'addEmployee.personalEmail': `Email cá nhân`,
'addEmployee.placeholder.personalEmail': ``,
'addEmployee.workEmail': `Email công việc`,
'addEmployee.placeholder.workEmail': `Nhập email công việc`,
'addEmployee.employeeType': `Loại nhân viên`,
'addEmployee.placeholder.employeeType': ``,
'addEmployee.employmentType': `Loại công việc`,
'addEmployee.placeholder.employmentType': ``,
'addEmployee.company': `Công ty`,
'addEmployee.placeholder.company': `Chọn công ty`,
'addEmployee.location': `Vị trí`,
'addEmployee.placeholder.location': ``,
'addEmployee.department': `Bộ phận`,
'addEmployee.placeholder.department': ``,
'addEmployee.roles': `Vai trò`,
'addEmployee.placeholder.roles': `Chọn vai trò`,
'addEmployee.jobTitle': `Chức danh công việc`,
'addEmployee.placeholder.jobTitle': `Chọn chức danh công việc`,
'addEmployee.manager': `Quản lý báo cáo`,
'addEmployee.placeholder.manager': `Chọn quản lý báo cáo`,
'addEmployee.required': `{label} được yêu cầu!`,
'addEmployee.validateEmail': ``,
'addEmployee.validateNumber': ``,
'employee.button.cancel': `Huỷ`,
'employee.button.submit': `Nộp`,
}