export default {
'component.employeeOnboarding.onboardingOverview': `Tổng quan về gia nhập`,
'component.employeeOnboarding.settings': `Cài đặt`,
'component.employeeOnboarding.newJoinees': `Người mới`,
'component.employeeOnboarding.customFields': `Trường tuỳ chỉnh`,
'component.employeeOnboarding.generate': `Xuất`,
'component.employeeOnboarding.viewActivityLogs': `Xem nhật ký hoạt động`,
'component.onboardingOverview.viewActivityLogs': `Xem nhật ký hoạt động`,
'component.onboardingOverview.sentEligibilityForms': `Gửi biểu mẫu chính thức`,
'component.onboardingOverview.receivedSubmittedDocuments': `Nhận lại tài liệu đã nộp`,
'component.receivedSubmittedDocuments.rookieId': `ID người mới`,
'component.onboardingOverview.candidateId': `ID ứng viên`,
'component.onboardingOverview.candidateName': `Tên ứng viên`,
'component.onboardingOverview.position': `Chức vụ`,
'component.onboardingOverview.location': `Vị trí`,
'component.onboardingOverview.dateSent': `Ngày gửi`,
'component.onboardingOverview.dateReceived': `Ngày nhận`,
'component.onboardingOverview.dateJoin': `Ngày gia nhập`,
'component.onboardingOverview.documentVerified': `Số tài liệu được xác minh`,
'component.onboardingOverview.resubmit': `Nộp lại`,
'component.onboardingOverview.expire': `Hết hạn vào`,
'component.onboardingOverview.changeRequest': `Đổi yêu cầu`,
'component.onboardingOverview.requestDate': `Ngày yêu cầu`,
'component.onboardingOverview.comments': `Bình luận`,
'component.onboardingOverview.actions': `Tách vụ`,
'component.onboardingOverview.viewDraft': `Xem nháp`,
'component.onboardingOverview.new': `Mới`,
'component.onboardingOverview.review': `xem lại`,
'component.onboardingOverview.prepareProvisionalOffer': ``,
'component.onboardingOverview.draftFinalOffer': ``,
'component.onboardingOverview.viewForm': `xem biểu mẫu`,
'component.onboardingOverview.viewDraft2': `Xem nháp`,
'component.onboardingOverview.sendOffer': `Gửi thư đề nghị`,
'component.onboardingOverview.sendForApproval': `Gửi phê duyệt`,
'component.onboardingOverview.createProfile': `Gửi phê duyệt`,
'component.onboardingOverview.noData': `Không có dữ liệu nào`,
'component.onboardingOverview.pendingEligibilityChecks': ``,
'component.onboardingOverview.addTeamMember': `Thêm thành viên`,
'component.documentAndTemplates.title': `Tài liệu & mẫu`,
'component.documentAndTemplates.subTitle': `Bạn có thể quản lý tất cả tài liệu, mẫu và email tùy chỉnh của mình tại đây. Ứng dụng có thể tạo và gửi thư mời làm việc, sổ tay nhân viên, thỏa thuận tuyển dụng và email tùy chỉnh của công ty bạn cho nhân viên mới.`,
'component.documentAndTemplates.download': `Tải về`,
'component.documentAndTemplates.delete': `Xoá`,
'component.documentAndTemplates.defaultTemplate': `Mẫu hệ thống mặc định`,
'component.documentAndTemplates.recentDocuments': ``,
'component.nonExtempNotice.title': ``,
'component.nonExtempNotice.formTitle': ``,
'component.nonExtempNotice.isSelfInsured': `Bjan có bảo hiểm tự túc không?`,
'component.nonExtempNotice.carrierName': `Tên hãng bảo hiểm`,
'component.nonExtempNotice.carrierAddress': `Địa chỉ hãng bảo hiểm`,
'component.nonExtempNotice.phoneNumber': `Số điện thoại`,
'component.nonExtempNotice.policyNumber': `Số chính sách`,
'component.nonExtempNotice.save': `Lưu`,
'component.nonExtempNotice.yes': `Đồng ý`,
'component.nonExtempNotice.no': `Không`,
'component.backgroundChecks.title': `Kiểm tra lý lịch`,
'component.backgroundChecks.subTitle': ``,
'component.backgroundChecks.learnMore': `Tìm hiểu thêm`,
'component.backgroundChecks.generalSettings': `Cài đặt chung`,
'component.authorization.title': `ủy quyền`,
'component.authorization.link': `Thay đổi người ký`,
'component.backgroundCheck.title': `Kiểm tra lý lịch`,
'component.billingInformation.title': `Thông tin thanh toán để kiểm tra lý lịch`,
'component.optionalOnboardingQuestions.title': ``,
'component.optionalOnboardingQuestions.subTitle': ``,
'component.optionalOnboardingQuestions.addCustomFields': `#ERROR!`,
'component.optionalOnboardingQuestions.customFields': `Trường tuỳ chỉnh`,
'component.optionalOnboardingQuestions.newSection': `#ERROR!`,
'component.optionalOnboardingQuestions.newField': `#ERROR!`,
'component.optionalOnboardingQuestions.sectionName': `Phần tên`,
'component.optionalOnboardingQuestions.fieldName': ``,
'component.optionalOnboardingQuestions.saveOrdering': `Lưu đặt hàng`,
'component.optionalOnboardingQuestions.addQuestion': `Thêm nhiều câu hỏi`,
'component.emailReminderNote.title': `Ghi chú`,
'component.emailReminderNote.note1': `Tuỳ chỉnh tin nhắn triong email là cách tốt để nhận ra ngày và cột mốc quan trọng.`,
'component.emailReminderNote.note2': `Ví dụ: bạn có thể nhắc người quản lý về ngày bắt đầu của thành viên trong nhóm hoặc tạo lời nhắc cho các sự kiện, chẳng hạn như gia hạn giấy phép hoặc đăng ký trong 30 ngày.`,
'component.emailReminderNote.note3': `Bạn có thể sử dụng tính năng Văn bản tự động để tạo email được cá nhân hóa từ một mẫu.`,
'component.emailReminderHeader.title': `Tạo lời nhắc email tùy chỉnh`,
'component.emailReminderForm.title': `Tạo lời nhắc email tùy chỉnh`,
'component.emailReminderForm.triggerNote': ``,
'component.emailReminderForm.triggerNoteLink': `Trường tuỳ chỉnh`,
'component.emailReminderForm.addCondition': `#ERROR!`,
'component.emailReminderForm.cancel': `Huỷ`,
'component.emailReminderForm.submit': `Nộp`,
'component.customEmailsTableField.title': `Email tuỳ chỉnh`,
'component.customEmailsTableField.description': ``,
'component.customEmailsTableField.titleTable': `Email tuỳ chỉnh đã được tạo`,
'component.customEmailsTableField.pagination.showing': ``,
'component.customEmailsTableField.pagination.of': ``,
'component.customEmailsTableField.emailSubject': ``,
'component.customEmailsTableField.createdOn': ``,
'component.customEmailsTableField.triggerEvent': ``,
'component.customEmailsTableField.frequency': ``,
'component.customEmailsTableField.actions': `Tách vụ`,
'component.companySignatory.title': `Người ký kết công ty`,
'component.companySignatory.description': ``,
'component.editEmailNote.title': `Ghi chú`,
'component.editEmailNote.note1': `Tuỳ chỉnh tin nhắn triong email là cách tốt để nhận ra ngày và cột mốc quan trọng.`,
'component.editEmailNote.note2': `Ví dụ: bạn có thể nhắc người quản lý về ngày bắt đầu của thành viên trong nhóm hoặc tạo lời nhắc cho các sự kiện, chẳng hạn như gia hạn giấy phép hoặc đăng ký trong 30 ngày.`,
'component.editEmailNote.note3': `Bạn có thể sử dụng tính năng Văn bản tự động để tạo email được cá nhân hóa từ một mẫu.`,
'component.customEmailsTableField.editEmail': `Chỉnh sửa email`,
'component.editEmailHeader.defaultTitle': ``,
'component.editEmailHeader.title': `Chỉnh sửa lời nhắc trên email tùy chỉnh`,
'component.editEmailForm.addCondition': `#ERROR!`,
'component.editEmailForm.triggerNote': ``,
'component.editEmailForm.triggerNoteLink': `Trường tuỳ chỉnh`,
'component.editEmailForm.cancel': `Huỷ`,
'component.editEmailForm.submit': `Nộp`,
'component.editEmailForm.title': `Chỉnh sửa trên email tùy chỉnh`,
}