export default {
'pages.employeeProfile.title': `Hồ sơ nhân viên`,
'pages.employeeProfile.updateSuccess': `Cập nhật thông tin thành công`,
'pages.employeeProfile.okay': `Đồng ý`,
'pages.employeeProfile.generalInfoTab': `Thông tin chung`,
'pages.employeeProfile.validateNumber': `Chỉ cần số và nhập tối đa 16 số!`,
'pages.employeeProfile.validateSocialSecurityNumber': `Chỉ cần số, ký tự "-" và nhập tối đa 12 số!`,
'pages.employeeProfile.validateWorkNumber': `Chỉ cần số và mã vùng!`,
'pages.employeeProfile.validateVisaNumber': `Số hộ chiếu không hợp lệ!`,
'pages.employeeProfile.validateVisaType': `Loại hộ chiếu không hợp lệ!`,
'pages.employeeProfile.validatePassPortNumber': `Số hộ chiếu không hợp lệ`,
'pages.employeeProfile.validateDate': ``,
'pages.employeeProfile.validateName': `Chỉ cần từ!`,
'pages.employeeProfile.validateEmail': ``,
'pages.employeeProfile.validatelinkedIn': ``,
'pages.employeeProfile.employmentAndCompensationTab': `Công việc & Lương thưởng`,
'pages.employeeProfile.performanceHistoryTab': `Lịch sửa đỉểm hiệu suất`,
'pages.employeeProfile.accountsAndPaychecksTab': `Tài khoản và tiền lương`,
'pages.employeeProfile.documentsTab': `Tài liệu`,
'pages.employeeProfile.workEligibilityAndI-9Tab': ``,
'pages.employeeProfile.timeAndSchedulingTab': ``,
'pages.employeeProfile.benefitPlansTab': `Chương trình phúc lợi`,
'pages.employeeProfile.putOnLeave': ``,
'pages.employeeProfile.raiseTermination': `Chỉ định được nêu lên`,
'pages.employeeProfile.requestDetails': `Yêu cầu chi tiết`,
'pages.employeeProfile.actionMenu': `Tách vụ`,
'pages.employeeProfile.location': `Vị trí`,
'pages.employeeProfile.joinedOn': `Gia nhập vào`,
'pages.employeeProfile.Payslip': `Không có phiếu lương`,
'pages.employeeProfile.bank': `Ngân hàng`,
'pages.employeeProfile.self': `Bản thân`,
'pages.employeeProfile.cancel': `Huỷ`,
'pages.employeeProfile.save': `Lưu thay đổi`,
'pages.employeeProfile.add': `Thêm`,
'pages.employeeProfile.firstName': `Họ`,
'pages.employeeProfile.firstName.placeholder': `Nhập họ`,
'pages.employeeProfile.firstName.validate': `Vui lòng nhập họ!`,
'pages.employeeProfile.lastName': `Tên`,
'pages.employeeProfile.lastName.placeholder': `Nhập tên`,
'pages.employeeProfile.lastName.validate': `Vui làng nhập tên`,
'pages.employeeProfile.gender': `Giới tính`,
'pages.employeeProfile.gender.placeholder': `Chọn giới tính`,
'pages.employeeProfile.gender.validate': `Vui lòng chọn giới tính!`,
'pages.employeeProfile.male': `Nam`,
'pages.employeeProfile.female': `Nữ`,
'pages.employeeProfile.other': `Khác`,
'pages.employeeProfile.relationship': `Quan hệ`,
'pages.employeeProfile.relationship.placeholder': `Nhập mối quan hệ`,
'pages.employeeProfile.relationship.validate': `Vui lòng chọn quạn hệ!`,
'pages.employeeProfile.father': `Ba`,
'pages.employeeProfile.mother': `Mẹ`,
'pages.employeeProfile.spouse': `Vợ/ chồng`,
'pages.employeeProfile.child': `Con`,
'pages.employeeProfile.grandfather': `Ông`,
'pages.employeeProfile.grandmother': `Bà`,
'pages.employeeProfile.dob': `Sinh nhật`,
'pages.employeeProfile.dob.placeholder': `Chọn sinh nhật`,
'pages.employeeProfile.dob.validate': `Vui lòng chọn ngày tháng năm sinh!`,
'pages.employeeProfile.download': `Tải về`,
'pages.employeeProfile.view': `Xem`,
'pages.employeeProfile.single': `Độc thân`,
'pages.employeeProfile.married': `Đã kết hôn`,
'pages.employeeProfile.widowed': `Goá chồng`,
'pages.employeeProfile.divorced': `Li dị`,
'pages.employeeProfile.separated': `Li thân`,
'pages.employeeProfile.notMention': `Không đề cập đến`,
'pages.employeeProfile.resident': `Thường trú`,
'pages.employeeProfile.nonResident': `Tạm trú`,
'pages.employeeProfile.eligibilityDocuments': `Tại liệu đủ điều kiện`,
'pages.employeeProfile.bankDetails': `Ngân hàng chi tiết`,
'pages.employeeProfile.adhaarIdDetails': `Chi tiết ID Adhaar`,
'pages.employeeProfile.passportInformation': `ID Adhaar chi tiết`,
'pages.employeeProfile.tdsCertificate': `Chứng chỉ TDS`,
'pages.employeeProfile.submit': `Nộp`,
'pages.employeeProfile.return': `Huỷ & quay lại`,
'pages.employeeProfile.reason': `Lý do`,
'pages.employeeProfile.requestSuccess': ``,
'pages.employeeProfile.delete': `Xoá`,
'pages.employeeProfile.oldTaxRegime': `Chế độ thuế cũ`,
'pages.employeeProfile.newTaxRegime': `Chế độ thuế mới`,
'pages.employeeProfile.addAnother': `Thêm khác`,
'pages.employeeProfile.continue': `Tiếp tục`,
'pages.employeeProfile.previous': `Trước`,
'pages.employeeProfile.edit': `Chỉnh sửa`,
'pages.employeeProfile.makeChanges': `Thay đổi`,
'pages.employeeProfile.editEmployment': `Chỉnh sửa công việc`,
'pages.employeeProfile.employmentHistory': ``,
'pages.employeeProfile.steps': `bước`,
'pages.employeeProfile.back': `Quay lại`,
'pages.employeeProfile.employmentDetails': `Chi tiết công việc`,
'pages.employeeProfile.customerLocation': `Vị trí của khách hàng`,
'pages.employeeProfile.jobTitle': `Chức danh công việc`,
'pages.employeeProfile.jobTitle.placeholder': `Nhập chức danh công việc`,
'pages.employeeProfile.department': `Bộ phận`,
'pages.employeeProfile.department.placeholder': ``,
'pages.employeeProfile.grade': `Bậc lương`,
'pages.employeeProfile.grade.placeholder': ``,
'pages.employeeProfile.joiningDate': `Ngày gia nhập`,
'pages.employeeProfile.initialJoiningDate': `Ngày dự kiến gia nhập`,
'pages.employeeProfile.workLocation': `Vị trí làm việc`,
'pages.employeeProfile.workLocation.placeholder': ``,
'pages.employeeProfile.locationCustomer': ``,
'pages.employeeProfile.employmentType': `Loại công việc`,
'pages.employeeProfile.employmentType.placeholder': ``,
'pages.employeeProfile.employeeType': `Loại nhân viên`,
'pages.employeeProfile.employeeType.placeholder': ``,
'pages.employeeProfile.timeOffPolicy': ``,
'pages.employeeProfile.regular': ``,
'pages.employeeProfile.contingentWorker': `Nhân viên dự phòng`,
'pages.employeeProfile.typeToSearch': `Nhập để tìm kiếm`,
'pages.employeeProfile.changedReason': `Thay đổi lý do`,
'pages.employeeProfile.changeType': ``,
'pages.employeeProfile.dateRequired': `Vui lòng nhập ngày`,
'pages.employeeProfile.titleRequired': `Vui lòng chọn chức danh công việc tương ứng với bộ phận đã chọn`,
'pages.employeeProfile.appropriateDateRequired': `Vui lòng nhập ngày thích hợp`,
'pages.employeeProfile.fifthStep': ``,
'pages.employeeProfile.firstStep': `Khi bạn muốn những thay đổi có hiệu lực?`,
'pages.employeeProfile.fourthStep': ``,
'pages.employeeProfile.secondStep': ``,
'pages.employeeProfile.seventhStep': ``,
'pages.employeeProfile.sixthStep': ``,
'pages.employeeProfile.thirdStep': ``,
'pages.employeeProfile.employee': `Nhân viên`,
'pages.employeeProfile.reportingManager': `Người quản lý báo cáo của nhân viên`,
'pages.employeeProfile.others': ``,
'pages.employeeProfile.annualCTC': `CTC hằng năm`,
'pages.employeeProfile.annualCTC.placeholder': ``,
'pages.employeeProfile.compensationType': ``,
'pages.employeeProfile.compensationType.placeholder': ``,
'pages.employeeProfile.reasonChange': `Nhập lý do cho việc thay đổi...`,
'pages.employeeProfile.titleLabel': `Tiêu đề`,
'pages.employeeProfile.titleLabel.placeholder': `Chọn một tiêu đề`,
'pages.employeeProfile.reportTo': `Báo cáo cho`,
'pages.employeeProfile.reportTo.placeholder': `Chọn một quản lý`,
'pages.employeeProfile.reportees': `người báo cáo`,
'pages.employeeProfile.reportees.placeholder': `Chọn người báo cáo`,
'pages.employeeProfile.noChange': `Không có thay đổi nào`,
'pages.employeeProfile.requiredField': `Phần bắt buộc!`,
'pages.employeeProfile.contactNo': `Số điện thoại liên hệ`,
'pages.employeeProfile.contactNo.placeholder': ``,
'pages.employeeProfile.addAnotherEmergencyContact': `Thêm một liên hệ khẩn cấp khác`,
'pages.employeeProfile.employeeInformation': `Thông tin nhân viên`,
'pages.employeeProfile.fullname': `Tên đầy đủ`,
'pages.employeeProfile.employeeId': `ID nhân viên`,
'pages.employeeProfile.workEmail': `Email công việc`,
'pages.employeeProfile.workEmail.placeholder': `Nhập email công việc`,
'pages.employeeProfile.workNumber': `Số điện thoại công việc`,
'pages.employeeProfile.workNumber.placeholder': `Nhập số điện thoại công việc`,
'pages.employeeProfile.adhaarCardNumber': ` Số ticket Adhaar`,
'pages.employeeProfile.adhaarCardNumber.placeholder': `Nhập số thẻ Adhaar`,
'pages.employeeProfile.nationalIdentificationNumber': `Mã quốc gia`,
'pages.employeeProfile.nationalIdentificationNumber.placeholder': `Nhập mã quốc gia`,
'pages.employeeProfile.socialSecurityNumber': `Số BHXH`,
'pages.employeeProfile.socialSecurityNumber.placeholder': ``,
'pages.employeeProfile.requireLegalReasons': ``,
'pages.employeeProfile.personalInformation': `Thông tin cá nhân`,
'pages.employeeProfile.personalNumber': `Số điện thoại cá nhân`,
'pages.employeeProfile.personalNumber.placeholder': `Nhập số điện thoại cá nhân`,
'pages.employeeProfile.personalEmail': `Email cá nhân`,
'pages.employeeProfile.personalEmail.placeholder': `Nhập email cá nhân`,
'pages.employeeProfile.bloodGroup': `Nhóm máu`,
'pages.employeeProfile.maritalStatus.placeholder': `Chọn tình trạng hôn nhân`,
'pages.employeeProfile.nationality': `Quốc tịch`,
'pages.employeeProfile.nationality.placeholder': `Nhập quốc tịch`,
'pages.employeeProfile.permanentAddress': `Địa chỉ thường trú`,
'pages.employeeProfile.currentAddress': `Địa chỉ hiện tại`,
'pages.employeeProfile.contentNumber': `Số này sẽ vẫn hiển thị với các nhóm Trình quản lý báo cáo, Nhân sự và Tài chính của bạn, tuy nhiên, bạn có thể chọn ẩn số này với đồng nghiệp bằng cách bật/tắt công tắc được đánh dấu!`,
'pages.employeeProfile.contentEmail': `Email sẽ vẫn hiển thị với các nhóm Trình quản lý báo cáo, Nhân sự và Tài chính của bạn, tuy nhiên, bạn có thể chọn ẩn số này với đồng nghiệp bằng cách bật/tắt công tắc được đánh dấu!`,
'pages.employeeProfile.addressLine1': `Địa chỉ 1`,
'pages.employeeProfile.addressLine1.placeholder': `Nhập địa chỉ email 1`,
'pages.employeeProfile.addressLine1.validate': `Vui lòng nhập địa chỉ`,
'pages.employeeProfile.addressLine2': `Địa chỉ 2`,
'pages.employeeProfile.addressLine2.placeholder': `Nhập địa chỉ email 2`,
'pages.employeeProfile.cityName': `Tên thành phố`,
'pages.employeeProfile.cityName.placeholder': `Nhập thành phố`,
'pages.employeeProfile.shortlyDisabledTitle': ``,
'pages.employeeProfile.passportDetails': `Chi tiết hộ chiếu`,
'pages.employeeProfile.uploadedFile': `file được tải lên:`,
'pages.employeeProfile.issuedByCountry': ``,
'pages.employeeProfile.issuedOn': ``,
'pages.employeeProfile.validTill': ``,
'pages.employeeProfile.passportNumber': `Số hộ chiếu`,
'pages.employeeProfile.country': `Quốc gia`,
'pages.employeeProfile.country.placeholder': `Chọn khu vực`,
'pages.employeeProfile.country.validate': `Vui lòng chọn quốc gia`,
'pages.employeeProfile.state': `Quận`,
'pages.employeeProfile.state.placeholder': `Chọn quận`,
'pages.employeeProfile.zipCode': `Mã bưu chính`,
'pages.employeeProfile.zipCode.placeholder': `Nhập mã bưu chính`,
'pages.employeeProfile.sameAsAbove': `Như trên`,
'pages.employeeProfile.professionalAcademicBackground': ``,
'pages.employeeProfile.preJobTitle': `Chức danh công việc trước đó`,
'pages.employeeProfile.preJobTitle.placeholder': `Nhập chức danh công việc trước đó`,
'pages.employeeProfile.preCompany': `Công ty trước`,
'pages.employeeProfile.preCompany.placeholder': `Loại của công ty trước`,
'pages.employeeProfile.totalExperience': `Tổng số năm kinh nghiệm`,
'pages.employeeProfile.totalExperience.inYrs': `Tổng số năm kinh nghiệm (năm)`,
'pages.employeeProfile.totalExperience.placeholder': `Nhập tổng số năm kinh nghiệm`,
'pages.employeeProfile.highestQualification': `Chất lượng tốt`,
'pages.employeeProfile.highestQualification.placeholder': `Nhập chất lượng tốt nhất`,
'pages.employeeProfile.linkedIn': `Linkedin`,
'pages.employeeProfile.linkedIn.placeholder': `Nhập URL Linkedin`,
'pages.employeeProfile.enterName': `Nhập tên`,
'pages.employeeProfile.sureToRemove': `Bạn có chắc muốn xoá?`,
'pages.employeeProfile.addAttachments': `Thêm file đính kèm`,
'pages.employeeProfile.visaDetails': `Chi tiết thị thực`,
'pages.employeeProfile.visaNumber': `Số thị thực`,
'pages.employeeProfile.visaType': `Loại thị thực`,
'pages.employeeProfile.entryType': `Loại mục nhập`,
'pages.employeeProfile.singleEntry': `Mục duy nhất`,
'pages.employeeProfile.multipleEntry': `Nhiều đầu vào`,
'pages.employeeProfile.validUntil': ``,
'pages.employeeProfile.visa': `Thị thực`,
'pages.employeeProfile.employeeDetails': `Chị tiết của nhân viên`,
'pages.employeeProfile.disabledTitle': ``,
'pages.employeeProfile.emergencyDetails': `Chi tiết liên hệ khẩn cấp `,
'pages.employeeProfile.bankDetail': `Ngân hàng chi tiết`,
'pages.employeeProfile.required': ``,
'pages.employeeProfile.emergencyPersonName': `Tên liên hệ khẩn cấp `,
'pages.employeeProfile.emergencyPersonName.placeholder': ``,
'pages.employeeProfile.emergencyPersonName.validate1': `Vui lòng nhập tên liên hệ khẩn cấp!`,
'pages.employeeProfile.emergencyPersonName.validate2': `Định dạng không hợp lệ, vui lòng thử lại`,
'pages.employeeProfile.relation': `Quan hệ`,
'pages.employeeProfile.relation.validate': `Vui lòng nhập mối quan hệ!`,
'pages.employeeProfile.select': `Vui lòng có một lưạ chọn`,
'pages.employeeProfile.emergencyContact': ``,
'pages.employeeProfile.emergencyContact.validate1': `Vui lòng nhập số điện thoại liên hệ khi khẩn cấp!`,
'pages.employeeProfile.emergencyContact.validate2': `Định dạng không hợp lệ, vui lòng thử lại`,
'pages.employeeProfile.AcademicBackground': ``,
'pages.employeeProfile.totalExp': `Tổng số năm kinh nghiệm`,
'pages.employeeProfile.totalExp.validate1': `Vui lòng nhập số năm kinh nghiệp liên quan!`,
'pages.employeeProfile.totalExp.validate2': ``,
'pages.employeeProfile.qualification': `Trình độ học vấn cao nhất`,
'pages.employeeProfile.qualification.validate': `Vui lòng nhập trình độ học vấn cao nhất của bạn!`,
'pages.employeeProfile.certifications': `Chứng chỉ`,
'pages.employeeProfile.addOtherCertification': `Thêm chúng nhận khác`,
'pages.employeeProfile.skills': `Kỹ năng`,
'pages.employeeProfile.skills.validate': `Vui lòng nhập kỷ năng`,
'pages.employeeProfile.bankName': `Tên ngân hàng`,
'pages.employeeProfile.bankName.validate': `Vui lòng nhập tên ngân hàng!`,
'pages.employeeProfile.branchName': `Tên chi nhánh`,
'pages.employeeProfile.branchName.validate': `Vui lòng nhập tên chi nhánh!`,
'pages.employeeProfile.accountType': `Loại tài khoản`,
'pages.employeeProfile.accountType.validate': `Vui lòng nhập loại tài khoản!`,
'pages.employeeProfile.salaryAccount': `Tài khoản lương`,
'pages.employeeProfile.personalAccount': `Tài khoản cá nhân`,
'pages.employeeProfile.accountNumber': `Số tài khoản`,
'pages.employeeProfile.accountNumber.validate1': `Vui lòng nhập số tài khoản!`,
'pages.employeeProfile.accountNumber.validate2': `Chỉ nhập số và tối đa 16 chữ số`,
'pages.employeeProfile.swiftcode': `Mã nhanh`,
'pages.employeeProfile.swiftcode.validate': `Vui lòng nhập mã nhanh!`,
'pages.employeeProfile.addAnotherAccount': `Thêm tại khoản khác`,
'pages.employeeProfile.limitedAccount': `Bạn có thể thêm 4 tài khoản`,
'pages.employeeProfile.checkingAccount': `Kiểm tra tài khoản`,
'pages.employeeProfile.savingsAccount': `Tài khoản tiết kiệm`,
'pages.employeeProfile.routingNumber': ``,
'pages.employeeProfile.routingNumber.validate1': `Vui lòng nhập số định tuyến!`,
'pages.employeeProfile.routingNumber.validate2': `Chỉ nhập số và tối đa 9 chữ số`,
'pages.employeeProfile.ifscCode': `Mã IFSC`,
'pages.employeeProfile.micrcCode': `Mã MICR`,
'pages.employeeProfile.micrcCode.validate': `Vui lòng nhập mã MICR!`,
'pages.employeeProfile.uanNumber': `Số UAN`,
'pages.employeeProfile.uanNumber.placeholder': `Nhập số UAN`,
'pages.employeeProfile.uanNumber.validate': `Chỉ nhập số và tối đa 16 chữ số`,
'pages.employeeProfile.taxDetails': `Chi tiết thuế`,
'pages.employeeProfile.nationalId': `Số CMND`,
'pages.employeeProfile.nationalId.validate': `Vui lòng nhập số CMND/CCCD`,
'pages.employeeProfile.maritalStatus': `Tình trạng hôn nhân`,
'pages.employeeProfile.maritalStatus.validate': `Vui lòng chọn tình trạng hôn nhân!`,
'pages.employeeProfile.noOfDependents': `Số người phụ thuộc`,
'pages.employeeProfile.noOfDependents.validate': `Vui lòng nhập số người phụ thuộc!`,
'pages.employeeProfile.residencyStatus': `Tình trạng cư trú`,
'pages.employeeProfile.residencyStatus.validate': `Vui lòng chọn tình trạng cư trú!`,
'pages.employeeProfile.socialSecurity': `Số sổ BHXH`,
'pages.employeeProfile.socialSecurity.validate': `Vui lòng nhập số ticket an sinh xã hội`,
'pages.employeeProfile.incomeTaxRule': `Quy tắc thuế thu nhập`,
'pages.employeeProfile.incomeTaxRule.validate': `Vui lòng chọn một quy tắc thuế thu nhập!`,
'pages.employeeProfile.panNumber': `Số PAN`,
'pages.employeeProfile.panNumber.validate': `Vui lòng nhập số PAN`,
'pages.employeeProfile.setApprovalChain': `Thiêt lập chuỗi phê duyệt`,
'pages.employeeProfile.approvalChain.validate': `Vui lòng nhập vào trường văn bản!`,
'pages.employeeProfile.approvalChain.extra': `Nhập Tên của Người quản lý hoặc bất kỳ cơ quan cấp trên nào.`,
'pages.employeeProfile.approvalChain.placeholder': `Chọn quản lý của bạn`,
'pages.employeeProfile.reason.validate': `Vui lòng nhập vào trường văn bản!`,
'pages.employeeProfile.reason.placeholder': `Nhập tại đây...`,
'pages.employeeProfile.manager': `Quản lý`,
'pages.employeeProfile.manager1': `Quản lý 1`,
'pages.employeeProfile.manager2': `Quản lý 2`,
'pages.employeeProfile.search': `Tìm kiếm...`,
'pages.employeeProfile.clickItemFilter': `Nhấp vào {key}`,
'pages.employeeProfile.validateUpload': `Bạn chỉ có thể tải lên file PNG/JPG/PDF`,
'pages.employeeProfile.isLt2M': `Hình ảnh phải nhỏ hơn 2MB`,
'pages.employeeProfile.isLt5M': `Hình ảnh phải nhỏ hơn 5MB`,
'pages.employeeProfile.uploadFile': `Tải file`,
'pages.employeeProfile.loadingChart': `Đang tải biểu đồ...`,
'pages.employeeProfile.year': `Năm`,
'pages.employeeProfile.performanceScore': `Điểm năng suất`,
'pages.employeeProfile.certainty': `chắc chắn`,
'pages.employeeProfile.tooltip': `tooltip`,
'pages.employeeProfile.effectiveDate': `Ngày hiệu lực`,
'pages.employeeProfile.changeDate': `Đổi ngày`,
'pages.employeeProfile.changedBy': `Thay đổi bởi`,
'pages.employeeProfile.careerPathChart': `Định hướng công việc`,
'pages.employeeProfile.documents.infoCollapseType2.type': `Loại`,
'pages.employeeProfile.documents.infoCollapseType2.generatedBy': ``,
'pages.employeeProfile.documents.infoCollapseType2.uploadedBy': `Tải lên bởi`,
'pages.employeeProfile.documents.infoCollapseType2.date': `Ngày`,
'pages.employeeProfile.documents.infoCollapseType2.status': `Trạng thái`,
'pages.employeeProfile.documents.viewDocument.title': `Xem tài liệu`,
'pages.employeeProfile.documents.viewDocument.goBack': `Quay lại`,
'pages.employeeProfile.documents.viewDocument.documentType': `Loại tài liệu`,
'pages.employeeProfile.documents.viewDocument.documentName': `Tên tài liệu`,
'pages.employeeProfile.documents.viewDocument.number': `Số`,
'pages.employeeProfile.documents.viewDocument.shareWith': ``,
'pages.employeeProfile.documents.viewDocument.emailPlaceholder': ``,
'pages.employeeProfile.documents.viewDocument.uploadNewBtn': `Tải lên mới`,
'pages.employeeProfile.documents.noDocument': ``,
'pages.employeeProfile.BenefitTab.coveredIndividuals': ``,
'pages.employeeProfile.BenefitTab.kycDetails': ``,
'pages.employeeProfile.BenefitTab.electedCoverage': ``,
'pages.employeeProfile.BenefitTab.availablePlans': `Kế hoặc phúc lợi có sẵn`,
'pages.employeeProfile.BenefitTab.forGlobalEmployees': `Từ nhân viên toàn cầu`,
'pages.employeeProfile.BenefitTab.forIndianEmployees': `Từ nhân viên Ấn Độ`,
'pages.employeeProfile.BenefitTab.addDependant': `Thêm người phụ thuộc`,
'pages.employeeProfile.BenefitTab.editDependant': `Chỉnh sửa người phụ thuộc`,
'pages.employeeProfile.BenefitTab.dependent': `Ngừoi phụ thuộc`,
'pages.employeeProfile.BenefitTab.kyc.kycStat': `Trạng thái KYC`,
'pages.employeeProfile.BenefitTab.kyc.walletStat': `Trạng thái ví`,
'pages.employeeProfile.BenefitTab.kyc.adhaar': ` Số Adhaar`,
'pages.employeeProfile.BenefitTab.kyc.paytm': ``,
'pages.employeeProfile.BenefitTab.health': `Sức khoẻ & Hạnh phúc`,
'pages.employeeProfile.BenefitTab.financial': `Tài chính`,
'pages.employeeProfile.BenefitTab.legal': `Hợp pháp`,
'pages.employeeProfile.BenefitTab.plan': `Kế hoạch`,
'pages.employeeProfile.BenefitTab.coverageEndDate': `Ngày kết thúc bảo hiểm`,
'pages.employeeProfile.performanceTab.syncWithEPAS': `Nhập vào đây để đồng bộ với EPAS`,
'pages.employeeProfile.performanceHistory.performanceReview': `Đánh giá hiệu suất`,
'pages.employeeProfile.performanceHistory.performanceReview.date': `Ngày`,
'pages.employeeProfile.performanceHistory.performanceReview.reportingTo': `Báo cáo cho`,
'pages.employeeProfile.performanceHistory.performanceReview.collaboration_teamwork': `Hợp tác & làm việc nhóm`,
'pages.employeeProfile.performanceHistory.performanceReview.problemSolving': `Giải quyết vấn đề`,
'pages.employeeProfile.performanceHistory.performanceReview.decisionMaking': `Đưa ra quyết định`,
'pages.employeeProfile.performanceHistory.performanceReview.organizing': `Tổ chức & kế hoạch`,
'pages.employeeProfile.performanceHistory.projectHistory': `Lịch sử dự án`,
'pages.employeeProfile.performanceHistory.projectHistory.projectName': `Tên dự án`,
'pages.employeeProfile.performanceHistory.projectHistory.team': `Nhóm`,
'pages.employeeProfile.performanceHistory.projectHistory.status': `Trạng thái`,
'pages.employeeProfile.performanceHistory.projectHistory.projectDuration': `Thời lượng dự án`,
'pages.employeeProfile.performanceHistory.projectHistory.engagement': `Cam kết`,
'pages.employeeProfile.performanceHistory.career.careerGraph': `Định hướng công việc`,
'pages.employeeProfile.performanceHistory.career.averageScore': `Điểm trung bình`,
'pages.employeeProfile.performanceHistory.career.duration': `Khoảng thời gian`,
'pages.employeeProfile.performanceHistory.career.performanceScore': `Điểm năng suất`,
'pages.employeeProfile.performanceHistory.lestThan1month': `Ít hơn 1 tháng`,
'pages.employeeProfile.performanceHistory.1month': `1 tháng`,
'pages.employeeProfile.performanceHistory.2month': `2 tháng`,
'pages.employeeProfile.performanceHistory.3month': `3 tháng`,
'pages.employeeProfile.performanceHistory.roomToImprove': ``,
'pages.employeeProfile.performanceHistory.budding': `Mới`,
'pages.employeeProfile.performanceHistory.nice': ``,
'pages.employeeProfile.performanceHistory.woah': ``,
'pages.employeeProfile.compensation.summary': ``,
'pages.employeeProfile.compensation.paySlips': `Phiếu lương`,
'pages.employeeProfile.compensation.form16': `Biểu mẫu 16`,
'pages.employeeProfile.compensation.bankAccount': `Tài khoản ngân hàng`,
'pages.employeeProfile.compensation.tax': `Thông tin khấu trừ thuế`,
'pages.employeeProfile.compensation.stocks': `Cổ phiếu`,
'pages.employeeProfile.compensation.addBankAccount': `Thêm tài khoản ngân hàng`,
'pages.employeeProfile.compensation.limitedAccount': `Bạn có thể có đến 4 tài khoản`,
'pages.employeeProfile.compensation.bankName': `Tên ngân hàng`,
'pages.employeeProfile.compensation.bankName.placeholder': `Tên ngân hàng`,
'pages.employeeProfile.compensation.bankName.validate': `Vui lòng nhập tên ngân hàng!`,
'pages.employeeProfile.compensation.branchName': `Tên chi nhánh`,
'pages.employeeProfile.compensation.branchName.placeholder': `Tên chi nhánh`,
'pages.employeeProfile.compensation.branchName.validate': `Vui lòng nhập tên chi nhánh!`,
'pages.employeeProfile.compensation.accountType': `Loại tài khoản`,
'pages.employeeProfile.compensation.accountType.validate': `Vui lòng nhập loại tài khoản!`,
'pages.employeeProfile.compensation.accountNumber': `Số tài khoản`,
'pages.employeeProfile.compensation.accountNumber.validate1': `Vui lòng nhập số tài khoản!`,
'pages.employeeProfile.compensation.accountNumber.validate2': `Chỉ nhập số và tối đa 16 chữ số`,
'pages.employeeProfile.compensation.swiftcode': `Mã nhanh`,
'pages.employeeProfile.compensation.swiftcode.placeholder': `Mã nhanh`,
'pages.employeeProfile.compensation.swiftcode.validate': `Vui lòng nhập mã nhanh!`,
'pages.employeeProfile.compensation.routingNumber': ``,
'pages.employeeProfile.compensation.routingNumber.placeholder': ``,
'pages.employeeProfile.compensation.routingNumber.validate1': `Vui lòng nhập số định tuyến!`,
'pages.employeeProfile.compensation.routingNumber.validate2': `Chỉ nhập số và tối đa 9 chữ số`,
'pages.employeeProfile.compensation.salaryAccount': `Tài khoản lương`,
'pages.employeeProfile.compensation.personalAccount': `Tài khoản cá nhân`,
'pages.employeeProfile.compensation.accountName': `Tên tài khoản`,
'pages.employeeProfile.compensation.accountName.placeholder': `Tên tài khoản`,
'pages.employeeProfile.compensation.accountName.validate': `Vui lòng nhập tên tài khoản!`,
'pages.employeeProfile.compensation.payDetail': `Chi tiết lương (hằng năm)`,
'pages.employeeProfile.compensation.payHistory': `Lịch sử chi trả`,
'pages.employeeProfile.compensation.annualCTC': `CTC hằng năm`,
'pages.employeeProfile.compensation.basic': `Cơ bản`,
'pages.employeeProfile.compensation.otherAllowances': `Các khoản phụ cấp khác`,
'pages.employeeProfile.compensation.variablePayTraget': ``,
'pages.employeeProfile.compensation.viewGrossPay': `Xem tổng lương`,
'pages.employeeProfile.compensation.viewDeductions': `#ERROR!`,
'pages.employeeProfile.compensation.changeType': ``,
'pages.employeeProfile.compensation.salary': `Lương`,
'pages.employeeProfile.compensation.effectiveDate': `Ngày hiệu lực`,
'pages.employeeProfile.compensation.initiatedDate': ``,
'pages.employeeProfile.compensation.changedBy': `Thay đổi bởi`,
'pages.employeeProfile.compensation.showing': ``,
'pages.employeeProfile.compensation.of': ``,
'pages.employeeProfile.compensation.grossPay': `Tổng lương`,
'pages.employeeProfile.compensation.deductions': ``,
'pages.employeeProfile.compensation.netPay': `Thực lãnh`,
'pages.employeeProfile.compensation.paySlipAugust': `Phiếu lương - Tháng 8`,
'pages.employeeProfile.requestDetails.requestType': `Loại yêu cầu`,
'pages.employeeProfile.requestDetails.requestType.placeholder': ``,
'pages.employeeProfile.requestDetails.requestType.validate': `Vui lòng chọn một loại`,
'pages.employeeProfile.requestDetails.additionalInfo': `Thông tin bổ sung`,
'pages.employeeProfile.requestDetails.eligibilityRequest': ``,
'pages.employeeProfile.happenChanged': `Một thay đổi đã xảy ra.`,
'pages.employeeProfile.immediateChanged': `Một sự thay đổi ngay lập tức.`,
'pages.employeeProfile.scheduledChanged': `Thay đổi lịch`,
'pages.employeeProfile.raiseTermination.changeTakeEffect': `Khi bạn muốn những thay đổi có hiệu lực?`,
'pages.employeeProfile.raiseTermination.selectLeaveDate': `Vui lòng chọn nghỉ từ ngày`,
'pages.employeeProfile.raiseTermination.dateChanged': `Vui lòng chọn ngày thay đổi!`,
'pages.employeeProfile.putOnLeave.warning': `Điều này sẽ khiến {full Name} nghỉ phép không lương những ngày đã chọn. Thông báo cập nhật cũng sẽ được gửi cho nhân viên.`,
'pages.employeeProfile.putOnLeave.leaveFrom': ``,
'pages.employeeProfile.putOnLeave.leaveFrom.validate': `Vui lòng chọn nghỉ từ ngày`,
'pages.employeeProfile.putOnLeave.leaveTo': `Nghỉ để`,
'pages.employeeProfile.putOnLeave.leaveTo.validate': `Vui lòng chọn nghỉ đến ngày`,
'pages.employeeProfile.warning': `Điều này sẽ khiến {full Name} nghỉ phép không lương những ngày đã chọn. Thông báo cập nhật cũng sẽ được gửi cho nhân viên.`,
}