export default {
'pages.helpPage.updateSetting': ``,
'pages.helpPage.settings': `Cài đặt`,
'pages.helpPage.support24/7': ``,
'pages.helpPage.contactUs': `Liên hệ với chúng tôi`,
'pages.helpPage.needHelp': ``,
'pages.helpPage.name': `{name} Tên`,
'pages.helpPage.enterName': `Nhập {name} tên`,
'pages.helpPage.addName': `Thêm {tên}`,
'pages.helpPage.editName': `Chỉnh sửa {name}`,
'pages.helpPage.viewName': `Xem {name}`,
'pages.helpPage.deleteName': `Xoá {name}`,
'pages.helpPage.updateName': `Tải lên {name}`,
'pages.helpPage.table.numOf': `Số {name}`,
'pages.helpPage.selectName': `Chọn {name}`,
'pages.helpPage.searchTopic': `Tìm kiếm theo chủ đề hoặc mô tả`,
'pages.helpPage.validate.selectCountry': `Vui lòng chọn khu vực`,
'pages.helpPage.validate.existName': `{name} đã tồn tại`,
'pages.helpPage.validate.requiredField': `Phần bắt buộc!`,
'pages.helpPage.validate.questionExist': `Câu hỏi này đã có`,
'pages.helpPage.validate.maxTopicCharacter': ``,
'pages.helpPage.validate.maxDescriptionCharacter': ``,
'pages.helpPage.table.category': ``,
'pages.helpPage.table.action': `Tách vụ`,
'pages.helpPage.editCategory': `Chỉnh sửa danh mục`,
'pages.helpPage.enterCategory': ``,
'pages.helpPage.saveChanges': `Lưu thay đổi`,
'pages.helpPage.deleteYes': `Đồng ý xoá`,
'pages.helpPage.confirmDelete': `Bạn có chắc không muốn xoá mục này?`,
'pages.helpPage.category': ``,
'pages.helpPage.categoryName': ``,
'pages.helpPage.categories': ``,
'pages.helpPage.addCategories': `Thêm danh mục`,
'pages.helpPage.faqCategories': ``,
'pages.helpPage.faqCategory': ``,
'pages.helpPage.faqList': ``,
'pages.helpPage.FAQ': ``,
'pages.helpPage.addFAQ': `Thêm FAQ`,
'pages.helpPage.editFAQ': `Chỉnh sửa FAQ`,
'pages.helpPage.question': ``,
'pages.helpPage.answer': `Trả lời`,
'pages.helpPage.faqSearch': `Tìm kiến theo câu hỏi hoặc câu trả lời`,
'pages.helpPage.helpCategories': `Danh mục trợ giúp`,
'pages.helpPage.helpTopics': `Đề mục trợ giúp`,
'pages.helpPage.topics': `Chủ đề`,
'pages.helpPage.topic': `Chủ đề`,
'pages.helpPage.searchByTopic': `Tìm kiếm theo chủ đề hoặc mô tả`,
'pages.helpPage.helpCategory': ``,
'pages.helpPage.description': `Mô tả`,
'pages.helpPage.uploadMedia': `Tải lên media file`,
'pages.helpPage.addedBy': `Được thêm bởi`,
'pages.helpPage.addedOn': `Đã thêm vào`,
'pages.helpPage.byCategoryName': `Thêm bởi`,
'pages.helpPage.searchByCategory': `Tìm kiếm theo tên danh mục`,
'pages.helpPage.byCreator': `Tạo bởi`,
'pages.helpPage.searchByCreator': `Tìm kiếm theo người tạo`,
'pages.helpPage.byCreatedDate': `Theo ngày tạo`,
'pages.helpPage.byDuration': `Theo khoản thời gian`,
'pages.helpPage.signPolicy': ``,
'pages.helpPage.sign': ``,
'pages.helpPage.signed': ``,
'pages.helpPage.readPolicy': `Vui lòng đọc tất cả các tài liệu chính sách và ký tên để đánh dấu sự chấp nhận của bạn. Vui lòng liên hệ với HR trong trường hợp có bất kỳ câu hỏi nào.`,
'pages.helpPage.acknowledgement': `Nhìn nhận`,
'pages.helpPage.instructions': ``,
'pages.helpPage.signatureEmployee': `Chữ ký nhân viên`,
'pages.helpPage.thank': `Cảm ơn!`,
'pages.helpPage.documentSent': `Bản sao của tài liệu đã ký đã được gửi cho bạn và HR. Bạn cũng có thể tìm thấy tài liệu này trong tab Tài liệu của Hồ sơ nhân viên.`,
'pages.helpPage.policies': `Chính sách`,
'pages.helpPage.policiesCertification': ``,
'pages.helpPage.exportPolicies': ``,
'pages.helpPage.policiesCategories': `Danh mục chính sách`,
'pages.helpPage.policiesRegulations': `Chính xách & Qui định`,
'pages.helpPage.addPolicy': `Thêm chính sách`,
'pages.helpPage.deletePolicy': `Xoá chính sách`,
'pages.helpPage.editPolicy': `Chỉnh sửa chỉnh sách`,
'pages.helpPage.policyName': `Tên chính sách`,
'pages.helpPage.searchPolicy': `Tfim kiếm theo tên chính sách`,
'pages.helpPage.addPoliciesCategories': `Thêm danh mục chính sách`,
'pages.helpPage.categoriesName': ``,
'pages.helpPage.documentCount': ``,
'pages.helpPage.deletePoliciesCategories': `Xoá danh mục chính sách`,
'pages.helpPage.editPoliciesCategories': `Chỉnh sửa danh mục chính sách`,
'pages.helpPage.selectCountry': `Vui lòng chọn công ty`,
'pages.helpPage.enterCategoriesName': `Vui lòng nhập tên danh mục`,
'pages.helpPage.selectPolicyCategories': `Vui lòng chọn danh mục chính sách`,
'pages.helpPage.selectPolicies': `Vui lòng chọn chính sách`,
'pages.helpPage.enterPolicyName': `Vui lòng nhập tên chính sách`,
'pages.helpPage.existPolicyName': ``,
'pages.helpPage.categoriesNameExist': ``,
'pages.helpPage.onlyUploadPDF': `Bạn chỉ có thể tải lên file PDF`,
'pages.helpPage.invalidFile': `file không hợp lệ`,
'pages.helpPage.dropFile': `Thả file tại đây`,
'pages.helpPage.browse': `duyệt`,
'pages.helpPage.toUpload': `để tải lên một file`,
'pages.helpPage.fileAndSizeSupport': `Kích thước file tối đa là 5 MB. Định dạng hỗ trợ: jpeg & pdf`,
'pages.helpPage.viewDocument': `Xem tài liệu`,
'pages.helpPage.uploadDocument': `Đã tải tài liệu`,
'pages.helpPage.policyDocument': `Tài liệu chính sách`,
}