export default {
'pages.home.notifyMess': `Bạn có`,
'pages.home.isFillTimesheet': `Bạn đã điền bảng chấm chông chưa?`,
'pages.home.announcements': `Thông báo`,
'pages.home.isAnnouncements': `Không có thông báo nào`,
'pages.home.editPost': `Chỉnh sửa bài đăng`,
'pages.home.newPost': `Bài đăng mới`,
'pages.home.deletePostMess': `Bạn có chắc không muốn xoá bài đăng này?`,
'pages.home.social': `Cộng đồng`,
'pages.home.shareSomething': `Hôm nay, hãy chia sẽ vài điều`,
'pages.home.enterDescription': ``,
'pages.home.charLimit': `Số từ giới hạn`,
'pages.home.mediaFile': `Media file`,
'pages.home.chooseFiles': `Chọn file`,
'pages.home.dropFiles': `hoặc thả file tại đây`,
'pages.home.fileSizeAndFormat': `Kích thước file tối đa là 5 MB. Định dạng hỗ trợ: png, jpg, jpeg, mp4 & mov`,
'pages.home.hidePost': ``,
'pages.home.flagPost': ``,
'pages.home.noComment': `Không bình luận`,
'pages.home.addComment': `Thêm một bình luận...`,
'pages.home.approvalPage': `Trang đã được duyệt`,
'pages.home.noBanners': ``,
'pages.home.letsCelebrate': `Chúng ta hãy ăn mừng`,
'pages.home.sayBirthday': `Hãy chúc mừng sinh nhật!`,
'pages.home.sayCongratulation': `Hãy chúc mừng!`,
'pages.home.congratulations': `Chúc mừng!`,
'pages.home.onCompleting': ``,
'pages.home.happyBirthday': `Chúc mừng sinh nhật`,
'pages.home.upBirthday': `Sinh nhật sắp tới`,
'pages.home.txtYear': `năm`,
'pages.home.txtYears': `năm`,
'pages.home.txtWith': `với`,
'pages.home.welcomeNewbie': `Chào mừng thành viên mới gia nhập !!!`,
'pages.home.birthdayEmpty': `Hôm nay không có sinh nhật ai`,
'pages.home.gallery': `Thư viện`,
'pages.home.myTeam': `Team`,
'pages.home.myTickets': `Ticket`,
'pages.home.myCalendar': `Lịch`,
'pages.home.quickLinks': `Liên kết`,
'pages.home.editQuickLink': `Chỉnh sửa liên kết`,
'pages.home.newQuickLink': `Liên kết mới`,
'pages.home.flagAsInappropriate': ``,
'pages.home.employeesVotedOption': `Nhân viên đã bình chọn cho option này`,
'pages.home.numberOfEmloyeesVoted': ``,
'pages.home.pollEndsOn': `Khảo sát kết thúc lúc`,
'pages.home.howDoYouFeel': ``,
'pages.home.addUpTo3Response': ``,
'pages.home.postManagement': `Quản lý bài đăng`,
'pages.home.quickLinkManagement': `Quản lý liên kết`,
'pages.home.employeePost': `Bài đăng của nhân viên`,
'pages.home.general': `Chung`,
'pages.home.forTimeoff': ``,
'pages.home.employeePlaceHolder': ``,
}