export default {
'pages.login.signIn': ``,
'pages.login.signInToYourAccount': ``,
'pages.login.emailLabel': `Địa chỉ email`,
'pages.login.pleaseInputYourEmail': `Vui lòng nhập địa chỉ email của bạn`,
'pages.login.invalidEmail': `Email không hợp lệ`,
'pages.login.passwordLabel': ``,
'pages.login.pleaseInputYourPassword': `Vui lòng nhập địa chỉ mật khẩu của bạn`,
'pages.login.keepMeSignedIn': ``,
'pages.login.forgotPassword': `Quên mật khẩu?`,
'pages.login.welcomeBack': ``,
'pages.login.enterCredentials': ``,
'pages.login.loginPortal': ``,
'pages.login.enterEmail': ``,
'pages.login.enterPassword': ``,
'pages.login.orSignIn': ``,
'pages.login.terralogicLogin': ``,
}