export default {
'menu.welcome': ``,
'menu.more-blocks': ``,
'menu.home': ``,
'menu.home-settings': `Cài đặt`,
'menu.home-settings.add-post': `Bài đăng mới`,
'menu.login': ``,
'menu.register': ``,
'menu.register.result': ``,
'menu.dashboard.analysis': `Phân tích`,
'menu.dashboard.monitor': ``,
'menu.dashboard.workplace': ``,
'menu.exception.403': ``,
'menu.exception.404': ``,
'menu.exception.500': ``,
'menu.form': `Biểu mẫu `,
'menu.form.basic-form': `Biểu mẫu cơ bản`,
'menu.form.step-form': `Bước từ`,
'menu.form.step-form.info': `Bước từ (viết thông tin chuyển giao)`,
'menu.form.step-form.confirm': `Bước từ (xác nhận thông tin chuyển giao)`,
'menu.form.step-form.result': `Bước từ (hoàn thành)`,
'menu.form.advanced-form': `Biểu mẫu nâng cao`,
'menu.list': `Danh sách`,
'menu.list.table-list': `Tìm bảng`,
'menu.list.basic-list': `Danh sách cơ bản`,
'menu.list.card-list': `Danh sách thẻ`,
'menu.list.search-list': `Tìm danh sách`,
'menu.list.search-list.articles': `Tìm danh sách (bài viết)`,
'menu.list.search-list.projects': `Tìm danh sách (dự án)`,
'menu.list.search-list.applications': `Tìm danh sách (ứng dụng)`,
'menu.profile': `Hồ sơ`,
'menu.profile.basic': `Hồ sơ cơ bản`,
'menu.profile.advanced': `Hồ sơ nâng cao`,
'menu.result': ``,
'menu.result.success': `Thành công`,
'menu.result.fail': ``,
'menu.exception': ``,
'menu.exception.not-permission': ``,
'menu.exception.not-find': ``,
'menu.exception.server-error': ``,
'menu.exception.trigger': ``,
'menu.account': `Tài khoản`,
'menu.account.center': `Trung tâm tài khoản`,
'menu.account.settings': `Cài đặt tài khoản`,
'menu.account.trigger': ``,
'menu.account.logout': `Đăng xuất`,
'menu.editor': ``,
'menu.editor.flow': ``,
'menu.editor.mind': ``,
'menu.editor.koni': ``,
'menu.change-password': `Đổi mật khẩu`,
'menu.control-panel.name': ``,
'menu.control-panel.companyProfile': `Hồ sơ công ty`,
'menu.admin': `Quản trị viên`,
'menu.admin-app': `App của quản trị viên`,
'menu.admin.sub-page': `Trang phụ`,
'menu.users': `Quản lý người dùng`,
'menu.employees': ``,
'menu.candidates': `Quàn lý ứng viên`,
'menu.companies': ``,
'menu.add-company': `Thêm công ty`,
'menu.company-detail': `Chi tiết công ty`,
'menu.documents': ``,
'menu.timeoff-management': ``,
'menu.offboarding-management': ``,
'menu.settings': `Cài đặt`,
'menu.permission': ``,
'menu.user-profile': `Hồ sơ người dùng`,
'menu.onboarding': ``,
'menu.employee-onboarding': `Nhân viên đang gia nhập`,
'menu.add-team-member': `Thêm một thành viên`,
'menu.onboarding.create-field-section': ``,
'menu.create-email-reminder': ``,
'menu.edit-email': `Chỉnh sửa email`,
'menu.view-email': `Xem email`,
'menu.offboarding': ``,
'menu.ticket-id': `ID ticket`,
'menu.offboarding.relieving-detail': `ID ticket`,
'menu.resignation-request': `Yêu cầu từ chức`,
'menu.review-resignation-ticket': `Xem lại ticket`,
'menu.create-custom-email': ``,
'menu.offboarding.template.email': ``,
'menu.offboarding.setting.form.view-form': `xem biểu mẫu`,
'menu.offboarding.setting.form.add-form': `Thêm biểu mẫu tùy chỉnh`,
'menu.offboarding.setting.form.edit-form': `Chỉnh sửa biểu mẫu`,
'menu.time-off': `Giờ nghỉ`,
'menu.request-for-timeoff': `Yêu cầu nghỉ`,
'menu.edit-timeoff-request': `Chỉnh sửa yêu cầu thời gian nghỉ`,
'menu.view-timeoff-request': `Xem yêu cầu thời gian nghỉ`,
'menu.request-for-compoff': `Yêu cầu OT(overtime)`,
'menu.edit-compoff-request': `Chỉnh sửa yêu cầu OT(overtime)`,
'menu.view-compoff-request': `Xem yêu cầu OT(overtime)`,
'menu.time-off-type-configuration': ``,
'menu.timeoff-setup': ``,
'menu.timeoff-history': `Lịch sử giờ nghỉ`,
'menu.timeoff-overview': `Tổng quan`,
'menu.project-management': ``,
'menu.project-management.view-project': `Xem dự án`,
'menu.ticket-management': `Quản lý ticket`,
'menu.ticket-management.view-ticket': `Xem ticket`,
'menu.ticket-management.settings': `Cài đặt`,
'menu.ticket-management.settings.config': ``,
'menu.resource-management': ``,
'menu.view-customer': `Xem chi tiết khách hàng`,
'menu.customer-management': ``,
'menu.directory': `Danh mục`,
'menu.employee-profile': `Hồ sơ nhân viên`,
'menu.candidate-profile': `Hồ sơ ứng viên`,
'menu.candidate-detail': `Chi tiết ứng viên`,
'menu.candidate-portal': `Cổng thông tin ứng viên`,
'menu.candidate-change-password': `Ứng viên thay đổi mặt khẩu`,
'menu.dashboard': `Bảng điều khiển`,
'menu.dashboard-approvals': `Duyệt`,
'menu.search-result': `Tìm kiếm kết quả`,
'menu.search-result.advanced-search': `Tìm kiếm nâng cao`,
'menu.timesheet': `Bảng chấm công`,
'menu.policies-regulations': `Chính xách & Qui định`,
'menu.policies-certification': `Chứng nhận chính sách`,
'menu.view-document': `Xem tài liệu`,
'menu.template-details': ``,
'menu.create-new-template': `Tạo mẫu mới`,
'menu.upload-document': `Thêm tài liệu`,
'menu.create-template': `Tạo mẫu mới`,
'menu.faqs': ``,
'menu.hrms-help-center': `HR-OS trợ giúp`,
}