export default {
'component.reminder.title': ``,
'component.reminder.content': ``,
'component.basicInformation.step1': ``,
'component.basicInformation.title': `Thông tin cơ bản`,
'component.basicInformation.subtitle': `Vui lòng xác nhận thông tin chi tiết bên dưới`,
'component.basicInformation.firstName': `Họ`,
'component.basicInformation.middleName': `Tên lót`,
'component.basicInformation.lastName': `Tên`,
'component.basicInformation.employeeId': `ID nhân viên`,
'component.basicInformation.firstNameRequiredAlert': `Vui lòng nhập họ!`,
'component.basicInformation.middleNameRequiredAlert': `Vui lòng nhập tên lót!`,
'component.basicInformation.lastNameRequiredAlert': `Vui lòng nhập tên!`,
'component.basicInformation.privateEmail': `ID email cá nhân`,
'component.basicInformation.workEmail': `ID email công việc`,
'component.basicInformation.experienceYear': ``,
'component.jobDetail.title': ``,
'component.jobDetail.subtitle': `Thông tin chi tiết về vị trí ứng viên đang tuyển dụng`,
'component.jobDetail.positionTab': `Chức vụ`,
'component.jobDetail.positionTabRadio1': `Nhân viên`,
'component.jobDetail.positionTabRadio2': `Nhân viên dự phòng`,
'component.jobDetail.classificationTab': `Phân loại`,
'component.jobDetail.classificationRadio1': `Full-time (nhân viên làm việc trên 30 giờ/ tuần)`,
'component.jobDetail.classificationRadio2': `Part-time (nhân viên làm việc dưới 30 giờ/ tuần)`,
'component.jobDetail.classificationRadio3': `Thực tập (sinh viên hoặc thực tập sinh tham gia thực tập)`,
'component.jobDetail.jobGrade': `Bậc lương`,
'component.jobDetail.department': `Bộ phận`,
'component.jobDetail.jobTitle': `Chức danh công việc`,
'component.jobDetail.jobCategory': `Danh mục công việc`,
'component.jobDetail.city': `Thành phố`,
'component.jobDetail.country': `Quốc gia`,
'component.jobDetail.workLocation': `Vị trí làm việc`,
'component.jobDetail.reportingManager': `Quản lý báo cáo`,
'component.jobDetail.filledByCandidate': `Vui lòng thêm ngày tham gia dự kiến cho ứng viên bên dưới.`,
'component.jobDetail.candidateNoticePeriod': `Thời hạn thông báo của ứng viên`,
'component.jobDetail.prefferedDateOfJoining': ``,
'component.jobDetail.reminder.content': `Dự kiến ngày gia nhập công ty`,
'component.jobDetail.reminder.content2': ``,
'component.offerDetail.title': ``,
'component.offerDetail.subtitle': `Tất cả các tài liệu hỗ trợ đủ điều kiện làm việc của ứng viên sẽ được hiển thị ở đây`,
'component.offerDetail.offerLetter': `Thư đề nghị`,
'component.offerDetail.notInclude': ``,
'component.offerDetail.include': ``,
'component.offerDetail.uploadOffer': ``,
'component.offerDetail.agreementTitle': ``,
'component.offerDetail.agreement': ``,
'component.offerDetail.handbookTitle': `Sổ tay công ty`,
'component.offerDetail.handbook': `Sổ tay công ty của tôi`,
'component.offerDetail.compensationTitle': ``,
'component.offerDetail.amountTitle': `Số tiền trong`,
'component.offerDetail.timeoffTitle': ``,
'component.offerDetail.alertContent1': ``,
'component.offerDetail.phase3': ``,
'component.offerDetail.alertContent2': ``,
'component.offerDetail.alertContent3': ``,
'component.offerDetail.alertContent4': `App quản lý bồi thường`,
'component.offerDetail.alertContent5': `Bạn có chắc không? Người thuê này sẽ không thể gửi yêu cầu nghỉ bất kỳ lúc nào.`,
'component.previewOffer.title': `Thoả thuận nhân viên`,
'component.previewOffer.hrSignature': `Chữ ký HR`,
'component.previewOffer.candidateSignature': `Chữ ký của ứng viên`,
'component.previewOffer.undersigned': ``,
'component.previewOffer.managerSignature': `Chữ ký Quản lý nhân sự`,
'component.previewOffer.managerUndersigned': ``,
'component.previewOffer.uploadNew': `Tải lên mới`,
'component.previewOffer.upload': `Tải lên`,
'component.previewOffer.submit': `Nộp`,
'component.previewOffer.submitted': ``,
'component.previewOffer.send': `Gửi phê duyệt`,
'component.previewOffer.note1': `Theo thông báo mặc định`,
'component.previewOffer.note2': `sẽ gửi cho HR`,
'component.previewOffer.note3': `, quản lý của bạn và lặp lại quy trình với trưởng bộ phận của bạn để phê duyệt.`,
'component.previewOffer.also': `Ngoài ra, thêm e-mail của người mới. Bạn có thể gửi ưu đãi sau khi tất cả các phê duyệt được sắp xếp theo thứ tự.`,
'component.previewOffer.hrMail': `ID email HR`,
'component.previewOffer.invalidMailErr': ``,
'component.previewOffer.emptyMailErr': `Vui lòng nhập email của bạn!`,
'component.previewOffer.sendForApproval': `Gửi phê duyệt`,
'component.customField.title': `Trường tuỳ chỉnh`,
'component.customField.subTitle': `Tất cả các tài liệu hỗ trợ đủ điều kiện làm việc của ứng viên sẽ được hiển thị ở đây`,
'component.customField.dentalLabel': ``,
'component.customField.visionLabel': ``,
'component.customField.medicalLabel': ``,
'component.customField.additionalLabel': ``,
'component.noteComponent.content': ``,
'component.noteComponent.title': `Ghi chú`,
'component.salaryStructureHeader.title': ``,
'component.salaryStructureHeader.subTitle1': `Phân chia lương theo chức danh công việc đã chọn. Ngoài ra, bạn có thể nhập một cấu trúc tiền lương mới. Làm như vậy`,
'component.salaryStructureHeader.subTitle2': ``,
'component.salaryStructureHeader.subTitle3': `và tải lên`,
'component.salaryStructure.tableWrapper': `Bảng cơ cấu tiền lương nên điền ở đâu. Cần làm rõ ở đây nếu bảng hoặc thông tin này có thể chỉnh sửa bởi bộ phận nhân sự?`,
'component.salaryAcceptanceContent.content': `Chấp nhận cơ cấu lương của ứng viên`,
'component.salaryAcceptance.title1': `Cơ cấu lương đã được ứng viên chấp nhận.`,
'component.salaryAcceptance.note1': `Bạn đã xem qua tất cả các nội dung của bảng và chấp nhận tiền lương như điều kiện làm việc của bạn.`,
'component.salaryAcceptance.title2': ``,
'component.salaryAcceptance.note2': ``,
'component.salaryAcceptance.title3': ``,
'component.salaryAcceptance.note3': `Bạn đã xem qua tất cả nội dung của bảng và không chấp nhận đề nghị của tôi.`,
'component.salaryAcceptance.closeCandidature': ``,
'component.salaryAcceptance.pendingMessage': `Chúng tôi đang chờ cô Ashwini Narayana đánh dấu việc chấp nhận cơ cấu lương chung`,
'component.salaryAcceptance.sendFormAgain': `Gửi lại biểu mẫu`,
'component.salaryAcceptance.submitForm': ``,
'component.salaryAcceptance.sendEmail': `Gửi email`,
'component.salaryAcceptance.acceptanceTitle': `Chấp nhận cấcơ cấu lương`,
'component.salaryAcceptance.note': ``,
'component.salaryStructureTemplate.done': `Hoàn thành`,
'component.salaryStructureTemplate.edit': `Chỉnh sửa`,
'component.eligibilityDocs.TypeA': ``,
'component.eligibilityDocs.aadharCard': ``,
'component.eligibilityDocs.pan': ``,
'component.eligibilityDocs.passport': `Hồ chiếu`,
'component.eligibilityDocs.drivingLicense': ``,
'component.eligibilityDocs.voterCard': `Phiếu bình chọn`,
'component.eligibilityDocs.TypeB': `Loại B: Địa chỉ`,
'component.eligibilityDocs.rentalAgreement': ``,
'component.eligibilityDocs.electricityUtilityBills': ``,
'component.eligibilityDocs.telephoneBills': ``,
'component.eligibilityDocs.TypeC': ``,
'component.eligibilityDocs.sslc': ``,
'component.eligibilityDocs.intermediateDiploma': ``,
'component.eligibilityDocs.graduation': ``,
'component.eligibilityDocs.postGraduate': ``,
'component.eligibilityDocs.phdDoctorate': ``,
'component.eligibilityDocs.TypeD': ``,
'component.eligibilityDocs.TypeE': ``,
'component.eligibilityDocs.offerLetter': `Thư đề nghị`,
'component.eligibilityDocs.appraisalLetter': `Thư thẩm định`,
'component.eligibilityDocs.paystubs': ``,
'component.eligibilityDocs.form16': `Biểu mẫu 16`,
'component.eligibilityDocs.relievingCard': ``,
'component.eligibilityDocs.employerDetail': ``,
'component.eligibilityDocs.nameOfTheEmployer': ``,
'component.eligibilityDocs.workDuration': ``,
'component.eligibilityDocs.proofOfEmployment': ``,
'component.eligibilityDocs.suggestion': ``,
'component.eligibilityDocs.noteNormal': `Ứng viên phải tải lên tất cả các tài liệu cần thiết. Và, HR phải phê duyệt các tài liệu và đánh dấu ứng viên là đủ điều kiện.`,
'component.eligibilityDocs.noteBold': `Đăng phê duyệt này, các quy trình còn lại sẽ mở cho giới thiệu.`,
'component.eligibilityDocs.sentForm': ``,
'component.eligibilityDocs.viaEmail': ``,
'component.eligibilityDocs.emailSubtitle': `Biểu mẫu sẽ được gửi trên id email cá nhân của ứng viên`,
'component.eligibilityDocs.generateLink': ``,
'component.eligibilityDocs.linkSubtitle': ``,
'component.eligibilityDocs.headerReminder': ``,
'component.eligibilityDocs.title': `Kiểm tra lý lịch`,
'component.eligibilityDocs.subtitle': `Vui lòng chọn tất cả các tài liệu được chấp nhận mà ứng viên có thể cung cấp. Các tài liệu bắt buộc là bắt buộc và không thể bỏ chọn.`,
'component.eligibilityDocs.emailLabel': ``,
'component.eligibilityDocs.sendEmail': `Gửi email`,
'component.eligibilityDocs.markAsDone': ``,
'component.eligibilityDocs.restrictedAccess': ``,
'component.eligibilityDocs.restrictedHelper': `Chỉ những người được uỷ quyền mới có thể truy cập vào liên kết này`,
'component.eligibilityDocs.owner': `Chủ`,
'component.eligibilityDocs.change': `Thay đổi`,
'component.Benefits.Title': `Phúc lợi`,
'component.Benefits.subTitle': ``,
'component.Benefits.globalEmployeeTitle': `Từ nhân viên toàn cầu`,
'component.Benefits.subHeader': ``,
'component.Benefits.medical': ``,
'component.Benefits.openAccess': ``,
'component.Benefits.OAP': ``,
'component.Benefits.dental': ``,
'component.Benefits.volDental': ``,
'component.Benefits.vision': ``,
'component.Benefits.visionPro': ``,
'component.Benefits.life': ``,
'component.Benefits.basicLife': ``,
'component.Benefits.volLife': ``,
'component.Benefits.shortTerm': ``,
'component.Benefits.shortTermTitle': ``,
'component.Benefits.IndiaEmployeeTitle': `Từ nhân viên Ấn Độ`,
'component.Benefits.paytm': ``,
'component.Benefits.Employee': `Quỹ tiết kiệm của nhân viên`,
'component.Benefits.employeeTitle': `Nhân viên dự phòng`,
'page.signUp.signUpHeader': ``,
'component.References.title': ``,
'component.References.subTitle': `Ứng viên cần điền vào các chi tiết liên quan`,
'component.References.mention': ``,
}