export default {
'pages.offBoarding.companyWide': `Toàn công ty`,
'pages.offBoarding.teamRequest': ``,
'pages.offBoarding.myRequest': ``,
'pages.offBoarding.settings': `Cài đặt`,
'pages.offBoarding.export': `Xuất`,
'pages.offBoarding.scheduledOn': ``,
'pages.offBoarding.joinGoogleMeet': `Tham gia Google Meet`,
'pages.offBoarding.reschedule': ``,
'pages.offBoarding.btn.accept': `Chấp nhận`,
'pages.offBoarding.btn.reject': `Từ chối`,
'pages.offBoarding.table.ticketId': `ID ticket`,
'pages.offBoarding.table.createdDate': `Ngày tạo`,
'pages.offBoarding.table.employeeId': `ID nhân viên`,
'pages.offBoarding.table.employeeName': `Tên nhân viên`,
'pages.offBoarding.table.requesteeName': `Tên người yêu cầu`,
'pages.offBoarding.table.manager': `Quản lý`,
'pages.offBoarding.table.position': `Chức vụ`,
'pages.offBoarding.table.department': `Bộ phận`,
'pages.offBoarding.table.dateOfJoining': ``,
'pages.offBoarding.table.reportingManager': `Quản lý báo cáo`,
'pages.offBoarding.table.hrPOC': `HR POC`,
'pages.offBoarding.table.1on1Date': ``,
'pages.offBoarding.table.action': `Tách vụ`,
'pages.offBoarding.table.managerApproved': `Quản lý đã duyệt`,
'pages.offBoarding.tableProject.projectName': `Tên dự án`,
'pages.offBoarding.tableProject.customerName': `Tên khách hàng`,
'pages.offBoarding.tableProject.projectManager': `Quản lý dự án`,
'pages.offBoarding.table.reAssignPersonPopup': `Chỉ định lại HR`,
'pages.offBoarding.table.reAssignManagerPopup': ``,
'pages.offBoarding.table.reAssignModal.title': `Đổi HR`,
'pages.offBoarding.workFlow.title': ``,
'pages.offBoarding.workFlow.resignationRequest': ``,
'pages.offBoarding.workFlow.step1': ``,
'pages.offBoarding.workFlow.step2': ``,
'pages.offBoarding.workFlow.step2.text': ``,
'pages.offBoarding.workFlow.initiateRequest': ``,
'pages.offBoarding.workFlow.submitRequest': `Nộp yêu cầu`,
'pages.offBoarding.workFlow.oneOnOne': `1-1 với người quản lý của bạn và nhận chấp thuận của họ`,
'pages.offBoarding.workFlow.hrApproval': `HR phê duyệt`,
'pages.offBoarding.workFlow.relieving.exitInterview': `Kết thúc pphỏng vấn và đóng hồ sơ`,
'pages.offBoarding.workFlow.relieving.hrSendsDocuments': `HR gửi thư cảm ơn`,
'pages.offBoarding.workFlow.relieving.terminationComplete': ``,
'pages.offBoarding.advise.title': ``,
'pages.offBoarding.advise.question': ``,
'pages.offBoarding.advise.text': `8/10 nhân viên đã thay đổi suy nghỉ sau khi nói chuyện với quản lý của họ.`,
'pages.offBoarding.advise.scheduleMeeting': ``,
'pages.offBoarding.advise.btn.scheduleOneOnOne': ``,
'pages.offBoarding.advise.noteText.firstText': ``,
'pages.offBoarding.advise.noteText.secondText': ``,
'pages.offBoarding.consider.title': ``,
'pages.offBoarding.consider.discussText': ``,
'pages.offBoarding.consider.makeSureText': `Đảm bảo rằng bạn đã hoàn thành dự án hiện tại của mình để tiếp tục cuộc thảo luận này.`,
'pages.offBoarding.consider.preparedText.firstContent': ``,
'pages.offBoarding.consider.preparedText.secondContent': `mà bạn có thể muốn xem trước khi đăng ký kết thúc liên hệ`,
'pages.offBoarding.consider.preparedText.checkList': ``,
'pages.offBoarding.consider.btn.speakToManager': ``,
'pages.offBoarding.quickLinks.title': `Liên kết`,
'pages.offBoarding.quickLinks.documentTitle': ``,
'pages.offBoarding.reasonForm.title': `Lý do nghỉ`,
'pages.offBoarding.reasonForm.LWD': ``,
'pages.offBoarding.reasonForm.LWD.noteText': ``,
'pages.offBoarding.reasonForm.LWD.notePolicy': ``,
'pages.offBoarding.reasonForm.placeHolderInput': `Lý do bạn quyết định kết thúc hành trình với công ty là...`,
'pages.offBoarding.reasonForm.remind.content': `Theo mặc định, thông báo sẽ được gửi cho HR, quản lý và lặp lại các bước với trưởng bộ phận của bạn`,
'pages.offBoarding.reasonForm.btn.submit': `Nộp`,
'pages.offBoarding.reasonForm.btn.draft': `Lưu nháp`,
'pages.offBoarding.reasonForm.notification.btn': `Đồng ý`,
'pages.offBoarding.reasonForm.notification.secondText': `Yêu cầu của bạn đã được gửi`,
'pages.offBoarding.reasonForm.notification.firstText': ``,
'pages.offBoarding.yourRequest.title': `Yêu cầu của bạn`,
'pages.offBoarding.yourRequest.titleForDraft': `Lưu nháp`,
'pages.offBoarding.yourRequest.assigned': `Đã phân công`,
'pages.offBoarding.yourRequest.tentativeLWD': `Dự kiến ngày làm việc cuối cùng`,
'pages.offBoarding.yourRequest.reasonText': `Lý do nghỉ`,
'pages.offBoarding.yourRequest.requestOn': ``,
'pages.offBoarding.yourRequest.tentativeLWDText': ``,
'pages.offBoarding.yourRequest.reason': `Lý do`,
'pages.offBoarding.yourRequest.lastEdited': ``,
'pages.offBoarding.yourRequest.btn.withdraw': `Rút lại`,
'pages.offBoarding.yourRequest.btn.schedule1on1': ``,
'pages.offBoarding.yourRequest.btn.backToEdit': `Quay lại chỉnh sửa`,
'pages.offBoarding.yourRequest.btn.delete': `Xoá`,
'pages.offBoarding.yourRequest.popupText': `Không thể rút lại yêu cầu nghỉ việc sau khi Người quản lý phê duyệt. Vui lòng nói chuyện với HR để thay đổi yêu cầu của bạn.`,
'pages.offBoarding.yourRequest.modal.title': ``,
'pages.offBoarding.partnerRole.manager': `Quản lý`,
'pages.offBoarding.partnerRole.employee': `Nhân viên`,
'pages.offBoarding.chainOfApproval.title': `Chuỗi phê duyệt`,
'pages.offBoarding.status': `Trạng thái`,
'pages.offBoarding.status.inProgress': `Đang tiến hành`,
'pages.offBoarding.status.accepted': `Đã chấp nhận`,
'pages.offBoarding.status.draft': `Nháp`,
'pages.offBoarding.status.rejected': `Đã từ chối`,
'pages.offBoarding.status.withdrawn': `Rút lại`,
'pages.offBoarding.status.pendingWithdraw': `Đang chờ`,
'pages.offBoarding.status.deleted': `Đã xoá`,
'pages.offBoarding.note.title': `Ghi chú`,
'pages.offBoarding.note.defaultContent.firstText': ``,
'pages.offBoarding.note.defaultContent.secondText': `để tìm hiểu thêm. LWD được tạo ra bởi hệ thống. Mọi yêu cầu thay đổi phải được sự chấp thuận của người quản lý nhân sự mới có hiệu lực.`,
'pages.offBoarding.note.inProgressContent.attentionText': ``,
'pages.offBoarding.note.inProgressContent.firstText': ``,
'pages.offBoarding.note.inProgressContent.secondText': ``,
'pages.offBoarding.stepsTitle': ``,
'pages.offBoarding.setMeetingModalText.name': `Tên`,
'pages.offBoarding.setMeetingModalText.label.date': `Ngày`,
'pages.offBoarding.setMeetingModalText.label.startTime': `Thời gian bắt đầu`,
'pages.offBoarding.setMeetingModalText.label.endTime': `Thời gian kết thúc`,
'pages.offBoarding.setMeetingModalText.btn.set': `Thiết lập`,
'pages.offBoarding.setMeetingModalText.placeHolderDate': `Chọn ngày`,
'pages.offBoarding.setMeetingModalText.placeHolderStartTime': `Chọn ngày bắt đầu`,
'pages.offBoarding.setMeetingModalText.placeHolderEndTime': `Chọn ngày kết thúc`,
'pages.offBoarding.whatNext.1on1Meeting': ``,
'pages.offBoarding.whatNext.acceptMeeting': `Chấp nhận cuộc họp`,
'pages.offBoarding.whatNext.title': ``,
'pages.offBoarding.whatNext.notes': `Ghi chú`,
'pages.offBoarding.whatNext.managerRejectDateText': ``,
'pages.offBoarding.whatNext.managerPickDateText': ``,
'pages.offBoarding.whatNext.managerConfirmDateText': `Yêu cầu họp đã được chấp nhận bởi`,
'pages.offBoarding.whatNext.employeePickDate.firstText': ``,
'pages.offBoarding.whatNext.employeePickDate.secondText': `để chấp nhận yêu cầu họp của bạn.`,
'pages.offBoarding.whatNext.schedule1-on-1': ``,
'pages.offBoarding.whatNext.meetingContent.notStart': ``,
'pages.offBoarding.whatNext.meetingContent.notStart.noteText': ``,
'pages.offBoarding.whatNext.meetingContent.confirmNotification': ``,
'pages.offBoarding.whatSteps.title': `Những bước kế tiếp`,
'pages.offBoarding.whatSteps.content.firstContent': `Bạn sẽ sớm nhận được tài liệu của buổi phỏng vấn thôi việc. Xem danh sách và nộp chúng trước buổi phỏng vấn.`,
'pages.offBoarding.whatSteps.content.secondContent': `Nhân sự sẽ sớm gửi lời mời cho cuộc phỏng vấn cho bạn.`,
'pages.offBoarding.reAssignModal.label.from': `Từ`,
'pages.offBoarding.reAssignModal.messageErrorRequired.to': `Vui lòng chọn một nhân viên`,
'pages.offBoarding.reAssignModal.label.to': `Đến`,
'pages.offBoarding.reAssignModal.placeHolder.to': `Nhập để tìm kiếm`,
'pages.offBoarding.reAssignModal.btnAdd': `Thêm`,
'pages.offBoarding.filters.byDate': `Theo ngày`,
'pages.offBoarding.filters.from': `Từ`,
'pages.offBoarding.filters.to': `Đến`,
'pages.offBoarding.searchPlaceHolder': `Tìm kiếm theo số ticket, người thôi việc, yêu cầu...`,
'pages.offBoarding.detailTicket.titlePage': ``,
'pages.offBoarding.detailTicket.requesteeTitle': `Người yêu cầu chi tiết`,
'pages.offBoarding.detailTicket.resignationTitle': `Yêu cầu từ chức chi tiết`,
'pages.offBoarding.detailTicket.currentProjectTitle': `Chi tiết dự án hiện tại`,
'pages.offBoarding.hrView.processStatusText.inProgress': `Yêu cầu vẫn đang được xem bởi người quản lý báo cáo`,
'pages.offBoarding.hrView.processStatusText.accepted': `Yêu cầu này được phê duyệt bởi`,
'pages.offBoarding.hrView.processStatusText.deleted': `Yêu cầu đã được xoá`,
'pages.offBoarding.hrView.processStatusText.rejected': `Yêu cầu đã được từ chối`,
'pages.offBoarding.resignation.dateRequest': `Ngày yêu cầu`,
'pages.offBoarding.resignation.changedLWDText': ``,
'pages.offBoarding.resignation.changedByHRManager': `Quản lý nhân sự`,
'pages.offBoarding.resignation.changedByManager': ``,
'pages.offBoarding.resignation.systemGenerated': `Hệ thống tự tạo`,
'pages.offBoarding.closingComment.placeHolder': ``,
'pages.offBoarding.closingComment.canBeRehired': ``,
'pages.offBoarding.closingComment.requestReplacement': `Yêu cầu thay thế`,
'pages.offBoarding.closingComment.hr1on1required': `Yêu cầu HR 1 kèm 1`,
'pages.offBoarding.closingComment.requestDifferentLWD': `Yêu cầu một LWD khác`,
'pages.offBoarding.closingComment.smallNotice.firstContent': `Vui lòng chọn tùy chọn này nếu bạn tin rằng nhân viên này có thể được thuê lại trong tương lai. Tùy chọn này sẽ vẫn là riêng tư đối với bạn và nhóm nhân sự.`,
'pages.offBoarding.closingComment.smallNotice.secondContent': `Vui lòng chọn tùy chọn này nếu bạn muốn mở một yêu cầu thay thế cho vị trí này.`,
'pages.offBoarding.closingComment.smallNotice.thirdContent': `Vui lòng chọn tùy chọn Có nếu bạn muốn HR  thảo luận về quyết định thôi việc với nhân viên này`,
'pages.offBoarding.closingComment.smallNotice.finalContent': `LWD thăng chức phải được người quản lý báo cáo của bạn xem xét và được người quản lý nhân sự phê duyệt để có hiệu l`,
'pages.offBoarding.closingComment.title': `Thêm Nhận xét kết thúc từ 1 trên 1 của bạn với nhân viên`,
'pages.offBoarding.closingComment.label.LWD': `Ngày làm việc cuối cùng (yêu cầu của quản lý`,
'pages.offBoarding.closingComment.label.notes': `Ghi chú`,
'pages.offBoarding.closingComment.label.notesPlaceHolder': `Lý do yêu cầu một LWD khác`,
'pages.offBoarding.closingComment.btn.reject': `Từ chối`,
'pages.offBoarding.closingComment.btn.accept': `Chấp nhận OT(overtime)`,
'pages.offBoarding.closingComment.btn.ok': `Đồng ý`,
'pages.offBoarding.closingComment.result.rejected': ``,
'pages.offBoarding.closingComment.result.accepted': `Yêu cầu OT(overtime) của nhân viên đã được chấp nhận`,
'pages.offBoarding.closingComment.notification.acceptContent': `Việc bạn chấp nhận yêu cầu đã được ghi lại và tất cả các bên liên quan sẽ được thông báo.`,
'pages.offBoarding.closingComment.notification.defaultContent': ``,
'pages.offBoarding.hrClosingComment.title': ``,
'pages.offBoarding.hrClosingComment.notice': `Bình luận của bạn cho yêu cầu 1 kèm 1 với {employeeName} đã được ghi lại. {employeeName} và quản lý nhân sự sẽ có thể xem bình luận này.`,
'pages.offBoarding.managerClosingComment.title': ``,
'pages.offBoarding.managerClosingComment.smallNotice.firstContent': ``,
'pages.offBoarding.managerClosingComment.smallNotice.firstContentIsRehired': `Ứng viên này có thể được nhận lại`,
'pages.offBoarding.managerClosingComment.smallNotice.secondContent': ``,
'pages.offBoarding.managerClosingComment.lastUpdated': ``,
'pages.offBoarding.hr1on1.title': ``,
'pages.offBoarding.hr1on1.defaultTitle': `Yêu cầu HR 1 kèm 1`,
'pages.offBoarding.hr1on1.contentTextNotStart': `Quản lý báo cáo đã yêu cầu HR nói chuyện với nhân viên về quyết định của họ.`,
'pages.offBoarding.requestDifferentLWD.title': ``,
'pages.offBoarding.requestDifferentLWD.reason': ``,
'pages.offBoarding.requestDifferentLWD.none': `Không`,
'pages.offBoarding.requestDifferentLWD.approvedBy': `LWD được phê duyệt bởi`,
'pages.offBoarding.requestDifferentLWD.rejectedBy': ``,
'pages.offBoarding.requestDifferentLWD.LWD.label': `Ngày làm việc cuối cùng`,
'pages.offBoarding.hrApproval.contentText': `Vui lòng chấp nhận hoặc từ chối đơn OT(overtime)`,
'pages.offBoarding.assignee.title': ``,
'pages.offBoarding.assignee.managerApproval': `Quản lý phê duyệt`,
'pages.offBoarding.assignee.note': ``,
'pages.offBoarding.assignee.btn.done': `Hoàn thành`,
'pages.offBoarding.assignee.btn.delegateRequest': ``,
'pages.offBoarding.assignee.type.primary': `Chính`,
'pages.offBoarding.assignee.type.secondary': `Thứ hai`,
'pages.offBoarding.assignee.input.placeholder': `Nhập để tìm kiếm`,
'pages.offBoarding.settings.emailNotifications.title': ``,
'pages.offBoarding.settings.emailNotifications.description': `Cho phép HR xác định tất cả những người sẽ được thêm vào email ban đầu được gửi, khi nhân viên nghỉ việc`,
'pages.offBoarding.settings.emailNotifications.notify.resignations': ``,
'pages.offBoarding.settings.emailNotifications.notify.tooltipText': `Địa chỉ email được thêm tại đây sẽ được thông báo đến những Đơn OT(overtime) mới.`,
'pages.offBoarding.settings.emailNotifications.notify.levelText.first': ``,
'pages.offBoarding.settings.emailNotifications.notify.levelText.last': ``,
}