export default {
'pages.offboardingManagement.title': ``,
'pages.offboardingManagement.status.approved': `Đã duyệt`,
'pages.offboardingManagement.status.inProgress': `Đang tiến hành`,
'pages.offboardingManagement.status.rejected': `Đã từ chối`,
'pages.offboardingManagement.status.draft': `Nháp`,
'pages.offboardingManagement.status.onHold': ``,
'pages.offboardingManagement.status.deleted': `Đã xoá`,
'pages.offboardingManagement.status.done': `Hoàn thành`,
'pages.offboardingManagement.status.completed': `Hoàn tất`,
'pages.offboardingManagement.userIdName': ``,
'pages.offboardingManagement.userA': `Người dùng A`,
'pages.offboardingManagement.userB': `Người dùng B`,
'pages.offboardingManagement.selectUser': ``,
'pages.offboardingManagement.getData': ``,
'pages.offboardingManagement.downloadCSV': ``,
'pages.offboardingManagement.no': `Số.`,
'pages.offboardingManagement.ticketID': `ID ticket`,
'pages.offboardingManagement.userID': `ID người dùng`,
'pages.offboardingManagement.fullName': `Tên đầy đủ`,
'pages.offboardingManagement.group': `Nhóm`,
'pages.offboardingManagement.submittedDate': ``,
'pages.offboardingManagement.status': `Trạng thái`,
'pages.offboardingManagement.lastWorkingDate': `Ngày làm việc cuối cùng`,
'pages.offboardingManagement.action': `Tách vụ`,
'pages.offboardingManagement.viewRequest': `Xem yêu cầu`,
}