export default {
'pages.OnboardingCustomField.customFields': `Trường tuỳ chỉnh`,
'pages.OnboardingCustomField.text': ``,
'pages.OnboardingCustomField.addNewSection': `Thêm vùng mới`,
'pages.OnboardingCustomField.addNewField': `Thêm trường mới`,
'pages.OnboardingCustomField.customSections&Fields': `Vùng & trường tuỳ chỉnh`,
'pages.OnboardingCustomField.sectionName': `Phần tên`,
'pages.OnboardingCustomField.fieldName': ``,
'pages.OnboardingCustomField.actions': `Tách vụ`,
'pages.OnboardingCustomField.createACustomFieldSection': ``,
'pages.OnboardingCustomField.CreateCustomFieldSection': ``,
'pages.OnboardingCustomField.fillingOutTheFields': ``,
'pages.OnboardingCustomField.text2': `Đây có phải là một lĩnh vực nhạy cảm? Chỉ quản trị viên không bị hạn chế xem các trường nhạy cảm mới có thể xem các trường tùy chỉnh nhạy cảm.`,
'pages.OnboardingCustomField.whoWillFillOutThisField': ``,
'pages.OnboardingCustomField.completedDuringOnboarding': ``,
'pages.OnboardingCustomField.shouldTheIndividual': ``,
'pages.OnboardingCustomField.shouldTheIndividualManager': ``,
'pages.OnboardingCustomField.Filters': `Lọc`,
'pages.OnboardingCustomField.text3': `Điều này áp dụng cho ai? Bạn có thể có các trường chỉ có thể áp dụng cho một số nhân viên nhất định. Bạn có thể tùy chỉnh trường để đảm bảo rằng bạn đang yêu cầu thông tin này khi cần.`,
'pages.OnboardingCustomField.Save&Return': `Lưu & quay lại`,
'pages.OnboardingCustomField.Cancel': `Huỷ`,
'pages.OnboardingCustomField.paragarph': ``,
'pages.OnboardingCustomField.FillingOutTheField': ``,
'pages.OnboardingCustomField.Prompt': ``,
'pages.OnboardingCustomField.note': ``,
'pages.OnboardingCustomField.HelpText': ``,
'pages.OnboardingCustomField.note2': ``,
'pages.OnboardingCustomField.Helpmedia': ``,
'pages.OnboardingCustomField.note3': `Trong tương lai, nếu bạn muốn thêm media file để hiển thị cho nhân viên, hãy tải lên bên dưới`,
}