export default {
'menu.documents': ``,
'pages.projectManagement.projects': `Dự án`,
'pages.projectManagement.tabSettings': `Cài đặt`,
'pages.projectManagement.export': `Xuất`,
'pages.projectManagement.allProjects': `Tất cả dự án`,
'pages.projectManagement.projectName': `Tên dự án`,
'pages.projectManagement.customer': `Khách hàng`,
'pages.projectManagement.projectType': `Loại dự án`,
'pages.projectManagement.projectManager': ``,
'pages.projectManagement.startDate': `Ngày bắt đầu`,
'pages.projectManagement.endDate': `Ngày kết thúc`,
'pages.projectManagement.division': `Bộ phận`,
'pages.projectManagement.status': `Trạng thái`,
'pages.projectManagement.editProject.title': `Chỉnh sửa trang thái`,
'pages.projectManagement.editProject.initialStatus': `Trang thái bạn đầu`,
'pages.projectManagement.editProject.newStatus': `Trạng thái mới`,
'pages.projectManagement.editProject.reason': ``,
'pages.projectManagement.resources': `Nguồn`,
'pages.projectManagement.resource': `Nguồn`,
'pages.projectManagement.action': `Tách vụ`,
'pages.projectManagement.addNewProject': `Thêm dự án mới`,
'pages.projectManagement.addNewProject.selectCustomer.placeholder': ``,
'pages.projectManagement.addNewProject.engagementType': `Loại cam kết`,
'pages.projectManagement.addNewProject.accountOwner': `Chủ tài khoản`,
'pages.projectManagement.addNewProject.projectId': `ID dự án`,
'pages.projectManagement.addNewProject.projectId.placeholder': `ID dự án (tự động tạo)`,
'pages.projectManagement.addNewProject.projectId.tooltip': ``,
'pages.projectManagement.addNewProject.projectStatus': `Trạng thái dự án`,
'pages.projectManagement.addNewProject.projectStatus.placeholder': `Chọn trạng thái dự án`,
'pages.projectManagement.addNewProject.projectName.placeholder': ``,
'pages.projectManagement.addNewProject.projectAlias': `Bí danh dự án (tuỳ chọn)`,
'pages.projectManagement.addNewProject.projectAlias.placeholder': ``,
'pages.projectManagement.addNewProject.tentativeEndDate': ``,
'pages.projectManagement.addNewProject.tentativeEndDate.placeholder': ``,
'pages.projectManagement.addNewProject.estimation': ``,
'pages.projectManagement.addNewProject.billableHeadCount': `Số nhân sự có thể thanh toán`,
'pages.projectManagement.addNewProject.billableHeadCount.placeholder': ``,
'pages.projectManagement.addNewProject.bufferHeadCount': `Số lượng nhân viên đệm`,
'pages.projectManagement.addNewProject.bufferHeadCount.placeholder': ``,
'pages.projectManagement.addNewProject.projectDescription': `Mô tả dự án`,
'pages.projectManagement.addNewProject.projectDescription.message': `Nhập mô tả dự án`,
'pages.projectManagement.addNewProject.engineeringOwner': ``,
'pages.projectManagement.addNewProject.engineeringOwner.message': ``,
'pages.projectManagement.addNewProject.tags': `Thẻ`,
'pages.projectManagement.addNewProject.tags.message': `Chọ thẻ`,
'pages.projectManagement.filterProject.projectId': `Theo ID dự án`,
'pages.projectManagement.filterProject.division': `Theo bộ phận`,
'pages.projectManagement.filterProject.resourceType': `Theo loại nguồn`,
'pages.projectManagement.filterProject.billingStatus': `Theo trang thái thanh toán`,
'pages.projectManagement.filterProject.projectName': `Theo tên dự án`,
'pages.projectManagement.filterProject.projectName.placeholder': `Chọn tên dự án`,
'pages.projectManagement.filterProject.customerId': `Theo khách hàng`,
'pages.projectManagement.filterProject.engagementType': `Theo loại tương tác`,
'pages.projectManagement.filterProject.projectManager': `Theo quản lý dự án`,
'pages.projectManagement.filterProject.projectStatus': `Theo trang thái`,
'pages.projectManagement.deleteProject.title': `Xoá dự án`,
'pages.projectManagement.deleteProject.buttonCancle': `Huỷ`,
'pages.projectManagement.deleteProject.buttonDelete': `Xoá`,
'pages.projectManagement.deleteProject.question': `Bạn có chắc không muốn xoá mục này <strong>{projectName}</strong>?`,
'pages.projectManagement.searchProject': `Tìm theo ID dự án, tên khách hàng`,
'pages.projectManagement.projectInformation.menu.summary': `Bản tóm tắt`,
'pages.projectManagement.projectInformation.menu.documents': `Tài liệu`,
'pages.projectManagement.projectInformation.menu.planning': ``,
'pages.projectManagement.projectInformation.menu.tracking': ``,
'pages.projectManagement.projectInformation.menu.reporting': ``,
'pages.projectManagement.projectInformation.menu.audit-trail': `Kiểm toán truy nguyên`,
'pages.projectManagement.projectInformation.summary.overview': `Tổng quan`,
'pages.projectManagement.projectInformation.summary.edit.startDate': ``,
'pages.projectManagement.projectInformation.summary.edit.tentativeEndDate': `Ngày kết thúc:`,
'pages.projectManagement.projectInformation.summary.edit.tentativeEndDate.placeholder': `Chọn ngày kết thúc`,
'pages.projectManagement.projectInformation.summary.edit.projectDescription': `Mô tả dự án:`,
'pages.projectManagement.projectInformation.summary.edit.billableHeadCount': `Số nhân sự có thể thanh toán`,
'pages.projectManagement.projectInformation.summary.edit.billableHeadCount.placeholder': ``,
'pages.projectManagement.projectInformation.summary.edit.bufferHeadCount': `Số lượng nhân viên đệm`,
'pages.projectManagement.projectInformation.summary.edit.bufferHeadCount.placeholder': ``,
'pages.projectManagement.projectInformation.summary.edit.estimation': ``,
'pages.projectManagement.projectInformation.cancleButton': `Huỷ`,
'pages.projectManagement.projectInformation.edit.updateButton': `Tải lên`,
'pages.projectManagement.projectInformation.summary.projectDescription': `Mô tả dự án:`,
'pages.projectManagement.projectInformation.summary.billableHeadCount': `Số nhân sự có thể thanh toán`,
'pages.projectManagement.projectInformation.summary.bufferHeadCount': `Số lượng nhân viên đệm`,
'pages.projectManagement.projectInformation.summary.estimation': ``,
'pages.projectManagement.projectInformation.summary.projectHistory.title': `Lịch sử dự án`,
'pages.projectManagement.projectInformation.summary.projectHistory.time': `Thời gian`,
'pages.projectManagement.projectInformation.description': `Mô tả`,
'pages.projectManagement.projectInformation.summary.projectHistory.comments': `Bình luận`,
'pages.projectManagement.projectInformation.summary.projectHistory.updatedByInfo': ``,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.title': ``,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.updateText': `Lưu thay đổi`,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.initialBillableHeadCount': ``,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.newBillableHeadCount': ``,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.newBillableHeadCount.message2': ``,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.newBillableHeadCount.placeholder': ``,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.reason': ``,
'pages.projectManagement.projectInformation.summary.editModal.billableHeadCount.changed': `Số nhân sự có thể thanh toán đã thay đổi`,
'pages.projectManagement.projectInformation.summary.editModal.bufferHeadCount.title': ``,
'pages.projectManagement.projectInformation.summary.editModal.bufferHeadCount.initialBufferHeadCount': ``,
'pages.projectManagement.projectInformation.summary.editModal.bufferHeadCount.newBufferHeadCount': ``,
'pages.projectManagement.projectInformation.summary.editModal.bufferHeadCount.newBufferHeadCount.message2': ``,
'pages.projectManagement.projectInformation.summary.editModal.bufferHeadCount.newBufferHeadCount.placeholder': ``,
'pages.projectManagement.projectInformation.summary.editModal.bufferHeadCount.reason': ``,
'pages.projectManagement.projectInformation.summary.editModal.bufferHeadCount.changed': `Số lượng nhân viên đệm đã thay đổi`,
'pages.projectManagement.projectInformation.summary.editModal.tentativeEndDate.title': ``,
'pages.projectManagement.projectInformation.summary.editModal.tentativeEndDate.initialEndDate': ``,
'pages.projectManagement.projectInformation.summary.editModal.tentativeEndDate.newEndDate': ``,
'pages.projectManagement.projectInformation.summary.editModal.tentativeEndDate.newEndDate.placeholder': `Nhập ngày kết thúc`,
'pages.projectManagement.projectInformation.summary.editModal.tentativeEndDate.reason': ``,
'pages.projectManagement.projectInformation.summary.editModal.tentativeEndDate.changed': ``,
'pages.projectManagement.projectInformation.documents.title': `Tài liệu`,
'pages.projectManagement.projectInformation.documents.addNewDocument': `Thêm tài liệu mới`,
'pages.projectManagement.projectInformation.documents.addDocument': `Thêm tài liệu`,
'pages.projectManagement.projectInformation.documents.searchDocument.placeholder': `Tìm theo loại tài liệu`,
'pages.projectManagement.projectInformation.documents.addDocument.documentType': `Loại tài liệu`,
'pages.projectManagement.projectInformation.documents.addDocument.documentType.message': ``,
'pages.projectManagement.projectInformation.documents.addDocument.documentName': `Tên tài liệu`,
'pages.projectManagement.projectInformation.documents.addDocument.documentName.message': ``,
'pages.projectManagement.projectInformation.documents.addDocument.comments': `Bình luận (tuỳ chọn)`,
'pages.projectManagement.projectInformation.documents.addDocument.file.message': `Vui lòng chọn tài liệu`,
'pages.projectManagement.projectInformation.documents.addDocument.file.drag': `Kéo và thả file tại đây`,
'pages.projectManagement.projectInformation.documents.addDocument.file.or': `hoặc`,
'pages.projectManagement.projectInformation.documents.addDocument.file.browse': `duyệt`,
'pages.projectManagement.projectInformation.documents.addDocument.file.upload': `để tải lên một file`,
'pages.projectManagement.projectInformation.documents.addDocument.file.type': `Kích thước file không nên nhiều hơn 25MB. Hỗ trợ file để xem: pdf & jpeg`,
'pages.projectManagement.projectInformation.documents.filterDocument.type': `Theo loại tài liệu`,
'pages.projectManagement.projectInformation.documents.filterDocument.uploadedBy': `Theo nhân viên`,
'pages.projectManagement.projectInformation.documents.filterDocument.uploadedDate': `Theo ngày tải lên`,
'pages.projectManagement.projectInformation.documents.table.documentName': `Tên tài liệu`,
'pages.projectManagement.projectInformation.documents.table.documentTypeName': `Loại tài liệu`,
'pages.projectManagement.projectInformation.documents.table.uploadedBy': `Tải lên bởi`,
'pages.projectManagement.projectInformation.documents.table.timeTaken': ``,
'pages.projectManagement.projectInformation.documents.detailDocument.queries': ``,
'pages.projectManagement.projectInformation.resource.emptyText1': ``,
'pages.projectManagement.projectInformation.resource.emptyText2': ``,
'pages.projectManagement.projectInformation.resource.addResource': `Thêm loại nguồn`,
'pages.projectManagement.projectInformation.resource.editResource': `Chỉnh sửa loại nguồn`,
'pages.projectManagement.projectInformation.resource.addResource.addButton': `Thêm`,
'pages.projectManagement.projectInformation.resource.addResource.projectName': `Tên dự án:`,
'pages.projectManagement.projectInformation.resource.addResource.engagementType': `Loại cam kết:`,
'pages.projectManagement.projectInformation.resource.addResource.tags': `ticket:`,
'pages.projectManagement.projectInformation.resource.addResource.resourceType.placeholder': ``,
'pages.projectManagement.projectInformation.resource.noOfResources': `Số nguồn`,
'pages.projectManagement.projectInformation.resource.addResource.noOfResources.placeholder': ``,
'pages.projectManagement.projectInformation.resource.addResource.billingStatus': `Trạng thái thanh toán`,
'pages.projectManagement.projectInformation.resource.addResource.billingStatus.placeholder': `Chọn trạng thái thanh toán`,
'pages.projectManagement.projectInformation.resource.addResource.estimatedEffort': ``,
'pages.projectManagement.projectInformation.resource.addResource.estimatedEffort.per': ``,
'pages.projectManagement.projectInformation.resource.addResource.estimatedEffort.technologies': ``,
'pages.projectManagement.projectInformation.resource.addResource.estimatedEffort.technologies.placeholder': ``,
'pages.projectManagement.projectInformation.resource.addResource.estimatedEffort.comments': `Bình luận/ ghi chú`,
'pages.projectManagement.projectInformation.resource.addResource.estimatedEffort.comments.placeholder': `Thêm bình luận/ghi chú`,
'pages.projectManagement.projectInformation.resource.resourceType': ``,
'pages.projectManagement.projectInformation.resource.resourceType.table.header.estimatedEffort': ``,
'pages.projectManagement.projectInformation.resource.resourceType.table.header.noOfResources': `Số nguồn`,
'pages.projectManagement.projectInformation.resource.resourceType.table.header.comments': `Bình luận/ ghi chú`,
'pages.projectManagement.projectInformation.resource.resourceType.view': `Xem`,
'pages.projectManagement.projectInformation.assign': `Phân công`,
'pages.projectManagement.projectInformation.resource.resourceType.edit': `Chỉnh sửa`,
'pages.projectManagement.projectInformation.resource.resourceType.delete': `Xoá`,
'pages.projectManagement.projectInformation.resource.resourceType.delete.message': `Bạn có chắc chắn muốn xóa loại nguồn này`,
'pages.projectManagement.projectInformation.resource.resourceType.view.name': `Tên`,
'pages.projectManagement.projectInformation.resource.resourceType.view.designation': `Chỉnh định`,
'pages.projectManagement.projectInformation.assignResource': `Nguồn được chỉ định`,
'pages.projectManagement.projectInformation.reviewResource': ``,
'pages.projectManagement.projectInformation.noteComments': `Ghi chú/ bình luận:`,
'pages.projectManagement.projectInformation.experience': `Kinh nghiệm`,
'pages.projectManagement.projectInformation.searchByName': `Tìm kiếm theo tên`,
'pages.projectManagement.projectInformation.next': `Kế tiếp`,
'pages.projectManagement.projectInformation.maybeLater': ``,
'pages.projectManagement.projectInformation.back': `Quay lại`,
'pages.projectManagement.projectInformation.needMore': ``,
'pages.projectManagement.projectInformation.raiseRequest': `Nêu lên yêu cầu`,
'pages.projectManagement.projectInformation.warning': ``,
'pages.projectManagement.projectInformation.yes': `Đồng ý`,
'pages.projectManagement.projectInformation.close': `Đóng`,
'pages.projectManagement.projectInformation.assigned': ``,
'pages.projectManagement.projectInformation.assignedSuccess': ``,
'pages.projectManagement.projectInformation.revisedEndDate': ``,
'pages.projectManagement.projectInformation.sureCancle': `Bạn có chắc muốn huỷ?`,
'pages.projectManagement.projectInformation.addResources': `Thêm nguồn`,
'pages.projectManagement.projectInformation.searchByNameResourceType': `Tìm kiếm theo tên/ loại nguồn`,
'pages.projectManagement.projectInformation.addedResources': ``,
'pages.projectManagement.projectInformation.addedSuccess': ``,
'pages.projectManagement.projectInformation.byDesignation': `Theo chỉ định`,
'pages.projectManagement.projectInformation.byStartDate': `Theo ngày bắt đầu`,
'pages.projectManagement.projectInformation.byEndDate': `Theo tên phòng ban`,
'pages.projectManagement.projectInformation.byRevised': `Theo ngày sử đổi`,
'pages.projectManagement.projectInformation.to': `đến`,
'pages.projectManagement.projectInformation.toBig': `Đến`,
'pages.projectManagement.projectInformation.byExperience': `Theo kinh nghiệm`,
'pages.projectManagement.projectInformation.byProject': `Theo dự án`,
'pages.projectManagement.projectInformation.planning.noMilestones': ``,
'pages.projectManagement.projectInformation.planning.noMilestones2': ``,
'pages.projectManagement.projectInformation.addMilestones': `Thêm mốc thời gian`,
'pages.projectManagement.projectInformation.addMilestone': `Thêm mốc thời gian`,
'pages.projectManagement.projectInformation.milestoneName': ``,
'pages.projectManagement.projectInformation.tentativeEndDate': ``,
'pages.projectManagement.projectInformation.planning.description': ``,
'pages.projectManagement.projectInformation.auditTrail.time': ``,
'pages.projectManagement.projectInformation.auditTrail.user': `Người dùng`,
'pages.projectManagement.projectInformation.auditTrail.changes': `Thay đổi`,
'pages.projectManagement.placeholder.pleaseSelect': `Vui lòng chọn`,
'pages.projectManagement.placeholder.milestoneName': ``,
'pages.projectManagement.selectStatus.placeholder': `Chọn trạng thái`,
'pages.projectManagement.enterComments.placeholder': ``,
'pages.projectManagement.selectEngagementType.placeholder': ``,
'pages.projectManagement.startDate.placeholder': `Chọn ngày bắt đầu`,
'pages.projectManagement.addNewProject.projectManager.placeholder': `Nhập để tìm kiếm`,
'pages.projectManagement.addNewProject.estimation.placeholder': ``,
'pages.projectManagement.yearOfExp.placeholder': `Số năm kinh nghiệm`,
'pages.projectManagement.selectProjectManager': ``,
'pages.projectManagement.selectGroups': `Chọn tài kiệu`,
'pages.projectManagement.division.placeholder': `Chọn bộ phận`,
'pages.projectManagement.rule.requiredField': `Phần bắt buộc!`,
'pages.projectManagement.rule.exp': `Exp không hợp lệ`,
'pages.projectManagement.rule.valueNumber': ``,
'pages.projectManagement.message.remove': `Bạn có chắc muốn xoá?`,
}