export default {
'pages.reports.hrReports': `Báo cáo HR`,
'pages.reports.resourceManagementReports': `Báo cáo quản lý tài nguyên`,
'pages.reports.hrReports.leaveReport': ``,
'pages.reports.hrReports.leaveReport.viewRequest': `Xem yêu cầu`,
'pages.reports.hrReports.leaveReport.leaveType': `Loại thời gian nghỉ`,
'pages.reports.hrReports.leaveReport.count': ``,
'pages.reports.hrReports.leftReport': ``,
'pages.reports.hrReports.joinedReport': `Báo cáo gia nhập`,
'pages.reports.hrReports.pendingLeaveReport': ``,
'pages.reports.hrReports.pendingLeaveReport.totalPTO': ``,
'pages.reports.hrReports.pendingLeaveReport.ptoTaken': ``,
'pages.reports.hrReports.pendingLeaveReport.ptoBalance': ``,
'pages.reports.hrReports.pendingLeaveReport.totalSLAccrued': ``,
'pages.reports.hrReports.pendingLeaveReport.slTaken': ``,
'pages.reports.hrReports.pendingLeaveReport.slBalance': ``,
'pages.reports.hrReports.biometricReport': `Báo cáo điểm danh vân tay`,
'pages.reports.hrReports.biometricReport.numberOfDay': ``,
'pages.reports.hrReports.biometricReport.totalNumberOfHours': ``,
'pages.reports.hrReports.payrollReport': ``,
'pages.reports.hrReports.payrollReport.doj': ``,
'pages.reports.hrReports.payrollReport.designation': `Chỉnh định`,
'pages.reports.hrReports.payrollReport.skillSet': ``,
'pages.reports.hrReports.payrollReport.dob': ``,
'pages.reports.hrReports.payrollReport.panNo': ``,
'pages.reports.hrReports.payrollReport.gender': ``,
'pages.reports.hrReports.payrollReport.fatherName': `Tên ba`,
'pages.reports.hrReports.payrollReport.maritalStatus': `Tình trạng hôn nhân`,
'pages.reports.hrReports.payrollReport.spouseName': `Tên vợ/ chồng`,
'pages.reports.hrReports.payrollReport.uanNo': ``,
'pages.reports.hrReports.payrollReport.adharr': ` Số ticket Adhaar`,
'pages.reports.hrReports.payrollReport.passportNo': ``,
'pages.reports.hrReports.payrollReport.emailId': ``,
'pages.reports.hrReports.payrollReport.banAccount': `Số tài khoản ngân hàng`,
'pages.reports.hrReports.payrollReport.totalCTC': ``,
'pages.reports.hrReports.payrollReport.payTm': ``,
'pages.reports.hrReports.payrollReport.kycStatus': `Trạng thái KYC`,
'pages.reports.hrReports.benefitsReport': `Báo cáo phúc lợi`,
'pages.reports.hrReports.benefitsReport.dayOfBirth': `Ngày tháng năm sinh`,
'pages.reports.hrReports.benefitsReport.spouseDOB': ``,
'pages.reports.hrReports.benefitsReport.child1Name': `Tên con 1`,
'pages.reports.hrReports.benefitsReport.child1Gender': `Giới tính bé 1`,
'pages.reports.hrReports.benefitsReport.child2Gender': `Giới tính bé 2`,
'pages.reports.hrReports.benefitsReport.child1DOB': ``,
'pages.reports.hrReports.benefitsReport.child2Name': `Tên con 2`,
'pages.reports.resourceManagement': `Báo cáo phân bổ băng thông(%)nkhoong thể lớn hơn 100%!`,
'pages.reports.projectTrackingReport': ``,
'pages.reports.skillsMatrixReport': ``,
'pages.reports.resourceAllocationEndDatesReport': ``,
'pages.reports.trackerReport': ``,
'pages.reports.resourceUtilizationReport': ``,
'pages.reports.projectUtilizationReport': ``,
'pages.reports.resourceAllocationEndDatesReport': `Báo cáo ngày kết thúc phân bổ nguồn lực`,
'pages.reports.searchPlaceholder': `Tìm kiếm theo tên khách hàng, tên dự án, bộ phận`,
'pages.reports.searchPlaceholder2': `Tìm theo ID dự án, tên khách hàng`,
'pages.reports.searchPlaceholder3': `Tìm theo tên nhân viên, ID nhân viêng, ID người dùng,..`,
'pages.reports.month': `Tháng`,
'pages.reports.total': `Tổng cộng`,
'pages.reports.bench': ``,
'pages.reports.billable': `Thanh toán`,
'pages.reports.buffer': `Lưu trữ dữ liệu`,
'pages.reports.unpaid': ``,
'pages.reports.efficiency': ``,
'pages.reports.allProjects': `Tất cả dự án`,
'pages.reports.allProjectsType': `Tất cả các loại dự án`,
'pages.reports.search': `Tìm kiếm...`,
'pages.reports.designation': `Chỉnh định`,
'pages.reports.currentManager': `Quản lý hiện tại`,
'pages.reports.experience': `Kinh nghiệm (năm)`,
'pages.reports.currentProject': `Dự án hiện tại`,
'pages.reports.billStatus': `Trạng thái thanh toán`,
'pages.reports.utilization': ``,
'pages.reports.revisedEndDate': ``,
'pages.reports.addComment': `Thêm bình luận`,
'pages.reports.employeesSkills': `Kỷ năng của nhân viên`,
'pages.reports.selectDate': `Chọn ngày`,
'pages.reports.engineeringOwner': ``,
'pages.reports.viewMoreDetails': `Xem thêm chi tiết`,
'pages.reports.engagementModel': ``,
}