export default {
'component.employeeOnboarding.onboardingOverview': `Tổng quan về gia nhập`,
'component.employeeOnboarding.settings': `Cài đặt`,
'component.employeeOnboarding.newJoinees': `Người mới`,
'component.employeeOnboarding.customFields': `Trường tuỳ chỉnh`,
'component.employeeOnboarding.generate': `Xuất`,
'component.employeeOnboarding.viewActivityLogs': `Xem nhật ký hoạt động`,
'component.onboardingOverview.viewActivityLogs': `Xem nhật ký hoạt động`,
'component.onboardingOverview.sentEligibilityForms': `Gửi biểu mẫu chính thức`,
'component.onboardingOverview.receivedSubmittedDocuments': `Nhận lại tài liệu đã nộp`,
'component.receivedSubmittedDocuments.rookieId': `ID người mới`,
'component.onboardingOverview.candidateId': `ID ứng viên`,
'component.onboardingOverview.candidateName': `Tên ứng viên`,
'component.onboardingOverview.position': `Chức vụ`,
'component.onboardingOverview.location': `Vị trí`,
'component.onboardingOverview.dateSent': `Ngày gửi`,
'component.onboardingOverview.dateReceived': `Ngày nhận`,
'component.onboardingOverview.dateJoin': `Ngày gia nhập`,
'component.onboardingOverview.documentVerified': `Số tài liệu được xác minh`,
'component.onboardingOverview.resubmit': `Nộp lại`,
'component.onboardingOverview.expire': `Hết hạn vào`,
'component.onboardingOverview.changeRequest': `Đổi yêu cầu`,
'component.onboardingOverview.requestDate': `Ngày yêu cầu`,
'component.onboardingOverview.comments': `Bình luận`,
'component.onboardingOverview.actions': `Tách vụ`,
'component.onboardingOverview.viewDraft': `Xem nháp`,
'component.onboardingOverview.new': `Mới`,
'component.onboardingOverview.review': `xem lại`,
'component.onboardingOverview.prepareProvisionalOffer': ``,
'component.onboardingOverview.draftFinalOffer': ``,
'component.onboardingOverview.viewForm': `xem biểu mẫu`,
'component.onboardingOverview.viewDraft2': `Xem nháp`,
'component.onboardingOverview.sendOffer': `Gửi thư đề nghị`,
'component.onboardingOverview.sendForApproval': `Gửi phê duyệt`,
'component.onboardingOverview.createProfile': `Gửi phê duyệt`,
'component.onboardingOverview.noData': `Không có dữ liệu nào`,
'component.onboardingOverview.pendingEligibilityChecks': ``,
'component.onboardingOverview.addTeamMember': `Thêm thành viên`,
'component.documentAndTemplates.title': `Tài liệu & mẫu`,
'component.documentAndTemplates.subTitle': `Bạn có thể quản lý tất cả tài liệu, mẫu và email tùy chỉnh của mình tại đây. Ứng dụng có thể tạo và gửi thư mời làm việc, sổ tay nhân viên, thỏa thuận tuyển dụng và email tùy chỉnh của công ty bạn cho nhân viên mới.`,
'component.documentAndTemplates.download': `Tải về`,
'component.documentAndTemplates.delete': `Xoá`,
'component.documentAndTemplates.defaultTemplate': `Mẫu hệ thống mặc định`,
'component.documentAndTemplates.recentDocuments': ``,
'component.nonExtempNotice.title': ``,
'component.nonExtempNotice.formTitle': ``,
'component.nonExtempNotice.isSelfInsured': `Bjan có bảo hiểm tự túc không?`,
'component.nonExtempNotice.carrierName': `Tên hãng bảo hiểm`,
'component.nonExtempNotice.carrierAddress': `Địa chỉ hãng bảo hiểm`,
'component.nonExtempNotice.phoneNumber': `Số điện thoại`,
'component.nonExtempNotice.policyNumber': `Số chính sách`,
'component.nonExtempNotice.save': `Lưu`,
'component.nonExtempNotice.yes': `Đồng ý`,
'component.nonExtempNotice.no': `Không`,
'component.backgroundChecks.title': `Kiểm tra lý lịch`,
'component.backgroundChecks.subTitle': ``,
'component.backgroundChecks.learnMore': `Tìm hiểu thêm`,
'component.backgroundChecks.generalSettings': `Cài đặt chung`,
'component.authorization.title': `ủy quyền`,
'component.authorization.link': `Thay đổi người ký`,
'component.backgroundCheck.title': `Kiểm tra lý lịch`,
'component.billingInformation.title': `Thông tin thanh toán để kiểm tra lý lịch`,
'component.optionalOnboardingQuestions.title': ``,
'component.optionalOnboardingQuestions.subTitle': ``,
'component.optionalOnboardingQuestions.addCustomFields': `#ERROR!`,
'component.optionalOnboardingQuestions.customFields': `Trường tuỳ chỉnh`,
'component.optionalOnboardingQuestions.newSection': `#ERROR!`,
'component.optionalOnboardingQuestions.newField': `#ERROR!`,
'component.optionalOnboardingQuestions.sectionName': `Phần tên`,
'component.optionalOnboardingQuestions.fieldName': ``,
'component.optionalOnboardingQuestions.saveOrdering': `Lưu đặt hàng`,
'component.optionalOnboardingQuestions.addQuestion': `Thêm nhiều câu hỏi`,
'component.emailReminderNote.title': `Ghi chú`,
'component.emailReminderNote.note1': `Tuỳ chỉnh tin nhắn triong email là cách tốt để nhận ra ngày và cột mốc quan trọng.`,
'component.emailReminderNote.note2': `Ví dụ: bạn có thể nhắc người quản lý về ngày bắt đầu của thành viên trong nhóm hoặc tạo lời nhắc cho các sự kiện, chẳng hạn như gia hạn giấy phép hoặc đăng ký trong 30 ngày.`,
'component.emailReminderNote.note3': `Bạn có thể sử dụng tính năng Văn bản tự động để tạo email được cá nhân hóa từ một mẫu.`,
'component.emailReminderHeader.title': `Tạo lời nhắc email tùy chỉnh`,
'component.emailReminderForm.title': `Tạo lời nhắc email tùy chỉnh`,
'component.emailReminderForm.triggerNote': ``,
'component.emailReminderForm.triggerNoteLink': `Trường tuỳ chỉnh`,
'component.emailReminderForm.addCondition': `#ERROR!`,
'component.emailReminderForm.cancel': `Huỷ`,
'component.emailReminderForm.submit': `Nộp`,
'component.customEmailsTableField.title': `Email tuỳ chỉnh`,
'component.customEmailsTableField.description': ``,
'component.customEmailsTableField.titleTable': `Email tuỳ chỉnh đã được tạo`,
'component.customEmailsTableField.pagination.showing': ``,
'component.customEmailsTableField.pagination.of': ``,
'component.customEmailsTableField.emailSubject': ``,
'component.customEmailsTableField.createdOn': ``,
'component.customEmailsTableField.triggerEvent': ``,
'component.customEmailsTableField.frequency': ``,
'component.customEmailsTableField.actions': `Tách vụ`,
'component.companySignatory.title': `Người ký kết công ty`,
'component.companySignatory.description': ``,
'component.editEmailNote.title': `Ghi chú`,
'component.editEmailNote.note1': `Tuỳ chỉnh tin nhắn triong email là cách tốt để nhận ra ngày và cột mốc quan trọng.`,
'component.editEmailNote.note2': `Ví dụ: bạn có thể nhắc người quản lý về ngày bắt đầu của thành viên trong nhóm hoặc tạo lời nhắc cho các sự kiện, chẳng hạn như gia hạn giấy phép hoặc đăng ký trong 30 ngày.`,
'component.editEmailNote.note3': `Bạn có thể sử dụng tính năng Văn bản tự động để tạo email được cá nhân hóa từ một mẫu.`,
'component.customEmailsTableField.editEmail': `Chỉnh sửa email`,
'component.editEmailHeader.defaultTitle': ``,
'component.editEmailHeader.title': `Chỉnh sửa lời nhắc trên email tùy chỉnh`,
'component.editEmailForm.addCondition': `#ERROR!`,
'component.editEmailForm.triggerNote': ``,
'component.editEmailForm.triggerNoteLink': `Trường tuỳ chỉnh`,
'component.editEmailForm.cancel': `Huỷ`,
'component.editEmailForm.submit': `Nộp`,
'component.editEmailForm.title': `Chỉnh sửa trên email tùy chỉnh`,
'pages.resourceManagement.overview': `Tổng quan`,
'pages.resourceManagement.resources': `Nguồn`,
'pages.resourceManagement.projects': `Dự án`,
'pages.resourceManagement.project': `Dự án`,
'pages.resourceManagement.people': `Người`,
'pages.resourceManagement.utilization': ``,
'pages.resourceManagement.latest': ``,
'pages.resourceManagement.trend': ``,
'pages.resourceManagement.export': `Xuất`,
'pages.resourceManagement.totalResources': ``,
'pages.resourceManagement.totalBillable': ``,
'pages.resourceManagement.totalBuffer': ``,
'pages.resourceManagement.totalBenched': ``,
'pages.resourceManagement.currentUtilization': `Mức sử dụng hiện tại`,
'pages.resourceManagement.currentUtilization.tooltip': `Mức sử dụng hiện tại được tính bằng tỷ lệ phần trăm của Tổng tài nguyên có thể thanh toán / Tổng tài nguyên  <br /><br />So với tuần trước, việc sử dụng Tài nguyên đã tăng thêm {increasePercent}%"`,
'pages.resourceManagement.jobTitle': `Chức danh công việc`,
'pages.resourceManagement.division': `Bộ phận`,
'pages.resourceManagement.noOfPeople': `Số người`,
'pages.resourceManagement.newJoinees': ``,
'pages.resourceManagement.byCandidateId': `Theo ID ứng viên`,
'pages.resourceManagement.byName': `Theo tên`,
'pages.resourceManagement.byJobTitle': `Theo chức danh công việc`,
'pages.resourceManagement.byJoiningDate': `Theo ngày gia nhập`,
'pages.resourceManagement.to': `đến`,
'pages.resourceManagement.filter': `Lọc`,
'pages.resourceManagement.byNameUserId': `Theo tên/ ID ngừoi dùng`,
'pages.resourceManagement.byDivision': `Theo bộ phận`,
'pages.resourceManagement.byDesignation': `Theo chỉ định`,
'pages.resourceManagement.bySkill': `Theo kỷ năng`,
'pages.resourceManagement.byCurrentProject': `Theo dự án hiện tại`,
'pages.resourceManagement.byBillingStatus': `Theo trang trang thái thanh toán`,
'pages.resourceManagement.byExperience': `Theo kinh nghiệm`,
'pages.resourceManagement.byStartDate': `Theo ngày bắt đầu`,
'pages.resourceManagement.byTentativeEndDate': `Theo ngày dự kiến kết thúc`,
'pages.resourceManagement.editPorjectDetail': `Chỉnh sửa chi tiết dự án`,
'pages.resourceManagement.skip': `Bỏ qua`,
'pages.resourceManagement.update': `Tải lên`,
'pages.resourceManagement.add': `Thêm`,
'pages.resourceManagement.delete': `Xoá`,
'pages.resourceManagement.viewProject': `Xem dự án`,
'pages.resourceManagement.viewComment': `Xem bình luận`,
'pages.resourceManagement.deleteComment': `Xoá bình luận`,
'pages.resourceManagement.close': `Đóng`,
'pages.resourceManagement.addComment': `Thêm bình luận`,
'pages.resourceManagement.editComment': `Chỉnh sửa bình luận`,
'pages.resourceManagement.resourceAssigned': ``,
'pages.resourceManagement.bandwidth': `Phân bổ băng thông (%)`,
'pages.resourceManagement.comments': `Bình luận (tuỳ chọn)`,
'pages.resourceManagement.projectDetails': ``,
'pages.resourceManagement.currentResource': `Phân bổ nguồn lực hiện tại:`,
'pages.resourceManagement.customer': `Khách hàng`,
'pages.resourceManagement.engagementType': `Loại cam kết`,
'pages.resourceManagement.status': `Trạng thái`,
'pages.resourceManagement.done': `Hoàn thành`,
'pages.resourceManagement.projectName': `Tên dự án`,
'pages.resourceManagement.current': `Hiện tại`,
'pages.resourceManagement.projectDescription': `Mô tả dự án`,
'pages.resourceManagement.readMore': `Xem thêm`,
'pages.resourceManagement.empId': ``,
'pages.resourceManagement.name': `Tên:`,
'pages.resourceManagement.designationDot': `Chỉnh định:`,
'pages.resourceManagement.experienceDot': `Kinh nghiệm:`,
'pages.resourceManagement.totalProjects': `Tổng dự án:`,
'pages.resourceManagement.manager': `Quản lý`,
'pages.resourceManagement.projectType': `Loại dự án`,
'pages.resourceManagement.projectManager': `Quản lý dự án`,
'pages.resourceManagement.resourcePlan': ``,
'pages.resourceManagement.resourceAssignedHeader': ``,
'pages.resourceManagement.billableResource': `Hóa đơn tài nguyên`,
'pages.resourceManagement.bufferResource': `Nguồn lưu trữ`,
'pages.resourceManagement.billEfficiency': `Hiệu quả thanh toán (%)`,
'pages.resourceManagement.billableEffort': `Nỗ lực có thể tính phí (ngày)`,
'pages.resourceManagement.spentEffort': ``,
'pages.resourceManagement.variance': ``,
'pages.resourceManagement.byProjectId': `Theo ID dự án`,
'pages.resourceManagement.byProjectName': `Theo tên dự án`,
'pages.resourceManagement.byCustomer': `Theo khách hàng`,
'pages.resourceManagement.byEngagementType': `Theo loại tương tác`,
'pages.resourceManagement.byProjectManager': `Theo quản lý dự án`,
'pages.resourceManagement.byStatus': `Theo trang thái`,
'pages.resourceManagement.customerId': `ID khách hàng:`,
'pages.resourceManagement.accountOwnerDot': `Chủ tài khoản`,
'pages.resourceManagement.contactPhone': `Số điện thoại liên hệ`,
'pages.resourceManagement.contactEmail': `Email liên hệ:`,
'pages.resourceManagement.address': `Địa chỉ:`,
'pages.resourceManagement.customerDetail': `Xem chi tiết khách hàng`,
'pages.resourceManagement.statusDot': `Trạng thái:`,
'pages.resourceManagement.projectTypeDot': `Loại dự án`,
'pages.resourceManagement.projectIdDot': `ID dự án:`,
'pages.resourceManagement.projectAlias': `Bí danh dự án:`,
'pages.resourceManagement.engineeringOwnerDot': ``,
'pages.resourceManagement.duration': `Khoảng thời gian:`,
'pages.resourceManagement.projectStatus': `Trạng thái dự án:`,
'pages.resourceManagement.projectDetail': `Xem chi tiết dự án`,
'pages.resourceManagement.accountOwner': `Chủ tài khoản`,
'pages.resourceManagement.engineeringOwner': ``,
'pages.resourceManagement.projectId': `ID dự án`,
'pages.resourceManagement.viewMoreDetail': `Xem thêm chi tiết`,
'pages.resourceManagement.ticketId': `ID ứng viên`,
'pages.resourceManagement.candidateFullName': `Tên`,
'pages.resourceManagement.joiningDate': `Ngày gia nhập`,
'pages.resourceManagement.designation': `Chỉnh định`,
'pages.resourceManagement.managerName': `Quản lý hiện tại`,
'pages.resourceManagement.experience': `Kinh nghiệm (năm)`,
'pages.resourceManagement.currentProjects': `Dự án hiện tại`,
'pages.resourceManagement.billStatus': `Trạng thái thanh toán`,
'pages.resourceManagement.utilizationTable': ``,
'pages.resourceManagement.startDate': `Ngày bắt đầu`,
'pages.resourceManagement.endDate': `Ngày kết thúc`,
'pages.resourceManagement.revisedDate': ``,
'pages.resourceManagement.comment': `Bình luận`,
'pages.resourceManagement.employeeSkills': `Kỷ năng của nhân viên`,
'pages.resourceManagement.action': `Tách vụ`,
'pages.resourceManagement.assignToProject': `Dự án được chỉ định`,
'pages.resourceManagement.changeManager': `Đổi quản lý`,
'pages.resourceManagement.resourceHistory': ``,
'pages.resourceManagement.effectiveDay': ``,
'pages.resourceManagement.nothing': ``,
'pages.resourceManagement.acceptNumber': `Chỉ chấp nhận số`,
'pages.resourceManagement.noData': `Không có dữ liệu trong khoản thời gian đã chọn`,
'pages.resourceManagement.selectTimeSmall': ``,
'pages.resourceManagement.changeManagerQuestion': ``,
'pages.resourceManagement.assignedSuccess': ``,
'pages.resourceManagement.assignProject': `Vui lòng chọn dự án!`,
'pages.resourceManagement.startDateEmpty': ``,
'pages.resourceManagement.endDateEmpty': ``,
'pages.resourceManagement.selectStatus': `Vui lòng chọn trạng thái!`,
'pages.resourceManagement.enterBandwidth': `Vui lòng nhập phân bổ băng thông (%)!`,
'pages.resourceManagement.valueNumber': ``,
'pages.resourceManagement.bandwidth100%': `Phân bổ băng thông `,
'pages.resourceManagement.lessThan0': ``,
'pages.resourceManagement.noData.message': `Không có dữ liệu nào`,
'pages.resourceManagement.enterBandwith': `Vui lòng nhập phân bổ băng thông (%)!`,
'pages.resourceManagement.selectManager': `Vui lòng chọn quản lý!`,
'pages.resourceManagement.duplicateManager': `Người quản lý trùng lặp với người quản lý hiện tại!`,
'pages.resourceManagement.selectEffectiveDay': `Vui lòng chọn ngày có hiệu lực!`,
'pages.resourceManagement.inputComment': `Vui lòng nhập bình luận của bạn`,
'pages.resourceManagement.chooseRange': `Vui lòng chọn phạm vị khác`,
'pages.resourceManagement.loadingExport': ``,
'pages.resourceManagement.multipleProject': ``,
'pages.resourceManagement.changeManager.description': `Bạn có chắc không muốn thay đổi quản lý`,
'pages.resourceManagement.sureDeleteComment': `Bạn có chắc không muốn xoá bình luận?`,
'pages.resourceManagement.searchDivision.placeholder': `Tìm kíếm bộ phận`,
'pages.resourceManagement.selectDivision.placeholder': ``,
'pages.resourceManagement.searchJobTitle.placeholder': `Tìm kíếm chức danh công việc`,
'pages.resourceManagement.searchCandidate.placeholder': `Tìm kiếm theo ID ứng viên, tên...`,
'pages.resourceManagement.selectCandidateId.placeholder': `Chọn ID ứng viên`,
'pages.resourceManagement.selectTheName.placeholder': ``,
'pages.resourceManagement.searchByName.placeholder': `Nhập để tìm kiếm theo tên/ ID người dùng`,
'pages.resourceManagement.selectDesignation.placeholder': ``,
'pages.resourceManagement.typeSearch.placeholder': `Nhập để tìm kiếm`,
'pages.resourceManagement.selectLocation.placeholder': ``,
'pages.resourceManagement.selectProject.placeholder': ``,
'pages.resourceManagement.selectBillingStatus.placeholder': `Theo trang trang thái thanh toán`,
'pages.resourceManagement.yearOfExp.placeholder': `Số năm kinh nghiệm`,
'pages.resourceManagement.fromDate.placeholder': `Từ ngày`,
'pages.resourceManagement.toDate.placeholder': `Đến ngày`,
'pages.resourceManagement.startDate.placeholder': ``,
'pages.resourceManagement.selectStatus.placeholder': `Chọn trạng thái`,
'pages.resourceManagement.enterEndDate.placeholder': `Nhập ngày kết thúc`,
'pages.resourceManagement.enterDate.placeholder': `Nhập ngày`,
'pages.resourceManagement.enterComments.placeholder': ``,
'pages.resourceManagement.selectEffectiveDay.placeholder': ``,
'pages.resourceManagement.searchCustomer.placeholder': `Tìm theo ID dự án, tên khách hàng`,
'pages.resourceManagement.select.placeholder': ``,
'pages.resourceManagement.selectProjectId.placeholder': ``,
'pages.resourceManagement.selectDivision2.placeholder': `Chọn bộ phận`,
'pages.resourceManagement.selectProjectName.placeholder': ``,
'pages.resourceManagement.selectCustomer.placeholder': ``,
'pages.resourceManagement.selectEngagementType.placeholder': ``,
'pages.resourceManagement.selectProjectManager.placeholder': ``,
'pages.resourceManagement.selectStatus2.placeholder': `Chọn trạng thái`,
}