export default {
'app.settings.menuMap.basic': `Cài đặt cơ bản`,
'app.settings.menuMap.security': ``,
'app.settings.menuMap.binding': `Ràng buộc tài khoản`,
'app.settings.menuMap.notification': ``,
'app.settings.basic.avatar': `Ảnh đại diện`,
'app.settings.basic.change-avatar': `Đổi ảnh đại diện`,
'app.settings.basic.email': `Email`,
'app.settings.basic.email-message': `Vui lòng nhập email của bạn!`,
'app.settings.basic.nickname': `Bí danh`,
'app.settings.basic.nickname-message': `Vui lòng nhập bí danh!`,
'app.settings.basic.profile': `Thông tin cá nhân`,
'app.settings.basic.profile-message': ``,
'app.settings.basic.profile-placeholder': `Giới thiệu ngắn gọn về bản thân`,
'app.settings.basic.country': `Quốc gia/ vùng`,
'app.settings.basic.country-message': `Vui lòng nhập quốc gia của bạn!`,
'app.settings.basic.geographic': ``,
'app.settings.basic.geographic-message': `Vui lòng nhập thông tin địa lý!`,
'app.settings.basic.address': `Địa chỉ đường`,
'app.settings.basic.address-message': `Vui lòng nhập địa chỉ của bạn`,
'app.settings.basic.phone': `Số điện thoại`,
'app.settings.basic.phone-message': `Vui lòng nhập số điện thoại!`,
'app.settings.basic.update': `Cập nhật thông tin`,
'app.settings.security.strong': `Mạnh`,
'app.settings.security.medium': `Trung bình`,
'app.settings.security.weak': `Yếu`,
'app.settings.security.password': `Mật khẩu tài khoản`,
'app.settings.security.password-description': `Độ mạnh mật khẩu hiện tại`,
'app.settings.security.phone': ``,
'app.settings.security.phone-description': `Điện thoại bị ràng buộc`,
'app.settings.security.question': ``,
'app.settings.security.question-description': ``,
'app.settings.security.email': `Email sao lưu`,
'app.settings.security.email-description': `Email bị ràng buộc`,
'app.settings.security.mfa': ``,
'app.settings.security.mfa-description': ``,
'app.settings.security.modify': `Chỉnh sửa`,
'app.settings.security.set': `Thiết lập`,
'app.settings.security.bind': `Liên kết`,
'app.settings.binding.taobao': `Liên kết Taobao`,
'app.settings.binding.taobao-description': `Hiện tại không có liên kết tài khoản Taobao`,
'app.settings.binding.alipay': `Liên kết Alipay`,
'app.settings.binding.alipay-description': `Hiện tại không có liên kết tài khoản Alipay`,
'app.settings.binding.dingding': `Liên kết DingTalk`,
'app.settings.binding.dingding-description': `Hiện tại không có liên kết tài khoản DingTalk`,
'app.settings.binding.bind': `Liên kết`,
'app.settings.notification.password': `Mật khẩu tài khoản`,
'app.settings.notification.password-description': ``,
'app.settings.notification.messages': ``,
'app.settings.notification.messages-description': ``,
'app.settings.notification.todo': ``,
'app.settings.notification.todo-description': ``,
'app.settings.open': `Mở`,
'app.settings.close': `Đóng`,
'app.settings': `Cài đặt`,
}