export default {
'app.setting.pagestyle': ``,
'app.setting.pagestyle.dark': ``,
'app.setting.pagestyle.light': ``,
'app.setting.content-width': ``,
'app.setting.content-width.fixed': ``,
'app.setting.content-width.fluid': ``,
'app.setting.themecolor': ``,
'app.setting.themecolor.dust': ``,
'app.setting.themecolor.volcano': ``,
'app.setting.themecolor.sunset': `Màu Cam`,
'app.setting.themecolor.cyan': ``,
'app.setting.themecolor.green': ``,
'app.setting.themecolor.daybreak': ``,
'app.setting.themecolor.geekblue': ``,
'app.setting.themecolor.purple': ``,
'app.setting.navigationmode': ``,
'app.setting.sidemenu': ``,
'app.setting.topmenu': ``,
'app.setting.fixedheader': ``,
'app.setting.fixedsidebar': ``,
'app.setting.fixedsidebar.hint': ``,
'app.setting.hideheader': ``,
'app.setting.hideheader.hint': ``,
'app.setting.othersettings': ``,
'app.setting.weakmode': `Chế độ yếu`,
'app.setting.copy': ``,
'app.setting.copyinfo': ``,
'app.setting.production.hint': `Bảng cài đặt chỉ hiển thị trong môi trường dev, vui lòng sửa đổi thủ công`,
}