export default {
'page.signUp.signUpHeader': ``,
'page.signUp.enterCompanyAddress': `Nhận địa chỉ mail công ty`,
'page.signUp.inputEmailMsg': `Vui lòng nhập email của bạn!`,
'page.signUp.inputEmailInvalid': ``,
'page.signUp.enterFullName': ``,
'page.signUp.inputFullNameMsg': `Vui lòng nhập tên đầy đủ!`,
'page.signUp.inputFullNameInvalid': ``,
'page.signUp.getStarted': ``,
'page.signUp.checkForCode': ``,
'page.signUp.weSentCode': ``,
'page.signUp.enterCode': ``,
'page.signUp.notReceiveCode': ``,
'page.signUp.sendAgain': `Gửi lại`,
'page.signUp.openGmail': ``,
'page.signUp.openOutlook': ``,
'page.signUp.step1.lbnError': `Vui lòng nhập tên doanh nghiệp hợp pháp của bạn`,
'page.signUp.step1.dbaError': `Vui lòng nhập DBA của bạn!`,
'page.signUp.step1.einError': `Vui lòng nhập EIN của bạn!`,
'page.signUp.step1.countryError': `Vui lòng nhập quốc gia của bạn!`,
'page.signUp.step1.stateError': `Vui lòng chọn quận!`,
'page.signUp.step1.zipCodeError': ``,
'page.signUp.step1.zipCodeError2': ``,
'page.signUp.step2.workLocations': `Vị trí làm việc`,
'page.signUp.step2.description': `Chúng tôi cần thu thập thông tin này để phân công nhân viên đến đúng văn phòng. Chúng tôi cũng sẽ cho phép bạn quản trị viên tại văn phòng, lọc nhân viên theo vị trí làm việc.`,
'page.signUp.step2.headquarter': `Địa chỉ trụ sở chính`,
'page.signUp.step2.address': `Địa chỉ`,
'page.signUp.step2.addressError': `Vui lòng nhập địa chỉ của bạn`,
'page.signUp.step2.country': `Quốc gia*`,
'page.signUp.step2.countryError': `Vui lòng nhập quốc gia của bạn!`,
'page.signUp.step2.state': `Quận*`,
'page.signUp.step2.stateError': `Vui lòng chọn quận!`,
'page.signUp.step2.zipCode': `Mã zip*`,
'page.signUp.step2.zipCodeError': ``,
'page.signUp.step2.zipCodeError2': ``,
'page.signUp.step2.add': `Thêm địa điểm làm việc`,
'page.signUp.step2.remove': ``,
'page.signUp.step2.back': `Quay lại`,
'page.signUp.step2.next': `Kế tiếp`,
'page.signUp.step3.phoneError': `Vui lòng nhập số điện thoại!`,
'page.signUp.step3.phoneError2': `Số điện thoại không hợp lệ!`,
}