export default {
'component.editForm.employmentDetails': `Chi tiết công việc`,
'component.editForm.yourInformation': ``,
'component.editForm.next': `Kế tiếp`,
'component.employmentDetails.yes': `Đồng ý`,
'component.employmentDetails.no': `Không`,
'component.yourInformation.fullName': `Tên đầy đủ`,
'component.yourInformation.designation': `Chỉnh định`,
'component.yourInformation.dragFile': ``,
'component.yourInformation.upload': `Tải lên`,
'component.modalContent.title1': ``,
'component.modalContent.title2': `Mẫu thư mời đã được gửi để phê duyệt`,
'component.modalContent.content': ``,
'component.modalContent.buttonApproval': `Gửi phê duyệt`,
'component.modalContent.buttonOK': `Đồng ý`,
'component.templateDetails.inputName': ``,
'component.templateDetailsNote.title': ``,
'component.templateDetailsNote.content1': `Bạn có thể tải về mẫu, chỉnh sửa và tải lên nội dung cũng khoản thời gian.`,
'component.templateDetailsNote.content2': ``,
}