export default {
'pages.ticketManagement.overView': `Tổng quan`,
'pages.ticketManagement.allTickets': `Tất cả ticket`,
'pages.ticketManagement.settings': `Cài đặt`,
'pages.ticketManagement.location': `Vị trí`,
'pages.ticketManagement.selectAll': ``,
'pages.ticketManagement.outOfSLA': ``,
'pages.ticketManagement.new': `Mới`,
'pages.ticketManagement.assigned': `Đã phân công`,
'pages.ticketManagement.inProgress': `Đang tiến hành`,
'pages.ticketManagement.clientPending': `Khách hàng đang chờ xử lý`,
'pages.ticketManagement.resolved': `Đã giải quyết`,
'pages.ticketManagement.closed': `Đã đóng`,
'pages.ticketManagement.searchRequesterByName': `Tìm kiếm theo người yêu cầu`,
'pages.ticketManagement.byName': `Theo tên`,
'pages.ticketManagement.byTeam': `Theo nhóm`,
'pages.ticketManagement.byRequestType': `Theo loại yêu cầu`,
'pages.ticketManagement.byPriority': `Theo mức mức độ ưu tiên`,
'pages.ticketManagement.byAssignedTo': `Bởi người được gửi đến`,
'pages.ticketManagement.byRequestDate': `Theo ngày yêu cầu`,
'pages.ticketManagement.ticketId': `ID ticket`,
'pages.ticketManagement.supportTeam': `Nhóm hỗ trợ`,
'pages.ticketManagement.requestType': `Loại yêu cầu`,
'pages.ticketManagement.subject': `Vấn đề`,
'pages.ticketManagement.priority': `Ưu tiên`,
'pages.ticketManagement.SLATime': ``,
'pages.ticketManagement.requestDate': `Ngày yêu cầu`,
'pages.ticketManagement.requesterName': `Tên người yêu cầu`,
'pages.ticketManagement.assignedTo': `Đã phân công cho`,
'pages.ticketManagement.actions': `Tách vụ`,
'pages.ticketManagement.dailyMail': ``,
'pages.ticketManagement.enabled': ``,
'pages.ticketManagement.disabled': ``,
'pages.ticketManagement.queryType': ``,
'pages.ticketManagement.status': `Trạng thái`,
'pages.ticketManagement.description': `Mô tả`,
'pages.ticketManagement.interestList': `Danh sách yêu thích`,
'pages.ticketManagement.emailAddress': `Địa chỉ email`,
'pages.ticketManagement.interestListTooltip': `Thêm bất kỳ người dùng nào bạn muốn sao chép vào ticket này`,
'pages.ticketManagement.addAttachMentDescription': ``,
'pages.ticketManagement.moveToAnotherTeam': ``,
'pages.ticketManagement.addNewTeam': `Thêm nhóm mới`,
'pages.ticketManagement.reAssign': ``,
'pages.ticketManagement.ccTo': `CC cho`,
'pages.ticketManagement.supportTeamSettingTab': `Nhóm hỗ trợ`,
'pages.ticketManagement.priorityLevelSettingTab': `Mức mức độ ưu tiên`,
'pages.ticketManagement.deleteWarning': `Bạn có chắc chắn muốn xóa nhóm hỗ trợ này không?`,
'pages.ticketManagement.onFinishPriorityLevelWarning': ``,
'pages.ticketManagement.deleteWarningPriorityLevel': `Bạn có chắc chắn muốn xóa mức mức độ ưu tiên này?`,
'pages.ticketManagement.configTeamSupportTitle': ``,
'pages.ticketManagement.configTeamSupportDescription': `Vui lòng tạo và xác định cấu hình các nhóm hỗ trợ cần thiết và các nhóm hỗ trợ tương ứng`,
'pages.ticketManagement.setupSupportTeam': ``,
'pages.ticketManagement.configSupportTeam': ``,
'pages.ticketManagement.configSupportTeamDesc': `Vui lòng xác định cấu hình tất cả các thuộc tính cho nhóm hỗ trợ bên dưới.`,
'pages.ticketManagement.basicInfoFormTitle': ``,
'pages.ticketManagement.enterNameSupportTeam': ``,
'pages.ticketManagement.addQueryTypes': `Thêm các loại tuy vấn`,
'pages.ticketManagement.queryTypeDropdown': ``,
'pages.ticketManagement.addEmailAddress': `Thêm địa chỉ email`,
'pages.ticketManagement.SLATitle': `Thiết lập thời gjan SLA cho mối mức mức độ ưu tiên`,
'pages.ticketManagement.configPriorityLevel': `Chọn và cấu hình mức mức độ ưu tiên`,
'pages.ticketManagement.addNewPriorityLevel': `Thêm mức mức độ ưu tiên`,
'pages.ticketManagement.addonAfterDay': `ngày(s)`,
'pages.ticketManagement.addonAfterHours': `Giờ`,
'pages.ticketManagement.editPriorityLevel': `Chỉnh sửa mức độ ưu tiên`,
'pages.ticketManagement.timeTaken': ``,
'pages.ticketManagement.ticketDetails': `Chi tiết ticket`,
'pages.ticketManagement.openBy': ``,
'pages.ticketManagement.attachments': `file đính kèm`,
'pages.ticketManagement.notes': `Ghi chú`,
'pages.ticketManagement.attachmentsRemoved': `file đính kèm đã xoá`,
'pages.ticketManagement.attachmentsAdded': `file đính kèm đã thêm`,
'pages.ticketManagement.notifyNewTicket': ``,
'pages.ticketManagement.notifyEveryNewTicket': `Tất cả người dùng trong danh sách sẽ được thông báo trên mỗi ticket mới.`,
'pages.ticketManagement.enableDailyEmail': ``,
'pages.ticketManagement.enableDailySendMail': ``,
'pages.ticketManagement.ticketQueue': ``,
'pages.ticketManagement.myTickets': `Ticket`,
'pages.ticketManagement.assignedTickets': `ticket được chỉ định`,
'pages.ticketManagement.highPriorityTickets': `Ticket mức độ ưu tiên cao`,
'pages.ticketManagement.ticketsOutOfSLA': ``,
'pages.ticketManagement.noSubmitTicket': ``,
'pages.ticketManagement.assignToSelf': `Phân công chính mình`,
'pages.ticketManagement.moveTo': ``,
'pages.ticketManagement.viewDetail': `Xem chi tiết`,
'pages.ticketManagement.remove': `Xoá`,
'pages.ticketManagement.send': `Gửi`,
'pages.ticketManagement.start': `Bắt đầu`,
'pages.ticketManagement.assignTo': `Phân công cho`,
'pages.ticketManagement.moveToTeam': ``,
'pages.ticketManagement.addAttachMent': `Thêm file đính kèm`,
'pages.ticketManagement.editTicket': `Chỉnh sửa ticket`,
'pages.ticketManagement.selectUser': ``,
'pages.ticketManagement.subjectPlaceHolder': ``,
'pages.ticketManagement.supportTeamPlaceholder': ``,
'pages.ticketManagement.queryTypePlaceholder': ``,
'pages.ticketManagement.descriptionPlaceHolder': ``,
'pages.ticketManagement.byNamePlaceHolder': `Tìm kiếm theo tên`,
'pages.ticketManagement.byTeamNamePlaceHolder': `Tìm kiếm theo tên nhóm`,
'pages.ticketManagement.byRequestTypePlaceHolder': ``,
'pages.ticketManagement.byPriorityPlaceHolder': `Chọn mức mức độ ưu tiên`,
'pages.ticketManagement.byAssignedToPlaceHolder': `Tìm kiếm theo chỉ định`,
'pages.ticketManagement.fromDatePlaceHolder': `Từ ngày`,
'pages.ticketManagement.toDatePlaceHolder': `Đến ngày`,
'pages.ticketManagement.interestListPlaceHolder': `Nhập để tìm kiếm`,
'pages.ticketManagement.ccToPlaceHolder': ``,
'pages.ticketManagement.nameSupportTeamPlaceHolder': ``,
'pages.ticketManagement.enterQueryTypePlaceHolder': ``,
'pages.ticketManagement.priorityPlaceHolder': `Chọn mức mức độ ưu tiên`,
'pages.ticketManagement.SLATimePlaceHolder': ``,
'pages.ticketManagement.namePriorityLevelPlaceHolder': ``,
'pages.ticketManagement.textAreaPlaceHolder': `Nhập lời nhắn ở đây...`,
'pages.ticketManagement.rulesSupportTeam': `Vui lòng chọn nhóm hỗ trợ!`,
'pages.ticketManagement.rulesQueryType': `Vui lòng chọn loại truy vấn`,
'pages.ticketManagement.rulesPriority': `Vui lòng chọn mức mức độ ưu tiên`,
'pages.ticketManagement.rulesSubject': `Vui lòng nhập chủ đề`,
'pages.ticketManagement.rulesDescription': `Vui lòng nhập mô tả`,
'pages.ticketManagement.rulesMoveToAnotherTeam': `Vui lòng chọn một nhóm!`,
'pages.ticketManagement.rulesLocation': `Vui lòng chọn khu vực!`,
'pages.ticketManagement.rulesNameSupportTeam': `Vui lòng nhập tên của nhóm hỗ trợ`,
'pages.ticketManagement.rulesEnterQueryType': `Vui lòng nhập loại truy vấn`,
'pages.ticketManagement.rulesEmailAddress': ``,
'pages.ticketManagement.rulesRequiredField': `Phần bắt buộc!`,
'pages.ticketManagement.rulesTimeTaken': ``,
'pages.ticketManagement.selectPriority': `Chọn mức mức độ ưu tiên`,
}