export default {
'pages.timeOff.timeoffRequest': ``,
'pages.timeOff.compoffRequest': ``,
'pages.timeOff.timeoff': `Giờ nghỉ`,
'pages.timeOff.setUp': `Thiết lập`,
'pages.timeOff.history': ``,
'pages.timeOff.setUpPolicy': ``,
'pages.timeOff.requestTimeoff': ``,
'pages.timeOff.requestCompoff': `Yêu cầu OT(overtime)`,
'pages.timeOff.requestBehalfOf': `Yêu cầu thay mặt`,
'pages.timeOff.inProgress': `Đang tiến hành`,
'pages.timeOff.approved': `Đã duyệt`,
'pages.timeOff.rejected': `Đã từ chối`,
'pages.timeOff.rejectedS': `Đã từ chối`,
'pages.timeOff.accepted': `Đã chấp nhận`,
'pages.timeOff.reject': `Từ chối`,
'pages.timeOff.drafts': `Nháp`,
'pages.timeOff.onHold': `Đang chờ`,
'pages.timeOff.withdrawn': `Rút lại`,
'pages.timeOff.withdrawnRequest': `Yêu cầu rút lại`,
'pages.timeOff.withdrawnRequestDetails': `Yêu cầu rút lại chị tiết`,
'pages.timeOff.unknown': ``,
'pages.timeOff.ticketId': `ID ticket`,
'pages.timeOff.days': `ngày`,
'pages.timeOff.daysB': `Ngày`,
'pages.timeOff.day': `Ngày`,
'pages.timeOff.leaveTime': ``,
'pages.timeOff.from': `Từ`,
'pages.timeOff.to': `Đến`,
'pages.timeOff.toS': `đến`,
'pages.timeOff.noOfDays': `Số ngày`,
'pages.timeOff.date': `Ngày`,
'pages.timeOff.cancel': `Huỷ`,
'pages.timeOff.countAndQty': ``,
'pages.timeOff.startTime': `Thời gian bắt đầu`,
'pages.timeOff.endTime': `Thời gian kết thúc`,
'pages.timeOff.noOfHours': `Số giờ`,
'pages.timeOff.subject': `Vấn đề`,
'pages.timeOff.duration': `Khoảng thời gian`,
'pages.timeOff.fromDate': `Từ ngày`,
'pages.timeOff.toDate': `Đến ngày`,
'pages.timeOff.description': `Mô tả`,
'pages.timeOff.attachments': `file đính kèm`,
'pages.timeOff.saveToDraft': `Lưu nháp`,
'pages.timeOff.submit': `Nộp`,
'pages.timeOff.ok': `Đồng ý`,
'pages.timeOff.start': `Bắt đầu`,
'pages.timeOff.end': `Kết thúc`,
'pages.timeOff.wholeDay': ``,
'pages.timeOff.morning': ``,
'pages.timeOff.afternoon': `Buổi trưa`,
'pages.timeOff.showAll': `Hiển thị tất cả`,
'pages.timeOff.holidays': `Ngày lễ`,
'pages.timeOff.holiday': `Ngày lễ`,
'pages.timeOff.applied': `Đã áp dụng`,
'pages.timeOff.edited': `Đã chỉnh sửa`,
'pages.timeOff.viewByList': ``,
'pages.timeOff.viewByCalendar': ``,
'pages.timeOff.requestForCompoff': `Yêu cầu OT(overtime)`,
'pages.timeOff.compoff': ``,
'pages.timeOff.managedBy': ``,
'pages.timeOff.extraTimeSpent': ``,
'pages.timeOff.timeSpent': `Thời gian sử dụng (giờ)`,
'pages.timeOff.totalExtraTime': `Tổng số năm kinh nghiệm`,
'pages.timeOff.hrs': `giờ`,
'pages.timeOff.hours': `Giờ`,
'pages.timeOff.hoursB': `Giờ`,
'pages.timeOff.note': `Ghi chú`,
'pages.timeOff.chainOfApproval': `Chuỗi phê duyệt`,
'pages.timeOff.timeoffRequests': `Yêu cầu nghỉ`,
'pages.timeOff.leaveRequests': `Yêu cầu nghỉ phép`,
'pages.timeOff.specialLeaveRequests': ``,
'pages.timeOff.LOPRequests': `Yêu cầu LOP`,
'pages.timeOff.wfhcpRequests': ``,
'pages.timeOff.compoffRequests': `Yêu cầu OT(overtime)`,
'pages.timeOff.project': `Dự án`,
'pages.timeOff.requestedOn': ``,
'pages.timeOff.assigned': `Đã phân công`,
'pages.timeOff.action': `Tách vụ`,
'pages.timeOff.updated': `Đã tải lên`,
'pages.timeOff.new': `Mới`,
'pages.timeOff.add': `Thêm`,
'pages.timeOff.type': ``,
'pages.timeOff.leaveDate': `thời gian nghỉ`,
'pages.timeOff.giveFeedback': `Gửi phản hổi`,
'pages.timeOff.yes': `Đồng ý`,
'pages.timeOff.no': `Không`,
'pages.timeOff.listView': `Xem danh sách`,
'pages.timeOff.calendarView': `Xem lịch`,
'pages.timeOff.timeoffCalendar': ``,
'pages.timeOff.upcoming': ``,
'pages.timeOff.leaveTaken': ``,
'pages.timeOff.viewLeaveBreakdown': ``,
'pages.timeOff.remaining': ``,
'pages.timeOff.totalLeaveBalance': ``,
'pages.timeOff.leaveBalancesDetail': `Số dư ngày phép chi tiết`,
'pages.timeOff.commonLeaves': ``,
'pages.timeOff.under': ``,
'pages.timeOff.specialLeaves': ``,
'pages.timeOff.requestee': `Người yêu cầu`,
'pages.timeOff.comment': ``,
'pages.timeOff.view': `Xem`,
'pages.timeOff.approve': `Duyệt`,
'pages.timeOff.viewRequest': `Xem yêu cầu`,
'pages.timeOff.leaveDates': `thời gian nghỉ`,
'pages.timeOff.noData': `Không có dữ liệu nào`,
'pages.timeOff.inProgressPM': `Đang tiến hành (PM phê duyệt)`,
'pages.timeOff.approvedPM': `Đã duyệt (PM đã duyệt)`,
'pages.timeOff.deleted': `Đã xoá`,
'pages.timeOff.delete': `Xoá`,
'pages.timeOff.viewReport': ``,
'pages.timeOff.requesteeDetails': `Người yêu cầu chi tiết`,
'pages.timeOff.EmployeeID': `ID nhân viên`,
'pages.timeOff.employeeName': `Tên nhân viên`,
'pages.timeOff.position': `Chức vụ`,
'pages.timeOff.currentProject': `Dự án hiện tại`,
'pages.timeOff.projectManager': ``,
'pages.timeOff.projectHealth': ``,
'pages.timeOff.viewReportS': ``,
'pages.timeOff.total': `Tổng cộng`,
'pages.timeOff.compoffRequestDetails': `Yêu cầu OT(overtime) chi tiết`,
'pages.timeOff.requestRejectionPM': ``,
'pages.timeOff.requestRejectionRH': ``,
'pages.timeOff.requestComments': ``,
'pages.timeOff.startDate': `Ngày bắt đầu`,
'pages.timeOff.endDate': `Ngày kết thúc`,
'pages.timeOff.noProject': ``,
'pages.timeOff.timeoffRequestDetails': `Yêu cầu nghỉ chi tiết`,
'pages.timeOff.reason': `Lý do`,
'pages.timeOff.reasonDot': ``,
'pages.timeOff.status': `Trạng thái`,
'pages.timeOff.withdraw': `Rút lại`,
'pages.timeOff.withdrawingApproved': `Rút lại một yêu cầu phê duyệt`,
'pages.timeOff.rejectWithdrawal': `Từ chối rút lại`,
'pages.timeOff.acceptWithdrawal': `Chấp nhận rút lại`,
'pages.timeOff.quickLinks': `Liên kết`,
'pages.timeOff.approvedWithdrawn': `Yêu cầu rút lại được phê duyệt`,
'pages.timeOff.waitingApproval': `Đang chờ phê duyệt`,
'pages.timeOff.waitingWithdrawn': `Đợi rút lại`,
'pages.timeOff.rejectedWithdrawn': `Từ chối yêu cầu rút lại`,
'pages.timeOff.noteWithdrawal': `Ghi chú - yêu cầu rút lại`,
'pages.timeOff.byTimeoffTypes': `Theo loại thời gian nghỉ`,
'pages.timeOff.byDuration': `Theo khoản thời gian`,
'pages.timeOff.timeoffHistory': `Lịch sử giờ nghỉ`,
'pages.timeOff.leaveType': `Loại thời gian nghỉ`,
'pages.timeOff.edit': `Chỉnh sửa`,
'pages.timeOff.withdrawalRequests': `Rút lại đơn/yêu cầu`,
'pages.timeOff.withdrawompoff': `Bạn có thể rút lại đơn OT(overtime) này...`,
'pages.timeOff.proceed': ``,
'pages.timeOff.viewMore': `Xem thêm`,
'pages.timeOff.discard': ``,
'pages.timeOff.balance': `Số dư`,
'pages.timeOff.afterWithdrawal': `Sau khi rút tiền`,
'pages.timeOff.timeoffRules': ``,
'pages.timeOff.employeeWorkSchedule': `Lịch làm việc của nhan viên`,
'pages.timeOff.holidayCalendar': `Lịch nghỉ lễ`,
'pages.timeOff.manageBalances': ``,
'pages.timeOff.assignPolicies': `Chính sách được chỉ định`,
'pages.timeOff.standardHoliday': ``,
'pages.timeOff.assignTo': `Phân công cho`,
'pages.timeOff.allEmployees': `Tất cả nhân viên`,
'pages.timeOff.excluding': ``,
'pages.timeOff.casualLeavePolicy': ``,
'pages.timeOff.sickLeavePolicy': ``,
'pages.timeOff.finish': ``,
'pages.timeOff.setupStandard': `Thiết  lập lịch nghỉ tiêu chuẩn của công ty`,
'pages.timeOff.loadingCountry': `Đang tải danh sách quốc gia...`,
'pages.timeOff.selectAll': ``,
'pages.timeOff.addAHoliday': `Thêm một kỳ nghỉ`,
'pages.timeOff.createHoliday': `Thêm một kỳ nghỉ`,
'pages.timeOff.switch': ``,
'pages.timeOff.importData': `Nhập data`,
'pages.timeOff.downloadSpreadsheet': ``,
'pages.timeOff.chooseFile': `Chọn file`,
'pages.timeOff.balancesEffectiveDate': `Số dư ngày có hiệu lực`,
'pages.timeOff.next': `Kế tiếp`,
'pages.timeOff.save': `Lưu`,
'pages.timeOff.leaveAccrual': ``,
'pages.timeOff.helpSetup': ``,
'pages.timeOff.getStarted': ``,
'pages.timeOff.configureTimeoff': ``,
'pages.timeOff.configureLeave': ``,
'pages.timeOff.configureAll': `Vui lòng xác định cấu hình tất cả các thuộc tính cho loại ngày phép bên dưới.`,
'pages.timeOff.carryForward': ``,
'pages.timeOff.setupTimeoff': ``,
'pages.timeOff.accrualMethod': `Phương pháp tính lũy kế`,
'pages.timeOff.unlimited': `Không giới hạn`,
'pages.timeOff.day/yearFrontload': ``,
'pages.timeOff.day/yearWorked': ``,
'pages.timeOff.day/yearFortnight': ``,
'pages.timeOff.accrualRate': `tỷ lệ dồn tích`,
'pages.timeOff.addAccrualRate': `Thêm tỷ lệ tích lũy`,
'pages.timeOff.perYear': ``,
'pages.timeOff.perQuarter': ``,
'pages.timeOff.perMonth': ``,
'pages.timeOff.perFortnight': ``,
'pages.timeOff.anniversaryDate': `Ngày kỷ niệm`,
'pages.timeOff.calendarDate': ``,
'pages.timeOff.addCarryForward': `Thêm chuyển tiếp mới`,
'pages.timeOff.carryForwardCap': ``,
'pages.timeOff.carryForwardAllowed': `Cho phép chuyển tiếp`,
'pages.timeOff.maximumCarryForward': ``,
'pages.timeOff.LOPSabbaticalLeave': ``,
'pages.timeOff.meansUnlimited': `có nghĩa không giới hạn`,
'pages.timeOff.maximumLeaveAmount': ``,
'pages.timeOff.negativeLeave': ``,
'pages.timeOff.maximumNegativeLeave': `Số dư ngày phép âm tối đa`,
'pages.timeOff.prorationRule': ``,
'pages.timeOff.addProrationRate': `Thêm một tỷ lệ mới`,
'pages.timeOff.endOfMonth': ``,
'pages.timeOff.startOfMonth': ``,
'pages.timeOff.percentageProrated': ``,
'pages.timeOff.leaveCategory': ``,
'pages.timeOff.totalAccrued': `Tổng ngày cộng dồn`,
'pages.timeOff.totalTaken': ``,
'pages.timeOff.totalRemaining': ``,
'pages.timeOff.historyTimeOff': ``,
'pages.timeOff.operation': ``,
'pages.timeOff.changedBy': `Thay đổi bởi`,
'pages.timeOff.numberOfDays': ``,
'pages.timeOff.currentBalance': `Số dư hiện tại`,
'pages.timeOff.holidayCelebrated': `Dưới đây là danh sách các ngày lễ được tổ chức tại khu vực/quốc gia của bạn. Chọn những ngày lễ mà công ty của bạn cung cấp. Bạn cũng có thể thêm ngày lễ vào danh sách.`,
'pages.timeOff.workHour': ``,
'pages.timeOff.employeeTakeOff': ``,
'pages.timeOff.totalHourWorkday': `Tổng giờ trong một ngày`,
'pages.timeOff.hours/day': `Giờ/ ngày`,
'pages.timeOff.workDayStart': ``,
'pages.timeOff.workDayEnd': ``,
'pages.timeOff.AM': `sáng`,
'pages.timeOff.PM': ``,
'pages.timeOff.onlyBalance': ``,
'pages.timeOff.Jan': ``,
'pages.timeOff.Feb': ``,
'pages.timeOff.Mar': ``,
'pages.timeOff.Apr': ``,
'pages.timeOff.May': ``,
'pages.timeOff.Jun': ``,
'pages.timeOff.Jul': ``,
'pages.timeOff.Aug': `Tháng 8`,
'pages.timeOff.Sep': ``,
'pages.timeOff.Oct': ``,
'pages.timeOff.Nov': ``,
'pages.timeOff.Dec': ``,
'pages.timeOff.timeoffRequest.description.withdraw': `Yêu cầu nghỉ [Ticket ID: {tickedId}] [Type: {typeName}] được rút lại`,
'pages.timeOff.timeoffRequest.description.drafts': `Yêu cầu nháp [Ticket ID: {tickedId}] [Type: {typeName}] đã được xoá`,
'pages.timeOff.timeoffRequest.description.approved': `Yêu cầu nghỉ [Ticket ID: {tickedId}] [Type: {typeName}] được gửi`,
'pages.timeOff.timeoffRequest.description.compoffRequest': `Yêu cầu OT(overtime) [Ticket ID: {tickedId}] đã đươc rút và xoá.`,
'pages.timeOff.applyForLeaves': `Áp dụng nghỉ phép có/không lương, làm việc tại nhà hoặc văn phòng khách hàng.`,
'pages.timeOff.requestcompensation': `Yêu cầu nghỉ bù nếu bạn đã làm thêm ngày/ giờ`,
'pages.timeOff.defaultNotifications': `Theo mặc định, thông báo sẽ được gửi cho HR, quản lý và lặp lại các bước với trưởng bộ phận của bạn`,
'pages.timeOff.notApplied': `Bạn chưa nộp đơn cho bất kỳ yêu cầu nghỉ phép nào.`,
'pages.timeOff.notAppliedSpecial': `Bạn chưa nộp đơn cho bất kỳ yêu cầu đặc biệt nào.`,
'pages.timeOff.notAppliedLOP': `Bạn chưa nộp đơn cho bất kỳ yêu cầu LOP nào.`,
'pages.timeOff.notAppliedWFH': `Bạn chưa nộp đơn cho bất kỳ yêu cầu làm liệc tại nhà hoặc tại văn phòng khách hàng nào.`,
'pages.timeOff.submittedCasual': `Các yêu cầu thông thường, bệnh tật & yêu cầu OT(overtime) sẽ được hiển thị tại đây.`,
'pages.timeOff.submittedRestricted': ``,
'pages.timeOff.submittedRequests': ``,
'pages.timeOff.noLeave': `Không nhận được yêu cầu nghỉ nào`,
'pages.timeOff.noLOP': `Không nhận được yêu cầu LOP nào`,
'pages.timeOff.noCompoff': `Không nhận được yêu cầu IT(overtime) nào`,
'pages.timeOff.noWFH': `Không nhận được yêu cầu làm việc tại nhà hoặc tại văn phòng khách hàng nào`,
'pages.timeOff.noSpecial': `Không nhận được yêu cầu nghỉ phép nào đặc biệt`,
'pages.timeOff.submitCSC': `Các yêu cầu thông thường, bệnh tật & yêu cầu OT(overtime) sẽ được hiển thị tại đây.`,
'pages.timeOff.submitRestricted': ``,
'pages.timeOff.withdrawApplication': `Bạn có thể rút lại đơn xin nghỉ một ngày trước ngày nọpo đơn. Tác vụ rút lại sẽ không khả dụng sau đó.`,
'pages.timeOff.withdrawCompoff': `Rút lại yêu cầu OT(overtime)?`,
'pages.timeOff.withdrawTimeoff': `Rút lại yêu cầu nghỉ?`,
'pages.timeOff.withdrawingDelete': `Yêu cầu rút sẽ xóa id vé này và sẽ không còn được theo dõi nữa.`,
'pages.timeOff.bothNotified': `Cả quản lý và HR sẽ được thông báo về thay đổi này.`,
'pages.timeOff.discardDraft': `Huỷ yêu cầu nháp?`,
'pages.timeOff.discardingDraft': ``,
'pages.timeOff.standardWorkhours': ``,
'pages.timeOff.belowHolidays': `Dưới đây là danh sách các ngày lễ được tổ chức tại khu vực/quốc gia của bạn. Chọn những ngày lễ mà công ty của bạn cung cấp. Bạn cũng có thể thêm ngày lễ vào danh sách.`,
'pages.timeOff.keepCurrent': `Giữ số dư thời gian nghỉ hiện tại của nhân viên, nhưng chuyển chúng sang các chính sách khác`,
'pages.timeOff.importTimeoff': ``,
'pages.timeOff.findGeneric': ``,
'pages.timeOff.rateAt': ``,
'pages.timeOff.conceptWhere': `một khái niệm trong đó những thời gian nghỉ không sử dụng của nhân viên từ năm hiện tại có thể được chuyển sang năm tiếp theo. Chuyển tiếp thường được thực hiện vào cuối năm.`,
'pages.timeOff.miniumNumber': ``,
'pages.timeOff.applyTimeoff': `Đăng ký thời gian nghỉ tại văn phòng`,
'pages.timeOff.applyForTimeoff': `Đăng ký thời gian nghỉ`,
'pages.timeOff.applyCompoff': `Áp dụng cho OT(overtime)`,
'pages.timeOff.notAllowedEdit': `Bạn không được phép chỉnh sửa yêu cầu ngày phép này!`,
'pages.timeOff.requiredApprovals': `Đơn xin nghỉ đã được phê duyệt.`,
'pages.timeOff.takesAnyWhere': ``,
'pages.timeOff.validLeaveTime': `Vui lòng chọn thời gian nghỉ phép hợp lệ!`,
'pages.timeOff.requestSavedDraft': `Yêu cầu đã lưu dưới bản nháp`,
'pages.timeOff.requestSubmitted': `yêu cầu được gửi bởi HR và quản lý của bạn`,
'pages.timeOff.editTicket': `Chỉnh sửa ID ticket: {ticklet} được gửi tới HR và quản lý`,
'pages.timeOff.needSelectDuration': ``,
'pages.timeOff.uploadDocument': ``,
'pages.timeOff.typeToSearch': `Nhập để tìm kiếm`,
'pages.timeOff.pleaseSelect': `Vui lòng chọn!`,
'pages.timeOff.miniumTimeOff': ``,
'pages.timeOff.maximumTimeOff': ``,
'pages.timeOff.notAllowedEditComoff': `Bạn không được phép chỉnh sửa yêu cầu OT(overtime) này!`,
'pages.timeOff.optionalAttach': ``,
'pages.timeOff.compOffDraft': `Yêu cầu OT(overtime) được lưu dưới bản nháp`,
'pages.timeOff.compOffRequest': `Yêu cầu OT(overtime) được gửi đến HR và quản lý của bạn`,
'pages.timeOff.editTicketId': `Chỉnh sửa ID ticket: {ticklet} được gửi tới HR và quản lý`,
'pages.timeOff.selectDuration': ``,
'pages.timeOff.allowdInput': `Cho phép nhập: 1-9 giờ/ngày`,
'pages.timeOff.compoffRequires': `Yêu cầu OT(overtime) đã được duyệt.`,
'pages.timeOff.onceCompoff': `Khi yêu cầu OT(overtime) đã được duyệt. Số dư thời gian nghỉ sẽ được hiển thị cùng với số dư còn lại của bạn. Sau đó, bạn có thể nộp đơn xin nghỉ bù.`,
'pages.timeOff.thankFeedback': `Cảm ơn đóng góp giá trị của bạn!`,
'pages.timeOff.helpUs': ``,
'pages.timeOff.takeSometime': `Chúng tôi cần biết các vấn đề bạn đang đối mặc`,
'pages.timeOff.satisfiedApp': `Bạn có hài lòng với app xin nghỉ của chúng tôi?`,
'pages.timeOff.recursivelyLoop': `Theo mặc định, thông báo sẽ được gửi cho HR, quản lý và lặp lại các bước với trưởng bộ phận của bạn`,
'pages.timeOff.compoffRejected': `Bạn đã từ chối yêu cầu OT(overtime) này. Các bước tiếp theo sẽ được thông báo cho bạn sau.`,
'pages.timeOff.compoffApproved': `Bạn đã chấp nhận yêu cầu OT(overtime) này. Các bước tiếp theo sẽ được thông báo cho bạn sau.`,
'pages.timeOff.timeOffRejected': `Bạn đã từ chối yêu cầu nghỉ này. Các bước tiếp theo sẽ được thông báo cho bạn sau.`,
'pages.timeOff.timeOffApproved': `Bạn đã chấp nhận yêu cầu nghỉ này. Các bước tiếp theo sẽ được thông báo cho bạn sau.`,
'pages.timeOff.withdrawingTimeOffApproved': `Rút lại yêu cầu nghỉ đã được duyệt. Các bước tiếp theo sẽ được thông báo cho bạn sau.`,
'pages.timeOff.withdrawingTimeOffRejected': ``,
'pages.timeOff.needLeaveBalances': `Tất cả những gì bạn cần biết về số thời gian nghỉ phép còn thừa.`,
'pages.timeOff.balanceShown': ``,
'pages.timeOff.sureWithdraw': `Bạn có chắn muốn rút lại yêu cầu nghỉ của bạn?`,
'pages.timeOff.thisWithdraw': `Rút lại yêu cầu nghỉ này?`,
'pages.timeOff.needApproveWithdraw': `Để rút lại yêu cầu nghỉ phép sẽ cần sự phê duyệt từ HR và quản lý của bạn.`,
'pages.timeOff.manageExisting': ``,
'pages.timeOff.uploadExcelFile': `Bạn chỉ có thể tải lên file Excel`,
'pages.timeOff.image2MB': `Hình ảnh phải nhỏ hơn 2MB`,
'pages.timeOff.dropFile': `Hoặc ticket file tại đây`,
'pages.timeOff.perAssigned': `Theo bất kỳ chính sách mới được chỉ định, việc tích lũy chúng sẽ bắt đầu vào`,
'pages.timeOff.tellTimeoff': `Cho chúng tôi biết loại thời gian nghỉ (nghỉ có lượng, nghỉ không lương và nghỉ lễ) công ty cung cấp. Chúng thôi sẽ thiết lập chính xác cho bạn. `,
'pages.timeOff.setupWorkSchedule': ``,
'pages.timeOff.completeRequiredFields': `Vui lòng hoàn thành trường yên cầu!`,
'pages.timeOff.requiredField': `Phần bắt buộc!`,
'pages.timeOff.invalidFormat': `Định dạng không hợp lệ`,
'pages.timeOff.yearLess': ``,
'pages.timeOff.yearService': ``,
'pages.timeOff.sureMove': `Bạn có chắc muốn xoá?`,
'pages.timeOff.wantReset': ``,
'pages.timeOff.selectDate': `Chọn ngày`,
'pages.timeOff.selectAllEmployeeType': ``,
'pages.timeOff.selectAllEmploymentType': ``,
'pages.timeOff.miniumCalendarDay': `Số ngày tối thiểu trước khi một nhân viên mới gia nhập có thể nộp đơn xin nghỉ phép.`,
'pages.timeOff.enterNameLeaveType': ``,
'pages.timeOff.accruesLOP': ``,
'pages.timeOff.maximumLeave': `Tối đa số dư ngày phép tối đa được cho phép (Dừng tích lũy nghỉ phép nếu nhân viên đạt đến giá trị này).`,
'pages.timeOff.maximumNumber': `Số lượng ngày tối đa được phéo nghỉ trong một yêu cầu`,
'pages.timeOff.minimumAmountApplied': `Số thời gian nghỉ phép tối thiểu cần được áp dụng.`,
'pages.timeOff.negativeLeaveAllowed': `Cho phép số dư ngày phép âm?`,
'pages.timeOff.shouldHire': ``,
'pages.timeOff.selectTimeOffProceed': `Vui lòng chọn loại thời gian nghỉ để tiếp tục!`,
'pages.timeOff.selectEmployee': ``,
'pages.timeOff.pleaseSelectEmployee': `Vui lòng chọn nhân viên!`,
'pages.timeOff.typeSearchEmployee': `Nhập để tìm kiếm nhân viên mà bạn muốn yêu cầu`,
'pages.timeOff.selectTimeOffType': ``,
'pages.timeOff.pleaseSelectTimeOffType': `Vui lòng chọn loại thời gian nghỉ!`,
'pages.timeOff.timeoffType': ``,
'pages.timeOff.pleaseInputSubject': `Vui lòng nhập vấn đề!`,
'pages.timeOff.enterSubject': ``,
'pages.timeOff.selectDayTakeOff': ``,
'pages.timeOff.pleaseSelectDate': `Vui lòng chọn một ngày!`,
'pages.timeOff.inputDescription': `Vui lòng nhập mô tả!`,
'pages.timeOff.reasonTakingTimeoff': ``,
'pages.timeOff.ccOnly': `CC (nếu bạn chỉ muốn thông báo cho người khác ngoài HR & quản lý của bạn)`,
'pages.timeOff.searchPerson': ``,
'pages.timeOff.typeSearchPerson': ``,
'pages.timeOff.enterProject': ``,
'pages.timeOff.pleaseEnterProjectName': `Vui lòng nhập tên dự án`,
'pages.timeOff.reasonRejecting': `Lý do tôi muốn huỷ yêu cầu này là...`,
'pages.timeOff.searchTimeoffTypes': `Tìm kiếm loại thời gian nghỉ`,
'pages.timeOff.searchEmployessID': `Tìm kiếm theo ID nhân viên, tên...`,
'pages.timeOff.none': `Không`,
'pages.timeOff.selectCountry': `Chọn quốc gia`,
'pages.timeOff.inputHoliday': ``,
'pages.timeOff.inputNameHoliday': ``,
'pages.timeOff.selectType': ``,
'pages.timeOff.inputDateHoliday': ``,
'pages.timeOff.chooseTypeHoliday': `Vui lòng chọn loại ngày lễ!`,
'pages.timeOff.enterTypeName': ``,
'pages.timeOff.youSureMove': `Bạn có chắc muốn xoá?`,
'pages.timeOff.leaveAccrues': ``,
'pages.timeOff.selectOperation': ``,
'pages.timeOff.selectLeaveType': ``,
'pages.timeOff.dateRange': `Khoản thời gian`,
'pages.timeOff.disableFeature': ``,
'pages.timeOff.annualResetPolicy': ``,
'pages.timeOff.schedulePolicy': `Chính sách lịch làm việc tiêu chuẩn`,
'pages.timeOff.accrualPolicy': ``,
'pages.timeOff.accrualStart': ``,
'pages.timeOff.carryForwardPolicy': ``,
'pages.timeOff.emailNotifications': ``,
'pages.timeOff.employmentType': `Loại công việc`,
'pages.timeOff.leaveApplicationStart': ``,
'pages.timeOff.leaveTypeName': ``,
'pages.timeOff.maximumBalanceAllowed': ``,
'pages.timeOff.minimumLeaveAmount': ``,
'pages.timeOff.hireProrationPolicy': ``,
'pages.timeOff.noticeAccrualPolicy': ``,
'pages.timeOff.hrNotify': `Thông báo cho HR khi một nhân viên nghỉ phép kiểu này`,
}