export default {
'pages.timeSheet.myTimesheet': `Bảng chấm công`,
'pages.timeSheet.hrReports': `Báo cáo HR`,
'pages.timeSheet.myTeam': `Team`,
'pages.timeSheet.financeReports': ``,
'pages.timeSheet.myProjects': `Dự án của tôi`,
'pages.timeSheet.weeklyReports': `Báo cáo tuần của tôi`,
'pages.timeSheet.settings': `Cài đặt`,
'pages.timeSheet.continue': `Tiếp tục`,
'pages.timeSheet.day': `ngày`,
'pages.timeSheet.activity': `Hoạt động`,
'pages.timeSheet.timeIn': ``,
'pages.timeSheet.timeOut': ``,
'pages.timeSheet.timeOff': `thời gian nghỉ`,
'pages.timeSheet.nightShift': ``,
'pages.timeSheet.totalHrs': `Tổng giờ`,
'pages.timeSheet.notes': `Ghi chú`,
'pages.timeSheet.action': `Tách vụ`,
'pages.timeSheet.division': `Bộ phận`,
'pages.timeSheet.designation': `Chỉnh định`,
'pages.timeSheet.department': `Bộ phận`,
'pages.timeSheet.requestLeave': `Yêu cầu nghỉ phép`,
'pages.timeSheet.addTask': `Thêm việc`,
'pages.timeSheet.import': `Nhập`,
'pages.timeSheet.incompleteTimesheets': ``,
'pages.timeSheet.dayOfHours': ``,
'pages.timeSheet.project': `Dự án`,
'pages.timeSheet.task': `Công việc`,
'pages.timeSheet.description': `Mô tả`,
'pages.timeSheet.time': ``,
'pages.timeSheet.totalHours': `Tổng giờ`,
'pages.timeSheet.is': ``,
'pages.timeSheet.allProjects': `Tất cả dự án`,
'pages.timeSheet.total': `Tổng cộng`,
'pages.timeSheet.noTasks': `Không có công việc nào`,
'pages.timeSheet.startTime': `Thời gian bắt đầu`,
'pages.timeSheet.endTime': `Thời gian kết thúc`,
'pages.timeSheet.breakTime': `Thời gian nghỉ giải lao (phút)`,
'pages.timeSheet.overTime': ``,
'pages.timeSheet.clientLocation': ``,
'pages.timeSheet.delete': `Xoá`,
'pages.timeSheet.submit': `Nộp`,
'pages.timeSheet.cancel': `Huỷ`,
'pages.timeSheet.update': `Tải lên`,
'pages.timeSheet.next': `Kế tiếp`,
'pages.timeSheet.reSubmit': ``,
'pages.timeSheet.previous': `Trước`,
'pages.timeSheet.export': `Xuất`,
'pages.timeSheet.download': `Tải về`,
'pages.timeSheet.totalHourDot': `Tổng giờ:`,
'pages.timeSheet.timeDuration': `Khoảng thời gian`,
'pages.timeSheet.timeOffDetail': ``,
'pages.timeSheet.timeoff': `Giờ nghỉ`,
'pages.timeSheet.noTimeOff': ``,
'pages.timeSheet.selectTimesheetPeriod': ``,
'pages.timeSheet.selectTheTimesheetPeriod': ``,
'pages.timeSheet.pleaseSelectTimesheetPeriod': `Vui lòng chọn khoảng thời gian của bảng chấm công`,
'pages.timeSheet.areHoliday': `là ngày lễ`,
'pages.timeSheet.workOn': ``,
'pages.timeSheet.viewDailyMode': ``,
'pages.timeSheet.viewMoreTask': `Xem +{task} công việc`,
'pages.timeSheet.taskDetails': `Chi tiết công việc`,
'pages.timeSheet.addAnotherTask': `Thêm việc khác`,
'pages.timeSheet.editTask': `Chỉnh sửa việc`,
'pages.timeSheet.totalHour': `Tổng giờ`,
'pages.timeSheet.daily': ``,
'pages.timeSheet.weekly': ``,
'pages.timeSheet.monthly': `Hằng tháng`,
'pages.timeSheet.importTasks': ``,
'pages.timeSheet.tasksSelected': ``,
'pages.timeSheet.yes': `Đồng ý`,
'pages.timeSheet.no': `Không`,
'pages.timeSheet.nightShift1': ``,
'pages.timeSheet.addActivity': `Thêm hoạt động`,
'pages.timeSheet.startDate': `Ngày bắt đầu`,
'pages.timeSheet.endDate': `Ngày kết thúc`,
'pages.timeSheet.employeeName': `Tên nhân viên`,
'pages.timeSheet.totalWorkedTime': `Số giờ làm việc`,
'pages.timeSheet.totalOTTime': `Số giờ làm thêm`,
'pages.timeSheet.pto': ``,
'pages.timeSheet.showing': ``,
'pages.timeSheet.of': ``,
'pages.timeSheet.duplicateTask': ``,
'pages.timeSheet.duplicate': ``,
'pages.timeSheet.employeeID': `ID nhân viên`,
'pages.timeSheet.location': `Vị trí`,
'pages.timeSheet.date': `Ngày`,
'pages.timeSheet.inTime': ``,
'pages.timeSheet.outTime': ``,
'pages.timeSheet.leaves': `Nghỉ`,
'pages.timeSheet.projectDetails': ``,
'pages.timeSheet.employee': `Nhân viên`,
'pages.timeSheet.projectName': `Tên dự án`,
'pages.timeSheet.taskName': ``,
'pages.timeSheet.date&Time': `Ngày & thời gian`,
'pages.timeSheet.days': `ngày`,
'pages.timeSheet.hour': `Giờ`,
'pages.timeSheet.customer': `Khách hàng`,
'pages.timeSheet.projectBasic': `Dự án`,
'pages.timeSheet.resouce': ``,
'pages.timeSheet.totalTime': ``,
'pages.timeSheet.byCustomer': `Theo khách hàng`,
'pages.timeSheet.byProject': `Theo dự án`,
'pages.timeSheet.byResources': `Theo nguồn`,
'pages.timeSheet.employeesSelected': `Nhân viên được chọn`,
'pages.timeSheet.remindEmployee': ``,
'pages.timeSheet.byEmployee': `Theo nhân viên`,
'pages.timeSheet.noMatches': ``,
'pages.timeSheet.byDepartment': `Theo ID phòng ban/ tên`,
'pages.timeSheet.reportingManager': `Quản lý báo cáo`,
'pages.timeSheet.projects': `Dự án`,
'pages.timeSheet.workingDays': ``,
'pages.timeSheet.timeOffInDay': `Thời gian nghỉ (theo ngày)`,
'pages.timeSheet.projectView': `Xem dự án`,
'pages.timeSheet.teamView': ``,
'pages.timeSheet.view': `Xem`,
'pages.timeSheet.moreTasks': ``,
'pages.timeSheet.projectManager': `Quản lý dự án`,
'pages.timeSheet.PMAssigned': ``,
'pages.timeSheet.viewDetails': `Xem chi tiết`,
'pages.timeSheet.ticketID': `ID ticket`,
'pages.timeSheet.dateRange': `Khoản thời gian`,
'pages.timeSheet.approvedBy': `Được duyệt bởi`,
'pages.timeSheet.comments': `Bình luận`,
'pages.timeSheet.comment': ``,
'pages.timeSheet.status': `Trạng thái`,
'pages.timeSheet.manager': `Quản lý`,
'pages.timeSheet.readMore': `Xem thêm`,
'pages.timeSheet.leaveOn': `Để lại trên `,
'pages.timeSheet.totalDays': `Tổng số ngày`,
'pages.timeSheet.resources': `Nguồn`,
'pages.timeSheet.hours': `Giờ`,
'pages.timeSheet.hrs': `giờ`,
'pages.timeSheet.paymentDueDate': ``,
'pages.timeSheet.projectType': `Loại dự án`,
'pages.timeSheet.timesheetDetails': ``,
'pages.timeSheet.timeTaken': ``,
'pages.timeSheet.overlap': ``,
'pages.timeSheet.takenTimeoff': `Bạn đang được đưa đến trang thời gian nghỉ - chi tiết nghỉ phép của bạn sẽ tự động được cập nhật trên bảng chấm công sau khi nó được áp dụng.`,
'pages.timeSheet.onlyImport': ``,
'pages.timeSheet.haveManager': ``,
'pages.timeSheet.invalidProjectName': `Tên dự án không hợp lệ`,
'pages.timeSheet.selectProject': ``,
'pages.timeSheet.selectTask': ``,
'pages.timeSheet.selectTheTask': ``,
'pages.timeSheet.selectStartTime': `Chọn ngày bắt đầu`,
'pages.timeSheet.onlyNumber': ``,
'pages.timeSheet.sureDelete': `Bạn có chắc không muốn xoá?`,
'pages.timeSheet.selectTimesheet': ``,
'pages.timeSheet.pleaseEnterDescription': `Vui lòng nhập mô tả`,
'pages.timeSheet.pleaseSelectTask': `Vui lòng chọn việc mà bạn muốn nhập vào`,
'pages.timeSheet.pleaseSelectMoreDate': `Vui lòng chọn một hoặc nhiều ngày mà việc phải được nhập vào`,
'pages.timeSheet.sheetForEmpty': ``,
'pages.timeSheet.sureToMove': `Bạn có chắc muốn xoá?`,
'pages.timeSheet.enterNote': `Nhập ghi chú...`,
'pages.timeSheet.selectTime': ``,
'pages.timeSheet.selectDurationDay': ``,
'pages.timeSheet.selectedTasks': ``,
'pages.timeSheet.byJobTitle': `Theo chức danh công việc`,
'pages.timeSheet.noReport': ``,
'pages.timeSheet.enterTaskName': ``,
'pages.timeSheet.enterDescription': ``,
'pages.timeSheet.selectTheStartTime': `Chọn ngày bắt đầu`,
'pages.timeSheet.selectTheEndTime': `Chọn ngày kết thúc`,
'pages.timeSheet.0': ``,
'pages.timeSheet.searchCustomer': `Tìm kiếm theo khách hàng`,
'pages.timeSheet.searchCustomerProjectEmployee': `Tìm kiếm theo khách hàng, dự án, nhân viên`,
'pages.timeSheet.searchEmployee': `Tìm kiếm theo nhân viên`,
'pages.timeSheet.searchProject': `Tìm kiếm theo dự án`,
'pages.timeSheet.searchResources': `Tìm kiếm theo nguồn`,
'pages.timeSheet.searchNameUserId': `Tìm kiếm theo tên/ ID người dùng`,
'pages.timeSheet.searchByDepartment': `Tìm kiếm theo bộ phận`,
'pages.timeSheet.pleaseSelectDurationDay': `Vui lòng chọn thời hạn`,
'pages.timeSheet.searchByDesignation': `Tìm kiếm theo chỉ định`,
'pages.timeSheet.resubmit': `Nộp lại`,
'pages.timeSheet.searchNameTask': `Tìm kiếm theo tên, nhậm vụ...`,
}